src/jelatine/array.c File Reference
#include `wrappers.h`
Functions
size_t array_get_nref_size (array_t *array)
size_t array_get_ref_n (array_t *array)
void arraycopy_ref (array_t *src, int32_t src_offset, array_t *dest, int32_t dest_offset, int32_t length)
Variables
const char * array_names []
uint8_t array_elem_sizes []
uint8_t prim_to_array_types []
Detailed Description
Array methods' implementation
Definition in file array.c.
Function Documentation
size_t array_get_nref_size (array_t * array)
Gets the size (in bytes) of the non-reference area of an array
Parameters
array A pointer to the array header
Returns
The size (in bytes) of the array's non-reference area
Definition at line 88 of file array.c.
References array_elem_size(), class_t::elem_type, array_t::header, header_get_class(), array_t::length, prim_to_array_type(), PT_BOOL, PT_REFERENCE, and size_div_inf().
Referenced by gc_sweep().
size_t array_get_ref_n (array_t * array)
Gets the number of references in an array
Parameters
array A pointer to an array header
Returns
The number of references in the array
Definition at line 113 of file array.c.
References class_is_array(), class_t::elem_type, array_t::header, header_get_class(), array_t::length, and PT_REFERENCE.
Referenced by gc_mark_reference(), and gc_sweep().
void arraycopy_ref (array_t * src, int32_t src_offset, array_t * dest, int32_t dest_offset, int32_t length)
C implementation of java.lang.System.arraycopy() for reference arrays. If an element is found not to be compatible with the destination array an ArrayStoreException is thrown
Parameters
src A pointer to the source array
src_offset The offset in the source array
dest A pointer to the destination array
dest_offset The offset in the destination array
length The number of elements to copy
Definition at line 135 of file array.c.
References array_ref_get_data(), bcl_is_assignable(), class_t::elem_class, gc_new_array_ref(), array_t::header, header_get_class(), and KNI_ThrowNew().
Referenced by java_lang_System_arraycopy().
Variable Documentation
uint8_t array_elem_sizes[]
Initial value:
 
    1,
    2,
    4,
    8,
    1,
    2,
    4,
    8
This array holds the size in bytes of the basic array element types. T_BOOLEAN is a special case as it set as having an element size of 1 byte per element when in fact it uses 1 bit per element
Definition at line 55 of file array.c.
Referenced by array_elem_size().
const char* array_names[]
Initial value:
 
    "[Z",
    "[C",
    "[F",
    "[D",
    "[B",
    "[S",
    "[I",
    "[J"
This array holds the names of the primitive-type arrays
Definition at line 40 of file array.c.
Referenced by array_name().
uint8_t prim_to_array_types[]
Initial value:
 
    T_BYTE,
    T_BOOLEAN,
    T_CHAR,
    T_SHORT,
    T_INT,
    T_FLOAT,
    T_LONG,
    T_DOUBLE
This array holds an array_type_t value for each primitive_type_t element which can be used in a non-reference array
Definition at line 69 of file array.c.
Referenced by prim_to_array_type().