src/jelatine/bytecode.c File Reference
#include `wrappers.h`
#include `bytecode.h`
#include `class.h`
#include `constantpool.h`
#include `loader.h`
#include `memory.h`
#include `method.h`
#include `opcodes.h`
#include `util.h`
Functions
void translate_bytecode (class_t *cl, method_t *method, uint8_t *code, exception_handler_t *handlers)
Detailed Description
Bytecode manipulation functions implementation
Definition in file bytecode.c.
Function Documentation
void translate_bytecode (class_t * cl, method_t * method, uint8_t * code, exception_handler_t * handlers)
Translates regular Java bytecode into the internal version used by the VM, bytecode verification could be done here too
Note that during bytecode translation constants larger than a single byte are turned to the machines native endian format (for unaligned constants only if the machine supports unaligned accesses). Static constraints in the bytecode are enforced here and partial verification happens too.
Parameters
cl A pointer to the class owning the method
method A pointer to the method to be translated
code The method code
handlers The method exception handlers
Definition at line 48 of file bytecode.c.
References c_throw, class_t::const_pool, CONSTANT_Class, CONSTANT_Double, CONSTANT_Float, CONSTANT_Integer, CONSTANT_Long, CONSTANT_String, cp_get_tag(), method_t::exception_table_length, JAVA_LANG_NOCLASSDEFFOUNDERROR, method_t::max_locals, method_get_code_length(), method_is_static(), method_is_synchronized(), size_ceil(), store_int16_un, and store_int32_un.
Referenced by bcl_link_method().