jelatine::VMResourceStream Class Reference
Public Member Functions
VMResourceStream (String resource)
native boolean open ()
int available ()
native int read ()
Protected Member Functions
native void finalize ()
Detailed Description
Internal VM class used for handling System's standard error and output streams
Definition at line 31 of file VMResourceStream.java.
Constructor & Destructor Documentation
jelatine::VMResourceStream::VMResourceStream (String resource) [inline]
Creates a new stream for the specified resource
Parameters
resource Resource name
Definition at line 46 of file VMResourceStream.java.
References available().
Member Function Documentation
int jelatine::VMResourceStream::available () [inline]
Returns the number of bytes that can be read (or skipped over) from this input stream without blocking by the next caller of a method for this input stream. The next caller might be the same thread or another thread
Returns
the number of bytes that can be read from this input stream without blocking
Reimplemented from java::io::InputStream .
Definition at line 67 of file VMResourceStream.java.
Referenced by VMResourceStream().
native void jelatine::VMResourceStream::finalize () [protected]
Finalize method
native boolean jelatine::VMResourceStream::open ()
Opens the resource stream
Returns
true if the resource held by the object is available, false otherwise
Referenced by java::lang::Class::getResourceAsStream().
native int jelatine::VMResourceStream::read () [virtual]
This method reads an unsigned byte from the input stream and returns it as an int in the range of 0-255. This method also will return -1 if the end of the stream has been reached.
This method will block until the byte can be read.
Returns
The byte read or -1 if end of stream
Implements java::io::InputStream .
The documentation for this class was generated from the following file:
src/classpath/jelatine/VMResourceStream.java