java::lang::Integer Class Reference
Public Member Functions
Integer (int value)
byte byteValue ()
short shortValue ()
int intValue ()
long longValue ()
float floatValue ()
double doubleValue ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Static Public Member Functions
static String toString (int num, int radix)
static String toHexString (int i)
static String toOctalString (int i)
static String toBinaryString (int i)
static String toString (int i)
static int parseInt (String str, int radix) throws NumberFormatException
static int parseInt (String s) throws NumberFormatException
static Integer valueOf (String s, int radix)
static Integer valueOf (String s)
Static Public Attributes
static final int MIN_VALUE = 0x80000000
static final int MAX_VALUE = 0x7fffffff
Static Package Functions
static String toUnsignedString (int num, int exp)
static int parseIntInternal (String str, int radix)
Detailed Description
Instances of class Integer represent primitive int values.
Additionally, this class provides various helper functions and variables related to ints.
Author
Paul Fisher
John Keiser
Warren Levy
Eric Blake (ebb9@email.byu.edu)
Tom Tromey (tromey@redhat.com)
Definition at line 54 of file Integer.java.
Constructor & Destructor Documentation
java::lang::Integer::Integer (int value) [inline]
Create an Integer object representing the value of the int argument.
Parameters
value the value to use
Definition at line 91 of file Integer.java.
Referenced by valueOf().
Member Function Documentation
byte java::lang::Integer::byteValue () [inline]
Return the value of this Integer as a byte.
Returns
the byte value
Definition at line 270 of file Integer.java.
double java::lang::Integer::doubleValue () [inline]
Return the value of this Integer as a double.
Returns
the double value
Definition at line 319 of file Integer.java.
boolean java::lang::Integer::equals (Object obj) [inline]
Returns true if obj is an instance of Integer and represents the same int value.
Parameters
obj the object to compare
Returns
whether these Objects are semantically equal
Definition at line 353 of file Integer.java.
float java::lang::Integer::floatValue () [inline]
Return the value of this Integer as a float.
Returns
the float value
Definition at line 309 of file Integer.java.
int java::lang::Integer::hashCode () [inline]
Return a hashcode representing this Object. Integer's hash code is simply its value.
Returns
this Object's hash code
Definition at line 341 of file Integer.java.
int java::lang::Integer::intValue () [inline]
Return the value of this Integer.
Returns
the int value
Definition at line 289 of file Integer.java.
long java::lang::Integer::longValue () [inline]
Return the value of this Integer as a long.
Returns
the long value
Definition at line 299 of file Integer.java.
static int java::lang::Integer::parseInt (String str, int radix) throws NumberFormatException [inline, static]
Converts the specified String into an int using the specified radix (base). The string must not be null or empty. It may begin with an optional '-', which will negate the answer, provided that there are also valid digits. Each digit is parsed as if by Character.digit(d, radix), and must be in the range 0 to radix - 1. Finally, the result must be within MIN_VALUE to MAX_VALUE, inclusive. Unlike Double.parseDouble, you may not have a leading '+'.
Parameters
str the String to convert
radix the radix (base) to use in the conversion
Returns
the String argument converted to int
Exceptions
NumberFormatException if s cannot be parsed as an int
Definition at line 214 of file Integer.java.
References parseIntInternal().
static int java::lang::Integer::parseInt (String s) throws NumberFormatException [inline, static]
Converts the specified String into an int. This function assumes a radix of 10.
Parameters
s the String to convert
Returns
the int value of s
Exceptions
NumberFormatException if s cannot be parsed as an int
See also
parseInt(String, int)
Definition at line 230 of file Integer.java.
References parseIntInternal().
static int java::lang::Integer::parseIntInternal (String str, int radix) [inline, static, package]
Helper for parsing ints, used by Integer, Short, and Byte.
Parameters
str the string to parse
radix the radix to use
Returns
the parsed int value
Exceptions
NumberFormatException if there is an error
See also
parseInt(String, int)
Byte::parseByte(String, int)
Short::parseShort(String, int)
Definition at line 393 of file Integer.java.
References java::lang::String::charAt(), java::lang::String::length(), MAX_VALUE, and MIN_VALUE.
Referenced by parseInt(), and valueOf().
short java::lang::Integer::shortValue () [inline]
Return the value of this Integer as a short.
Returns
the short value
Definition at line 280 of file Integer.java.
static String java::lang::Integer::toBinaryString (int i) [inline, static]
Converts the int to a String assuming it is unsigned in base 2.
Parameters
i the int to convert to String
Returns
the String representation of the argument
Definition at line 177 of file Integer.java.
References toUnsignedString().
static String java::lang::Integer::toHexString (int i) [inline, static]
Converts the int to a String assuming it is unsigned in base 16.
Parameters
i the int to convert to String
Returns
the String representation of the argument
Definition at line 153 of file Integer.java.
References toUnsignedString().
static String java::lang::Integer::toOctalString (int i) [inline, static]
Converts the int to a String assuming it is unsigned in base 8.
Parameters
i the int to convert to String
Returns
the String representation of the argument
Definition at line 165 of file Integer.java.
References toUnsignedString().
String java::lang::Integer::toString () [inline]
Converts the Integer value to a String and assumes a radix of 10.
Returns
the String representation
Definition at line 330 of file Integer.java.
References java::lang::String::valueOf().
static String java::lang::Integer::toString (int num, int radix) [inline, static]
Converts the int to a String using the specified radix (base). If the radix exceeds Character.MIN_RADIX or Character.MAX_RADIX, 10 is used instead. If the result is negative, the leading character is '-' ('\u002D'). The remaining characters come from Character.forDigit(digit, radix) ('0'-'9','a'-'z').
Parameters
num the int to convert to String
radix the radix (base) to use in the conversion
Returns
the String representation of the argument
Definition at line 108 of file Integer.java.
static String java::lang::Integer::toString (int i) [inline, static]
Converts the int to a String and assumes a radix of 10.
Parameters
i the int to convert to String
Returns
the String representation of the argument
See also
toString(int, int)
Definition at line 190 of file Integer.java.
References java::lang::String::valueOf().
static String java::lang::Integer::toUnsignedString (int num, int exp) [inline, static, package]
Helper for converting unsigned numbers to String.
Parameters
num the number
exp log2(digit) (ie. 1, 3, or 4 for binary, oct, hex)
Definition at line 365 of file Integer.java.
Referenced by toBinaryString(), toHexString(), and toOctalString().
static Integer java::lang::Integer::valueOf (String s, int radix) [inline, static]
Creates a new Integer object using the String and specified radix (base).
Parameters
s the String to convert
radix the radix (base) to convert with
Returns
the new Integer
Exceptions
NumberFormatException if s cannot be parsed as an int
See also
parseInt(String, int)
Definition at line 246 of file Integer.java.
References Integer(), and parseIntInternal().
static Integer java::lang::Integer::valueOf (String s) [inline, static]
Creates a new Integer object using the String, assuming a radix of 10.
Parameters
s the String to convert
Returns
the new Integer
Exceptions
NumberFormatException if s cannot be parsed as an int
Definition at line 260 of file Integer.java.
References Integer(), and parseIntInternal().
Field Documentation
final int java::lang::Integer::MAX_VALUE = 0x7fffffff [static]
The maximum value an int can represent is 2147483647 (or 2$^{\mbox{31}}$ - 1).
Definition at line 66 of file Integer.java.
Referenced by parseIntInternal().
final int java::lang::Integer::MIN_VALUE = 0x80000000 [static]
The minimum value an int can represent is -2147483648 (or -2$^{\mbox{31}}$).
Definition at line 60 of file Integer.java.
Referenced by parseIntInternal().
The documentation for this class was generated from the following file:
src/classpath/java/lang/Integer.java