java::lang::String Class Reference
Public Member Functions
String ()
String (String str)
String (char[] data)
String (char[] data, int offset, int count)
String (byte[] data, int offset, int count, String encoding) throws UnsupportedEncodingException
String (byte[] data, String encoding) throws UnsupportedEncodingException
String (byte[] data, int offset, int count)
String (byte[] data)
String (StringBuffer buffer)
int length ()
char charAt (int index)
void getChars (int srcBegin, int srcEnd, char dst[], int dstBegin)
byte[] getBytes (String encoding) throws UnsupportedEncodingException
byte[] getBytes ()
boolean equals (Object anObject)
boolean equalsIgnoreCase (String anotherString)
int compareTo (String anotherString)
boolean regionMatches (boolean ignoreCase, int toffset, String other, int ooffset, int len)
boolean startsWith (String prefix, int toffset)
boolean startsWith (String prefix)
boolean endsWith (String suffix)
int hashCode ()
int indexOf (int ch)
int indexOf (int ch, int fromIndex)
int lastIndexOf (int ch)
int lastIndexOf (int ch, int fromIndex)
int indexOf (String str)
int indexOf (String str, int fromIndex)
String substring (int begin)
String substring (int beginIndex, int endIndex)
String concat (String str)
String replace (char oldChar, char newChar)
String toLowerCase ()
String toUpperCase ()
String trim ()
String toString ()
char[] toCharArray ()
native String intern ()
Static Public Member Functions
static String valueOf (Object obj)
static String valueOf (char[] data)
static String valueOf (char[] data, int offset, int count)
static String valueOf (boolean b)
static String valueOf (char c)
static String valueOf (int i)
static String valueOf (long l)
static String valueOf (float f)
static String valueOf (double d)
Package Functions
String (char[] data, int offset, int count, boolean dont_copy)
Package Attributes
final char[] value
final int count
final int offset
Detailed Description
Strings represent an immutable set of characters. All String literals are instances of this class, and two string literals with the same contents refer to the same String object.
This class also includes a number of methods for manipulating the contents of strings (of course, creating a new object if there are any changes, as String is immutable). Case mapping relies on Unicode 3.0.0 standards, where some character sequences have a different number of characters in the uppercase version than the lower case.
Strings are special, in that they are the only object with an overloaded operator. When you use '+' with at least one String argument, both arguments have String conversion performed on them, and another String (not guaranteed to be unique) results.
String is special-cased when doing data serialization - rather than listing the fields of this class, a String object is converted to a string literal in the object stream.
Author
Paul N. Fisher
Eric Blake (ebb9@email.byu.edu)
Per Bothner (bothner@cygnus.com)
Since
1.0
Definition at line 71 of file String.java.
Constructor & Destructor Documentation
java::lang::String::String () [inline]
Creates an empty String (length 0). Unless you really need a new object, consider using `` instead.
Definition at line 106 of file String.java.
References count, offset, and value.
Referenced by concat(), replace(), substring(), toLowerCase(), toUpperCase(), and valueOf().
java::lang::String::String (String str) [inline]
Copies the contents of a String to a new String. Since Strings are immutable, only a shallow copy is performed.
Parameters
str String to copy
Exceptions
NullPointerException if value is null
Definition at line 120 of file String.java.
References count, offset, and value.
java::lang::String::String (char[] data) [inline]
Creates a new String using the character sequence of the char array. Subsequent changes to data do not affect the String.
Parameters
data char array to copy
Exceptions
NullPointerException if data is null
Definition at line 135 of file String.java.
java::lang::String::String (char[] data, int offset, int count) [inline]
Creates a new String using the character sequence of a subarray of characters. The string starts at offset, and copies count chars. Subsequent changes to data do not affect the String.
Parameters
data char array to copy
offset position (base 0) to start copying out of data
count the number of characters from data to copy
Exceptions
NullPointerException if data is null
IndexOutOfBoundsException if (offset < 0 || count < 0 || offset + count < 0 (overflow) || offset + count > data.length) (while unspecified, this is a StringIndexOutOfBoundsException)
Definition at line 154 of file String.java.
java::lang::String::String (byte[] data, int offset, int count, String encoding) throws UnsupportedEncodingException [inline]
Creates a new String using the portion of the byte array starting at the offset and ending at offset + count. Uses the specified encoding type to decode the byte array, so the resulting string may be longer or shorter than the byte array. The behavior is not specified if the decoder encounters invalid characters; this implementation throws an Error.
Parameters
data byte array to copy
offset the offset to start at
count the number of bytes in the array to use
encoding the name of the encoding to use
Exceptions
NullPointerException if data or encoding is null
IndexOutOfBoundsException if offset or count is incorrect (while unspecified, this is a StringIndexOutOfBoundsException)
UnsupportedEncodingException if encoding is not found
Error if the decoding fails
Since
1.1
Definition at line 178 of file String.java.
References count, offset, and value.
java::lang::String::String (byte[] data, String encoding) throws UnsupportedEncodingException [inline]
Creates a new String using the byte array. Uses the specified encoding type to decode the byte array, so the resulting string may be longer or shorter than the byte array. The behavior is not specified if the decoder encounters invalid characters; this implementation throws an Error.
Parameters
data byte array to copy
encoding the name of the encoding to use
Exceptions
NullPointerException if data or encoding is null
UnsupportedEncodingException if encoding is not found
Error if the decoding fails
See also
String(byte[], int, int, String)
Since
1.1
Definition at line 225 of file String.java.
java::lang::String::String (byte[] data, int offset, int count) [inline]
Creates a new String using the portion of the byte array starting at the offset and ending at offset + count. Uses the encoding of the platform's default charset, so the resulting string may be longer or shorter than the byte array. The behavior is not specified if the decoder encounters invalid characters; this implementation throws an Error.
Parameters
data byte array to copy
offset the offset to start at
count the number of bytes in the array to use
Exceptions
NullPointerException if data is null
IndexOutOfBoundsException if offset or count is incorrect
Error if the decoding fails
See also
String(byte[], int, int, String)
Since
1.1
Definition at line 248 of file String.java.
References value.
java::lang::String::String (byte[] data) [inline]
Creates a new String using the byte array. Uses the encoding of the platform's default charset, so the resulting string may be longer or shorter than the byte array. The behavior is not specified if the decoder encounters invalid characters; this implementation throws an Error.
Parameters
data byte array to copy
Exceptions
NullPointerException if data is null
Error if the decoding fails
See also
String(byte[], int, int)
String(byte[], int, int, String)
Since
1.1
Definition at line 284 of file String.java.
java::lang::String::String (StringBuffer buffer) [inline]
Creates a new String using the character sequence represented by the StringBuffer. Subsequent changes to buf do not affect the String.
Parameters
buffer StringBuffer to copy
Exceptions
NullPointerException if buffer is null
Definition at line 296 of file String.java.
References java::lang::StringBuffer::count, count, offset, java::lang::StringBuffer::shared, value, and java::lang::StringBuffer::value.
java::lang::String::String (char[] data, int offset, int count, boolean dont_copy) [inline, package]
Special constructor which can share an array when safe to do so.
Parameters
data the characters to copy
offset the location to start from
count the number of characters to use
dont_copy true if the array is trusted, and need not be copied
Exceptions
NullPointerException if chars is null
StringIndexOutOfBoundsException if bounds check fails
Definition at line 327 of file String.java.
References value.
Member Function Documentation
char java::lang::String::charAt (int index) [inline]
Returns the character located at the specified index within this String.
Parameters
index position of character to return (base 0)
Returns
character located at position index
Exceptions
IndexOutOfBoundsException if index < 0 || index >= length() (while unspecified, this is a StringIndexOutOfBoundsException)
Definition at line 373 of file String.java.
References count, offset, and value.
Referenced by java::lang::Double::parseDouble(), and java::lang::Integer::parseIntInternal().
int java::lang::String::compareTo (String anotherString) [inline]
Compares this String and another String (case sensitive, lexicographically). The result is less than 0 if this string sorts before the other, 0 if they are equal, and greater than 0 otherwise. After any common starting sequence is skipped, the result is this.charAt(k) - anotherString.charAt(k) if both strings have characters remaining, or this.length() - anotherString.length() if one string is a subsequence of the other.
Parameters
anotherString the String to compare against
Returns
the comparison
Exceptions
NullPointerException if anotherString is null
Definition at line 551 of file String.java.
References count, offset, and value.
String java::lang::String::concat (String str) [inline]
Concatenates a String to this String. This results in a new string unless one of the two originals is ``.
Parameters
str String to append to this String
Returns
newly concatenated String
Exceptions
NullPointerException if str is null
Definition at line 861 of file String.java.
References count, offset, String(), and value.
boolean java::lang::String::endsWith (String suffix) [inline]
Predicate which determines if this String ends with a given suffix. If the suffix is an empty String, true is returned.
Parameters
suffix String to compare
Returns
true if this String ends with the suffix
Exceptions
NullPointerException if suffix is null
See also
regionMatches(boolean, int, String, int, int)
Definition at line 657 of file String.java.
References count, and regionMatches().
boolean java::lang::String::equals (Object anObject) [inline]
Predicate which compares anObject to this. This is true only for Strings with the same character sequence.
Parameters
anObject the object to compare
Returns
true if anObject is semantically equal to this
See also
compareTo(String)
equalsIgnoreCase(String)
Definition at line 465 of file String.java.
References count, offset, and value.
Referenced by java::lang::System::getProperty(), java::lang::Double::parseDouble(), and jelatine::VMOutputStream::VMOutputStream().
boolean java::lang::String::equalsIgnoreCase (String anotherString) [inline]
Compares a String to this String, ignoring case. This does not handle multi-character capitalization exceptions; instead the comparison is made on a character-by-character basis, and is true if:
c1 == c2
Character.toUpperCase(c1) == Character.toUpperCase(c2)
Character.toLowerCase(c1) == Character.toLowerCase(c2)
Parameters
anotherString String to compare to this String
Returns
true if anotherString is equal, ignoring case
See also
equals(Object)
Character::toUpperCase(char)
Character::toLowerCase(char)
Definition at line 511 of file String.java.
References count, offset, and value.
byte [] java::lang::String::getBytes (String encoding) throws UnsupportedEncodingException [inline]
Converts the Unicode characters in this String to a byte array. Uses the specified encoding method, so the result may be longer or shorter than the String. Unsupported characters get replaced by an encoding specific byte.
Parameters
encoding encoding name
Returns
the resulting byte array
Exceptions
NullPointerException if enc is null
UnsupportedEncodingException if encoding is not supported
Since
1.1
Definition at line 417 of file String.java.
References count, offset, and value.
byte [] java::lang::String::getBytes () [inline]
Converts the Unicode characters in this String to a byte array. Uses the encoding of the platform's default charset, so the result may be longer or shorter than the String. Unsupported characters get replaced by an encoding specific byte.
Returns
the resulting byte array, or null on a problem
Since
1.1
Definition at line 443 of file String.java.
References count, offset, and value.
void java::lang::String::getChars (int srcBegin, int srcEnd, char dst[], int dstBegin) [inline]
Copies characters from this String starting at a specified start index, ending at a specified stop index, to a character array starting at a specified destination begin index.
Parameters
srcBegin index to begin copying characters from this String
srcEnd index after the last character to be copied from this String
dst character array which this String is copied into
dstBegin index to start writing characters into dst
Exceptions
NullPointerException if dst is null
IndexOutOfBoundsException if any indices are out of bounds (while unspecified, source problems cause a StringIndexOutOfBoundsException, and dst problems cause an ArrayIndexOutOfBoundsException)
Definition at line 396 of file String.java.
References count, offset, and value.
Referenced by java::lang::StringBuffer::append(), java::lang::StringBuffer::insert(), and java::lang::StringBuffer::StringBuffer().
int java::lang::String::hashCode () [inline]
Computes the hashcode for this String. This is done with int arithmetic, where ** represents exponentiation, by this formula:
 s[0]*31**(n-1) + s[1]*31**(n-2) + ... + s[n-1].
Returns
hashcode value of this String
Definition at line 669 of file String.java.
References count, offset, and value.
int java::lang::String::indexOf (String str) [inline]
Finds the first instance of a String in this String.
Parameters
str String to find
Returns
location (base 0) of the String, or -1 if not found
Exceptions
NullPointerException if str is null
Definition at line 771 of file String.java.
References indexOf().
int java::lang::String::indexOf (String str, int fromIndex) [inline]
Finds the first instance of a String in this String, starting at a given index. If starting index is less than 0, the search starts at the beginning of this String. If the starting index is greater than the length of this String, -1 is returned.
Parameters
str String to find
fromIndex index to start the search
Returns
location (base 0) of the String, or -1 if not found
Exceptions
NullPointerException if str is null
Definition at line 787 of file String.java.
References count, and value.
int java::lang::String::indexOf (int ch) [inline]
Finds the first instance of a character in this String.
Parameters
ch character to find
Returns
location (base 0) of the character, or -1 if not found
Definition at line 690 of file String.java.
Referenced by jelatine::cldc::io::URL::getParamsMap(), indexOf(), and jelatine::cldc::io::URL::URL().
int java::lang::String::indexOf (int ch, int fromIndex) [inline]
Finds the first instance of a character in this String, starting at a given index. If starting index is less than 0, the search starts at the beginning of this String. If the starting index is greater than the length of this String, -1 is returned.
Parameters
ch character to find
fromIndex index to start the search
Returns
location (base 0) of the character, or -1 if not found
Definition at line 705 of file String.java.
References count, offset, and value.
native String java::lang::String::intern ()
If two Strings are considered equal, by the equals() method, then intern() will return the same String instance. ie. if (s1.equals(s2)) then (s1.intern() == s2.intern()). All string literals and string-valued constant expressions are already interned.
Returns
the interned String
int java::lang::String::lastIndexOf (int ch) [inline]
Finds the last instance of a character in this String.
Parameters
ch character to find
Returns
location (base 0) of the character, or -1 if not found
Definition at line 730 of file String.java.
References count.
int java::lang::String::lastIndexOf (int ch, int fromIndex) [inline]
Finds the last instance of a character in this String, starting at a given index. If starting index is greater than the maximum valid index, then the search begins at the end of this String. If the starting index is less than zero, -1 is returned.
Parameters
ch character to find
fromIndex index to start the search
Returns
location (base 0) of the character, or -1 if not found
Definition at line 745 of file String.java.
References count, offset, and value.
int java::lang::String::length () [inline]
Returns the number of characters contained in this String.
Returns
the length of this String
Definition at line 360 of file String.java.
References count.
Referenced by java::lang::Double::parseDouble(), and java::lang::Integer::parseIntInternal().
boolean java::lang::String::regionMatches (boolean ignoreCase, int toffset, String other, int ooffset, int len) [inline]
Predicate which determines if this String matches another String starting at a specified offset for each String and continuing for a specified length, optionally ignoring case. Indices out of bounds are harmless, and give a false result. Case comparisons are based on Character.toLowerCase() and Character.toUpperCase(), not on multi-character capitalization expansions.
Parameters
ignoreCase true if case should be ignored in comparision
toffset index to start comparison at for this String
other String to compare region to this String
ooffset index to start comparison at for other
len number of characters to compare
Returns
true if regions match, false otherwise
Exceptions
NullPointerException if other is null
Definition at line 585 of file String.java.
References count, offset, and value.
Referenced by endsWith(), and startsWith().
String java::lang::String::replace (char oldChar, char newChar) [inline]
Replaces every instance of a character in this String with a new character. If no replacements occur, this is returned.
Parameters
oldChar the old character to replace
newChar the new character
Returns
new String with all instances of oldChar replaced with newChar
Definition at line 884 of file String.java.
References count, offset, String(), and value.
Referenced by java::lang::Class::getName().
boolean java::lang::String::startsWith (String prefix, int toffset) [inline]
Predicate which determines if this String contains the given prefix, beginning comparison at toffset. The result is false if toffset is negative or greater than this.length(), otherwise it is the same as this.substring(toffset).startsWith(prefix).
Parameters
prefix String to compare
toffset offset for this String where comparison starts
Returns
true if this String starts with prefix
Exceptions
NullPointerException if prefix is null
See also
regionMatches(boolean, int, String, int, int)
Definition at line 629 of file String.java.
References count, and regionMatches().
boolean java::lang::String::startsWith (String prefix) [inline]
Predicate which determines if this String starts with a given prefix. If the prefix is an empty String, true is returned.
Parameters
prefix String to compare
Returns
true if this String starts with the prefix
Exceptions
NullPointerException if prefix is null
See also
startsWith(String, int)
Definition at line 643 of file String.java.
References count, and regionMatches().
String java::lang::String::substring (int beginIndex, int endIndex) [inline]
Creates a substring of this String, starting at a specified index and ending at one character before a specified index.
Parameters
beginIndex index to start substring (inclusive, base 0)
endIndex index to end at (exclusive)
Returns
new String which is a substring of this String
Exceptions
IndexOutOfBoundsException if begin < 0 || end > length() || begin > end (while unspecified, this is a StringIndexOutOfBoundsException)
Definition at line 839 of file String.java.
References count, offset, String(), and value.
String java::lang::String::substring (int begin) [inline]
Creates a substring of this String, starting at a specified index and ending at the end of this String.
Parameters
begin index to start substring (base 0)
Returns
new String which is a substring of this String
Exceptions
IndexOutOfBoundsException if begin < 0 || begin > length() (while unspecified, this is a StringIndexOutOfBoundsException)
Definition at line 823 of file String.java.
References count.
Referenced by jelatine::cldc::io::URL::getParamsMap(), java::lang::Double::parseDouble(), trim(), and jelatine::cldc::io::URL::URL().
char [] java::lang::String::toCharArray () [inline]
Copies the contents of this String into a character array. Subsequent changes to the array do not affect the String.
Returns
character array copying the String
Definition at line 1044 of file String.java.
References count, offset, and value.
String java::lang::String::toLowerCase () [inline]
Lowercases this String. This uses Unicode's special case mappings, as applied to the platform's default Locale, so the resulting string may be a different length.
Returns
new lowercased String, or this if no characters were lowercased
Definition at line 922 of file String.java.
References count, offset, String(), and value.
String java::lang::String::toString () [inline]
Returns this, as it is already a String!
Returns
this
Definition at line 1033 of file String.java.
Referenced by java::lang::Thread::Thread(), java::lang::Long::toString(), and valueOf().
String java::lang::String::toUpperCase () [inline]
Uppercases this String. This uses Unicode's special case mappings, as applied to the platform's default Locale, so the resulting string may be a different length.
Returns
new uppercased String, or this if no characters were uppercased
Definition at line 963 of file String.java.
References count, offset, String(), and value.
String java::lang::String::trim () [inline]
Trims all characters less than or equal to '0020' (' ') from the beginning and end of this String. This includes many, but not all, ASCII control characters, and all whitespace characters.
Returns
new trimmed String, or this if nothing trimmed
Definition at line 1005 of file String.java.
References count, offset, substring(), and value.
static String java::lang::String::valueOf (double d) [inline, static]
Returns a String representing a double.
Parameters
d the double
Returns
String containing the double
See also
Double::toString(double)
Definition at line 1167 of file String.java.
References toString().
static String java::lang::String::valueOf (char c) [inline, static]
Returns a String representing a character.
Parameters
c the character
Returns
String containing the single character c
Definition at line 1117 of file String.java.
References String().
static String java::lang::String::valueOf (float f) [inline, static]
Returns a String representing a float.
Parameters
f the float
Returns
String containing the float
See also
Float::toString(float)
Definition at line 1155 of file String.java.
References toString().
static String java::lang::String::valueOf (int i) [inline, static]
Returns a String representing an integer.
Parameters
i the integer
Returns
String containing the integer in base 10
See also
Integer::toString(int)
Definition at line 1130 of file String.java.
References toString().
static String java::lang::String::valueOf (char[] data) [inline, static]
Returns a String representation of a character array. Subsequent changes to the array do not affect the String.
Parameters
data the character array
Returns
a String containing the same character sequence as data
Exceptions
NullPointerException if data is null
See also
valueOf(char[], int, int)
String(char[])
Definition at line 1074 of file String.java.
References valueOf().
static String java::lang::String::valueOf (Object obj) [inline, static]
Returns a String representation of an Object. This is `null` if the object is null, otherwise it is obj.toString() (which can be null).
Parameters
obj the Object
Returns
the string conversion of obj
Definition at line 1059 of file String.java.
References java::lang::Object::toString().
Referenced by java::lang::Short::toString(), java::lang::Integer::toString(), java::lang::Byte::toString(), and valueOf().
static String java::lang::String::valueOf (long l) [inline, static]
Returns a String representing a long.
Parameters
l the long
Returns
String containing the long in base 10
See also
Long::toString(long)
Definition at line 1143 of file String.java.
References toString().
static String java::lang::String::valueOf (boolean b) [inline, static]
Returns a String representing a boolean.
Parameters
b the boolean
Returns
`true` if b is true, else `false`
Definition at line 1106 of file String.java.
static String java::lang::String::valueOf (char[] data, int offset, int count) [inline, static]
Returns a String representing the character sequence of the char array, starting at the specified offset, and copying chars up to the specified count. Subsequent changes to the array do not affect the String.
Parameters
data character array
offset position (base 0) to start copying out of data
count the number of characters from data to copy
Returns
String containing the chars from data[offset..offset+count]
Exceptions
NullPointerException if data is null
IndexOutOfBoundsException if (offset < 0 || count < 0 || offset + count < 0 (overflow) || offset + count > data.length) (while unspecified, this is a StringIndexOutOfBoundsException)
See also
String(char[], int, int)
Definition at line 1095 of file String.java.
References String().
Field Documentation
final int java::lang::String::count [package]
Holds the number of characters in value. This number is generally the same as value.length, but can be smaller because substrings and StringBuffers can share arrays. Package visible for use by trusted code.
Definition at line 87 of file String.java.
Referenced by java::lang::StringBuffer::append(), charAt(), compareTo(), concat(), endsWith(), equals(), equalsIgnoreCase(), getBytes(), getChars(), hashCode(), indexOf(), java::lang::StringBuffer::insert(), lastIndexOf(), length(), regionMatches(), replace(), startsWith(), String(), java::lang::StringBuffer::StringBuffer(), substring(), toCharArray(), toLowerCase(), toUpperCase(), and trim().
final int java::lang::String::offset [package]
Holds the starting position for characters in value[]. Since substring()'s are common, the use of offset allows the operation to perform in O(1). Package access is granted for use by StringBuffer.
Definition at line 100 of file String.java.
Referenced by charAt(), compareTo(), concat(), equals(), equalsIgnoreCase(), getBytes(), getChars(), hashCode(), indexOf(), lastIndexOf(), regionMatches(), replace(), String(), substring(), toCharArray(), toLowerCase(), toUpperCase(), and trim().
final char [] java::lang::String::value [package]
Characters which make up the String. Package access is granted for use by StringBuffer.
Definition at line 80 of file String.java.
Referenced by charAt(), compareTo(), concat(), equals(), equalsIgnoreCase(), getBytes(), getChars(), hashCode(), indexOf(), lastIndexOf(), regionMatches(), replace(), String(), substring(), toCharArray(), toLowerCase(), toUpperCase(), and trim().
The documentation for this class was generated from the following file:
src/classpath/java/lang/String.java