java::util::Date Class Reference
Public Member Functions
Date ()
Date (long time)
long getTime ()
void setTime (long time)
boolean equals (Object obj)
int hashCode ()
String toString ()
Detailed Description
This class represents a specific time in milliseconds since the epoch. The epoch is 1970, January 1 00:00:00.0000 UTC.
Date is intended to reflect universal time coordinate (UTC), but this depends on the underlying host environment. Most operating systems don't handle the leap second, which occurs about once every year or so. The leap second is added to the last minute of the day on either the 30th of June or the 31st of December, creating a minute 61 seconds in length.
The representations of the date fields are as follows:
Years are specified as the difference between the year and 1900. Thus, the final year used is equal to 1900 + y, where y is the input value.
Months are represented using zero-based indexing, making 0 January and 11 December.
Dates are represented with the usual values of 1 through to 31.
Hours are represented in the twenty-four hour clock, with integer values from 0 to 23. 12am is 0, and 12pm is 12.
Minutes are again as usual, with values from 0 to 59.
Seconds are represented with the values 0 through to 61, with 60 and 61 being leap seconds (as per the ISO C standard).
Prior to JDK 1.1, this class was the sole class handling date and time related functionality. However, this particular solution was not amenable to internationalization. The new Calendar class should now be used to handle dates and times, with Date being used only for values in milliseconds since the epoch. The Calendar class, and its concrete implementations, handle the interpretation of these values into minutes, hours, days, months and years. The formatting and parsing of dates is left to the DateFormat class, which is able to handle the different types of date format which occur in different locales.
See also
Calendar
GregorianCalendar
java.text.DateFormat
Author
Jochen Hoenicke
Per Bothner (bothner@cygnus.com)
Andrew John Hughes (gnu_andrew@member.fsf.org)
Definition at line 103 of file Date.java.
Constructor & Destructor Documentation
java::util::Date::Date () [inline]
Creates a new Date Object representing the current time.
Definition at line 125 of file Date.java.
java::util::Date::Date (long time) [inline]
Creates a new Date Object representing the given time.
Parameters
time the time in milliseconds since the epoch.
Definition at line 135 of file Date.java.
Member Function Documentation
boolean java::util::Date::equals (Object obj) [inline]
Compares two dates for equality.
Parameters
obj the object to compare.
Returns
true, if obj is a Date object and the time represented by obj is exactly the same as the time represented by this object.
Definition at line 168 of file Date.java.
long java::util::Date::getTime () [inline]
Gets the time represented by this object.
Returns
the time in milliseconds since the epoch.
Definition at line 145 of file Date.java.
Referenced by java::util::Calendar::setTime().
int java::util::Date::hashCode () [inline]
Computes the hash code of this Date as the XOR of the most significant and the least significant 32 bits of the 64 bit milliseconds value.
Returns
the hash code.
Definition at line 180 of file Date.java.
void java::util::Date::setTime (long time) [inline]
Sets the time which this object should represent.
Parameters
time the time in milliseconds since the epoch.
Definition at line 155 of file Date.java.
String java::util::Date::toString () [inline]
Returns a string representation of this date using the following date format:
day mon dd hh:mm:ss zz yyyy
where the fields used here are:
day -- the day of the week (Sunday through to Saturday).
mon -- the month (Jan to Dec).
dd -- the day of the month as two decimal digits (01 to 31).
hh -- the hour of the day as two decimal digits in 24-hour clock notation (01 to 23).
mm -- the minute of the day as two decimal digits (01 to 59).
ss -- the second of the day as two decimal digits (01 to 61).
zz -- the time zone information if available. The possible time zones used include the abbreviations recognised by parse() (e.g. GMT, CET, etc.) and may reflect the fact that daylight savings time is in effect. The empty string is used if there is no time zone information.
yyyy -- the year as four decimal digits.
The DateFormat class should now be preferred over using this method.
Returns
A string of the form 'day mon dd hh:mm:ss zz yyyy'
Definition at line 238 of file Date.java.
References java::util::Calendar::get(), java::util::TimeZone::getID(), java::util::Calendar::getTimeZone(), and java::util::Calendar::setTimeInMillis().
The documentation for this class was generated from the following file:
src/classpath/java/util/Date.java