java::io::PrintStream Class Reference
Public Member Functions
PrintStream (OutputStream out)
void flush ()
void close ()
boolean checkError ()
void write (int oneByte)
void write (byte[] buffer, int offset, int len)
void print (boolean bool)
synchronized void print (char ch)
void print (int inum)
void print (long lnum)
void print (float fnum)
void print (double dnum)
void print (char[] charArray)
void print (String str)
void print (Object obj)
void println ()
void println (boolean bool)
synchronized void println (char ch)
void println (int inum)
void println (long lnum)
void println (float fnum)
void println (double dnum)
void println (char[] charArray)
void println (String str)
void println (Object obj)
Protected Member Functions
void setError ()
Detailed Description
This class prints Java primitive values and object to a stream as text. None of the methods in this class throw an exception. However, errors can be detected by calling the checkError() method. Additionally, this stream can be designated as `autoflush` when created so that any writes are automatically flushed to the underlying output sink when the current line is terminated.
This class converts char's into byte's using the system default encoding.
Author
Aaron M. Renn (arenn@urbanophile.com)
Tom Tromey (tromey@cygnus.com)
Definition at line 59 of file PrintStream.java.
Constructor & Destructor Documentation
java::io::PrintStream::PrintStream (OutputStream out) [inline]
This method intializes a new PrintStream object to write to the specified output sink.
Parameters
out The OutputStream to write to.
Definition at line 88 of file PrintStream.java.
Member Function Documentation
boolean java::io::PrintStream::checkError () [inline]
This method checks to see if an error has occurred on this stream. Note that once an error has occurred, this method will continue to report true forever for this stream. Before checking for an error condition, this method flushes the stream.
Returns
true if an error has occurred, false otherwise
Definition at line 135 of file PrintStream.java.
References flush().
void java::io::PrintStream::close () [inline]
This method closes this stream and all underlying streams.
Reimplemented from java::io::OutputStream .
Definition at line 113 of file PrintStream.java.
References java::io::OutputStream::close(), flush(), and setError().
void java::io::PrintStream::flush () [inline]
This method flushes any buffered bytes to the underlying stream and then flushes that stream as well.
Reimplemented from java::io::OutputStream .
Definition at line 98 of file PrintStream.java.
References java::io::OutputStream::flush(), and setError().
Referenced by checkError(), and close().
synchronized void java::io::PrintStream::print (char ch) [inline]
This method prints a char to the stream. The actual value printed is determined by the character encoding in use.
Parameters
ch The char value to be printed
Definition at line 208 of file PrintStream.java.
References print().
void java::io::PrintStream::print (int inum) [inline]
This method prints an integer to the stream. The value printed is determined using the String.valueOf() method.
Parameters
inum The int value to be printed
Definition at line 219 of file PrintStream.java.
References print().
void java::io::PrintStream::print (long lnum) [inline]
This method prints a long to the stream. The value printed is determined using the String.valueOf() method.
Parameters
lnum The long value to be printed
Definition at line 230 of file PrintStream.java.
References print().
void java::io::PrintStream::print (float fnum) [inline]
This method prints a float to the stream. The value printed is determined using the String.valueOf() method.
Parameters
fnum The float value to be printed
Definition at line 241 of file PrintStream.java.
References print().
void java::io::PrintStream::print (double dnum) [inline]
This method prints a double to the stream. The value printed is determined using the String.valueOf() method.
Parameters
dnum The double value to be printed
Definition at line 252 of file PrintStream.java.
References print().
void java::io::PrintStream::print (char[] charArray) [inline]
This method prints an array of characters to the stream. The actual value printed depends on the system default encoding.
Parameters
charArray The array of characters to print.
Definition at line 263 of file PrintStream.java.
References print().
void java::io::PrintStream::print (boolean bool) [inline]
This methods prints a boolean value to the stream. true values are printed as `true` and false values are printed as `false`.
Parameters
bool The boolean value to print
Definition at line 197 of file PrintStream.java.
Referenced by print(), and println().
void java::io::PrintStream::print (String str) [inline]
This method prints a String to the stream. The actual value printed depends on the system default encoding.
Parameters
str The String to print.
Definition at line 274 of file PrintStream.java.
References print().
void java::io::PrintStream::print (Object obj) [inline]
This method prints an Object to the stream. The actual value printed is determined by calling the String.valueOf() method.
Parameters
obj The Object to print.
Definition at line 286 of file PrintStream.java.
References print().
void java::io::PrintStream::println (char[] charArray) [inline]
This method prints an array of characters to the stream. The actual value printed depends on the system default encoding.
This method prints a line termination sequence after printing the value.
Parameters
charArray The array of characters to print.
Definition at line 388 of file PrintStream.java.
References print().
void java::io::PrintStream::println (Object obj) [inline]
This method prints an Object to the stream. The actual value printed is determined by calling the String.valueOf() method.
This method prints a line termination sequence after printing the value.
Parameters
obj The Object to print.
Definition at line 415 of file PrintStream.java.
References print().
void java::io::PrintStream::println () [inline]
This method prints a line separator sequence to the stream. The value printed is determined by the system property line.separator and is not necessarily the Unix newline character.
Definition at line 296 of file PrintStream.java.
References print().
void java::io::PrintStream::println (double dnum) [inline]
This method prints a double to the stream. The value printed is determined using the String.valueOf() method.
This method prints a line termination sequence after printing the value.
Parameters
dnum The double value to be printed
Definition at line 375 of file PrintStream.java.
References print().
void java::io::PrintStream::println (long lnum) [inline]
This method prints a long to the stream. The value printed is determined using the String.valueOf() method.
This method prints a line termination sequence after printing the value.
Parameters
lnum The long value to be printed
Definition at line 349 of file PrintStream.java.
References print().
void java::io::PrintStream::println (boolean bool) [inline]
This methods prints a boolean value to the stream. true values are printed as `true` and false values are printed as `false`.
This method prints a line termination sequence after printing the value.
Parameters
bool The boolean value to print
Definition at line 310 of file PrintStream.java.
References print().
synchronized void java::io::PrintStream::println (char ch) [inline]
This method prints a char to the stream. The actual value printed is determined by the character encoding in use.
This method prints a line termination sequence after printing the value.
Parameters
ch The char value to be printed
Definition at line 323 of file PrintStream.java.
References print().
void java::io::PrintStream::println (float fnum) [inline]
This method prints a float to the stream. The value printed is determined using the String.valueOf() method.
This method prints a line termination sequence after printing the value.
Parameters
fnum The float value to be printed
Definition at line 362 of file PrintStream.java.
References print().
void java::io::PrintStream::println (String str) [inline]
This method prints a String to the stream. The actual value printed depends on the system default encoding.
This method prints a line termination sequence after printing the value.
Parameters
str The String to print.
Definition at line 401 of file PrintStream.java.
References print().
void java::io::PrintStream::println (int inum) [inline]
This method prints an integer to the stream. The value printed is determined using the String.valueOf() method.
This method prints a line termination sequence after printing the value.
Parameters
inum The int value to be printed
Definition at line 336 of file PrintStream.java.
References print().
void java::io::PrintStream::setError () [inline, protected]
This method can be called by subclasses to indicate that an error has occurred and should be reported by checkError.
Definition at line 145 of file PrintStream.java.
Referenced by close(), flush(), and write().
void java::io::PrintStream::write (byte[] buffer, int offset, int len) [inline]
This method writes len bytes from the specified array starting at index offset into the array.
Parameters
buffer The array of bytes to write
offset The index into the array to start writing from
len The number of bytes to write
Reimplemented from java::io::OutputStream .
Definition at line 178 of file PrintStream.java.
References setError(), and java::io::OutputStream::write().
void java::io::PrintStream::write (int oneByte) [inline, virtual]
This method writes a byte of data to the stream. If auto-flush is enabled, printing a newline character will cause the stream to be flushed after the character is written.
Parameters
oneByte The byte to be written
Implements java::io::OutputStream .
Definition at line 157 of file PrintStream.java.
References setError(), and java::io::OutputStream::write().
The documentation for this class was generated from the following file:
src/classpath/java/io/PrintStream.java