java::util::Random Class Reference
Public Member Functions
Random ()
Random (long seed)
synchronized void setSeed (long seed)
int nextInt ()
int nextInt (int n)
long nextLong ()
float nextFloat ()
double nextDouble ()
Protected Member Functions
synchronized int next (int bits)
Detailed Description
This class generates pseudorandom numbers. It uses the same algorithm as the original JDK-class, so that your programs behave exactly the same way, if started with the same seed.
The algorithm is described in The Art of Computer Programming, Volume 2 by Donald Knuth in Section 3.2.1. It is a 48-bit seed, linear congruential formula.
If two instances of this class are created with the same seed and the same calls to these classes are made, they behave exactly the same way. This should be even true for foreign implementations (like this), so every port must use the same algorithm as described here.
If you want to implement your own pseudorandom algorithm, you should extend this class and overload the next() and setSeed(long) method. In that case the above paragraph doesn't apply to you.
This class shouldn't be used for security sensitive purposes (like generating passwords or encryption keys. See SecureRandom in package java.security for this purpose.
For simple random doubles between 0.0 and 1.0, you may consider using Math.random instead.
See also
Math::random()
Author
Jochen Hoenicke
Eric Blake (ebb9@email.byu.edu)
Definition at line 71 of file Random.java.
Constructor & Destructor Documentation
java::util::Random::Random () [inline]
Creates a new pseudorandom number generator. The seed is initialized to the current time, as if by setSeed(System.currentTimeMillis());.
See also
System::currentTimeMillis()
Definition at line 88 of file Random.java.
java::util::Random::Random (long seed) [inline]
Creates a new pseudorandom number generator, starting with the specified seed, using setSeed(seed);.
Parameters
seed the initial seed
Definition at line 99 of file Random.java.
References setSeed().
Member Function Documentation
synchronized int java::util::Random::next (int bits) [inline, protected]
Generates the next pseudorandom number. This returns an int value whose bits low order bits are independent chosen random bits (0 and 1 are equally likely). The implementation for java.util.Random is:
protected synchronized int next(int bits)
 {
     seed = (seed * 0x5DEECE66DL + 0xBL) & ((1L << 48) - 1);
     return (int) (seed >>> (48 - bits));
 }
Parameters
bits the number of random bits to generate, in the range 1..32
Returns
the next pseudorandom value
Definition at line 138 of file Random.java.
Referenced by nextDouble(), nextFloat(), nextInt(), and nextLong().
double java::util::Random::nextDouble () [inline]
Generates the next pseudorandom double uniformly distributed between 0.0 (inclusive) and 1.0 (exclusive). The implementation is as follows.
public double nextDouble()
 {
     return (((long) next(26) << 27) + next(27)) / (double)(1L << 53);
 }
Returns
the next pseudorandom double
Definition at line 273 of file Random.java.
References next().
float java::util::Random::nextFloat () [inline]
Generates the next pseudorandom float uniformly distributed between 0.0f (inclusive) and 1.0f (exclusive). The implementation is as follows.
public float nextFloat()
 {
     return next(24) / ((float)(1 << 24));
 }
Returns
the next pseudorandom float
Definition at line 256 of file Random.java.
References next().
int java::util::Random::nextInt (int n) [inline]
Generates the next pseudorandom number. This returns a value between 0(inclusive) and n(exclusive), and each value has the same likelihodd (1/n). (0 and 1 are equally likely). The implementation for java.util.Random is:
 public int nextInt(int n)
 {
     if (n <= 0)
         throw new IllegalArgumentException("n must be positive");
     if ((n & -n) == n) // i.e., n is a power of 2
         return (int)((n * (long) next(31)) >> 31);
     int bits, val;
     do
     {
         bits = next(31);
         val = bits % n;
     }
     while(bits - val + (n-1) < 0);
     return val;
 }
This algorithm would return every value with exactly the same probability, if the next()-method would be a perfect random number generator.
The loop at the bottom only accepts a value, if the random number was between 0 and the highest number less then 1<<31, which is divisible by n. The probability for this is high for small n, and the worst case is 1/2 (for n=(1<<30)+1).
The special treatment for n = power of 2, selects the high bits of the random number (the loop at the bottom would select the low order bits). This is done, because the low order bits of linear congruential number generators (like the one used in this class) are known to be ``less random'' than the high order bits.
Parameters
n the upper bound
Exceptions
IllegalArgumentException if the given upper bound is negative
Returns
the next pseudorandom value
Definition at line 208 of file Random.java.
References next().
int java::util::Random::nextInt () [inline]
Generates the next pseudorandom number. This returns an int value whose 32 bits are independent chosen random bits (0 and 1 are equally likely). The implementation for java.util.Random is:
public int nextInt()
 {
     return next(32);
 }
Returns
the next pseudorandom value
Definition at line 157 of file Random.java.
References next().
long java::util::Random::nextLong () [inline]
Generates the next pseudorandom long number. All bits of this long are independently chosen and 0 and 1 have equal likelihood. The implementation for java.util.Random is:
public long nextLong()
 {
     return ((long) next(32) << 32) + next(32);
 }
Returns
the next pseudorandom value
Definition at line 239 of file Random.java.
References next().
synchronized void java::util::Random::setSeed (long seed) [inline]
Sets the seed for this pseudorandom number generator. As described above, two instances of the same random class, starting with the same seed, should produce the same results, if the same methods are called. The implementation for java.util.Random is:
public synchronized void setSeed(long seed)
 {
     this.seed = (seed ^ 0x5DEECE66DL) & ((1L << 48) - 1);
     haveNextNextGaussian = false;
 }
Parameters
seed the new seed
Definition at line 118 of file Random.java.
Referenced by Random().
The documentation for this class was generated from the following file:
src/classpath/java/util/Random.java