java::io::OutputStreamWriter Class Reference
Public Member Functions
OutputStreamWriter (OutputStream out, String encoding) throws UnsupportedEncodingException
OutputStreamWriter (OutputStream out)
void write (int ch) throws IOException
void write (char[] buf, int offset, int count) throws IOException
void write (String str, int offset, int count) throws IOException
void flush () throws IOException
void close () throws IOException
Detailed Description
This class writes characters to an output stream that is byte oriented It converts the chars that are written to bytes using an encoding layer, which is specific to a particular encoding standard. The desired encoding can either be specified by name, or if no encoding is specified, the system default encoding will be used. The system default encoding name is determined from the system property file.encoding. The only encodings that are guaranteed to be available are `8859_1` (the Latin-1 character set) and `UTF8`. Unfortunately, Java does not provide a mechanism for listing the encodings that are supported in a given implementation.
Here is a list of standard encoding names that may be available:
8859_1 (ISO-8859-1/Latin-1)
ASCII (7-bit ASCII)
More Later
Author
Aaron M. Renn (arenn@urbanophile.com)
Per Bothner (bothner@cygnus.com)
Definition at line 63 of file OutputStreamWriter.java.
Constructor & Destructor Documentation
java::io::OutputStreamWriter::OutputStreamWriter (OutputStream out, String encoding) throws UnsupportedEncodingException [inline]
This method initializes a new instance of OutputStreamWriter to write to the specified stream using a caller supplied character encoding scheme. Note that due to a deficiency in the Java language design, there is no way to determine which encodings are supported.
Parameters
out The OutputStream to write to
encoding The name of the encoding scheme to use for character to byte translation
Exceptions
UnsupportedEncodingException If the named encoding is not available.
Definition at line 83 of file OutputStreamWriter.java.
java::io::OutputStreamWriter::OutputStreamWriter (OutputStream out) [inline]
This method initializes a new instance of OutputStreamWriter to write to the specified stream using the default encoding.
Parameters
out The OutputStream to write to
Definition at line 102 of file OutputStreamWriter.java.
Member Function Documentation
void java::io::OutputStreamWriter::close () throws IOException [inline, virtual]
This method closes this stream, and the underlying OutputStream
Exceptions
IOException If an error occurs
Implements java::io::Writer .
Definition at line 182 of file OutputStreamWriter.java.
References java::io::OutputStream::close(), flush(), and java::io::Writer::lock.
void java::io::OutputStreamWriter::flush () throws IOException [inline, virtual]
This method flushes any buffered bytes to the underlying output sink.
Exceptions
IOException If an error occurs
Implements java::io::Writer .
Definition at line 168 of file OutputStreamWriter.java.
References java::io::OutputStream::flush().
Referenced by close().
void java::io::OutputStreamWriter::write (char[] buf, int offset, int count) throws IOException [inline, virtual]
This method writes count characters from the specified array to the output stream starting at position offset into the array.
Parameters
buf The array of character to write from
offset The offset into the array to start writing chars from
count The number of chars to write.
Exceptions
IOException If an error occurs
Implements java::io::Writer .
Definition at line 130 of file OutputStreamWriter.java.
References java::io::OutputStream::write().
void java::io::OutputStreamWriter::write (String str, int offset, int count) throws IOException [inline]
This method writes count bytes from the specified String starting at position offset into the String.
Parameters
str The String to write chars from
offset The position in the String to start writing chars from
count The number of chars to write
Exceptions
IOException If an error occurs
Reimplemented from java::io::Writer .
Definition at line 155 of file OutputStreamWriter.java.
References write().
void java::io::OutputStreamWriter::write (int ch) throws IOException [inline]
This method writes a single character to the output stream.
Parameters
ch The char to write, passed as an int.
Exceptions
IOException If an error occurs
Reimplemented from java::io::Writer .
Definition at line 114 of file OutputStreamWriter.java.
Referenced by write().
The documentation for this class was generated from the following file:
src/classpath/java/io/OutputStreamWriter.java