src/jelatine/classfile.c File Reference
#include `wrappers.h`
#include `class.h`
#include `classfile.h`
#include `memory.h`
#include `util.h`
#include `vm.h`
Data Structures
struct path_t
struct classpath_t
Typedefs
typedef struct path_t path_t
typedef struct classpath_t classpath_t
Functions
static void set_classpath_string (path_t *, const char *)
void classpath_init (void)
void classpath_teardown (void)
static class_file_t * cf_open_with_classpath (const char *name, const path_t *cp)
class_file_t * cf_open (const char *name)
void cf_close (class_file_t *cf)
uint8_t cf_load_u1 (class_file_t *cf)
uint16_t cf_load_u2 (class_file_t *cf)
uint32_t cf_load_u4 (class_file_t *cf)
void cf_seek (class_file_t *cf, long offset, int whence)
long cf_tell (class_file_t *cf)
Variables
static classpath_t * classpath
Detailed Description
Class-file wrapper implementation
Definition in file classfile.c.
Typedef Documentation
typedef struct classpath_t classpath_t
Typedef for the struct classpath_t
Definition at line 58 of file classfile.c.
typedef struct path_t path_t
Typedef for the struct path_t
Definition at line 47 of file classfile.c.
Function Documentation
void cf_close (class_file_t * cf)
Closes a class file and disposes the relevant structure
Parameters
cf A pointer to the class_file_t structure to be closed and disposed
Definition at line 243 of file classfile.c.
References class_file_t::file, gc_free(), class_file_t::jar, and class_file_t::plain.
Referenced by load_bytecode(), load_class(), and load_exception_handlers().
uint8_t cf_load_u1 (class_file_t * cf)
Reads a single-byte value from the provided class-file, throws an exception if the end of the file has been already reached
Parameters
cf A pointer to an open class-file
Returns
A single-byte constant read from the class-file
Definition at line 263 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by cp_create(), and load_bytecode().
uint16_t cf_load_u2 (class_file_t * cf)
Reads a two-bytes value from the provided class-file, throws an exception if the end of the file has been already reached
Parameters
cf A pointer to an open class-file
Returns
A two-bytes constant read from the class-file
Definition at line 291 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by cp_create(), derive_class(), load_attribute_Code_attributes(), load_attributes(), load_exception_handlers(), load_field_attribute_ConstantValue(), load_field_attributes(), load_field_info(), load_fields(), load_interfaces(), load_method_attribute_Code(), load_method_attribute_Exceptions(), load_method_attributes(), and load_methods().
uint32_t cf_load_u4 (class_file_t * cf)
Reads a four-bytes value from the provided class-file, throws an exception if the end of the file has been already reached
Parameters
cf A pointer to an open class-file
Returns
A four-bytes constant read from the class-file
Definition at line 319 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by cp_create(), derive_class(), load_attribute_Code_attributes(), load_attributes(), load_field_attributes(), load_method_attribute_Code(), and load_method_attributes().
class_file_t* cf_open (const char * name)
Opens a class file with the specified class name (in the internal class format) looking in the classpath directory or JAR file, throws an exception if the class file cannot be found or opened.
Parameters
name The class name
Definition at line 212 of file classfile.c.
References classpath_t::boot, c_throw, cf_open_with_classpath(), classpath_t::entries, JAVA_LANG_NOCLASSDEFFOUNDERROR, and classpath_t::user.
Referenced by load_bytecode(), load_class(), and load_exception_handlers().
static class_file_t* cf_open_with_classpath (const char * name, const path_t * cp) [static]
Opens a class file by looking it up in the specified classpath
Parameters
name The class name
cp The classpath used for the class lookup
Returns
A new classfile object, throws an exception upon failure
Definition at line 152 of file classfile.c.
References class_file_t::file, gc_free(), gc_malloc(), class_file_t::jar, class_file_t::plain, and path_t::str.
Referenced by cf_open().
void cf_seek (class_file_t * cf, long offset, int whence)
Seeks to the position specified by the offset parameter, throws an exception if the position is out of the file's range. This function's semantic is the same as fseek() but only the SEEK_SET and SEEK_CUR whence modes are supported
Parameters
cf A pointer to an open class-file
offset The new position in the class-file
whence From where to start seeking
Definition at line 350 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by load_attribute_Code_attributes(), load_attributes(), load_bytecode(), load_exception_handlers(), load_field_attributes(), load_method_attribute_Code(), and load_method_attributes().
long cf_tell (class_file_t * cf)
Returns the position inside the current class-file
Parameters
cf A pointer to an open class-file
Returns
An integer holding the current position inside the class-file
Definition at line 374 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by load_attribute_Code_attributes(), load_attributes(), load_field_attributes(), load_method_attribute_Code(), and load_method_attributes().
void classpath_init (void)
Initializes the classpath by processing the related options
Definition at line 102 of file classfile.c.
References classpath_t::boot, classpath_t::entries, gc_palloc(), opts_get_boot_classpath(), opts_get_classpath(), set_classpath_string(), and classpath_t::user.
Referenced by vm_init().
void classpath_teardown (void)
Tear down the classpath
Definition at line 132 of file classfile.c.
References classpath_t::entries, and classpath_t::user.
Referenced by vm_teardown().
static void set_classpath_string (path_t * path, const char * str) [static]
Set the classpath string provided in str
Parameters
path The path to be set
str The input string
Definition at line 81 of file classfile.c.
References c_throw, JAVA_LANG_VIRTUALMACHINEERROR, and path_t::str.
Referenced by classpath_init().
Variable Documentation
classpath_t* classpath [static]
Global classpath information
Definition at line 65 of file classfile.c.