java::util::TimeZone Class Reference
Public Member Functions
abstract int getOffset (int era, int year, int month, int day, int dayOfWeek, int milliseconds) throws IllegalArgumentException
abstract int getRawOffset ()
abstract boolean useDaylightTime ()
String getID ()
Static Public Member Functions
static TimeZone getTimeZone (String ID)
static TimeZone getDefault ()
static String[] getAvailableIDs ()
Detailed Description
This class represents a time zone offset and handles daylight savings.
You can get the default time zone with getDefault. This represents the time zone where program is running.
Another way to create a time zone is getTimeZone, where you can give an identifier as parameter. For instance, the identifier of the Central European Time zone is `CET`.
With the getAvailableIDs method, you can get all the supported time zone identifiers.
See also
Calendar
SimpleTimeZone
Author
Jochen Hoenicke
Definition at line 61 of file TimeZone.java.
Member Function Documentation
static String [] java::util::TimeZone::getAvailableIDs () [inline, static]
Gets all the avaible IDs supported
Returns
An array with all the supported IDs
Definition at line 142 of file TimeZone.java.
static TimeZone java::util::TimeZone::getDefault () [inline, static]
Returns the time zone under which the host is running. This can be changed with setDefault.
Returns
A clone of the current default time zone for this host.
Definition at line 129 of file TimeZone.java.
Referenced by java::util::Calendar::Calendar(), and getTimeZone().
String java::util::TimeZone::getID () [inline]
Gets the identifier of this time zone. For instance, PST for Pacific Standard Time.
Returns
the ID of this time zone.
Definition at line 105 of file TimeZone.java.
Referenced by jelatine::VMTimeZone::toString(), and java::util::Date::toString().
abstract int java::util::TimeZone::getOffset (int era, int year, int month, int day, int dayOfWeek, int milliseconds) throws IllegalArgumentException [pure virtual]
Gets the time zone offset, for current date, modified in case of daylight savings. This is the offset to add to UTC to get the local time.
Parameters
era the era of the given date
year the year of the given date
month the month of the given date, 0 for January.
day the day of month
dayOfWeek the day of week
milliseconds the millis in the day (in local standard time)
Returns
the time zone offset in milliseconds.
Implemented in jelatine::VMTimeZone .
abstract int java::util::TimeZone::getRawOffset () [pure virtual]
Gets the time zone offset, ignoring daylight savings. This is the offset to add to UTC to get the local time.
Returns
the time zone offset in milliseconds.
Implemented in jelatine::VMTimeZone .
Referenced by java::util::Calendar::clear().
static TimeZone java::util::TimeZone::getTimeZone (String ID) [inline, static]
Gets the TimeZone for the given ID.
Parameters
ID the time zone identifier.
Returns
The time zone for the identifier or GMT, if no such time zone exists.
Definition at line 117 of file TimeZone.java.
References getDefault().
abstract boolean java::util::TimeZone::useDaylightTime () [pure virtual]
Returns true, if this time zone uses Daylight Savings Time.
Implemented in jelatine::VMTimeZone .
The documentation for this class was generated from the following file:
src/classpath/java/util/TimeZone.java