java::io::Writer Class Reference
Public Member Functions
void write (int b) throws IOException
void write (char[] buf) throws IOException
abstract void write (char[] buf, int offset, int len) throws IOException
void write (String str) throws IOException
void write (String str, int offset, int len) throws IOException
abstract void flush () throws IOException
abstract void close () throws IOException
Protected Member Functions
Writer ()
Writer (Object lock)
Protected Attributes
Object lock
Detailed Description
This abstract class forms the base of the hierarchy of classes that write output as a stream of chars. It provides a common set of methods for writing chars to stream. Subclasses implement and/or extend these methods to write chars in a particular manner or to a particular destination such as a file on disk or network connection.
Author
Aaron M. Renn (arenn@urbanophile.com)
Per Bothner (bothner@cygnus.com)
Definition at line 56 of file Writer.java.
Constructor & Destructor Documentation
java::io::Writer::Writer () [inline, protected]
This is the default no-argument constructor for this class. This method will set up the class to synchronize criticial sections on itself.
Definition at line 69 of file Writer.java.
References lock.
java::io::Writer::Writer (Object lock) [inline, protected]
This method initializes a Writer that will synchronize on the specified Object.
Parameters
lock The Object to use for synchronizing critical sections. Must not be null.
Definition at line 81 of file Writer.java.
Member Function Documentation
abstract void java::io::Writer::close () throws IOException [pure virtual]
This method closes the stream. Any internal or native resources associated with this stream are freed. Any subsequent attempt to access the stream might throw an exception.
This method in this class does nothing.
Exceptions
IOException If an error occurs
Implemented in java::io::OutputStreamWriter .
abstract void java::io::Writer::flush () throws IOException [pure virtual]
This method forces any data that may have been buffered to be written to the underlying output device. Please note that the host environment might perform its own buffering unbeknowst to Java. In that case, a write made (for example, to a disk drive) might be cached in OS buffers instead of actually being written to disk.
Exceptions
IOException If an error occurs
Implemented in java::io::OutputStreamWriter .
abstract void java::io::Writer::write (char[] buf, int offset, int len) throws IOException [pure virtual]
This method writes len char from the specified array buf starting at index offset into the array.
Subclasses must provide an implementation of this abstract method.
Parameters
buf The array of char to write from
offset The index into the array to start writing from
len The number of char to write
Exceptions
IOException If an error occurs
Implemented in java::io::OutputStreamWriter .
void java::io::Writer::write (String str, int offset, int len) throws IOException [inline]
This method writes len chars from the String starting at position offset.
Parameters
str The String that is to be written
offset The character offset into the String to start writing from
len The number of chars to write
Exceptions
IOException If an error occurs
Reimplemented in java::io::OutputStreamWriter .
Definition at line 158 of file Writer.java.
References write().
void java::io::Writer::write (String str) throws IOException [inline]
This method writes all the characters in a String to the output.
Parameters
str The String whose chars are to be written.
Exceptions
IOException If an error occurs
Definition at line 142 of file Writer.java.
References write().
void java::io::Writer::write (int b) throws IOException [inline]
This method writes a single char to the output stream.
Parameters
b The char to be written to the output stream, passed as an int
Exceptions
IOException If an error occurs
Reimplemented in java::io::OutputStreamWriter .
Definition at line 96 of file Writer.java.
Referenced by write().
void java::io::Writer::write (char[] buf) throws IOException [inline]
This method all the writes char from the passed array to the output stream. This method is equivalent to write(buf, 0, buf.length) which is exactly how it is implemented in this class.
Parameters
buf The array of char to write
Exceptions
IOException If an error occurs
Definition at line 114 of file Writer.java.
References write().
Field Documentation
Object java::io::Writer::lock [protected]
This is the object used to synchronize criticial code sections for thread safety. Subclasses should use this field instead of using synchronized methods or explicity synchronizations on this
Definition at line 63 of file Writer.java.
Referenced by java::io::OutputStreamWriter::close(), and Writer().
The documentation for this class was generated from the following file:
src/classpath/java/io/Writer.java