java::util::Calendar Class Reference
Public Member Functions
final Date getTime ()
final void setTime (Date date)
long getTimeInMillis ()
void setTimeInMillis (long time)
final int get (int field) throws ArrayIndexOutOfBoundsException
void set (int field, int value) throws ArrayIndexOutOfBoundsException
boolean equals (Object o)
boolean before (Object o)
boolean after (Object o)
void setTimeZone (TimeZone zone)
TimeZone getTimeZone ()
final void clear ()
Static Public Member Functions
static synchronized Calendar getInstance ()
static synchronized Calendar getInstance (TimeZone zone)
Static Public Attributes
static final int YEAR = 1
static final int MONTH = 2
static final int DATE = 5
static final int DAY_OF_MONTH = 5
static final int DAY_OF_WEEK = 7
static final int AM_PM = 9
static final int HOUR = 10
static final int HOUR_OF_DAY = 11
static final int MINUTE = 12
static final int SECOND = 13
static final int MILLISECOND = 14
static final int SUNDAY = 1
static final int MONDAY = 2
static final int TUESDAY = 3
static final int WEDNESDAY = 4
static final int THURSDAY = 5
static final int FRIDAY = 6
static final int SATURDAY = 7
static final int JANUARY = 0
static final int FEBRUARY = 1
static final int MARCH = 2
static final int APRIL = 3
static final int MAY = 4
static final int JUNE = 5
static final int JULY = 6
static final int AUGUST = 7
static final int SEPTEMBER = 8
static final int OCTOBER = 9
static final int NOVEMBER = 10
static final int DECEMBER = 11
static final int AM = 0
static final int PM = 1
static final int FIELD_COUNT = 15
Protected Member Functions
Calendar ()
void complete ()
abstract void computeTime ()
abstract void computeFields ()
Protected Attributes
int[] fields = new int[FIELD_COUNT]
boolean[] isSet = new boolean[FIELD_COUNT]
long time
boolean isTimeSet
boolean areFieldsSet
Detailed Description
This class is an abstract base class for Calendars, which can be used to convert between Date objects and a set of integer fields which represent YEAR, MONTH, DAY, etc. The Date object represents a time in milliseconds since the Epoch.
This class is locale sensitive. To get the Object matching the current locale you can use getInstance. You can even provide a locale or a timezone. getInstance returns currently a GregorianCalendar for the current date.
If you want to convert a date from the Year, Month, Day, DayOfWeek, etc. Representation to a Date-Object, you can create a new Calendar with getInstance(), clear() all fields, set(int,int) the fields you need and convert it with getTime().
If you want to convert a Date-object to the Calendar representation, create a new Calendar, assign the Date-Object with setTime(), and read the fields with get(int).
When computing the date from time fields, it may happen, that there are either two few fields set, or some fields are inconsistent. This cases will handled in a calendar specific way. Missing fields are replaced by the fields of the epoch: 1970 January 1 00:00.
To understand, how the day of year is computed out of the fields look at the following table. It is traversed from top to bottom, and for the first line all fields are set, that line is used to compute the day.
month + day_of_month
month + week_of_month + day_of_week
month + day_of_week_of_month + day_of_week
day_of_year
day_of_week + week_of_year
The hour_of_day-field takes precedence over the ampm and hour_of_ampm fields.
Note: This can differ for non-Gregorian calendar.
Other useful things you can do with an calendar, is rolling fields (that means increase/decrease a specific field by one, propagating overflows), or adding/substracting a fixed amount to a field.
See also
Date
TimeZone
Definition at line 95 of file Calendar.java.
Constructor & Destructor Documentation
java::util::Calendar::Calendar () [inline, protected]
Constructs a new Calendar with the default time zone and the default locale.
Definition at line 303 of file Calendar.java.
References clear(), and java::util::TimeZone::getDefault().
Member Function Documentation
boolean java::util::Calendar::after (Object o) [inline]
Compares the given calendar with this.
Parameters
o the object to that we should compare.
Returns
true, if the given object is a calendar, and this calendar represents a bigger time than the calendar o.
Exceptions
ClassCastException if o is not an calendar.
Definition at line 468 of file Calendar.java.
References getTimeInMillis().
boolean java::util::Calendar::before (Object o) [inline]
Compares the given calendar with this.
Parameters
o the object to that we should compare.
Returns
true, if the given object is a calendar, and this calendar represents a smaller time than the calendar o.
Exceptions
ClassCastException if o is not an calendar.
Definition at line 453 of file Calendar.java.
References getTimeInMillis().
final void java::util::Calendar::clear () [inline]
Clears the values of all the time fields.
Definition at line 523 of file Calendar.java.
References AM, areFieldsSet, FIELD_COUNT, fields, java::util::TimeZone::getRawOffset(), isSet, isTimeSet, JANUARY, and THURSDAY.
Referenced by Calendar(), and setTimeInMillis().
void java::util::Calendar::complete () [inline, protected]
Fills any unset fields in the time field list
Definition at line 497 of file Calendar.java.
References areFieldsSet, computeFields(), computeTime(), and isTimeSet.
Referenced by get(), and jelatine::VMCalendar::VMCalendar().
abstract void java::util::Calendar::computeFields () [protected, pure virtual]
Converts the milliseconds since the epoch UTC (time) to time fields (fields). Override this method if you write your own Calendar.
Implemented in jelatine::VMCalendar .
Referenced by complete(), and setTimeInMillis().
abstract void java::util::Calendar::computeTime () [protected, pure virtual]
Converts the time field values (fields) to milliseconds since the epoch UTC (time). Override this method if you write your own Calendar.
Implemented in jelatine::VMCalendar .
Referenced by complete(), getTime(), and getTimeInMillis().
boolean java::util::Calendar::equals (Object o) [inline]
Compares the given calendar with this.
Parameters
o the object to that we should compare.
Returns
true, if the given object is a calendar, that represents the same time (but doesn't necessary have the same fields).
Definition at line 429 of file Calendar.java.
References getTimeInMillis(), and getTimeZone().
final int java::util::Calendar::get (int field) throws ArrayIndexOutOfBoundsException [inline]
Gets the value of the specified field. They are recomputed if they are invalid.
Parameters
field the time field. One of the time field constants.
Returns
the value of the specified field
Exceptions
ArrayIndexOutOfBoundsException if the field is outside the valid range. The value of field must be >= 0 and <= FIELD_COUNT.
Definition at line 392 of file Calendar.java.
References areFieldsSet, complete(), fields, and isSet.
Referenced by java::util::Date::toString().
static synchronized Calendar java::util::Calendar::getInstance (TimeZone zone) [inline, static]
Creates a calendar representing the actual time, using the given time zone and the default locale.
Parameters
zone a time zone.
Definition at line 347 of file Calendar.java.
References getInstance(), and setTimeZone().
static synchronized Calendar java::util::Calendar::getInstance () [inline, static]
Creates a calendar representing the actual time, using the default time zone and locale.
Definition at line 337 of file Calendar.java.
Referenced by getInstance().
final Date java::util::Calendar::getTime () [inline]
Converts the time represented by this object to a Date-Object.
Returns
the Date.
Definition at line 315 of file Calendar.java.
References computeTime(), isTimeSet, and time.
long java::util::Calendar::getTimeInMillis () [inline]
Returns the time represented by this Calendar.
Returns
the time in milliseconds since the epoch.
Definition at line 359 of file Calendar.java.
References computeTime(), isTimeSet, and time.
Referenced by after(), before(), and equals().
TimeZone java::util::Calendar::getTimeZone () [inline]
Gets the time zone of this calendar
Returns
the current time zone.
Definition at line 489 of file Calendar.java.
Referenced by equals(), and java::util::Date::toString().
void java::util::Calendar::set (int field, int value) throws ArrayIndexOutOfBoundsException [inline]
Sets the time field with the given value. This does invalidate the time in milliseconds.
Parameters
field the time field. One of the time field constants
value the value to be set.
Exceptions
ArrayIndexOutOfBoundsException if field is outside the valid range. The value of field must be >= 0 and <= FIELD_COUNT.
Definition at line 412 of file Calendar.java.
References FIELD_COUNT, fields, isSet, and isTimeSet.
final void java::util::Calendar::setTime (Date date) [inline]
Sets this Calendar's time to the given Date. All time fields are invalidated by this method.
Parameters
date the Date
Definition at line 328 of file Calendar.java.
References java::util::Date::getTime(), and setTimeInMillis().
void java::util::Calendar::setTimeInMillis (long time) [inline]
Sets this Calendar's time to the given Time. All time fields are invalidated by this method.
Parameters
time the time in milliseconds since the epoch
Definition at line 375 of file Calendar.java.
References clear(), computeFields(), and isTimeSet.
Referenced by setTime(), java::util::Date::toString(), and jelatine::VMCalendar::VMCalendar().
void java::util::Calendar::setTimeZone (TimeZone zone) [inline]
Sets the time zone to the specified value.
Parameters
zone the new time zone
Definition at line 480 of file Calendar.java.
Referenced by getInstance().
Field Documentation
final int java::util::Calendar::AM = 0 [static]
Useful constant for 12-hour clock.
Definition at line 253 of file Calendar.java.
Referenced by clear(), and jelatine::VMCalendar::computeFields().
final int java::util::Calendar::AM_PM = 9 [static]
Constant representing the part of the day for 12-hour clock. This should be one of AM or PM.
Definition at line 128 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
final int java::util::Calendar::APRIL = 3 [static]
Constant representing April.
Definition at line 208 of file Calendar.java.
boolean java::util::Calendar::areFieldsSet [protected]
Tells if the fields have a valid value. This superseeds the isSet array.
Definition at line 290 of file Calendar.java.
Referenced by clear(), complete(), jelatine::VMCalendar::computeFields(), and get().
final int java::util::Calendar::AUGUST = 7 [static]
Constant representing August.
Definition at line 228 of file Calendar.java.
final int java::util::Calendar::DATE = 5 [static]
Constant representing the day time field, synonym for DAY_OF_MONTH.
Definition at line 111 of file Calendar.java.
final int java::util::Calendar::DAY_OF_MONTH = 5 [static]
Constant representing the day time field.
Definition at line 116 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
final int java::util::Calendar::DAY_OF_WEEK = 7 [static]
Constant representing the day of week time field. This field should contain one of the SUNDAY,...,SATURDAY constants below.
Definition at line 122 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
final int java::util::Calendar::DECEMBER = 11 [static]
Constant representing December.
Definition at line 248 of file Calendar.java.
final int java::util::Calendar::FEBRUARY = 1 [static]
Constant representing February.
Definition at line 198 of file Calendar.java.
final int java::util::Calendar::FIELD_COUNT = 15 [static]
Number of time fields.
Definition at line 263 of file Calendar.java.
Referenced by clear(), and set().
int [] java::util::Calendar::fields = new int[FIELD_COUNT] [protected]
The time fields. The array is indexed by the constants YEAR to DST_OFFSET.
Definition at line 269 of file Calendar.java.
Referenced by clear(), jelatine::VMCalendar::computeFields(), jelatine::VMCalendar::computeTime(), get(), and set().
final int java::util::Calendar::FRIDAY = 6 [static]
Constant representing Friday.
Definition at line 183 of file Calendar.java.
final int java::util::Calendar::HOUR = 10 [static]
Constant representing the hour time field for 12-hour clock.
Definition at line 133 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
final int java::util::Calendar::HOUR_OF_DAY = 11 [static]
Constant representing the hour of day time field for 24-hour clock.
Definition at line 138 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
boolean [] java::util::Calendar::isSet = new boolean[FIELD_COUNT] [protected]
The flags which tell if the fields above have a value.
Definition at line 274 of file Calendar.java.
Referenced by clear(), jelatine::VMCalendar::computeFields(), jelatine::VMCalendar::computeTime(), get(), and set().
boolean java::util::Calendar::isTimeSet [protected]
Tells if the above field has a valid value.
Definition at line 284 of file Calendar.java.
Referenced by clear(), complete(), jelatine::VMCalendar::computeTime(), getTime(), getTimeInMillis(), set(), and setTimeInMillis().
final int java::util::Calendar::JANUARY = 0 [static]
Constant representing January.
Definition at line 193 of file Calendar.java.
Referenced by clear().
final int java::util::Calendar::JULY = 6 [static]
Constant representing July.
Definition at line 223 of file Calendar.java.
final int java::util::Calendar::JUNE = 5 [static]
Constant representing June.
Definition at line 218 of file Calendar.java.
final int java::util::Calendar::MARCH = 2 [static]
Constant representing March.
Definition at line 203 of file Calendar.java.
final int java::util::Calendar::MAY = 4 [static]
Constant representing May.
Definition at line 213 of file Calendar.java.
final int java::util::Calendar::MILLISECOND = 14 [static]
Constant representing the millisecond time field.
Definition at line 153 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
final int java::util::Calendar::MINUTE = 12 [static]
Constant representing the minute of hour time field.
Definition at line 143 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
final int java::util::Calendar::MONDAY = 2 [static]
Constant representing Monday.
Definition at line 163 of file Calendar.java.
final int java::util::Calendar::MONTH = 2 [static]
Constant representing the month time field. This field should contain one of the JANUARY,...,DECEMBER constants below.
Definition at line 106 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
final int java::util::Calendar::NOVEMBER = 10 [static]
Constant representing November.
Definition at line 243 of file Calendar.java.
final int java::util::Calendar::OCTOBER = 9 [static]
Constant representing October.
Definition at line 238 of file Calendar.java.
final int java::util::Calendar::PM = 1 [static]
Useful constant for 12-hour clock.
Definition at line 258 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
final int java::util::Calendar::SATURDAY = 7 [static]
Constant representing Saturday.
Definition at line 188 of file Calendar.java.
final int java::util::Calendar::SECOND = 13 [static]
Constant representing the second time field.
Definition at line 148 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
final int java::util::Calendar::SEPTEMBER = 8 [static]
Constant representing September.
Definition at line 233 of file Calendar.java.
final int java::util::Calendar::SUNDAY = 1 [static]
Constant representing Sunday.
Definition at line 158 of file Calendar.java.
final int java::util::Calendar::THURSDAY = 5 [static]
Constant representing Thursday.
Definition at line 178 of file Calendar.java.
Referenced by clear(), and jelatine::VMCalendar::computeTime().
long java::util::Calendar::time [protected]
The time in milliseconds since the epoch.
Definition at line 279 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), jelatine::VMCalendar::computeTime(), getTime(), and getTimeInMillis().
final int java::util::Calendar::TUESDAY = 3 [static]
Constant representing Tuesday.
Definition at line 168 of file Calendar.java.
final int java::util::Calendar::WEDNESDAY = 4 [static]
Constant representing Wednesday.
Definition at line 173 of file Calendar.java.
final int java::util::Calendar::YEAR = 1 [static]
Constant representing the year time field.
Definition at line 100 of file Calendar.java.
Referenced by jelatine::VMCalendar::computeFields(), and jelatine::VMCalendar::computeTime().
The documentation for this class was generated from the following file:
src/classpath/java/util/Calendar.java