src/jelatine/classfile.h File Reference
#include `wrappers.h`
#include `util.h`
Data Structures
struct class_file_t
struct field_info_t
struct field_attributes_t
struct method_attributes_t
Defines
#define JELATINE_CLASSFILE_H (1)
#define CLASS_ACC_FLAGS_MASK (ACC_PUBLIC | ACC_FINAL | ACC_SUPER | ACC_INTERFACE | ACC_ABSTRACT)
#define FIELD_ACC_FLAGS_MASK
#define METHOD_ACC_FLAGS_MASK
Typedefs
typedef enum primitive_type_t primitive_type_t
typedef enum const_pool_type_t const_pool_type_t
typedef enum access_flags_t access_flags_t
typedef struct class_file_t class_file_t
typedef struct field_info_t field_info_t
typedef struct field_attributes_t field_attributes_t
typedef struct method_attributes_t method_attributes_t
Enumerations
enum primitive_type_t {
PT_BYTE,
PT_BOOL,
PT_CHAR,
PT_SHORT,
PT_INT,
PT_FLOAT,
PT_LONG,
PT_DOUBLE,
PT_REFERENCE,
PT_VOID
 }
enum const_pool_type_t {
CONSTANT_Utf8 = 1,
CONSTANT_Integer = 3,
CONSTANT_Float = 4,
CONSTANT_Long = 5,
CONSTANT_Double = 6,
CONSTANT_Class = 7,
CONSTANT_String = 8,
CONSTANT_Fieldref = 9,
CONSTANT_Methodref = 10,
CONSTANT_InterfaceMethodref = 11,
CONSTANT_NameAndType = 12,
CONSTANT_Class_resolved = 13,
CONSTANT_Fieldref_resolved = 14,
CONSTANT_Methodref_resolved = 15,
CONSTANT_InterfaceMethodref_resolved = 2
 }
enum access_flags_t {
ACC_PUBLIC = 0x0001,
ACC_PRIVATE = 0x0002,
ACC_PROTECTED = 0x0004,
ACC_STATIC = 0x0008,
ACC_FINAL = 0x0010,
ACC_SYNCHRONIZED = 0x0020,
ACC_SUPER = 0x0020,
ACC_VOLATILE = 0x0040,
ACC_TRANSIENT = 0x0080,
ACC_NATIVE = 0x0100,
ACC_INTERFACE = 0x0200,
ACC_ABSTRACT = 0x0400,
ACC_STRICT = 0x0800,
ACC_ARRAY = 0x1000,
ACC_HAS_FINALIZER = 0x2000,
ACC_LINKED = 0x1000,
ACC_MAIN = 0x2000
 }
Functions
void classpath_init (void)
void classpath_teardown (void)
class_file_t * cf_open (const char *)
void cf_close (class_file_t *)
uint8_t cf_load_u1 (class_file_t *)
uint16_t cf_load_u2 (class_file_t *)
uint32_t cf_load_u4 (class_file_t *)
void cf_seek (class_file_t *, long, int)
long cf_tell (class_file_t *)
Detailed Description
Wrapper structure for class file access, this file also contains the definitions which can be found in a class-file
Definition in file classfile.h.
Define Documentation
#define CLASS_ACC_FLAGS_MASK (ACC_PUBLIC | ACC_FINAL | ACC_SUPER | ACC_INTERFACE | ACC_ABSTRACT)
Mask of defined flags of a class access_flags field
Definition at line 123 of file classfile.h.
#define FIELD_ACC_FLAGS_MASK
Value:
(ACC_PUBLIC | ACC_PRIVATE | ACC_PROTECTED | ACC_STATIC | ACC_FINAL |
    ACC_VOLATILE | ACC_TRANSIENT)
Mask of defined flags of a field access_flags field
Definition at line 126 of file classfile.h.
#define JELATINE_CLASSFILE_H (1)
classfile.h inclusion macro
Definition at line 29 of file classfile.h.
#define METHOD_ACC_FLAGS_MASK
Value:
(ACC_PUBLIC | ACC_PRIVATE | ACC_PROTECTED | ACC_STATIC | ACC_FINAL |
    ACC_SYNCHRONIZED | ACC_NATIVE | ACC_ABSTRACT | ACC_STRICT)
Mask of defined flags of a method access_flags field
Definition at line 130 of file classfile.h.
Typedef Documentation
typedef enum access_flags_t access_flags_t
Typedef for enum access_flags_t
Definition at line 120 of file classfile.h.
typedef struct class_file_t class_file_t
Typedef for struct class_file_t
Definition at line 150 of file classfile.h.
typedef enum const_pool_type_t const_pool_type_t
Typedef for enum const_pool_type_t
Definition at line 93 of file classfile.h.
typedef struct field_attributes_t field_attributes_t
Typedef for struct field_attributes_t
Definition at line 190 of file classfile.h.
typedef struct field_info_t field_info_t
Typedef for struct field_info_t
Definition at line 180 of file classfile.h.
typedef struct method_attributes_t method_attributes_t
Typedef for struct method_attributes_t
Definition at line 205 of file classfile.h.
typedef enum primitive_type_t primitive_type_t
Typedef for enum primitive_type_t
Definition at line 66 of file classfile.h.
Enumeration Type Documentation
enum access_flags_t
Represents the different access flags of a class, field or method
Enumerator:
ACC_PUBLIC
 Public access is allowed.
ACC_PRIVATE
 This field or method is private.
ACC_PROTECTED
 This field is protected.
ACC_STATIC
 This field or method is static.
ACC_FINAL
 This object or method cannot be modified.
ACC_SYNCHRONIZED
 This method is synchronized.
ACC_SUPER
 Alters the behaviour of INVOKESPECIAL.
ACC_VOLATILE
 This field cannot be cached.
ACC_TRANSIENT
 Not written or read by a POM.
ACC_NATIVE
 This method is native.
ACC_INTERFACE
 This class is an interface.
ACC_ABSTRACT
 This class is abstract.
ACC_STRICT
 This method is strict-fp.
ACC_ARRAY
 This class is an array.
ACC_HAS_FINALIZER
 This class has a finalizer.
ACC_LINKED
 This method has been linked.
ACC_MAIN
 This is the main() method.
Definition at line 97 of file classfile.h.
enum const_pool_type_t
Defines the type of a constant pool element. Note that some of the entries are not part of the Java VM spec but were specifically added by the Jelatine JVM. Those are not found in regular class files but will be used by its in-memory representation
Enumerator:
CONSTANT_Utf8
 Modified UTF8 string.
CONSTANT_Integer
 32-bit Integer constant
CONSTANT_Float
 Single-precision floating point constant.
CONSTANT_Long
 64-bit Integer constant
CONSTANT_Double
 Double-precision floating point constant.
CONSTANT_Class
 Represents a class or an interface.
CONSTANT_String
 Java string constant.
CONSTANT_Fieldref
 Represents a class' field.
CONSTANT_Methodref
 Represents a class' method.
CONSTANT_InterfaceMethodref
 Represents an interface's method.
CONSTANT_NameAndType
 Name and type of a field or method.
CONSTANT_Class_resolved
 Represents a resolved class.
CONSTANT_Fieldref_resolved
 Represents a resolved field.
CONSTANT_Methodref_resolved
 Represents a resolved method.
CONSTANT_InterfaceMethodref_resolved
 Represents a resolved interface method.
Definition at line 73 of file classfile.h.
enum primitive_type_t
Represents the basic type of a field or element of a Java class
Enumerator:
PT_BYTE
 Field of type byte.
PT_BOOL
 Field of type bool.
PT_CHAR
 Field of type char.
PT_SHORT
 Field of type short.
PT_INT
 Field of type int.
PT_FLOAT
 Field of type float.
PT_LONG
 Field of type long.
PT_DOUBLE
 Field of type double.
PT_REFERENCE
 Generic reference field.
PT_VOID
 Used only for method descriptors!
Definition at line 52 of file classfile.h.
Function Documentation
void cf_close (class_file_t * cf)
Closes a class file and disposes the relevant structure
Parameters
cf A pointer to the class_file_t structure to be closed and disposed
Definition at line 243 of file classfile.c.
References class_file_t::file, gc_free(), class_file_t::jar, and class_file_t::plain.
Referenced by load_bytecode(), load_class(), and load_exception_handlers().
uint8_t cf_load_u1 (class_file_t * cf)
Reads a single-byte value from the provided class-file, throws an exception if the end of the file has been already reached
Parameters
cf A pointer to an open class-file
Returns
A single-byte constant read from the class-file
Definition at line 263 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by cp_create(), and load_bytecode().
uint16_t cf_load_u2 (class_file_t * cf)
Reads a two-bytes value from the provided class-file, throws an exception if the end of the file has been already reached
Parameters
cf A pointer to an open class-file
Returns
A two-bytes constant read from the class-file
Definition at line 291 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by cp_create(), derive_class(), load_attribute_Code_attributes(), load_attributes(), load_exception_handlers(), load_field_attribute_ConstantValue(), load_field_attributes(), load_field_info(), load_fields(), load_interfaces(), load_method_attribute_Code(), load_method_attribute_Exceptions(), load_method_attributes(), and load_methods().
uint32_t cf_load_u4 (class_file_t * cf)
Reads a four-bytes value from the provided class-file, throws an exception if the end of the file has been already reached
Parameters
cf A pointer to an open class-file
Returns
A four-bytes constant read from the class-file
Definition at line 319 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by cp_create(), derive_class(), load_attribute_Code_attributes(), load_attributes(), load_field_attributes(), load_method_attribute_Code(), and load_method_attributes().
class_file_t* cf_open (const char * name)
Opens a class file with the specified class name (in the internal class format) looking in the classpath directory or JAR file, throws an exception if the class file cannot be found or opened.
Parameters
name The class name
Definition at line 212 of file classfile.c.
References classpath_t::boot, c_throw, cf_open_with_classpath(), classpath_t::entries, JAVA_LANG_NOCLASSDEFFOUNDERROR, and classpath_t::user.
Referenced by load_bytecode(), load_class(), and load_exception_handlers().
void cf_seek (class_file_t * cf, long offset, int whence)
Seeks to the position specified by the offset parameter, throws an exception if the position is out of the file's range. This function's semantic is the same as fseek() but only the SEEK_SET and SEEK_CUR whence modes are supported
Parameters
cf A pointer to an open class-file
offset The new position in the class-file
whence From where to start seeking
Definition at line 350 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by load_attribute_Code_attributes(), load_attributes(), load_bytecode(), load_exception_handlers(), load_field_attributes(), load_method_attribute_Code(), and load_method_attributes().
long cf_tell (class_file_t * cf)
Returns the position inside the current class-file
Parameters
cf A pointer to an open class-file
Returns
An integer holding the current position inside the class-file
Definition at line 374 of file classfile.c.
References c_throw, class_file_t::file, class_file_t::jar, JAVA_LANG_NOCLASSDEFFOUNDERROR, and class_file_t::plain.
Referenced by load_attribute_Code_attributes(), load_attributes(), load_field_attributes(), load_method_attribute_Code(), and load_method_attributes().
void classpath_init (void)
Initializes the classpath by processing the related options
Definition at line 102 of file classfile.c.
References classpath_t::boot, classpath_t::entries, gc_palloc(), opts_get_boot_classpath(), opts_get_classpath(), set_classpath_string(), and classpath_t::user.
Referenced by vm_init().
void classpath_teardown (void)
Tear down the classpath
Definition at line 132 of file classfile.c.
References classpath_t::entries, and classpath_t::user.
Referenced by vm_teardown().