jelatine::VMTimeZone Class Reference
Public Member Functions
VMTimeZone (int rawOffset, String id)
void setStartYear (int year)
void setStartRule (int month, int day, int dayOfWeek, int time)
void setStartRule (int month, int day, int dayOfWeek, int time, boolean after)
void setStartRule (int month, int day, int time)
void setEndRule (int month, int day, int dayOfWeek, int time)
void setEndRule (int month, int day, int dayOfWeek, int time, boolean after)
void setEndRule (int month, int day, int time)
int getOffset (int era, int year, int month, int day, int dayOfWeek, int millis)
int getRawOffset ()
void setRawOffset (int rawOffset)
int getDSTSavings ()
void setDSTSavings (int dstSavings)
boolean useDaylightTime ()
synchronized int hashCode ()
String toString ()
Static Public Attributes
static final int STANDARD_TIME = 1
static final int WALL_TIME = 0
static final int UTC_TIME = 2
Detailed Description
Internal VM implementation of the standard TimeZone
Definition at line 29 of file VMTimeZone.java.
Constructor & Destructor Documentation
jelatine::VMTimeZone::VMTimeZone (int rawOffset, String id) [inline]
Create a SimpleTimeZone with the given time offset from GMT and without daylight savings.
Parameters
rawOffset the time offset from GMT in milliseconds.
id The identifier of this time zone.
Definition at line 189 of file VMTimeZone.java.
Member Function Documentation
int jelatine::VMTimeZone::getDSTSavings () [inline]
Gets the daylight savings offset. This is a positive offset in milliseconds with respect to standard time. Typically this is one hour, but for some time zones this may be half an our.
Returns
the daylight savings offset in milliseconds.
Definition at line 556 of file VMTimeZone.java.
int jelatine::VMTimeZone::getOffset (int era, int year, int month, int day, int dayOfWeek, int millis) [inline, virtual]
Gets the time zone offset, for current date, modified in case of daylight savings. This is the offset to add to UTC to get the local time.
In the standard JDK the results given by this method may result in inaccurate results at the end of February or the beginning of March. To avoid this, you should use Calendar instead: offset = cal.get(Calendar.ZONE_OFFSET) + cal.get(Calendar.DST_OFFSET);
This version doesn't suffer this inaccuracy.
The arguments don't follow the approach for setting start and end rules. The day must be a positive number and dayOfWeek must be a positive value from Calendar. dayOfWeek is redundant, but must match the other values or an inaccurate result may be returned.
Parameters
era the era of the given date
year the year of the given date
month the month of the given date, 0 for January.
day the day of month
dayOfWeek the day of week; this must match the other fields.
millis the millis in the day (in local standard time)
Returns
the time zone offset in milliseconds.
Exceptions
IllegalArgumentException if arguments are incorrect.
Implements java::util::TimeZone .
Definition at line 487 of file VMTimeZone.java.
int jelatine::VMTimeZone::getRawOffset () [inline, virtual]
Returns the time zone offset to GMT in milliseconds, ignoring day light savings.
Returns
the time zone offset.
Implements java::util::TimeZone .
Definition at line 536 of file VMTimeZone.java.
synchronized int jelatine::VMTimeZone::hashCode () [inline]
Generates the hashCode for the SimpleDateFormat object. It is the rawOffset, possibly, if useDaylightSavings is true, xored with startYear, startMonth, startDayOfWeekInMonth, ..., endTime.
Definition at line 716 of file VMTimeZone.java.
void jelatine::VMTimeZone::setDSTSavings (int dstSavings) [inline]
Sets the daylight savings offset. This is a positive offset in milliseconds with respect to standard time.
Parameters
dstSavings the daylight savings offset in milliseconds.
Definition at line 567 of file VMTimeZone.java.
void jelatine::VMTimeZone::setEndRule (int month, int day, int time) [inline]
Sets the daylight savings end rule. You must also set the start rule with setStartRule or the result of getOffset is undefined. For the parameters see the ten-argument constructor above.
Parameters
month The end month of daylight savings.
day A day in month, or a day of week in month.
time A time in millis in standard time.
Definition at line 455 of file VMTimeZone.java.
References setEndRule().
void jelatine::VMTimeZone::setEndRule (int month, int day, int dayOfWeek, int time) [inline]
Sets the daylight savings end rule. You must also set the start rule with setStartRule or the result of getOffset is undefined. For the parameters see the ten-argument constructor above.
Parameters
month The end month of daylight savings.
day A day in month, or a day of week in month.
dayOfWeek A day of week, when daylight savings ends.
time A time in millis in standard time.
Definition at line 370 of file VMTimeZone.java.
References STANDARD_TIME, and WALL_TIME.
Referenced by setEndRule().
void jelatine::VMTimeZone::setEndRule (int month, int day, int dayOfWeek, int time, boolean after) [inline]
Sets the daylight savings end rule. You must also set the start rule with setStartRule or the result of getOffset is undefined. For the parameters see the ten-argument constructor above.
Note that this API isn't incredibly well specified. It appears that the after flag must override the parameters, since normally, the day and dayofweek can select this. I.e., if day < 0 and dayOfWeek < 0, on or before mode is chosen. But if after == true, this implementation overrides the signs of the other arguments. And if dayOfWeek == 0, it falls back to the behavior in the other APIs. I guess this should be checked against Sun's implementation.
Parameters
month The end month of daylight savings.
day A day in month, or a day of week in month.
dayOfWeek A day of week, when daylight savings ends.
time A time in millis in standard time.
after If true, day and dayOfWeek specify first day of week on or after day, else first day of week on or before.
Definition at line 414 of file VMTimeZone.java.
References STANDARD_TIME, and WALL_TIME.
void jelatine::VMTimeZone::setRawOffset (int rawOffset) [inline]
Sets the standard time zone offset to GMT.
Parameters
rawOffset The time offset from GMT in milliseconds.
Definition at line 545 of file VMTimeZone.java.
void jelatine::VMTimeZone::setStartRule (int month, int day, int dayOfWeek, int time) [inline]
Sets the daylight savings start rule. You must also set the end rule with setEndRule or the result of getOffset is undefined. For the parameters see the ten-argument constructor above.
Parameters
month The month where daylight savings start, zero based. You should use the constants in Calendar.
day A day of month or day of week in month.
dayOfWeek The day of week where daylight savings start.
time The time in milliseconds standard time where daylight savings start.
Exceptions
IllegalArgumentException if parameters are out of range.
Definition at line 268 of file VMTimeZone.java.
References STANDARD_TIME, and WALL_TIME.
Referenced by setStartRule().
void jelatine::VMTimeZone::setStartRule (int month, int day, int time) [inline]
Sets the daylight savings start rule. You must also set the end rule with setEndRule or the result of getOffset is undefined. For the parameters see the ten-argument constructor above.
Parameters
month The month where daylight savings start, zero based. You should use the constants in Calendar.
day A day of month or day of week in month.
time The time in milliseconds standard time where daylight savings start.
Definition at line 354 of file VMTimeZone.java.
References setStartRule().
void jelatine::VMTimeZone::setStartRule (int month, int day, int dayOfWeek, int time, boolean after) [inline]
Sets the daylight savings start rule. You must also set the end rule with setEndRule or the result of getOffset is undefined. For the parameters see the ten-argument constructor above.
Note that this API isn't incredibly well specified. It appears that the after flag must override the parameters, since normally, the day and dayofweek can select this. I.e., if day < 0 and dayOfWeek < 0, on or before mode is chosen. But if after == true, this implementation overrides the signs of the other arguments. And if dayOfWeek == 0, it falls back to the behavior in the other APIs. I guess this should be checked against Sun's implementation.
Parameters
month The month where daylight savings start, zero based. You should use the constants in Calendar.
day A day of month or day of week in month.
dayOfWeek The day of week where daylight savings start.
time The time in milliseconds standard time where daylight savings start.
after If true, day and dayOfWeek specify first day of week on or after day, else first day of week on or before.
Definition at line 312 of file VMTimeZone.java.
References STANDARD_TIME, and WALL_TIME.
void jelatine::VMTimeZone::setStartYear (int year) [inline]
Sets the first year, where daylight savings applies. The daylight savings rule never apply for years in the BC era. Note that this is gregorian calendar specific.
Parameters
year the start year.
Definition at line 202 of file VMTimeZone.java.
String jelatine::VMTimeZone::toString () [inline]
Returns a string representation of this SimpleTimeZone object.
Returns
a string representation of this SimpleTimeZone object.
Definition at line 728 of file VMTimeZone.java.
References java::util::TimeZone::getID().
boolean jelatine::VMTimeZone::useDaylightTime () [inline, virtual]
Returns if this time zone uses daylight savings time.
Returns
true, if we use daylight savings time, false otherwise.
Implements java::util::TimeZone .
Definition at line 579 of file VMTimeZone.java.
Field Documentation
final int jelatine::VMTimeZone::STANDARD_TIME = 1 [static]
Constant to indicate that start and end times are specified in standard time, without adjusting for daylight savings.
Definition at line 170 of file VMTimeZone.java.
Referenced by setEndRule(), and setStartRule().
final int jelatine::VMTimeZone::UTC_TIME = 2 [static]
Constant to indicate that start and end times are specified in UTC.
Definition at line 181 of file VMTimeZone.java.
final int jelatine::VMTimeZone::WALL_TIME = 0 [static]
Constant to indicate that start and end times are specified in wall time, adjusting for daylight savings. This is the default.
Definition at line 176 of file VMTimeZone.java.
Referenced by setEndRule(), and setStartRule().
The documentation for this class was generated from the following file:
src/classpath/jelatine/VMTimeZone.java