jelatine::cldc::io::URL Class Reference
Public Member Functions
URL (String name) throws IllegalArgumentException
Hashtable getParamsMap (String params)
String getName ()
String getScheme ()
String getTarget ()
String getParams ()
Package Attributes
String name
String scheme
String target
String params
Detailed Description
This class stores URL format as described in RFC 2396. This takes the general form:
 {scheme}:[{target}][{params}]
 where {scheme} is the name of a protocol such as http.
 The {target} is normally some kind of network address.
 Any {params} are formed as a series of equates of the form `;x=y`. Example: `;type=a`.
Definition at line 35 of file URL.java.
Constructor & Destructor Documentation
jelatine::cldc::io::URL::URL (String name) throws IllegalArgumentException [inline]
Default constructor for an URL
Parameters
name A string holding the URL
Definition at line 45 of file URL.java.
References java::lang::String::indexOf(), name, params, scheme, java::lang::String::substring(), and target.
Member Function Documentation
String jelatine::cldc::io::URL::getName () [inline]
Return the URL name
Returns
The URL name as a string
Definition at line 105 of file URL.java.
References name.
String jelatine::cldc::io::URL::getParams () [inline]
Return the URL parameters
Returns
The URL parameters as a string
Definition at line 126 of file URL.java.
References params.
Hashtable jelatine::cldc::io::URL::getParamsMap (String params) [inline]
Parses the parameters held by params and returns them in an hash table
Parameters
params a string holding the URL parameters
Returns
The parameters parsed in an hash-table
Definition at line 70 of file URL.java.
References java::lang::String::indexOf(), java::util::Hashtable::put(), and java::lang::String::substring().
String jelatine::cldc::io::URL::getScheme () [inline]
Return the URL scheme
Returns
The URL scheme as a string
Definition at line 112 of file URL.java.
References scheme.
Referenced by javax::microedition::io::Connector::open().
String jelatine::cldc::io::URL::getTarget () [inline]
Return the URL target
Returns
The URL target as a string
Definition at line 119 of file URL.java.
References target.
Field Documentation
String jelatine::cldc::io::URL::name [package]
The URL name
Definition at line 37 of file URL.java.
Referenced by getName(), and URL().
String jelatine::cldc::io::URL::params [package]
The URL parameters
Definition at line 40 of file URL.java.
Referenced by getParams(), and URL().
String jelatine::cldc::io::URL::scheme [package]
The URL scheme
Definition at line 38 of file URL.java.
Referenced by getScheme(), and URL().
String jelatine::cldc::io::URL::target [package]
The URL target
Definition at line 39 of file URL.java.
Referenced by getTarget(), and URL().
The documentation for this class was generated from the following file:
src/classpath/jelatine/cldc/io/URL.java