java::io::OutputStream Class Reference
Public Member Functions
OutputStream ()
abstract void write (int b) throws IOException
void write (byte[] b) throws IOException, NullPointerException
void write (byte[] b, int off, int len) throws IOException, NullPointerException, IndexOutOfBoundsException
void flush () throws IOException
void close () throws IOException
Detailed Description
This abstract class forms the base of the hierarchy of classes that write output as a stream of bytes. It provides a common set of methods for writing bytes to stream. Subclasses implement and/or extend these methods to write bytes in a particular manner or to a particular destination such as a file on disk or network connection.
Author
Aaron M. Renn (arenn@urbanophile.com)
Tom Tromey (tromey@cygnus.com)
Definition at line 51 of file OutputStream.java.
Constructor & Destructor Documentation
java::io::OutputStream::OutputStream () [inline]
This is the default no-argument constructor for this class. This method does nothing in this class.
Definition at line 57 of file OutputStream.java.
Member Function Documentation
void java::io::OutputStream::close () throws IOException [inline]
This method closes the stream. Any internal or native resources associated with this stream are freed. Any subsequent attempt to access the stream might throw an exception.
This method in this class does nothing.
Exceptions
IOException If an error occurs
Reimplemented in java::io::ByteArrayOutputStream , and java::io::PrintStream .
Definition at line 138 of file OutputStream.java.
Referenced by java::io::PrintStream::close(), java::io::OutputStreamWriter::close(), and java::io::DataOutputStream::close().
void java::io::OutputStream::flush () throws IOException [inline]
This method forces any data that may have been buffered to be written to the underlying output device. Please note that the host environment might perform its own buffering unbeknowst to Java. In that case, a write made (for example, to a disk drive) might be cached in OS buffers instead of actually being written to disk.
This method in this class does nothing.
Exceptions
IOException If an error occurs
Reimplemented in java::io::PrintStream .
Definition at line 125 of file OutputStream.java.
Referenced by java::io::PrintStream::flush(), java::io::OutputStreamWriter::flush(), and java::io::DataOutputStream::flush().
void java::io::OutputStream::write (byte[] b) throws IOException, NullPointerException [inline]
This method all the writes bytes from the passed array to the output stream. This method is equivalent to write(b, 0, buf.length) which is exactly how it is implemented in this class.
Parameters
b The array of bytes to write
Exceptions
IOException If an error occurs
Reimplemented in jelatine::cldc::io::socket::ProtocolImpl::SocketOutputStream .
Definition at line 84 of file OutputStream.java.
References write().
void java::io::OutputStream::write (byte[] b, int off, int len) throws IOException, NullPointerException, IndexOutOfBoundsException [inline]
This method writes len bytes from the specified array b starting at index off into the array.
This method in this class calls the single byte write() method in a loop until all bytes have been written. Subclasses should override this method if possible in order to provide a more efficent implementation.
Parameters
b The array of bytes to write from
off The index into the array to start writing from
len The number of bytes to write
Exceptions
IOException If an error occurs
Reimplemented in java::io::ByteArrayOutputStream , java::io::PrintStream , and jelatine::cldc::io::socket::ProtocolImpl::SocketOutputStream .
Definition at line 104 of file OutputStream.java.
References write().
abstract void java::io::OutputStream::write (int b) throws IOException [pure virtual]
This method writes a single byte to the output stream. The byte written is the low eight bits of the int passed and a argument.
Subclasses must provide an implementation of this abstract method
Parameters
b The byte to be written to the output stream, passed as the low eight bits of an int
Exceptions
IOException If an error occurs
Implemented in java::io::ByteArrayOutputStream , java::io::PrintStream , jelatine::cldc::io::socket::ProtocolImpl::SocketOutputStream , and jelatine::VMOutputStream .
Referenced by java::io::PrintStream::write(), java::io::OutputStreamWriter::write(), write(), java::io::DataOutputStream::write(), java::io::DataOutputStream::writeBoolean(), java::io::DataOutputStream::writeByte(), java::io::DataOutputStream::writeChar(), java::io::DataOutputStream::writeInt(), java::io::DataOutputStream::writeLong(), and java::io::DataOutputStream::writeShort().
The documentation for this class was generated from the following file:
src/classpath/java/io/OutputStream.java