java::lang::Character Class Reference
Public Member Functions
Character (char value)
char charValue ()
int hashCode ()
boolean equals (Object o)
String toString ()
Static Public Member Functions
static boolean isLowerCase (char ch)
static boolean isUpperCase (char ch)
static boolean isDigit (char ch)
static char toLowerCase (char ch)
static char toUpperCase (char ch)
static int digit (char ch, int radix)
Static Public Attributes
static final int MIN_RADIX = 2
static final int MAX_RADIX = 36
static final char MIN_VALUE = '\u0000'
static final char MAX_VALUE = '\uFFFF'
Detailed Description
Wrapper class for the primitive char data type. In addition, this class allows one to retrieve property information and perform transformations on the 57,707 defined characters in the Unicode Standard, Version 3.0.0. java.lang.Character is designed to be very dynamic, and as such, it retrieves information on the Unicode character set from a separate database, gnu.java.lang.CharData, which can be easily upgraded.
For predicates, boundaries are used to describe the set of characters for which the method will return true. This syntax uses fairly normal regular expression notation. See 5.13 of the Unicode Standard, Version 3.0, for the boundary specification.
See http://www.unicode.org for more information on the Unicode Standard.
Author
Tom Tromey (tromey@cygnus.com)
Paul N. Fisher
Jochen Hoenicke
Eric Blake (ebb9@email.byu.edu)
Definition at line 62 of file Character.java.
Constructor & Destructor Documentation
java::lang::Character::Character (char value) [inline]
Wraps up a character.
Parameters
value the character to wrap
Definition at line 96 of file Character.java.
Member Function Documentation
char java::lang::Character::charValue () [inline]
Returns the character which has been wrapped by this class.
Returns
the character wrapped
Definition at line 106 of file Character.java.
static int java::lang::Character::digit (char ch, int radix) [inline, static]
Converts a character into a digit of the specified radix. If the radix exceeds MIN_RADIX or MAX_RADIX, or if the result of getNumericValue(ch) exceeds the radix, or if ch is not a decimal digit or in the case insensitive set of 'a'-'z', the result is -1.
 character argument boundary = [Nd]|U+0041-U+005A|U+0061-U+007A |U+FF21-U+FF3A|U+FF41-U+FF5A
Parameters
ch character to convert into a digit
radix radix in which ch is a digit
Returns
digit which ch represents in radix, or -1 not a valid digit
Definition at line 252 of file Character.java.
References isLowerCase(), and isUpperCase().
boolean java::lang::Character::equals (Object o) [inline]
Determines if an object is equal to this object. This is only true for another Character object wrapping the same value.
Parameters
o object to compare
Returns
true if o is a Character with the same value
Definition at line 129 of file Character.java.
int java::lang::Character::hashCode () [inline]
Returns the numerical value (unsigned) of the wrapped character. Range of returned values: 0x0000-0xFFFF.
Returns
the value of the wrapped character
Definition at line 117 of file Character.java.
static boolean java::lang::Character::isDigit (char ch) [inline, static]
Determines if a character is a Unicode decimal digit. For example, '0' is a digit.
 Unicode decimal digit = [Nd]
Parameters
ch character to test
Returns
true if ch is a Unicode decimal digit, else false
Definition at line 193 of file Character.java.
static boolean java::lang::Character::isLowerCase (char ch) [inline, static]
Determines if a character is a Unicode lowercase letter. For example, 'a' is lowercase.
 lowercase = [Ll]
Parameters
ch character to test
Returns
true if ch is a Unicode lowercase letter, else false
Definition at line 155 of file Character.java.
Referenced by digit().
static boolean java::lang::Character::isUpperCase (char ch) [inline, static]
Determines if a character is a Unicode uppercase letter. For example, 'A' is uppercase.
 uppercase = [Lu]
Parameters
ch character to test
Returns
true if ch is a Unicode uppercase letter, else false
Definition at line 174 of file Character.java.
Referenced by digit().
static char java::lang::Character::toLowerCase (char ch) [inline, static]
Converts a Unicode character into its lowercase equivalent mapping. If a mapping does not exist, then the character passed is returned. Note that isLowerCase(toLowerCase(ch)) does not always return true.
Parameters
ch character to convert to lowercase
Returns
lowercase mapping of ch, or ch if lowercase mapping does not exist
Definition at line 210 of file Character.java.
String java::lang::Character::toString () [inline]
Converts the wrapped character into a String.
Returns
a String containing one character -- the wrapped character of this instance
Definition at line 140 of file Character.java.
static char java::lang::Character::toUpperCase (char ch) [inline, static]
Converts a Unicode character into its uppercase equivalent mapping. If a mapping does not exist, then the character passed is returned. Note that isUpperCase(toUpperCase(ch)) does not always return true.
Parameters
ch character to convert to uppercase
Returns
uppercase mapping of ch, or ch if uppercase mapping does not exist
Definition at line 229 of file Character.java.
Field Documentation
final int java::lang::Character::MAX_RADIX = 36 [static]
Largest value allowed for radix arguments in Java. This value is 36.
Definition at line 72 of file Character.java.
final char java::lang::Character::MAX_VALUE = '\uFFFF' [static]
The maximum value the char data type can hold. This value is '\uFFFF'.
Definition at line 84 of file Character.java.
final int java::lang::Character::MIN_RADIX = 2 [static]
Smallest value allowed for radix arguments in Java. This value is 2.
Definition at line 67 of file Character.java.
final char java::lang::Character::MIN_VALUE = '\u0000' [static]
The minimum value the char data type can hold. This value is '\u0000'.
Definition at line 78 of file Character.java.
The documentation for this class was generated from the following file:
src/classpath/java/lang/Character.java