java::io::InputStreamReader Class Reference
Public Member Functions
InputStreamReader (InputStream in)
InputStreamReader (InputStream in, String encoding) throws UnsupportedEncodingException
int read () throws IOException
int read (char[] buf, int offset, int length) throws IOException
long skip (long count) throws IOException
boolean ready () throws IOException
void mark (int readLimit) throws IOException
void reset () throws IOException
void close () throws IOException
Detailed Description
This class reads characters from a byte input stream. The characters read are converted from bytes in the underlying stream by a decoding layer. The decoding layer transforms bytes to chars according to an encoding standard. There are many available encodings to choose from. The desired encoding can either be specified by name, or if no encoding is selected, the system default encoding will be used. The system default encoding name is determined from the system property file.encoding. The only encodings that are guaranteed to be availalbe are `8859_1` (the Latin-1 character set) and `UTF8`. Unforunately, Java does not provide a mechanism for listing the ecodings that are supported in a given implementation.
Here is a list of standard encoding names that may be available:
8859_1 (ISO-8859-1/Latin-1)
ASCII (7-bit ASCII)
More later
It is recommended that applications do not use InputStreamReader's directly. Rather, for efficiency purposes, an object of this class should be wrapped by a BufferedReader.
Due to a deficiency the Java class library design, there is no standard way for an application to install its own byte-character encoding.
See also
InputStream
Author
Robert Schuster
Aaron M. Renn (arenn@urbanophile.com)
Per Bothner (bothner@cygnus.com)
Definition at line 76 of file InputStreamReader.java.
Constructor & Destructor Documentation
java::io::InputStreamReader::InputStreamReader (InputStream in) [inline]
This method initializes a new instance of InputStreamReader to read from the specified stream using the default encoding.
Parameters
in The InputStream to read from
Definition at line 89 of file InputStreamReader.java.
java::io::InputStreamReader::InputStreamReader (InputStream in, String encoding) throws UnsupportedEncodingException [inline]
This method initializes a new instance of InputStreamReader to read from the specified stream using a caller supplied character encoding scheme. Note that due to a deficiency in the Java language design, there is no way to determine which encodings are supported.
Parameters
in The InputStream to read from
encoding The name of the encoding scheme to use
Exceptions
UnsupportedEncodingException If the encoding scheme requested is not available.
Definition at line 106 of file InputStreamReader.java.
Member Function Documentation
void java::io::InputStreamReader::close () throws IOException [inline, virtual]
This method closes this stream, as well as the underlying InputStream.
Exceptions
IOException If an error occurs
Implements java::io::Reader .
Definition at line 235 of file InputStreamReader.java.
References java::io::InputStream::close(), and java::io::Reader::lock.
void java::io::InputStreamReader::mark (int readLimit) throws IOException [inline]
Marks the current position in the underlying stream
Parameters
readLimit The number of chars that can be read before the mark becomes invalid
Exceptions
IOException if an error occurs
Reimplemented from java::io::Reader .
Definition at line 213 of file InputStreamReader.java.
References java::io::InputStream::mark().
int java::io::InputStreamReader::read () throws IOException [inline]
Reads an char from the input stream and returns it as an int in the range of 0-65535. This method also will return -1 if the end of the stream has been reached.
This method will block until the char can be read.
Returns
The char read or -1 if end of stream
Exceptions
IOException If an error occurs
Reimplemented from java::io::Reader .
Definition at line 130 of file InputStreamReader.java.
Referenced by read().
int java::io::InputStreamReader::read (char[] buf, int offset, int length) throws IOException [inline]
This method reads up to length characters from the stream into the specified array starting at index offset into the array.
Parameters
buf The character array to recieve the data read
offset The offset into the array to start storing characters
length The requested number of characters to read.
Returns
The actual number of characters read, or -1 if end of stream.
Exceptions
IOException If an error occurs
Definition at line 151 of file InputStreamReader.java.
References java::io::InputStream::read(), and read().
boolean java::io::InputStreamReader::ready () throws IOException [inline]
This method checks to see if the stream is ready to be read. It will return true if is, or false if it is not. If the stream is not ready to be read, it could (although is not required to) block on the next read attempt.
Returns
true if the stream is ready to be read, false otherwise
Exceptions
IOException If an error occurs
Reimplemented from java::io::Reader .
Definition at line 199 of file InputStreamReader.java.
References java::io::InputStream::available().
void java::io::InputStreamReader::reset () throws IOException [inline]
Resets the underlying stream to the last marked position
Exceptions
IOException If an error occurs
Reimplemented from java::io::Reader .
Definition at line 223 of file InputStreamReader.java.
References java::io::InputStream::reset().
long java::io::InputStreamReader::skip (long count) throws IOException [inline]
Skips the specified number of chars in the stream. It returns the actual number of chars skipped, which may be less than the requested amount.
Parameters
count The requested number of chars to skip
Returns
The actual number of chars skipped.
Exceptions
IOException If an error occurs
IllegalArgumentException If count is negative
Reimplemented from java::io::Reader .
Definition at line 177 of file InputStreamReader.java.
The documentation for this class was generated from the following file:
src/classpath/java/io/InputStreamReader.java