jelatine::VMFinalizer Class Reference
Public Member Functions
void run ()
void finalize ()
Static Public Member Functions
static native VMFinalizer getNextObject ()
Detailed Description
Internal VM class used for finalizing other objects. This class uses a number of tricks to achieve its purpose. For example all objects which need to be finalized are cast to VMFinalizer even though they do not inherit from the class. Since this is done only for invoking the finalize() method which is available in every class the call works
Definition at line 32 of file VMFinalizer.java.
Member Function Documentation
void jelatine::VMFinalizer::finalize () [inline]
Make java.lang.Object.finalize() public so we can call it
Definition at line 65 of file VMFinalizer.java.
Referenced by run().
static native VMFinalizer jelatine::VMFinalizer::getNextObject () [static]
Gets the next object in the finalization queue
Returns
An object or null if the queue is empty
Referenced by run().
void jelatine::VMFinalizer::run () [inline]
Implements the java.lang.Runnable.run() method
Implements java::lang::Runnable .
Definition at line 43 of file VMFinalizer.java.
References finalize(), and getNextObject().
The documentation for this class was generated from the following file:
src/classpath/jelatine/VMFinalizer.java