java::lang::Long Class Reference
Public Member Functions
Long (long value)
long longValue ()
float floatValue ()
double doubleValue ()
String toString ()
int hashCode ()
boolean equals (Object obj)
Static Public Member Functions
static String toString (long num, int radix)
static String toString (long num)
static long parseLong (String str, int radix) throws NumberFormatException
static long parseLong (String s) throws NumberFormatException
Static Public Attributes
static final long MIN_VALUE = 0x8000000000000000L
static final long MAX_VALUE = 0x7fffffffffffffffL
Detailed Description
Instances of class Long represent primitive long values.
Additionally, this class provides various helper functions and variables related to longs.
Author
Paul Fisher
John Keiser
Warren Levy
Eric Blake (ebb9@email.byu.edu)
Definition at line 52 of file Long.java.
Constructor & Destructor Documentation
java::lang::Long::Long (long value) [inline]
Create a Long object representing the value of the long argument.
Parameters
value the value to use
Definition at line 86 of file Long.java.
Member Function Documentation
double java::lang::Long::doubleValue () [inline]
Return the value of this Long as a double.
Returns
the double value
Definition at line 222 of file Long.java.
boolean java::lang::Long::equals (Object obj) [inline]
Returns true if obj is an instance of Long and represents the same long value.
Parameters
obj the object to compare
Returns
whether these Objects are semantically equal
Definition at line 256 of file Long.java.
float java::lang::Long::floatValue () [inline]
Return the value of this Long as a float.
Returns
the float value
Definition at line 212 of file Long.java.
int java::lang::Long::hashCode () [inline]
Return a hashcode representing this Object. Long's hash code is calculated by (int) (value ^ (value >> 32)).
Returns
this Object's hash code
Definition at line 244 of file Long.java.
long java::lang::Long::longValue () [inline]
Return the value of this Long.
Returns
the long value
Definition at line 202 of file Long.java.
static long java::lang::Long::parseLong (String str, int radix) throws NumberFormatException [inline, static]
Converts the specified String into an int using the specified radix (base). The string must not be null or empty. It may begin with an optional '-', which will negate the answer, provided that there are also valid digits. Each digit is parsed as if by Character.digit(d, radix), and must be in the range 0 to radix - 1. Finally, the result must be within MIN_VALUE to MAX_VALUE, inclusive. Unlike Double.parseDouble, you may not have a leading '+'; and 'l' or 'L' as the last character is only valid in radices 22 or greater, where it is a digit and not a type indicator.
Parameters
str the String to convert
radix the radix (base) to use in the conversion
Returns
the String argument converted to long
Exceptions
NumberFormatException if s cannot be parsed as a long
Definition at line 176 of file Long.java.
Referenced by parseLong().
static long java::lang::Long::parseLong (String s) throws NumberFormatException [inline, static]
Converts the specified String into a long. This function assumes a radix of 10.
Parameters
s the String to convert
Returns
the int value of s
Exceptions
NumberFormatException if s cannot be parsed as a long
See also
parseLong(String, int)
Definition at line 192 of file Long.java.
References parseLong().
String java::lang::Long::toString () [inline]
Converts the Long value to a String and assumes a radix of 10.
Returns
the String representation
Definition at line 233 of file Long.java.
Referenced by toString().
static String java::lang::Long::toString (long num) [inline, static]
Converts the long to a String and assumes a radix of 10.
Parameters
num the long to convert to String
Returns
the String representation of the argument
See also
toString(long, int)
Definition at line 153 of file Long.java.
References toString().
static String java::lang::Long::toString (long num, int radix) [inline, static]
Converts the long to a String using the specified radix (base). If the radix exceeds Character.MIN_RADIX or Character.MAX_RADIX, 10 is used instead. If the result is negative, the leading character is '-' ('\u002D'). The remaining characters come from Character.forDigit(digit, radix) ('0'-'9','a'-'z').
Parameters
num the long to convert to String
radix the radix (base) to use in the conversion
Returns
the String representation of the argument
Definition at line 103 of file Long.java.
References java::lang::String::toString().
Field Documentation
final long java::lang::Long::MAX_VALUE = 0x7fffffffffffffffL [static]
The maximum value a long can represent is 9223372036854775807 (or 2$^{\mbox{63}}$ - 1).
Definition at line 71 of file Long.java.
final long java::lang::Long::MIN_VALUE = 0x8000000000000000L [static]
The minimum value a long can represent is -9223372036854775808L (or -2$^{\mbox{63}}$).
Definition at line 65 of file Long.java.
The documentation for this class was generated from the following file:
src/classpath/java/lang/Long.java