java::lang::Class Class Reference
Public Member Functions
String toString ()
native Object newInstance () throws InstantiationException, IllegalAccessException
native boolean isInstance (Object o)
native boolean isAssignableFrom (Class c) throws NullPointerException
boolean isInterface ()
boolean isArray ()
String getName ()
InputStream getResourceAsStream (String name)
Static Public Member Functions
static native Class forName (String name) throws ClassNotFoundException
Package Functions
Class ()
Detailed Description
A Class represents a Java type. There will never be multiple Class objects with identical names and ClassLoaders. Primitive types, array types, and void also have a Class object.
Arrays with identical type and number of dimensions share the same class. The array class ClassLoader is the same as the ClassLoader of the element type of the array (which can be null to indicate the bootstrap classloader). The name of an array class is [<signature format>;.
For example, String[]'s class is [Ljava.lang.String;. boolean, byte, short, char, int, long, float and double have the `type name` of Z,B,S,C,I,J,F,D for the purposes of array classes. If it's a multidimensioned array, the same principle applies: int[][][] == [[[I.
There is no public constructor - Class objects are obtained only through the virtual machine, as defined in ClassLoaders.
Author
John Keiser
Eric Blake (ebb9@email.byu.edu)
Tom Tromey (tromey@cygnus.com)
Definition at line 67 of file Class.java.
Constructor & Destructor Documentation
java::lang::Class::Class () [inline, package]
Class is non-instantiable from Java code; only the VM can create instances of this class.
Definition at line 80 of file Class.java.
Member Function Documentation
static native Class java::lang::Class::forName (String name) throws ClassNotFoundException [static]
Use the classloader of the current class to load, link, and initialize a class. This is equivalent to your code calling Class.forName(name, true, getClass().getClassLoader()).
Parameters
name the name of the class to find
Returns
the Class object representing the class
Exceptions
ClassNotFoundException if the class was not found by the classloader
LinkageError if linking the class fails
ExceptionInInitializerError if the class loads, but an exception occurs during initialization
String java::lang::Class::getName () [inline]
Get the name of this class, separated by dots for package separators. If the class represents a primitive type, or void, then the name of the type as it appears in the Java programming language is returned. For instance, Byte.TYPE.getName() returns `byte`.
Arrays are specially encoded as shown on this table.
 array type [element type
                     (note that the element type is encoded per
                      this table)
 boolean Z
 byte B
 char C
 short S
 int I
 long J
 float F
 double D
 void V
 class or interface, alone: <dotted name>
 class or interface, as element type: L<dotted name>;
Returns
the name of this class
Definition at line 210 of file Class.java.
References java::lang::String::replace().
Referenced by getResourceAsStream(), java::lang::Object::toString(), and toString().
InputStream java::lang::Class::getResourceAsStream (String name) [inline]
Finds a resource with a given name in the application's JAR file and returns it as an InputStream
Parameters
name The name of the resource in either relative or absolute format
Returns
An InputStream used for accessing the resource or null if none was found
Definition at line 236 of file Class.java.
References java::lang::StringBuffer::charAt(), java::lang::StringBuffer::delete(), java::lang::StringBuffer::deleteCharAt(), getName(), java::lang::StringBuffer::insert(), java::lang::StringBuffer::length(), jelatine::VMResourceStream::open(), java::lang::StringBuffer::setCharAt(), and java::lang::StringBuffer::toString().
boolean java::lang::Class::isArray () [inline]
Return whether this class is an array type.
Returns
whether this class is an array type
Since
1.1
Definition at line 175 of file Class.java.
native boolean java::lang::Class::isAssignableFrom (Class c) throws NullPointerException
Discover whether an instance of the Class parameter would be an instance of this Class as well. Think of doing isInstance(c.newInstance()) or even c.newInstance() instanceof (this class). While this checks widening conversions for objects, it must be exact for primitive types.
Parameters
c the class to check
Returns
whether an instance of c would be an instance of this class as well
Exceptions
NullPointerException if c is null
Since
1.1
native boolean java::lang::Class::isInstance (Object o)
Discover whether an Object is an instance of this Class. Think of it as almost like o instanceof (this class).
Parameters
o the Object to check
Returns
whether o is an instance of this class
boolean java::lang::Class::isInterface () [inline]
Check whether this class is an interface or not. Array types are not interfaces.
Returns
whether this class is an interface or not
Definition at line 161 of file Class.java.
Referenced by toString().
native Object java::lang::Class::newInstance () throws InstantiationException, IllegalAccessException
Get a new instance of this class by calling the no-argument constructor. The class is initialized if it has not been already. A security check may be performed, with checkMemberAccess(this, Member.PUBLIC) as well as checkPackageAccess both having to succeed.
Returns
a new instance of this class
Exceptions
InstantiationException if there is not a no-arg constructor for this class, including interfaces, abstract classes, arrays, primitive types, and void; or if an exception occurred during the constructor
IllegalAccessException if you are not allowed to access the no-arg constructor because of scoping reasons
String java::lang::Class::toString () [inline]
Return the human-readable form of this Object. For an object, this is either `interface ` or `class ` followed by getName(), for primitive types and void it is just getName().
Returns
the human-readable form of this Object
Definition at line 91 of file Class.java.
References getName(), and isInterface().
The documentation for this class was generated from the following file:
src/classpath/java/lang/Class.java