javax::microedition::io::Connector Class Reference
Static Public Member Functions
static Connection open (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException
static Connection open (String name, int mode) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException
static Connection open (String name, int mode, boolean timeouts) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException
static DataInputStream openDataInputStream (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException
static DataOutputStream openDataOutputStream (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException
static InputStream openInputStream (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException
static OutputStream openOutputStream (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException
Static Public Attributes
static final int READ = 1
static final int WRITE = 2
static final int READ_WRITE = 3
Detailed Description
This class is a factory for creating Connection objects
Definition at line 35 of file Connector.java.
Member Function Documentation
static Connection javax::microedition::io::Connector::open (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException [inline, static]
Create a connection object and open it
Parameters
name A String holding an URL
Returns
A newly created Connection object
Exceptions
IllegalArgumentException If the parameter is invalid
ConnectionNotFoundException If the passed name cannot be found or the protocol is unsupported
IOException If any I/O error happens
SecurityException If access to the requested protocol handler is not allowed
Definition at line 74 of file Connector.java.
References READ_WRITE.
Referenced by open().
static Connection javax::microedition::io::Connector::open (String name, int mode) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException [inline, static]
Create a connection object and open it with the requested access mode
Parameters
name A String holding an URL
mode The access mode
Returns
A newly created Connection object
Exceptions
IllegalArgumentException If the parameter is invalid
ConnectionNotFoundException If the passed name cannot be found or the protocol is unsupported
IOException If any I/O error happens
SecurityException If access to the requested protocol handler is not allowed
Definition at line 94 of file Connector.java.
References open().
static Connection javax::microedition::io::Connector::open (String name, int mode, boolean timeouts) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException [inline, static]
Create a connection object and open it with the requested access mode and an explicit flag asking (or not) for timeout exceptions
Parameters
name A String holding an URL
mode The access mode
timeouts True if timeout-related exceptions must be thrown
Returns
A newly created Connection object
Exceptions
IllegalArgumentException If the parameter is invalid
ConnectionNotFoundException If the passed name cannot be found or the protocol is unsupported
IOException If any I/O error happens
SecurityException If access to the requested protocol handler is not allowed
Definition at line 115 of file Connector.java.
References jelatine::cldc::io::URL::getScheme(), and jelatine::cldc::io::Protocol::open().
static DataInputStream javax::microedition::io::Connector::openDataInputStream (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException [inline, static]
Creates a new connection input stream and open it
Parameters
name A String holding an URL
Returns
A newly created DataInputStream object
Exceptions
IllegalArgumentException If the parameter is invalid
ConnectionNotFoundException If the passed name cannot be found or the protocol is unsupported
IOException If any I/O error happens
SecurityException If access to the requested protocol handler is not allowed
Definition at line 157 of file Connector.java.
References javax::microedition::io::Connection::close(), and javax::microedition::io::InputConnection::openDataInputStream().
Referenced by openInputStream().
static DataOutputStream javax::microedition::io::Connector::openDataOutputStream (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException [inline, static]
Creates a new connection output stream and open it
Parameters
name A String holding an URL
Returns
A newly created DataOutputStream object
Exceptions
IllegalArgumentException If the parameter is invalid
ConnectionNotFoundException If the passed name cannot be found or the protocol is unsupported
IOException If any I/O error happens
SecurityException If access to the requested protocol handler is not allowed
Definition at line 188 of file Connector.java.
References javax::microedition::io::Connection::close(), and javax::microedition::io::OutputConnection::openDataOutputStream().
Referenced by openOutputStream().
static InputStream javax::microedition::io::Connector::openInputStream (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException [inline, static]
Creates a new connection input stream and open it
Parameters
name A String holding an URL
Returns
A newly created InputStream object
Exceptions
IllegalArgumentException If the parameter is invalid
ConnectionNotFoundException If the passed name cannot be found or the protocol is unsupported
IOException If any I/O error happens
SecurityException If access to the requested protocol handler is not allowed
Definition at line 219 of file Connector.java.
References openDataInputStream().
static OutputStream javax::microedition::io::Connector::openOutputStream (String name) throws IllegalArgumentException, ConnectionNotFoundException, IOException, SecurityException [inline, static]
Creates a new connection output stream and open it
Parameters
name A String holding an URL
Returns
A newly created OutputStream object
Exceptions
IllegalArgumentException If the parameter is invalid
ConnectionNotFoundException If the passed name cannot be found or the protocol is unsupported
IOException If any I/O error happens
SecurityException If access to the requested protocol handler is not allowed
Definition at line 237 of file Connector.java.
References openDataOutputStream().
Field Documentation
final int javax::microedition::io::Connector::READ = 1 [static]
READ access mode
Definition at line 40 of file Connector.java.
final int javax::microedition::io::Connector::READ_WRITE = 3 [static]
READ_WRITE access mode
Definition at line 50 of file Connector.java.
Referenced by open().
final int javax::microedition::io::Connector::WRITE = 2 [static]
WRITE access mode
Definition at line 45 of file Connector.java.
The documentation for this class was generated from the following file:
src/classpath/javax/microedition/io/Connector.java