java::io::Reader Class Reference
Public Member Functions
int read () throws IOException
int read (char buf[]) throws IOException
abstract int read (char buf[], int offset, int count) throws IOException
long skip (long count) throws IOException, IllegalArgumentException
boolean ready () throws IOException
boolean markSupported ()
void mark (int readLimit) throws IOException
void reset () throws IOException
abstract void close () throws IOException
Protected Member Functions
Reader ()
Reader (Object lock)
Protected Attributes
Object lock
Detailed Description
This abstract class forms the base of the hierarchy of classes that read input as a stream of characters. It provides a common set of methods for reading characters from streams. Subclasses implement and extend these methods to read characters from a particular input source such as a file or network connection.
Author
Per Bothner (bothner@cygnus.com)
Date
April 21, 1998.
Author
Aaron M. Renn (arenn@urbanophile.com)
Definition at line 56 of file Reader.java.
Constructor & Destructor Documentation
java::io::Reader::Reader () [inline, protected]
Unitializes a Reader that will use the object itself for synchronization of critical code sections.
Definition at line 69 of file Reader.java.
References lock.
java::io::Reader::Reader (Object lock) [inline, protected]
Initializes a Reader that will use the specified Object for synchronization of critical code sections.
Parameters
lock The Object to use for synchronization
Definition at line 80 of file Reader.java.
Member Function Documentation
abstract void java::io::Reader::close () throws IOException [pure virtual]
Closes the stream. Any futher attempts to read from the stream may generate an IOException.
Exceptions
IOException If an error occurs
Implemented in java::io::InputStreamReader .
void java::io::Reader::mark (int readLimit) throws IOException [inline]
Marks a position in the input to which the stream can be `reset` by calling the reset() method. The parameter readlimit is the number of chars that can be read from the stream after setting the mark before the mark becomes invalid. For example, if mark() is called with a read limit of 10, then when 11 chars of data are read from the stream before the reset() method is called, then the mark is invalid and the stream object instance is not required to remember the mark.
Parameters
readLimit The number of chars that can be read before the mark becomes invalid
Exceptions
IOException If an error occurs such as mark not being supported for this class
Reimplemented in java::io::InputStreamReader .
Definition at line 251 of file Reader.java.
boolean java::io::Reader::markSupported () [inline]
Returns a boolean that indicates whether the mark/reset methods are supported in this class. Those methods can be used to remember a specific point in the stream and reset the stream to that point.
This method always returns false in this class, but subclasses can override this method to return true if they support mark/reset functionality.
Returns
true if mark/reset functionality is supported, false otherwise
Definition at line 230 of file Reader.java.
int java::io::Reader::read () throws IOException [inline]
Reads an char from the input stream and returns it as an int in the range of 0-65535. This method also will return -1 if the end of the stream has been reached.
This method will block until the char can be read.
Returns
The char read or -1 if end of stream
Exceptions
IOException If an error occurs
Reimplemented in java::io::InputStreamReader .
Definition at line 96 of file Reader.java.
Referenced by read(), and skip().
int java::io::Reader::read (char buf[]) throws IOException [inline]
Reads chars from a stream and stores them into a caller supplied buffer. This method attempts to completely fill the buffer, but can return before doing so. The actual number of chars read is returned as an int. A -1 is returned to indicate the end of the stream.
This method will block until some data can be read.
This method operates by calling an overloaded read method like so: read(buf, 0, buf.length)
Parameters
buf The buffer into which the chars read will be stored.
Returns
The number of chars read or -1 if end of stream.
Exceptions
IOException If an error occurs.
Definition at line 121 of file Reader.java.
References read().
abstract int java::io::Reader::read (char buf[], int offset, int count) throws IOException [pure virtual]
Read chars from a stream and stores them into a caller supplied buffer. It starts storing the data at index offset into the buffer and attempts to read len chars. This method can return before reading the number of chars requested. The actual number of chars read is returned as an int. A -1 is returned to indicate the end of the stream.
This method will block until some data can be read.
This method operates by calling the single char read() method in a loop until the desired number of chars are read. The read loop stops short if the end of the stream is encountered or if an IOException is encountered on any read operation except the first. If the first attempt to read a chars fails, the IOException is allowed to propagate upward. And subsequent IOException is caught and treated identically to an end of stream condition. Subclasses can (and should if possible) override this method to provide a more efficient implementation.
Parameters
buf The array into which the chars read should be stored
offset The offset into the array to start storing chars
count The requested number of chars to read
Returns
The actual number of chars read, or -1 if end of stream.
Exceptions
IOException If an error occurs.
boolean java::io::Reader::ready () throws IOException [inline]
Determines whether or not this stream is ready to be read. If it returns false the stream may block if a read is attempted, but it is not guaranteed to do so.
This method always returns false in this class
Returns
true if the stream is ready to be read, false otherwise.
Exceptions
IOException If an error occurs
Reimplemented in java::io::InputStreamReader .
Definition at line 211 of file Reader.java.
void java::io::Reader::reset () throws IOException [inline]
Resets a stream to the point where the mark() method was called. Any chars that were read after the mark point was set will be re-read during subsequent reads.
This method always throws an IOException in this class, but subclasses can override this method if they provide mark/reset functionality.
Exceptions
IOException Always thrown for this class
Reimplemented in java::io::InputStreamReader .
Definition at line 266 of file Reader.java.
long java::io::Reader::skip (long count) throws IOException, IllegalArgumentException [inline]
Skips the specified number of chars in the stream. It returns the actual number of chars skipped, which may be less than the requested amount.
This method reads and discards chars into a 256 char array until the specified number of chars were skipped or until either the end of stream is reached or a read attempt returns a short count. Subclasses can override this method to provide a more efficient implementation where one exists.
Parameters
count The requested number of chars to skip
Returns
The actual number of chars skipped.
Exceptions
IOException If an error occurs
IllegalArgumentException If count is negative
Reimplemented in java::io::InputStreamReader .
Definition at line 174 of file Reader.java.
References lock, and read().
Field Documentation
Object java::io::Reader::lock [protected]
This is the Object used for synchronizing critical code sections. Subclasses should use this variable instead of a synchronized method or an explicit synchronization on this
Definition at line 63 of file Reader.java.
Referenced by java::io::InputStreamReader::close(), Reader(), and skip().
The documentation for this class was generated from the following file:
src/classpath/java/io/Reader.java