java::lang::Float Class Reference
Public Member Functions
Float (float value)
Float (double value)
boolean isNaN ()
boolean isInfinite ()
String toString ()
byte byteValue ()
short shortValue ()
int intValue ()
long longValue ()
float floatValue ()
double doubleValue ()
int hashCode ()
boolean equals (Object obj)
Static Public Member Functions
static native String toString (float f)
static Float valueOf (String s)
static float parseFloat (String str)
static boolean isNaN (float v)
static boolean isInfinite (float v)
static native int floatToIntBits (float value)
static native float intBitsToFloat (int bits)
Static Public Attributes
static final float MAX_VALUE = 3.4028235e+38f
static final float MIN_VALUE = 1.4e-45f
static final float NEGATIVE_INFINITY = -1.0f / 0.0f
static final float POSITIVE_INFINITY = 1.0f / 0.0f
static final float NaN = 0.0f / 0.0f
Detailed Description
Instances of class Float represent primitive float values.
Additionally, this class provides various helper functions and variables related to floats.
Author
Paul Fisher
Andrew Haley (aph@cygnus.com)
Eric Blake (ebb9@email.byu.edu)
Definition at line 54 of file Float.java.
Constructor & Destructor Documentation
java::lang::Float::Float (float value) [inline]
Create a Float from the primitive float specified.
Parameters
value the float argument
Definition at line 96 of file Float.java.
Referenced by valueOf().
java::lang::Float::Float (double value) [inline]
Create a Float from the primitive double specified.
Parameters
value the double argument
Definition at line 107 of file Float.java.
Member Function Documentation
byte java::lang::Float::byteValue () [inline]
Return the value of this Float as a byte.
Returns
the byte value
Definition at line 280 of file Float.java.
double java::lang::Float::doubleValue () [inline]
Return the value of this Float as a double
Returns
the double value
Definition at line 331 of file Float.java.
boolean java::lang::Float::equals (Object obj) [inline]
Returns true if obj is an instance of Float and represents the same float value. Unlike comparing two floats with ==, this treats two instances of Float.NaN as equal, but treats 0.0 and -0.0 as unequal.
Note that f1.equals(f2) is identical to floatToIntBits(f1.floatValue()) == floatToIntBits(f2.floatValue()).
Parameters
obj the object to compare
Returns
whether the objects are semantically equal
Definition at line 362 of file Float.java.
References isNaN().
static native int java::lang::Float::floatToIntBits (float value) [static]
Convert the float to the IEEE 754 floating-point `single format` bit layout. Bit 31 (the most significant) is the sign bit, bits 30-23 (masked by 0x7f800000) represent the exponent, and bits 22-0 (masked by 0x007fffff) are the mantissa. This function collapses all versions of NaN to 0x7fc00000. The result of this function can be used as the argument to Float.intBitsToFloat(int) to obtain the original float value.
Parameters
value the float to convert
Returns
the bits of the float
See also
intBitsToFloat(int)
Referenced by hashCode().
float java::lang::Float::floatValue () [inline]
Return the value of this Float.
Returns
the float value
Definition at line 321 of file Float.java.
int java::lang::Float::hashCode () [inline]
Return a hashcode representing this Object. Float's hash code is calculated by calling floatToIntBits(floatValue()).
Returns
this Object's hash code
See also
floatToIntBits(float)
Definition at line 343 of file Float.java.
References floatToIntBits().
static native float java::lang::Float::intBitsToFloat (int bits) [static]
Convert the argument in IEEE 754 floating-point `single format` bit layout to the corresponding float. Bit 31 (the most significant) is the sign bit, bits 30-23 (masked by 0x7f800000) represent the exponent, and bits 22-0 (masked by 0x007fffff) are the mantissa. This function leaves NaN alone, so that you can recover the bit pattern with Float.floatToRawIntBits(float).
Parameters
bits the bits to convert
Returns
the float represented by the bits
int java::lang::Float::intValue () [inline]
Return the value of this Integer as an int.
Returns
the int value
Definition at line 301 of file Float.java.
static boolean java::lang::Float::isInfinite (float v) [inline, static]
Return true if the float has a value equal to either NEGATIVE_INFINITY or POSITIVE_INFINITY, otherwise return false.
Parameters
v the float to compare
Returns
whether the argument is (-/+) infinity
Definition at line 234 of file Float.java.
References NEGATIVE_INFINITY, and POSITIVE_INFINITY.
boolean java::lang::Float::isInfinite () [inline]
Return true if the value of this Float is the same as NEGATIVE_INFINITY or POSITIVE_INFINITY, otherwise return false.
Returns
whether this Float is (-/+) infinity
Definition at line 257 of file Float.java.
static boolean java::lang::Float::isNaN (float v) [inline, static]
Return true if the float has the same value as NaN, otherwise return false.
Parameters
v the float to compare
Returns
whether the argument is NaN
Definition at line 219 of file Float.java.
boolean java::lang::Float::isNaN () [inline]
Return true if the value of this Float is the same as NaN, otherwise return false.
Returns
whether this Float is NaN
Definition at line 245 of file Float.java.
Referenced by equals().
long java::lang::Float::longValue () [inline]
Return the value of this Integer as a long.
Returns
the long value
Definition at line 311 of file Float.java.
static float java::lang::Float::parseFloat (String str) [inline, static]
Parse the specified String as a float. The extended BNF grammar is as follows:
 DecodableString:
      ([ - | + ] NaN)
    | ([ - | + ] Infinity)
    | ([ - | + ] FloatingPoint
              [ f | F | d
                | D])
 FloatingPoint:
      ({ Digit }+ [ . { Digit } ]
              [ Exponent ])
    | (. { Digit }+ [ Exponent ])
 Exponent:
      ((e | E)
              [ - | + ] { Digit }+)
 Digit: '0' through '9'
NaN and infinity are special cases, to allow parsing of the output of toString. Otherwise, the result is determined by calculating n * 10$^{\mbox{exponent}}$ to infinite precision, then rounding to the nearest float. Remember that many numbers cannot be precisely represented in floating point. In case of overflow, infinity is used, and in case of underflow, signed zero is used. Unlike Integer.parseInt, this does not accept Unicode digits outside the ASCII range.
If an unexpected character is found in the String, a NumberFormatException will be thrown. Leading and trailing 'whitespace' is ignored via String.trim(), but spaces internal to the actual number are not allowed.
To parse numbers according to another format, consider using java.text.NumberFormat.
Parameters
str the String to convert
Returns
the float value of s
Exceptions
NumberFormatException if s cannot be parsed as a float
NullPointerException if s is null
See also
MIN_VALUE
MAX_VALUE
POSITIVE_INFINITY
NEGATIVE_INFINITY
Definition at line 205 of file Float.java.
Referenced by valueOf().
short java::lang::Float::shortValue () [inline]
Return the value of this Float as a short.
Returns
the short value
Since
1.1
Definition at line 291 of file Float.java.
static native String java::lang::Float::toString (float f) [static]
Convert the float to a String. Floating-point string representation is fairly complex: here is a rundown of the possible values. `<code>[-]</code>` indicates that a negative sign will be printed if the value (or exponent) is negative. `<code>&lt;number&gt;</code>` means a string of digits ('0' to '9'). `<code>&lt;digit&gt;</code>` means a single digit ('0' to '9').
Value of Float String Representation
[+-] 0 [-]0.0
Between [+-] 10$^{\mbox{-\/3}}$ and 10$^{\mbox{7}}$ , exclusive [-]number.number
Other numeric value [-]<digit>.<number> E[-]<number>
[+-] infinity [-]Infinity
NaN NaN
Yes, negative zero is a possible value. Note that there is always a . and at least one digit printed after it: even if the number is 3, it will be printed as 3.0. After the `.`, all digits will be printed except trailing zeros. The result is rounded to the shortest decimal number which will parse back to the same float.
Parameters
f the float to convert
Returns
the String representing the float
String java::lang::Float::toString () [inline]
Convert the float value of this Float to a String. This method calls Float.toString(float) to do its dirty work.
Returns
the String representation
See also
toString(float)
Definition at line 270 of file Float.java.
static Float java::lang::Float::valueOf (String s) [inline, static]
Creates a new Float object using the String.
Parameters
s the String to convert
Returns
the new Float
Exceptions
NumberFormatException if s cannot be parsed as a float
NullPointerException if s is null
See also
parseFloat(String)
Definition at line 154 of file Float.java.
References Float(), and parseFloat().
Field Documentation
final float java::lang::Float::MAX_VALUE = 3.4028235e+38f [static]
The maximum positive value a double may represent is 3.4028235e+38f.
Definition at line 60 of file Float.java.
final float java::lang::Float::MIN_VALUE = 1.4e-45f [static]
The minimum positive value a float may represent is 1.4e-45.
Definition at line 66 of file Float.java.
final float java::lang::Float::NaN = 0.0f / 0.0f [static]
All IEEE 754 values of NaN have the same value in Java.
Definition at line 81 of file Float.java.
final float java::lang::Float::NEGATIVE_INFINITY = -1.0f / 0.0f [static]
The value of a float representation -1.0/0.0, negative infinity.
Definition at line 71 of file Float.java.
Referenced by isInfinite().
final float java::lang::Float::POSITIVE_INFINITY = 1.0f / 0.0f [static]
The value of a float representation 1.0/0.0, positive infinity.
Definition at line 76 of file Float.java.
Referenced by isInfinite().
The documentation for this class was generated from the following file:
src/classpath/java/lang/Float.java