java::io::InputStream Class Reference
Public Member Functions
InputStream ()
int available () throws IOException
void close () throws IOException
void mark (int readLimit)
boolean markSupported ()
abstract int read () throws IOException
int read (byte[] b) throws IOException
int read (byte[] b, int off, int len) throws IOException
void reset () throws IOException
long skip (long n) throws IOException
Detailed Description
This abstract class forms the base of the hierarchy of classes that read input as a stream of bytes. It provides a common set of methods for reading bytes from streams. Subclasses implement and extend these methods to read bytes from a particular input source such as a file or network connection.
Author
Aaron M. Renn (arenn@urbanophile.com)
Warren Levy (warrenl@cygnus.com)
Definition at line 51 of file InputStream.java.
Constructor & Destructor Documentation
java::io::InputStream::InputStream () [inline]
Default, no-arg, public constructor
Definition at line 56 of file InputStream.java.
Member Function Documentation
int java::io::InputStream::available () throws IOException [inline]
This method returns the number of bytes that can be read from this stream before a read can block. A return of 0 indicates that blocking might (or might not) occur on the very next read attempt.
This method always returns 0 in this class
Returns
The number of bytes that can be read before blocking could occur
Exceptions
IOException If an error occurs
Reimplemented in java::io::ByteArrayInputStream , and jelatine::VMResourceStream .
Definition at line 71 of file InputStream.java.
Referenced by java::io::DataInputStream::available(), and java::io::InputStreamReader::ready().
void java::io::InputStream::close () throws IOException [inline]
This method closes the stream. Any futher attempts to read from the stream may generate an IOException
This method does nothing in this class, but subclasses may override this method in order to provide additional functionality.
Exceptions
IOException If an error occurs, which can only happen in a subclass
Reimplemented in java::io::ByteArrayInputStream .
Definition at line 86 of file InputStream.java.
Referenced by java::io::InputStreamReader::close(), and java::io::DataInputStream::close().
void java::io::InputStream::mark (int readLimit) [inline]
This method marks a position in the input to which the stream can be `reset` by calling the reset() method. The parameter readlimit is the number of bytes that can be read from the stream after setting the mark before the mark becomes invalid. For example, if mark() is called with a read limit of 10, then when 11 bytes of data are read from the stream before the reset() method is called, then the mark is invalid and the stream object instance is not required to remember the mark.
This method does nothing in this class, but subclasses may override it to provide mark/reset functionality.
Parameters
readLimit The number of bytes that can be read before the mark becomes invalid
Reimplemented in java::io::ByteArrayInputStream .
Definition at line 108 of file InputStream.java.
Referenced by java::io::InputStreamReader::mark(), and java::io::DataInputStream::mark().
boolean java::io::InputStream::markSupported () [inline]
This method returns a boolean that indicates whether the mark/reset methods are supported in this class. Those methods can be used to remember a specific point in the stream and reset the stream to that point.
This method always returns false in this class, but subclasses can override this method to return true if they support mark/reset functionality.
Returns
true if mark/reset functionality is supported, false otherwise
Reimplemented in java::io::ByteArrayInputStream .
Definition at line 126 of file InputStream.java.
Referenced by java::io::DataInputStream::markSupported().
int java::io::InputStream::read (byte[] b, int off, int len) throws IOException [inline]
This method read bytes from a stream and stores them into a caller supplied buffer. It starts storing the data at index off into the buffer and attempts to read len bytes. This method can return before reading the number of bytes requested. The actual number of bytes read is returned as an int. A -1 is returned to indicate the end of the stream.
This method will block until some data can be read.
This method operates by calling the single byte read() method in a loop until the desired number of bytes are read. The read loop stops short if the end of the stream is encountered or if an IOException is encountered on any read operation except the first. If the first attempt to read a bytes fails, the IOException is allowed to propagate upward. And subsequent IOException is caught and treated identically to an end of stream condition. Subclasses can (and should if possible) override this method to provide a more efficient implementation.
Parameters
b The array into which the bytes read should be stored
off The offset into the array to start storing bytes
len The requested number of bytes to read
Returns
The actual number of bytes read, or -1 if end of stream.
Exceptions
IOException If an error occurs.
Reimplemented in java::io::ByteArrayInputStream , and jelatine::cldc::io::socket::ProtocolImpl::SocketInputStream .
Definition at line 194 of file InputStream.java.
References read().
abstract int java::io::InputStream::read () throws IOException [pure virtual]
This method reads an unsigned byte from the input stream and returns it as an int in the range of 0-255. This method also will return -1 if the end of the stream has been reached.
This method will block until the byte can be read.
Returns
The byte read or -1 if end of stream
Exceptions
IOException If an error occurs
Implemented in java::io::ByteArrayInputStream , jelatine::cldc::io::socket::ProtocolImpl::SocketInputStream , and jelatine::VMResourceStream .
Referenced by java::io::InputStreamReader::read(), read(), java::io::DataInputStream::read(), java::io::DataInputStream::readBoolean(), java::io::DataInputStream::readByte(), java::io::DataInputStream::readFully(), java::io::DataInputStream::readUnsignedByte(), and skip().
int java::io::InputStream::read (byte[] b) throws IOException [inline]
This method reads bytes from a stream and stores them into a caller supplied buffer. This method attempts to completely fill the buffer, but can return before doing so. The actual number of bytes read is returned as an int. A -1 is returned to indicate the end of the stream.
This method will block until some data can be read.
This method operates by calling an overloaded read method like so: read(b, 0, b.length)
Parameters
b The buffer into which the bytes read will be stored.
Returns
The number of bytes read or -1 if end of stream.
Exceptions
IOException If an error occurs.
Reimplemented in jelatine::cldc::io::socket::ProtocolImpl::SocketInputStream .
Definition at line 161 of file InputStream.java.
References read().
void java::io::InputStream::reset () throws IOException [inline]
This method resets a stream to the point where the mark() method was called. Any bytes that were read after the mark point was set will be re-read during subsequent reads.
This method always throws an IOException in this class, but subclasses can override this method if they provide mark/reset functionality.
Exceptions
IOException Always thrown for this class
Reimplemented in java::io::ByteArrayInputStream .
Definition at line 235 of file InputStream.java.
Referenced by java::io::InputStreamReader::reset(), and java::io::DataInputStream::reset().
long java::io::InputStream::skip (long n) throws IOException [inline]
This method skips the specified number of bytes in the stream. It returns the actual number of bytes skipped, which may be less than the requested amount.
This method reads and discards bytes into a byte array until the specified number of bytes were skipped or until either the end of stream is reached or a read attempt returns a short count. Subclasses can override this metho to provide a more efficient implementation where one exists.
Parameters
n The requested number of bytes to skip
Returns
The actual number of bytes skipped.
Exceptions
IOException If an error occurs
Reimplemented in java::io::ByteArrayInputStream .
Definition at line 257 of file InputStream.java.
References read().
Referenced by java::io::DataInputStream::skip(), and java::io::DataInputStream::skipBytes().
The documentation for this class was generated from the following file:
src/classpath/java/io/InputStream.java