java::lang::Double Class Reference
Public Member Functions
Double (double value)
String toString ()
boolean isNaN ()
boolean isInfinite ()
byte byteValue ()
short shortValue ()
int intValue ()
long longValue ()
float floatValue ()
double doubleValue ()
int hashCode ()
boolean equals (Object obj)
Static Public Member Functions
static native String toString (double d)
static Double valueOf (String s) throws NumberFormatException, NullPointerException
static double parseDouble (String str) throws NumberFormatException, NullPointerException
static boolean isNaN (double v)
static boolean isInfinite (double v)
static native long doubleToLongBits (double value)
static native double longBitsToDouble (long bits)
Static Public Attributes
static final double MAX_VALUE = 1.7976931348623157e+308
static final double MIN_VALUE = 5e-324
static final double NEGATIVE_INFINITY = -1.0 / 0.0
static final double POSITIVE_INFINITY = 1.0 / 0.0
static final double NaN = 0.0 / 0.0
Detailed Description
Instances of class Double represent primitive double values.
Additionally, this class provides various helper functions and variables related to doubles.
Author
Paul Fisher
Andrew Haley (aph@cygnus.com)
Eric Blake (ebb9@email.byu.edu)
Definition at line 52 of file Double.java.
Constructor & Destructor Documentation
java::lang::Double::Double (double value) [inline]
Create a Double from the primitive double specified.
Parameters
value the double argument
Definition at line 95 of file Double.java.
Referenced by valueOf().
Member Function Documentation
byte java::lang::Double::byteValue () [inline]
Return the value of this Double as a byte.
Returns
the byte value
Definition at line 376 of file Double.java.
static native long java::lang::Double::doubleToLongBits (double value) [static]
Convert the double to the IEEE 754 floating-point `double format` bit layout. Bit 63 (the most significant) is the sign bit, bits 62-52 (masked by 0x7ff0000000000000L) represent the exponent, and bits 51-0 (masked by 0x000fffffffffffffL) are the mantissa. This function collapses all versions of NaN to 0x7ff8000000000000L. The result of this function can be used as the argument to Double.longBitsToDouble(long) to obtain the original double value.
Parameters
value the double to convert
Returns
the bits of the double
See also
longBitsToDouble(long)
Referenced by hashCode().
double java::lang::Double::doubleValue () [inline]
Return the value of this Double.
Returns
the double value
Definition at line 426 of file Double.java.
boolean java::lang::Double::equals (Object obj) [inline]
Returns true if obj is an instance of Double and represents the same double value. Unlike comparing two doubles with ==, this treats two instances of Double.NaN as equal, but treats 0.0 and -0.0 as unequal.
Note that d1.equals(d2) is identical to doubleToLongBits(d1.doubleValue()) == doubleToLongBits(d2.doubleValue()).
Parameters
obj the object to compare
Returns
whether the objects are semantically equal
Definition at line 461 of file Double.java.
References isNaN().
float java::lang::Double::floatValue () [inline]
Return the value of this Double as a float.
Returns
the float value
Definition at line 416 of file Double.java.
int java::lang::Double::hashCode () [inline]
Return a hashcode representing this Object. Double's hash code is calculated by:
 long v = Double.doubleToLongBits(doubleValue());
 int hash = (int)(v^(v>>32)).
Returns
this Object's hash code
See also
doubleToLongBits(double)
Definition at line 440 of file Double.java.
References doubleToLongBits().
int java::lang::Double::intValue () [inline]
Return the value of this Double as an int.
Returns
the int value
Definition at line 396 of file Double.java.
boolean java::lang::Double::isInfinite () [inline]
Return true if the value of this Double is the same as NEGATIVE_INFINITY or POSITIVE_INFINITY, otherwise return false.
Returns
whether this Double is (-/+) infinity
Definition at line 366 of file Double.java.
static boolean java::lang::Double::isInfinite (double v) [inline, static]
Return true if the double has a value equal to either NEGATIVE_INFINITY or POSITIVE_INFINITY, otherwise return false.
Parameters
v the double to compare
Returns
whether the argument is (-/+) infinity.
Definition at line 330 of file Double.java.
References NEGATIVE_INFINITY, and POSITIVE_INFINITY.
static boolean java::lang::Double::isNaN (double v) [inline, static]
Return true if the double has the same value as NaN, otherwise return false.
Parameters
v the double to compare
Returns
whether the argument is NaN.
Definition at line 315 of file Double.java.
boolean java::lang::Double::isNaN () [inline]
Return true if the value of this Double is the same as NaN, otherwise return false.
Returns
whether this Double is NaN
Definition at line 354 of file Double.java.
Referenced by equals().
static native double java::lang::Double::longBitsToDouble (long bits) [static]
Convert the argument in IEEE 754 floating-point `double format` bit layout to the corresponding float. Bit 63 (the most significant) is the sign bit, bits 62-52 (masked by 0x7ff0000000000000L) represent the exponent, and bits 51-0 (masked by 0x000fffffffffffffL) are the mantissa. This function leaves NaN alone, so that you can recover the bit pattern with Double.doubleToRawLongBits(double).
Parameters
bits the bits to convert
Returns
the double represented by the bits
long java::lang::Double::longValue () [inline]
Return the value of this Double as a long.
Returns
the long value
Definition at line 406 of file Double.java.
static double java::lang::Double::parseDouble (String str) throws NumberFormatException, NullPointerException [inline, static]
Parse the specified String as a double. The extended BNF grammar is as follows:
 DecodableString:
      ([ - | + ] NaN)
    | ([ - | + ] Infinity)
    | ([ - | + ] FloatingPoint
              [ f | F | d
                | D])
 FloatingPoint:
      ({ Digit }+ [ . { Digit } ]
              [ Exponent ])
    | (. { Digit }+ [ Exponent ])
 Exponent:
      ((e | E)
              [ - | + ] { Digit }+)
 Digit: '0' through '9'
NaN and infinity are special cases, to allow parsing of the output of toString. Otherwise, the result is determined by calculating n * 10$^{\mbox{exponent}}$ to infinite precision, then rounding to the nearest double. Remember that many numbers cannot be precisely represented in floating point. In case of overflow, infinity is used, and in case of underflow, signed zero is used. Unlike Integer.parseInt, this does not accept Unicode digits outside the ASCII range.
If an unexpected character is found in the String, a NumberFormatException will be thrown. Leading and trailing 'whitespace' is ignored via String.trim(), but spaces internal to the actual number are not allowed.
Parameters
str the String to convert
Returns
the double value of s
Exceptions
NumberFormatException if s cannot be parsed as a double
NullPointerException if s is null
See also
MIN_VALUE
MAX_VALUE
POSITIVE_INFINITY
NEGATIVE_INFINITY
Definition at line 191 of file Double.java.
References java::lang::String::charAt(), java::lang::String::equals(), java::lang::String::length(), and java::lang::String::substring().
Referenced by valueOf().
short java::lang::Double::shortValue () [inline]
Return the value of this Double as a short.
Returns
the short value
Definition at line 386 of file Double.java.
String java::lang::Double::toString () [inline]
Convert the double value of this Double to a String. This method calls Double.toString(double) to do its dirty work.
Returns
the String representation
See also
toString(double)
Definition at line 343 of file Double.java.
static native String java::lang::Double::toString (double d) [static]
Convert the double to a String. Floating-point string representation is fairly complex: here is a rundown of the possible values. `<code>[-]</code>` indicates that a negative sign will be printed if the value (or exponent) is negative. `<code>&lt;number&gt;</code>` means a string of digits ('0' to '9'). `<code>&lt;digit&gt;</code>` means a single digit ('0' to '9').
Value of Double String Representation
[+-] 0 [-]0.0
Between [+-] 10$^{\mbox{-\/3}}$ and 10$^{\mbox{7}}$ , exclusive [-]number.number
Other numeric value [-]<digit>.<number> E[-]<number>
[+-] infinity [-]Infinity
NaN NaN
Yes, negative zero is a possible value. Note that there is always a . and at least one digit printed after it: even if the number is 3, it will be printed as 3.0. After the `.`, all digits will be printed except trailing zeros. The result is rounded to the shortest decimal number which will parse back to the same double.
Parameters
d the double to convert
Returns
the String representing the double
static Double java::lang::Double::valueOf (String s) throws NumberFormatException, NullPointerException [inline, static]
Create a new Double object using the String.
Parameters
s the String to convert
Returns
the new Double
Exceptions
NumberFormatException if s cannot be parsed as a double
NullPointerException if s is null.
See also
parseDouble(String)
Definition at line 142 of file Double.java.
References Double(), and parseDouble().
Field Documentation
final double java::lang::Double::MAX_VALUE = 1.7976931348623157e+308 [static]
The maximum positive value a double may represent is 1.7976931348623157e+308.
Definition at line 58 of file Double.java.
final double java::lang::Double::MIN_VALUE = 5e-324 [static]
The minimum positive value a double may represent is 5e-324.
Definition at line 64 of file Double.java.
final double java::lang::Double::NaN = 0.0 / 0.0 [static]
All IEEE 754 values of NaN have the same value in Java.
Definition at line 80 of file Double.java.
final double java::lang::Double::NEGATIVE_INFINITY = -1.0 / 0.0 [static]
The value of a double representation -1.0/0.0, negative infinity.
Definition at line 70 of file Double.java.
Referenced by isInfinite().
final double java::lang::Double::POSITIVE_INFINITY = 1.0 / 0.0 [static]
The value of a double representing 1.0/0.0, positive infinity.
Definition at line 75 of file Double.java.
Referenced by isInfinite().
The documentation for this class was generated from the following file:
src/classpath/java/lang/Double.java