src/jelatine/class.h File Reference
#include `wrappers.h`
#include `classfile.h`
#include `constantpool.h`
#include `field.h`
#include `header.h`
#include `method.h`
#include `memory.h`
#include `thread.h`
#include `java_lang_Class.h`
Data Structures
struct interface_manager_t
struct interface_iterator_t
struct class_t
Defines
#define JELATINE_CLASS_H (1)
Typedefs
typedef struct interface_manager_t interface_manager_t
typedef struct interface_iterator_t interface_iterator_t
typedef enum class_state_t class_state_t
typedef struct class_t class_t
Enumerations
enum class_state_t {
CS_DUMMY = 0,
CS_PRELOADED = 1,
CS_LINKING = 2,
CS_LINKED = 3,
CS_INITIALIZING = 4,
CS_INITIALIZED = 5,
CS_ERRONEOUS = 6
 }
Functions
interface_manager_t * im_create (void)
void im_add (interface_manager_t *, struct class_t *)
void im_flatten (interface_manager_t *)
bool im_is_present (interface_manager_t *, struct class_t *)
static interface_iterator_t interface_itr (interface_manager_t *im)
static bool interface_itr_has_next (interface_iterator_t itr)
static struct class_t * interface_itr_get_next (interface_iterator_t *itr)
bool class_is_parent (const class_t *, const class_t *)
void class_add_field (class_t *, const field_info_t *, const field_attributes_t *)
field_t * class_get_field (const class_t *, const char *, const char *, bool)
void class_purge_initializer (class_t *)
static uint32_t class_get_ref_n (const class_t *cl)
static uint32_t class_get_nref_size (const class_t *cl)
static class_t * class_get_parent (const class_t *cl)
static uint32_t class_get_id (const class_t *cl)
static bool class_is_object (const class_t *cl)
static bool class_is_array (const class_t *cl)
static uint8_t class_get_dimensions (const class_t *cl)
static bool class_is_interface (const class_t *cl)
static bool class_is_abstract (const class_t *cl)
static bool class_is_final (const class_t *cl)
static bool class_is_public (const class_t *cl)
static bool class_is_super (const class_t *cl)
static void class_set_state (class_t *cl, class_state_t state)
static bool class_is_preloaded (const class_t *cl)
static bool class_is_being_linked (const class_t *cl)
static bool class_is_linked (const class_t *cl)
static bool class_is_being_initialized (const class_t *cl)
static bool class_is_initialized (const class_t *cl)
static uintptr_t class_get_object (const class_t *cl)
static void class_alloc_fields (class_t *cl, size_t count)
Detailed Description
C object mirroring the java.lang.Class class
Definition in file class.h.
Define Documentation
#define JELATINE_CLASS_H (1)
class.h inclusion macro
Definition at line 28 of file class.h.
Typedef Documentation
typedef enum class_state_t class_state_t
Typedef for enum class_state_t
Definition at line 137 of file class.h.
typedef struct class_t class_t
Typedef for struct class_t
Definition at line 176 of file class.h.
typedef struct interface_iterator_t interface_iterator_t
Typedef for the struct interface_iterator_t type
Definition at line 82 of file class.h.
typedef struct interface_manager_t interface_manager_t
Typedef for struct interface_manager_t
Definition at line 58 of file class.h.
Enumeration Type Documentation
enum class_state_t
Loading state of a class
Enumerator:
CS_DUMMY
 Initial state of a newly allocated & cleared class.
CS_PRELOADED
 Preloading, this may happen during bootstrap.
CS_LINKING
 Linking, this happens during class resolution.
CS_LINKED
 Class has been resolved & linked but not initialized.
CS_INITIALIZING
 The class is being initialized.
CS_INITIALIZED
 The class has been initialized.
CS_ERRONEOUS
 The class is an erroneous state.
Definition at line 126 of file class.h.
Function Documentation
void class_add_field (class_t * cl, const field_info_t * info, const field_attributes_t * attr)
Adds a field to the class
Parameters
cl A pointer to a class being loaded
info A pointer to the information of the new field
attr A pointer to the field attributes of the new field
Definition at line 126 of file class.c.
References field_info_t::access_flags, field_t::access_flags, field_attributes_t::constant_value_found, field_attributes_t::constant_value_index, field_info_t::descriptor, field_t::descriptor, field_is_static(), class_t::fields, class_t::fields_n, field_info_t::name, field_t::name, and field_t::offset.
Referenced by load_fields().
static void class_alloc_fields (class_t * cl, size_t count) [inline, static]
Pre-allocate enough space for holding count fields
Parameters
cl A pointer to a class being loaded
count The number of fields to be pre-allocated
Definition at line 385 of file class.h.
References class_t::fields, class_t::fields_n, and gc_palloc().
Referenced by load_fields().
static uint8_t class_get_dimensions (const class_t * cl) [inline, static]
Gets the number of dimensions of an array class
Parameters
cl A pointer to an array class
Returns
The number of dimensions of the array class
Definition at line 252 of file class.h.
References class_is_array(), and class_t::dimensions.
Referenced by bcl_link_opcode().
field_t* class_get_field (const class_t * cl, const char * name, const char * descriptor, bool stat)
Finds a field by its name and descriptor, this function will only look for the field inside the specified class, not its parents
Parameters
cl A pointer to the class where to look for the field
name The field name
descriptor The descriptor name
stat true if the field looked for is static, false otherwise
Returns
A pointer to the field or NULL if none was found
Definition at line 153 of file class.c.
References field_t::descriptor, field_is_static(), class_t::fields, class_t::fields_n, and field_t::name.
Referenced by KNI_GetFieldID(), KNI_GetStaticFieldID(), and lookup_field().
static uint32_t class_get_id (const class_t * cl) [inline, static]
Gets the index of the passed class
Parameters
cl A valid pointer to a class_t structure
Returns
The id of the passed class
Definition at line 225 of file class.h.
References class_t::id.
Referenced by bcl_link_opcode().
static uint32_t class_get_nref_size (const class_t * cl) [inline, static]
Gets the size (in bytes) of the non-reference area of the given class' instances
Parameters
cl A valid pointer to a class_t structure
Returns
The size of the non-reference area of the class' instances
Definition at line 207 of file class.h.
References class_t::nref_size.
Referenced by gc_new(), gc_sweep(), and layout_fields().
static uintptr_t class_get_object (const class_t * cl) [inline, static]
Returns the java.lang.Class object associated with this class
Parameters
cl A pointer to a class structure
Returns
A reference to the java.lang.Class object associated with this class
Definition at line 376 of file class.h.
References class_t::obj.
Referenced by bcl_mark(), initialize_class(), interpreter(), java_lang_Class_forName(), java_lang_Object_getClass(), KNI_FindClass(), KNI_GetClassPointer(), KNI_GetObjectClass(), and KNI_GetSuperClass().
static class_t* class_get_parent (const class_t * cl) [inline, static]
Gets a pointer to the parent class of the passed one
Parameters
cl A valid pointer to a class_t structure
Returns
A pointer to the parent class
Definition at line 216 of file class.h.
References class_t::parent.
Referenced by KNI_GetSuperClass().
static uint32_t class_get_ref_n (const class_t * cl) [inline, static]
Gets the number of reference fields of the given class' instances
Parameters
cl A valid pointer to a class_t structure
Returns
The number of reference fields of the class' instances
Definition at line 197 of file class.h.
References class_t::ref_n.
Referenced by gc_mark_reference(), gc_new(), gc_sweep(), and layout_fields().
static bool class_is_abstract (const class_t * cl) [inline, static]
Checks if a class is abstract
Parameters
cl A valid pointer to a class_t structure
Returns
true if the class is abstract, false otherwise
Definition at line 271 of file class.h.
References class_t::access_flags.
Referenced by bcl_link_opcode(), derive_class(), and resolve_method().
static bool class_is_array (const class_t * cl) [inline, static]
Checks if a class is an array class
Parameters
cl A valid pointer to a class_t structure
Returns
true if the class is an array class, false otherwise
Definition at line 243 of file class.h.
References class_t::access_flags.
Referenced by array_get_ref_n(), bcl_is_assignable(), bcl_resolve_class(), class_get_dimensions(), derive_class(), gc_mark_reference(), gc_sweep(), java_lang_System_arraycopy(), and load_class().
static bool class_is_being_initialized (const class_t * cl) [inline, static]
Checks if the class is being initialized
Parameters
cl A pointer to a class structure
Returns
true if the class is in the initializing state, false otherwise
Definition at line 357 of file class.h.
References class_t::state.
Referenced by initialize_class().
static bool class_is_being_linked (const class_t * cl) [inline, static]
Checks if a class is being linked
Parameters
cl A pointer to a class structure
Returns
true if the class is in the linking state, false otherwise
Definition at line 339 of file class.h.
References class_t::state.
Referenced by bcl_resolve_class().
static bool class_is_final (const class_t * cl) [inline, static]
Checks if a class is final
Parameters
cl A valid pointer to a class_t structure
Returns
true if the class is final, false otherwise
Definition at line 280 of file class.h.
References class_t::access_flags.
Referenced by derive_class().
static bool class_is_initialized (const class_t * cl) [inline, static]
Checks if the class is being initialized
Parameters
cl A pointer to a class structure
Returns
true if the class is in the initializing state, false otherwise
Definition at line 366 of file class.h.
References class_t::state.
Referenced by initialize_class().
static bool class_is_interface (const class_t * cl) [inline, static]
Checks if a class is an interface
Parameters
cl A valid pointer to a class_t structure
Returns
true if the class is an interface, false otherwise
Definition at line 262 of file class.h.
References class_t::access_flags.
Referenced by bcl_is_assignable(), derive_class(), load_class(), load_interfaces(), load_methods(), resolve_method(), and verify_field().
static bool class_is_linked (const class_t * cl) [inline, static]
Checks if a class has been linked
Parameters
cl A pointer to a class structure
Returns
true if the class is in the linked state, false otherwise
Definition at line 348 of file class.h.
References class_t::state.
static bool class_is_object (const class_t * cl) [inline, static]
Checks if a class is the Object class
Parameters
cl A valid pointer to a class_t structure
Returns
true if the class is the java.lang.Object class, false otherwise
Definition at line 234 of file class.h.
References class_t::parent.
Referenced by bcl_is_assignable(), derive_class(), initialize_class(), lookup_field(), and resolve_method().
bool class_is_parent (const class_t * parent, const class_t * child)
Returns true if child is a child class of parent
Parameters
parent The potentially parent class
child The potentially child class
Returns
true if child inherits from parent, false otherwise
Definition at line 108 of file class.c.
References class_t::parent.
Referenced by bcl_link_opcode(), interpreter(), resolve_method(), and verify_field_access().
static bool class_is_preloaded (const class_t * cl) [inline, static]
Checks if a class has been preloaded
Parameters
cl A pointer to a class structure
Returns
true if the class is in the preloaded state, false otherwise
Definition at line 330 of file class.h.
References class_t::state.
Referenced by bcl_resolve_class().
static bool class_is_public (const class_t * cl) [inline, static]
Checks if a class is public
Parameters
cl A valid pointer to a class_t structure
Returns
true if the class is public
Definition at line 289 of file class.h.
References class_t::access_flags.
Referenced by bcl_resolve_class(), and derive_class().
static bool class_is_super (const class_t * cl) [inline, static]
Checks if a class has the ACC_SUPER flag set
Parameters
cl A valid pointer to a class_t structure
Returns
true if the class is public
Definition at line 298 of file class.h.
References class_t::access_flags.
Referenced by bcl_link_opcode().
void class_purge_initializer (class_t * cl)
This function unloads the class initializer method
Parameters
cl A pointer to a class_t structure
Definition at line 175 of file class.c.
References class_t::method_manager, method_purge(), and mm_get().
Referenced by initialize_class().
static void class_set_state (class_t * cl, class_state_t state) [inline, static]
Sets the linkage state of a class
Parameters
cl A pointer to a class structure
state The new state
Definition at line 320 of file class.h.
References class_t::state.
Referenced by initialize_class(), load_class(), and preload_class().
void im_add (interface_manager_t * im, class_t * cl)
Adds a new interface to the manager
Parameters
im A pointer to the interface manager
cl A pointer to an interface
Definition at line 51 of file class.c.
References interface_manager_t::entries, gc_free(), gc_malloc(), and interface_manager_t::interfaces.
Referenced by load_interfaces().
interface_manager_t* im_create (void)
Creates an interface manager
Returns
A new interface manager
Definition at line 40 of file class.c.
References gc_palloc().
Referenced by load_interfaces().
void im_flatten (interface_manager_t * im)
Flattens the interface manager internal representation turning it into a permanent structure
Parameters
im A pointer to the interface manager
Definition at line 74 of file class.c.
References interface_manager_t::entries, gc_free(), gc_palloc(), and interface_manager_t::interfaces.
Referenced by load_interfaces().
bool im_is_present (interface_manager_t * im, class_t * interface)
Checks if an interface is present in the interface manager
Parameters
im A pointer to the interface manager
interface A pointer to a class
Returns
true if the specified interface is present, false otherwise
Definition at line 88 of file class.c.
References interface_manager_t::entries, and interface_manager_t::interfaces.
Referenced by bcl_is_assignable().
static interface_iterator_t interface_itr (interface_manager_t * im) [inline, static]
Creates an interface iterator from the interface manager im
Parameters
im A pointer to a class' interface manager
Returns
An initialized instance interface iterator
Definition at line 88 of file class.h.
References interface_manager_t::entries, interface_iterator_t::entries, interface_iterator_t::index, interface_manager_t::interfaces, and interface_iterator_t::interfaces.
Referenced by create_interface_dispatch_table(), load_interfaces(), lookup_field(), and resolve_method().
static struct class_t* interface_itr_get_next (interface_iterator_t * itr) [static, read]
Returns the next interface, if the iterator has just been created it returns the data of the first interface (if it is present)
Parameters
itr A pointer to an interface iterator
Returns
A pointer to an interface
Definition at line 113 of file class.h.
References interface_iterator_t::index, interface_itr_has_next(), and interface_iterator_t::interfaces.
Referenced by create_interface_dispatch_table(), load_interfaces(), lookup_field(), and resolve_method().
static bool interface_itr_has_next (interface_iterator_t itr) [inline, static]
Returns true if another interface is available
Parameters
itr iterator An interface iterator
Returns
true if there are more interfaces, false otherwise
Definition at line 103 of file class.h.
References interface_iterator_t::entries, and interface_iterator_t::index.
Referenced by create_interface_dispatch_table(), interface_itr_get_next(), load_interfaces(), lookup_field(), and resolve_method().