java::util::Hashtable Class Reference
Data Structures
class Enumerator
class HashEntry
Public Member Functions
Hashtable ()
Hashtable (int initialCapacity)
synchronized int size ()
synchronized boolean isEmpty ()
Enumeration keys ()
Enumeration elements ()
synchronized boolean contains (Object value)
synchronized boolean containsKey (Object key)
synchronized Object get (Object key)
synchronized Object put (Object key, Object value)
synchronized Object remove (Object key)
synchronized void clear ()
synchronized String toString ()
Protected Member Functions
void rehash ()
Package Attributes
HashEntry[] buckets
int size
Static Package Attributes
static final int KEYS = 0
static final int VALUES = 1
static final int ENTRIES = 2
Detailed Description
A class which implements a hashtable data structure.
This implementation of Hashtable uses a hash-bucket approach. That is: linear probing and rehashing is avoided; instead, each hashed value maps to a simple linked-list which, in the best case, only has one node. Assuming a large enough table, low enough load factor, and / or well implemented hashCode() methods, Hashtable should provide O(1) insertion, deletion, and searching of keys. Hashtable is O(n) in the worst case for all of these (if all keys hash to the same bucket).
This is a JDK-1.2 compliant implementation of Hashtable. As such, it belongs, partially, to the Collections framework (in that it implements Map). For backwards compatibility, it inherits from the obsolete and utterly useless Dictionary class.
Being a hybrid of old and new, Hashtable has methods which provide redundant capability, but with subtle and even crucial differences. For example, one can iterate over various aspects of a Hashtable with either an Iterator (which is the JDK-1.2 way of doing things) or with an Enumeration. The latter can end up in an undefined state if the Hashtable changes while the Enumeration is open.
Unlike HashMap, Hashtable does not accept `null' as a key value. Also, all accesses are synchronized: in a single thread environment, this is expensive, but in a multi-thread environment, this saves you the effort of extra synchronization. However, the old-style enumerators are not synchronized, because they can lead to unspecified behavior even if they were synchronized. You have been warned.
The iterators are fail-fast, meaning that any structural modification, except for remove() called on the iterator itself, cause the iterator to throw a ConcurrentModificationException rather than exhibit non-deterministic behavior.
Author
Jon Zeppieri
Warren Levy
Bryce McKinlay
Eric Blake (ebb9@email.byu.edu)
Definition at line 91 of file Hashtable.java.
Constructor & Destructor Documentation
java::util::Hashtable::Hashtable () [inline]
Construct a new Hashtable with the default capacity (11) and the default load factor (0.75).
Definition at line 251 of file Hashtable.java.
java::util::Hashtable::Hashtable (int initialCapacity) [inline]
Construct a new Hashtable with a specific inital capacity and default load factor of 0.75.
Parameters
initialCapacity the initial capacity of this Hashtable (>= 0)
Exceptions
IllegalArgumentException if (initialCapacity < 0)
Definition at line 263 of file Hashtable.java.
References buckets, and size().
Member Function Documentation
synchronized void java::util::Hashtable::clear () [inline]
Clears the hashtable so it has no keys. This is O(1).
Definition at line 536 of file Hashtable.java.
References buckets, and size().
synchronized boolean java::util::Hashtable::contains (Object value) [inline]
Returns true if this Hashtable contains a value o, such that o.equals(value). This is the same as containsValue(), and is O(n).
Parameters
value the value to search for in this Hashtable
Returns
true if at least one key maps to the value
Exceptions
NullPointerException if value is null
Definition at line 329 of file Hashtable.java.
References buckets.
synchronized boolean java::util::Hashtable::containsKey (Object key) [inline]
Returns true if the supplied object equals() a key in this Hashtable.
Parameters
key the key to search for in this Hashtable
Returns
true if the key is in the table
Exceptions
NullPointerException if key is null
Definition at line 359 of file Hashtable.java.
References buckets.
Enumeration java::util::Hashtable::elements () [inline]
Return an enumeration of the values of this table. There's no point in synchronizing this, as you have already been warned that the enumeration is not specified to be thread-safe.
Returns
the values
Definition at line 314 of file Hashtable.java.
References VALUES.
synchronized Object java::util::Hashtable::get (Object key) [inline]
Return the value in this Hashtable associated with the supplied key, or null if the key maps to nothing.
Parameters
key the key for which to fetch an associated value
Returns
what the key maps to, if present
Exceptions
NullPointerException if key is null
See also
put(Object, Object)
containsKey(Object)
Definition at line 384 of file Hashtable.java.
References buckets.
synchronized boolean java::util::Hashtable::isEmpty () [inline]
Returns true if there are no key-value mappings currently in this table.
Returns
size() == 0
Definition at line 290 of file Hashtable.java.
References size().
Enumeration java::util::Hashtable::keys () [inline]
Return an enumeration of the keys of this table. There's no point in synchronizing this, as you have already been warned that the enumeration is not specified to be thread-safe.
Returns
the keys
Definition at line 302 of file Hashtable.java.
References KEYS.
synchronized Object java::util::Hashtable::put (Object key, Object value) [inline]
Puts the supplied value into the Map, mapped by the supplied key. Neither parameter may be null. The value may be retrieved by any object which equals() this key.
Parameters
key the key used to locate the value
value the value to be stored in the table
Returns
the prior mapping of the key, or null if there was none
Exceptions
NullPointerException if key or value is null
See also
get(Object)
Object::equals(Object)
Definition at line 459 of file Hashtable.java.
References buckets, rehash(), and size().
Referenced by jelatine::cldc::io::URL::getParamsMap().
void java::util::Hashtable::rehash () [inline, protected]
Increases the size of the Hashtable and rehashes all keys to new array indices; this is called when the addition of a new value would cause size() > threshold. Note that the existing Entry objects are reused in the new hash table.
This is not specified, but the new size is twice the current size plus one; this number is not always prime, unfortunately. This implementation is not synchronized, as it is only invoked from synchronized methods.
Definition at line 411 of file Hashtable.java.
References buckets.
Referenced by put().
synchronized Object java::util::Hashtable::remove (Object key) [inline]
Removes from the table and returns the value which is mapped by the supplied key. If the key maps to nothing, then the table remains unchanged, and null is returned.
Parameters
key the key used to locate the value to remove
Returns
whatever the key mapped to, if present
Definition at line 506 of file Hashtable.java.
References buckets, and size().
synchronized int java::util::Hashtable::size () [inline]
Returns the number of key-value mappings currently in this hashtable.
Returns
the size
Definition at line 281 of file Hashtable.java.
References size.
Referenced by clear(), Hashtable(), isEmpty(), put(), remove(), and toString().
synchronized String java::util::Hashtable::toString () [inline]
Converts this Hashtable to a String, surrounded by braces, and with key/value pairs listed with an equals sign between, separated by a comma and space. For example, `{a=1, b=2}`.
NOTE: if the toString() method of any key or value throws an exception, this will fail for the same reason.
Returns
the string representation
Definition at line 557 of file Hashtable.java.
References ENTRIES, java::util::Enumeration::nextElement(), and size().
Field Documentation
HashEntry [] java::util::Hashtable::buckets [package]
Array containing the actual key-value mappings.
Definition at line 125 of file Hashtable.java.
Referenced by clear(), contains(), containsKey(), get(), Hashtable(), put(), rehash(), and remove().
final int java::util::Hashtable::ENTRIES = 2 [static, package]
Enumerator for ENTRIES
Definition at line 107 of file Hashtable.java.
Referenced by toString().
final int java::util::Hashtable::KEYS = 0 [static, package]
Enumerator for KEYS
Definition at line 103 of file Hashtable.java.
Referenced by keys().
int java::util::Hashtable::size [package]
The size of this Hashtable: denotes the number of key-value pairs.
Definition at line 131 of file Hashtable.java.
Referenced by size().
final int java::util::Hashtable::VALUES = 1 [static, package]
Enumerator for VALUES
Definition at line 105 of file Hashtable.java.
Referenced by elements().
The documentation for this class was generated from the following file:
src/classpath/java/util/Hashtable.java