src/jelatine/class.c File Reference
#include `wrappers.h`
#include `array.h`
#include `class.h`
#include `memory.h`
#include `method.h`
#include `header.h`
#include `util.h`
Functions
interface_manager_t * im_create (void)
void im_add (interface_manager_t *im, class_t *cl)
void im_flatten (interface_manager_t *im)
bool im_is_present (interface_manager_t *im, class_t *interface)
bool class_is_parent (const class_t *parent, const class_t *child)
void class_add_field (class_t *cl, const field_info_t *info, const field_attributes_t *attr)
field_t * class_get_field (const class_t *cl, const char *name, const char *descriptor, bool stat)
void class_purge_initializer (class_t *cl)
Detailed Description
Class related functions implementation
Definition in file class.c.
Function Documentation
void class_add_field (class_t * cl, const field_info_t * info, const field_attributes_t * attr)
Adds a field to the class
Parameters
cl A pointer to a class being loaded
info A pointer to the information of the new field
attr A pointer to the field attributes of the new field
Definition at line 126 of file class.c.
References field_info_t::access_flags, field_t::access_flags, field_attributes_t::constant_value_found, field_attributes_t::constant_value_index, field_info_t::descriptor, field_t::descriptor, field_is_static(), class_t::fields, class_t::fields_n, field_info_t::name, field_t::name, and field_t::offset.
Referenced by load_fields().
field_t* class_get_field (const class_t * cl, const char * name, const char * descriptor, bool stat)
Finds a field by its name and descriptor, this function will only look for the field inside the specified class, not its parents
Parameters
cl A pointer to the class where to look for the field
name The field name
descriptor The descriptor name
stat true if the field looked for is static, false otherwise
Returns
A pointer to the field or NULL if none was found
Definition at line 153 of file class.c.
References field_t::descriptor, field_is_static(), class_t::fields, class_t::fields_n, and field_t::name.
Referenced by KNI_GetFieldID(), KNI_GetStaticFieldID(), and lookup_field().
bool class_is_parent (const class_t * parent, const class_t * child)
Returns true if child is a child class of parent
Parameters
parent The potentially parent class
child The potentially child class
Returns
true if child inherits from parent, false otherwise
Definition at line 108 of file class.c.
References class_t::parent.
Referenced by bcl_link_opcode(), interpreter(), resolve_method(), and verify_field_access().
void class_purge_initializer (class_t * cl)
This function unloads the class initializer method
Parameters
cl A pointer to a class_t structure
Definition at line 175 of file class.c.
References class_t::method_manager, method_purge(), and mm_get().
Referenced by initialize_class().
void im_add (interface_manager_t * im, class_t * cl)
Adds a new interface to the manager
Parameters
im A pointer to the interface manager
cl A pointer to an interface
Definition at line 51 of file class.c.
References interface_manager_t::entries, gc_free(), gc_malloc(), and interface_manager_t::interfaces.
Referenced by load_interfaces().
interface_manager_t* im_create (void)
Creates an interface manager
Returns
A new interface manager
Definition at line 40 of file class.c.
References gc_palloc().
Referenced by load_interfaces().
void im_flatten (interface_manager_t * im)
Flattens the interface manager internal representation turning it into a permanent structure
Parameters
im A pointer to the interface manager
Definition at line 74 of file class.c.
References interface_manager_t::entries, gc_free(), gc_palloc(), and interface_manager_t::interfaces.
Referenced by load_interfaces().
bool im_is_present (interface_manager_t * im, class_t * interface)
Checks if an interface is present in the interface manager
Parameters
im A pointer to the interface manager
interface A pointer to a class
Returns
true if the specified interface is present, false otherwise
Definition at line 88 of file class.c.
References interface_manager_t::entries, and interface_manager_t::interfaces.
Referenced by bcl_is_assignable().