java::lang::StringBuffer Class Reference
Public Member Functions
StringBuffer ()
StringBuffer (int capacity)
StringBuffer (String str)
synchronized int length ()
synchronized int capacity ()
synchronized void ensureCapacity (int minimumCapacity)
synchronized void setLength (int newLength)
synchronized char charAt (int index)
synchronized void getChars (int srcOffset, int srcEnd, char[] dst, int dstOffset)
synchronized void setCharAt (int index, char ch)
StringBuffer append (Object obj)
synchronized StringBuffer append (String str)
synchronized StringBuffer append (StringBuffer stringBuffer)
StringBuffer append (char[] data)
synchronized StringBuffer append (char[] data, int offset, int count)
StringBuffer append (boolean bool)
synchronized StringBuffer append (char ch)
StringBuffer append (int inum)
StringBuffer append (long lnum)
StringBuffer append (float fnum)
StringBuffer append (double dnum)
synchronized StringBuffer delete (int start, int end)
StringBuffer deleteCharAt (int index)
StringBuffer insert (int offset, Object obj)
synchronized StringBuffer insert (int offset, String str)
StringBuffer insert (int offset, char[] data)
StringBuffer insert (int offset, boolean bool)
synchronized StringBuffer insert (int offset, char ch)
StringBuffer insert (int offset, int inum)
StringBuffer insert (int offset, long lnum)
StringBuffer insert (int offset, float fnum)
StringBuffer insert (int offset, double dnum)
synchronized StringBuffer reverse ()
String toString ()
Package Attributes
int count
char[] value
boolean shared
Detailed Description
StringBuffer represents a changeable String. It provides the operations required to modify the StringBuffer, including insert, replace, delete, append, and reverse. It is thread-safe; meaning that all modifications to a buffer are in synchronized methods.
StringBuffers are variable-length in nature, so even if you initialize them to a certain size, they can still grow larger than that. Capacity indicates the number of characters the StringBuffer can have in it before it has to grow (growing the char array is an expensive operation involving new).
Incidentally, compilers often implement the String operator `+` by using a StringBuffer operation:
 a + b
 is the same as
 new StringBuffer().append(a).append(b).toString().
Classpath's StringBuffer is capable of sharing memory with Strings for efficiency. This will help when a StringBuffer is converted to a String and the StringBuffer is not changed after that (quite common when performing string concatenation).
Author
Paul Fisher
John Keiser
Tom Tromey
Eric Blake (ebb9@email.byu.edu)
See also
String
Since
1.0
Definition at line 74 of file StringBuffer.java.
Constructor & Destructor Documentation
java::lang::StringBuffer::StringBuffer () [inline]
Create a new StringBuffer with default capacity 16.
Definition at line 105 of file StringBuffer.java.
java::lang::StringBuffer::StringBuffer (int capacity) [inline]
Create an empty StringBuffer with the specified initial capacity.
Parameters
capacity the initial capacity
Exceptions
NegativeArraySizeException if capacity is negative
Definition at line 117 of file StringBuffer.java.
References value.
java::lang::StringBuffer::StringBuffer (String str) [inline]
Create a new StringBuffer with the characters in the specified String. Initial capacity will be the size of the String plus 16.
Parameters
str the String to convert
Exceptions
NullPointerException if str is null
Definition at line 130 of file StringBuffer.java.
References java::lang::String::count, count, java::lang::String::getChars(), and value.
Member Function Documentation
StringBuffer java::lang::StringBuffer::append (Object obj) [inline]
Append the String value of the argument to this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
obj the Object to convert and append
Returns
this StringBuffer
See also
String::valueOf(Object)
append(String)
Definition at line 286 of file StringBuffer.java.
References java::lang::Object::toString().
Referenced by append().
synchronized StringBuffer java::lang::StringBuffer::append (String str) [inline]
Append the String to this StringBuffer. If str is null, the String `null` is appended.
Parameters
str the String to append
Returns
this StringBuffer
Definition at line 298 of file StringBuffer.java.
References count, java::lang::String::count, java::lang::String::getChars(), and value.
StringBuffer java::lang::StringBuffer::append (long lnum) [inline]
Append the String value of the argument to this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
lnum the long to convert and append
Returns
this StringBuffer
See also
String::valueOf(long)
Definition at line 427 of file StringBuffer.java.
References append().
StringBuffer java::lang::StringBuffer::append (float fnum) [inline]
Append the String value of the argument to this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
fnum the float to convert and append
Returns
this StringBuffer
See also
String::valueOf(float)
Definition at line 441 of file StringBuffer.java.
References append().
StringBuffer java::lang::StringBuffer::append (double dnum) [inline]
Append the String value of the argument to this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
dnum the double to convert and append
Returns
this StringBuffer
See also
String::valueOf(double)
Definition at line 455 of file StringBuffer.java.
References append().
synchronized StringBuffer java::lang::StringBuffer::append (StringBuffer stringBuffer) [inline]
Append the StringBuffer value of the argument to this StringBuffer. This behaves the same as append((Object) stringBuffer), except it is more efficient.
Parameters
stringBuffer the StringBuffer to convert and append
Returns
this StringBuffer
See also
append(Object)
Since
1.4
Definition at line 320 of file StringBuffer.java.
References append(), count, and value.
StringBuffer java::lang::StringBuffer::append (char[] data) [inline]
Append the char array to this StringBuffer. This is similar (but more efficient) than append(new String(data)), except in the case of null.
Parameters
data the char[] to append
Returns
this StringBuffer
Exceptions
NullPointerException if str is null
See also
append(char[], int, int)
Definition at line 346 of file StringBuffer.java.
References append().
synchronized StringBuffer java::lang::StringBuffer::append (char[] data, int offset, int count) [inline]
Append part of the char array to this StringBuffer. This is similar (but more efficient) than append(new String(data, offset, count)), except in the case of null.
Parameters
data the char[] to append
offset the start location in str
count the number of characters to get from str
Returns
this StringBuffer
Exceptions
NullPointerException if str is null
IndexOutOfBoundsException if offset or count is out of range (while unspecified, this is a StringIndexOutOfBoundsException)
Definition at line 365 of file StringBuffer.java.
References value.
StringBuffer java::lang::StringBuffer::append (boolean bool) [inline]
Append the String value of the argument to this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
bool the boolean to convert and append
Returns
this StringBuffer
See also
String::valueOf(boolean)
Definition at line 385 of file StringBuffer.java.
References append().
synchronized StringBuffer java::lang::StringBuffer::append (char ch) [inline]
Append the char to this StringBuffer.
Parameters
ch the char to append
Returns
this StringBuffer
Definition at line 396 of file StringBuffer.java.
References count, and value.
StringBuffer java::lang::StringBuffer::append (int inum) [inline]
Append the String value of the argument to this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
inum the int to convert and append
Returns
this StringBuffer
See also
String::valueOf(int)
Definition at line 413 of file StringBuffer.java.
References append().
synchronized int java::lang::StringBuffer::capacity () [inline]
Get the total number of characters this StringBuffer can support before it must be grown. Not to be confused with length.
Returns
the capacity of this StringBuffer
See also
length()
ensureCapacity(int)
Definition at line 160 of file StringBuffer.java.
References value.
synchronized char java::lang::StringBuffer::charAt (int index) [inline]
Get the character at the specified index.
Parameters
index the index of the character to get, starting at 0
Returns
the character at the specified index
Exceptions
IndexOutOfBoundsException if index is negative or >= length()
Definition at line 226 of file StringBuffer.java.
References count, and value.
Referenced by java::lang::Class::getResourceAsStream().
synchronized StringBuffer java::lang::StringBuffer::delete (int start, int end) [inline]
Delete characters from this StringBuffer. delete(10, 12) will delete 10 and 11, but not 12. It is harmless for end to be larger than length().
Parameters
start the first character to delete
end the index after the last character to delete
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if start or end are out of bounds
Since
1.2
Definition at line 471 of file StringBuffer.java.
References count, and value.
Referenced by java::lang::Class::getResourceAsStream().
StringBuffer java::lang::StringBuffer::deleteCharAt (int index) [inline]
Delete a character from this StringBuffer.
Parameters
index the index of the character to delete
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if index is out of bounds
Since
1.2
Definition at line 497 of file StringBuffer.java.
Referenced by java::lang::Class::getResourceAsStream().
synchronized void java::lang::StringBuffer::ensureCapacity (int minimumCapacity) [inline]
Increase the capacity of this StringBuffer. This will ensure that an expensive growing operation will not occur until minimumCapacity is reached. The buffer is grown to the larger of minimumCapacity and capacity() * 2 + 2, if it is not already large enough.
Parameters
minimumCapacity the new capacity
See also
capacity()
Definition at line 175 of file StringBuffer.java.
synchronized void java::lang::StringBuffer::getChars (int srcOffset, int srcEnd, char[] dst, int dstOffset) [inline]
Get the specified array of characters. srcOffset - srcEnd characters will be copied into the array you pass in.
Parameters
srcOffset the index to start copying from (inclusive)
srcEnd the index to stop copying from (exclusive)
dst the array to copy into
dstOffset the index to start copying into
Exceptions
NullPointerException if dst is null
IndexOutOfBoundsException if any source or target indices are out of range (while unspecified, source problems cause a StringIndexOutOfBoundsException, and dest problems cause an ArrayIndexOutOfBoundsException)
See also
System::arraycopy(Object, int, Object, int, int)
Definition at line 249 of file StringBuffer.java.
References count, and value.
StringBuffer java::lang::StringBuffer::insert (int offset, boolean bool) [inline]
Insert the String value of the argument into this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
offset the place to insert in this buffer
bool the boolean to convert and insert
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if offset is out of bounds
See also
String::valueOf(boolean)
Definition at line 575 of file StringBuffer.java.
References insert().
StringBuffer java::lang::StringBuffer::insert (int offset, float fnum) [inline]
Insert the String value of the argument into this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
offset the place to insert in this buffer
fnum the float to convert and insert
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if offset is out of bounds
See also
String::valueOf(float)
Definition at line 643 of file StringBuffer.java.
References insert().
StringBuffer java::lang::StringBuffer::insert (int offset, double dnum) [inline]
Insert the String value of the argument into this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
offset the place to insert in this buffer
dnum the double to convert and insert
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if offset is out of bounds
See also
String::valueOf(double)
Definition at line 659 of file StringBuffer.java.
References insert().
StringBuffer java::lang::StringBuffer::insert (int offset, Object obj) [inline]
Insert the String value of the argument into this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
offset the place to insert in this buffer
obj the Object to convert and insert
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if offset is out of bounds
See also
String::valueOf(Object)
Definition at line 513 of file StringBuffer.java.
References java::lang::Object::toString().
Referenced by java::lang::Class::getResourceAsStream(), and insert().
synchronized StringBuffer java::lang::StringBuffer::insert (int offset, String str) [inline]
Insert the String argument into this StringBuffer. If str is null, the String `null` is used instead.
Parameters
offset the place to insert in this buffer
str the String to insert
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if offset is out of bounds
Definition at line 528 of file StringBuffer.java.
References java::lang::String::count, count, java::lang::String::getChars(), and value.
StringBuffer java::lang::StringBuffer::insert (int offset, int inum) [inline]
Insert the String value of the argument into this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
offset the place to insert in this buffer
inum the int to convert and insert
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if offset is out of bounds
See also
String::valueOf(int)
Definition at line 611 of file StringBuffer.java.
References insert().
StringBuffer java::lang::StringBuffer::insert (int offset, long lnum) [inline]
Insert the String value of the argument into this StringBuffer. Uses String.valueOf() to convert to String.
Parameters
offset the place to insert in this buffer
lnum the long to convert and insert
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if offset is out of bounds
See also
String::valueOf(long)
Definition at line 627 of file StringBuffer.java.
References insert().
synchronized StringBuffer java::lang::StringBuffer::insert (int offset, char ch) [inline]
Insert the char argument into this StringBuffer.
Parameters
offset the place to insert in this buffer
ch the char to insert
Returns
this StringBuffer
Exceptions
StringIndexOutOfBoundsException if offset is out of bounds
Definition at line 588 of file StringBuffer.java.
References count, and value.
StringBuffer java::lang::StringBuffer::insert (int offset, char[] data) [inline]
Insert the char[] argument into this StringBuffer.
Parameters
offset the place to insert in this buffer
data the char[] to insert
Returns
this StringBuffer
Exceptions
NullPointerException if data is null
StringIndexOutOfBoundsException if offset is out of bounds
Definition at line 554 of file StringBuffer.java.
References value.
synchronized int java::lang::StringBuffer::length () [inline]
Get the length of the String this StringBuffer would create. Not to be confused with the capacity of the StringBuffer.
Returns
the length of this StringBuffer
See also
capacity()
setLength(int)
Definition at line 147 of file StringBuffer.java.
References count.
Referenced by java::lang::Class::getResourceAsStream().
synchronized StringBuffer java::lang::StringBuffer::reverse () [inline]
Reverse the characters in this StringBuffer. The same sequence of characters exists, but in the reverse index ordering.
Returns
this StringBuffer
Definition at line 670 of file StringBuffer.java.
References count, and value.
synchronized void java::lang::StringBuffer::setCharAt (int index, char ch) [inline]
Set the character at the specified index.
Parameters
index the index of the character to set starting at 0
ch the value to set that character to
Exceptions
IndexOutOfBoundsException if index is negative or >= length() (while unspecified, this is a StringIndexOutOfBoundsException)
Definition at line 266 of file StringBuffer.java.
References count, and value.
Referenced by java::lang::Class::getResourceAsStream().
synchronized void java::lang::StringBuffer::setLength (int newLength) [inline]
Set the length of this StringBuffer. If the new length is greater than the current length, all the new characters are set to 0. If the new length is less than the current length, the first newLength characters of the old array will be preserved, and the remaining characters are truncated.
Parameters
newLength the new length
Exceptions
IndexOutOfBoundsException if the new length is negative (while unspecified, this is a StringIndexOutOfBoundsException)
See also
length()
Definition at line 192 of file StringBuffer.java.
References count, and value.
String java::lang::StringBuffer::toString () [inline]
Convert this StringBuffer to a String. The String is composed of the characters currently in this StringBuffer. Note that the result is a copy, and that future modifications to this buffer do not affect the String.
Returns
the characters in this StringBuffer
Definition at line 693 of file StringBuffer.java.
Referenced by java::lang::Class::getResourceAsStream().
Field Documentation
int java::lang::StringBuffer::count [package]
Index of next available character (and thus the size of the current string contents). Note that this has permissions set this way so that String can get the value.
Definition at line 81 of file StringBuffer.java.
Referenced by append(), charAt(), delete(), getChars(), insert(), length(), reverse(), setCharAt(), setLength(), java::lang::String::String(), and StringBuffer().
boolean java::lang::StringBuffer::shared [package]
True if the buffer is shared with another object (StringBuffer or String); this means the buffer must be copied before writing to it again. Note that this has permissions set this way so that String can get the value.
Definition at line 95 of file StringBuffer.java.
Referenced by java::lang::String::String().
char [] java::lang::StringBuffer::value [package]
The buffer. Note that this has permissions set this way so that String can get the value.
Definition at line 87 of file StringBuffer.java.
Referenced by append(), capacity(), charAt(), delete(), getChars(), insert(), reverse(), setCharAt(), setLength(), java::lang::String::String(), and StringBuffer().
The documentation for this class was generated from the following file:
src/classpath/java/lang/StringBuffer.java