java::io::DataInputStream Class Reference
Public Member Functions
DataInputStream (InputStream in)
int read () throws IOException
final int read (byte[] b) throws IOException
final int read (byte[] b, int off, int len) throws IOException
final void readFully (byte[] b) throws EOFException, IOException
final void readFully (byte[] buf, int offset, int len) throws EOFException, IOException
int skipBytes (int n) throws IOException
final boolean readBoolean () throws IOException
final byte readByte () throws IOException
final int readUnsignedByte () throws IOException
final short readShort () throws IOException
final int readUnsignedShort () throws IOException
final char readChar () throws IOException
final int readInt () throws IOException
final long readLong () throws IOException
final float readFloat () throws IOException
final double readDouble () throws IOException
final String readUTF () throws IOException
long skip (long n) throws IOException
int available () throws IOException
void close () throws IOException
synchronized void mark (int limit)
synchronized void reset () throws IOException
boolean markSupported ()
Static Public Member Functions
static final String readUTF (DataInput in) throws IOException
Protected Attributes
InputStream in
Detailed Description
This subclass of FilteredInputStream implements the DataInput interface that provides method for reading primitive Java data types from a stream.
See also
DataInput
Author
Warren Levy (warrenl@cygnus.com)
Aaron M. Renn (arenn@urbanophile.com)
Date
October 20, 1998.
Definition at line 57 of file DataInputStream.java.
Constructor & Destructor Documentation
java::io::DataInputStream::DataInputStream (InputStream in) [inline]
This constructor initializes a new DataInputStream to read from the specified subordinate stream.
Parameters
in The subordinate InputStream to read from
Definition at line 73 of file DataInputStream.java.
Member Function Documentation
int java::io::DataInputStream::available () throws IOException [inline]
Returns the number of available bytes which may be read w/o blocking
Returns
The number of available bytes
Exceptions
IOException if any I/O error occurs
Definition at line 622 of file DataInputStream.java.
References java::io::InputStream::available(), and in.
void java::io::DataInputStream::close () throws IOException [inline]
Closes the input stream
Exceptions
IOException if any I/O error occurs
Definition at line 632 of file DataInputStream.java.
References java::io::InputStream::close(), and in.
synchronized void java::io::DataInputStream::mark (int limit) [inline]
Marks the current position in the input stream
Parameters
limit The number of bytes which may be read before the mark becomes invalid
Definition at line 643 of file DataInputStream.java.
References in, and java::io::InputStream::mark().
boolean java::io::DataInputStream::markSupported () [inline]
Returns true if this stream supports the mark() and reset() methods
Definition at line 662 of file DataInputStream.java.
References in, and java::io::InputStream::markSupported().
final int java::io::DataInputStream::read (byte[] b) throws IOException [inline]
This method reads bytes from the underlying stream into the specified byte array buffer. It will attempt to fill the buffer completely, but may return a short count if there is insufficient data remaining to be read to fill the buffer.
Parameters
b The buffer into which bytes will be read.
Returns
The actual number of bytes read, or -1 if end of stream reached before reading any bytes.
Exceptions
IOException If an error occurs.
Definition at line 102 of file DataInputStream.java.
References in, and java::io::InputStream::read().
int java::io::DataInputStream::read () throws IOException [inline]
This method reads a byte from the underlying stream
Returns
An int holding the byte read from the stream
Exceptions
IOException If an error occurs.
Definition at line 84 of file DataInputStream.java.
References in, and java::io::InputStream::read().
final int java::io::DataInputStream::read (byte[] b, int off, int len) throws IOException [inline]
This method reads bytes from the underlying stream into the specified byte array buffer. It will attempt to read len bytes and will start storing them at position off into the buffer. This method can return a short count if there is insufficient data remaining to be read to complete the desired read length.
Parameters
b The buffer into which bytes will be read.
off The offset into the buffer to start storing bytes.
len The requested number of bytes to read.
Returns
The actual number of bytes read, or -1 if end of stream reached before reading any bytes.
Exceptions
IOException If an error occurs.
Definition at line 123 of file DataInputStream.java.
References in, and java::io::InputStream::read().
final boolean java::io::DataInputStream::readBoolean () throws IOException [inline]
This method reads a Java boolean value from an input stream. It does so by reading a single byte of data. If that byte is zero, then the value returned is false. If the byte is non-zero, then the value returned is true.
This method can read a boolean written by an object implementing the writeBoolean() method in the DataOutput interface.
Returns
The boolean value read
Exceptions
EOFException If end of file is reached before reading the boolean
IOException If any other error occurs
See also
DataOutput::writeBoolean
Implements java::io::DataInput .
Definition at line 232 of file DataInputStream.java.
References in, and java::io::InputStream::read().
final byte java::io::DataInputStream::readByte () throws IOException [inline]
This method reads a Java byte value from an input stream. The value is in the range of -128 to 127.
This method can read a byte written by an object implementing the writeByte() method in the DataOutput interface.
Returns
The byte value read
Exceptions
EOFException If end of file is reached before reading the byte
IOException If any other error occurs
See also
DataOutput::writeByte
Implements java::io::DataInput .
Definition at line 252 of file DataInputStream.java.
References in, and java::io::InputStream::read().
final char java::io::DataInputStream::readChar () throws IOException [inline]
This method reads a Java char value from an input stream. It operates by reading two bytes from the stream and converting them to a single 16-bit Java char. The two bytes are stored most significant byte first (i.e., `big endian`) regardless of the native host byte ordering.
As an example, if byte1 and byte2 represent the first and second byte read from the stream respectively, they will be transformed to a char in the following manner:
(char)(((byte1 & 0xFF) << 8) | (byte2 & 0xFF)
This method can read a char written by an object implementing the writeChar() method in the DataOutput interface.
Returns
The char value read
Exceptions
EOFException If end of file is reached before reading the char
IOException If any other error occurs
See also
DataOutput::writeChar
Implements java::io::DataInput .
Definition at line 371 of file DataInputStream.java.
References readFully().
final double java::io::DataInputStream::readDouble () throws IOException [inline]
This method reads a Java double value from an input stream. It operates by first reading a long value from the stream by calling the readLong() method in this interface, then converts that long to a double using the longBitsToDouble method in the class java.lang.Double
This method can read a double written by an object implementing the writeDouble() method in the DataOutput interface.
Returns
The double value read
Exceptions
EOFException If end of file is reached before reading the double
IOException If any other error occurs
See also
DataOutput::writeDouble
java.lang.Double::longBitsToDouble
Implements java::io::DataInput .
Definition at line 496 of file DataInputStream.java.
References readLong().
final float java::io::DataInputStream::readFloat () throws IOException [inline]
This method reads a Java float value from an input stream. It operates by first reading an int value from the stream by calling the readInt() method in this interface, then converts that int to a float using the intBitsToFloat method in the class java.lang.Float
This method can read a float written by an object implementing the writeFloat() method in the DataOutput interface.
Returns
The float value read
Exceptions
EOFException If end of file is reached before reading the float
IOException If any other error occurs
See also
DataOutput::writeFloat
java.lang.Float::intBitsToFloat
Implements java::io::DataInput .
Definition at line 470 of file DataInputStream.java.
References readInt().
final void java::io::DataInputStream::readFully (byte[] b) throws EOFException, IOException [inline]
This method reads raw bytes into the passed array until the array is full. Note that this method blocks until the data is available and throws an exception if there is not enough data left in the stream to fill the buffer. Note also that zero length buffers are permitted. In this case, the method will return immediately without reading any bytes from the stream.
Parameters
b The buffer into which to read the data
Exceptions
EOFException If end of file is reached before filling the buffer
IOException If any other error occurs
Implements java::io::DataInput .
Definition at line 142 of file DataInputStream.java.
Referenced by readChar(), readInt(), readLong(), readShort(), and readUnsignedShort().
final void java::io::DataInputStream::readFully (byte[] buf, int offset, int len) throws EOFException, IOException [inline]
This method reads raw bytes into the passed array buf starting offset bytes into the buffer. The number of bytes read will be exactly len. Note that this method blocks until the data is available and throws an exception if there is not enough data left in the stream to read len bytes. Note also that zero length buffers are permitted. In this case, the method will return immediately without reading any bytes from the stream.
Parameters
buf The buffer into which to read the data
offset The offset into the buffer to start storing data
len The number of bytes to read into the buffer
Exceptions
EOFException If end of file is reached before filling the buffer
IOException If any other error occurs
Implements java::io::DataInput .
Definition at line 166 of file DataInputStream.java.
References in, and java::io::InputStream::read().
final int java::io::DataInputStream::readInt () throws IOException [inline]
This method reads a Java int value from an input stream It operates by reading four bytes from the stream and converting them to a single Java int. The bytes are stored most significant byte first (i.e., `big endian`) regardless of the native host byte ordering.
As an example, if byte1 through byte4 represent the first four bytes read from the stream, they will be transformed to an int in the following manner:
(int)(((byte1 & 0xFF) << 24) + ((byte2 & 0xFF) << 16) + ((byte3 & 0xFF)<< 8) + (byte4 & 0xFF)))
The value returned is in the range of -2147483648 to 2147483647.
This method can read an int written by an object implementing the writeInt() method in the DataOutput interface.
Returns
The int value read
Exceptions
EOFException If end of file is reached before reading the int
IOException If any other error occurs
See also
DataOutput::writeInt
Implements java::io::DataInput .
Definition at line 405 of file DataInputStream.java.
References readFully().
Referenced by readFloat().
final long java::io::DataInputStream::readLong () throws IOException [inline]
This method reads a Java long value from an input stream It operates by reading eight bytes from the stream and converting them to a single Java long. The bytes are stored most significant byte first (i.e., `big endian`) regardless of the native host byte ordering.
As an example, if byte1 through byte8 represent the first eight bytes read from the stream, they will be transformed to an long in the following manner:
(long)(((byte1 & 0xFF) << 56) + ((byte2 & 0xFF) << 48) + ((byte3 & 0xFF) << 40) + ((byte4 & 0xFF) << 32) + ((byte5 & 0xFF) << 24) + ((byte6 & 0xFF) << 16) + ((byte7 & 0xFF) << 8) + (byte8 & 0xFF)))
The value returned is in the range of -9223372036854775808 to 9223372036854775807.
This method can read an long written by an object implementing the writeLong() method in the DataOutput interface.
Returns
The long value read
Exceptions
EOFException If end of file is reached before reading the long
IOException If any other error occurs
See also
DataOutput::writeLong
Implements java::io::DataInput .
Definition at line 443 of file DataInputStream.java.
References readFully().
Referenced by readDouble().
final short java::io::DataInputStream::readShort () throws IOException [inline]
This method reads a signed 16-bit value into a Java in from the stream. It operates by reading two bytes from the stream and converting them to a single 16-bit Java short. The two bytes are stored most significant byte first (i.e., `big
 endian`) regardless of the native host byte ordering.
As an example, if byte1 and byte2 represent the first and second byte read from the stream respectively, they will be transformed to a short. in the following manner:
(short)(((byte1 & 0xFF) << 8) | (byte2 & 0xFF))
The value returned is in the range of -32768 to 32767.
This method can read a short written by an object implementing the writeShort() method in the DataOutput interface.
Returns
The short value read
Exceptions
EOFException If end of file is reached before reading the value
IOException If any other error occurs
See also
DataOutput::writeShort
Implements java::io::DataInput .
Definition at line 305 of file DataInputStream.java.
References readFully().
final int java::io::DataInputStream::readUnsignedByte () throws IOException [inline]
This method reads 8 unsigned bits into a Java int value from the stream. The value returned is in the range of 0 to 255.
This method can read an unsigned byte written by an object implementing the writeUnsignedByte() method in the DataOutput interface.
Returns
The unsigned bytes value read as a Java int.
Exceptions
EOFException If end of file is reached before reading the value
IOException If any other error occurs
See also
DataOutput::writeByte
Implements java::io::DataInput .
Definition at line 273 of file DataInputStream.java.
References in, and java::io::InputStream::read().
final int java::io::DataInputStream::readUnsignedShort () throws IOException [inline]
This method reads 16 unsigned bits into a Java int value from the stream. It operates by reading two bytes from the stream and converting them to a single Java int The two bytes are stored most significant byte first (i.e., `big endian`) regardless of the native host byte ordering.
As an example, if byte1 and byte2 represent the first and second byte read from the stream respectively, they will be transformed to an int in the following manner:
(int)(((byte1 & 0xFF) << 8) + (byte2 & 0xFF))
The value returned is in the range of 0 to 65535.
This method can read an unsigned short written by an object implementing the writeUnsignedShort() method in the DataOutput interface.
Returns
The unsigned short value read as a Java int
Exceptions
EOFException If end of file is reached before reading the value
IOException If any other error occurs
See also
DataOutput::writeShort
Implements java::io::DataInput .
Definition at line 339 of file DataInputStream.java.
References readFully().
final String java::io::DataInputStream::readUTF () throws IOException [inline]
This method reads a String from an input stream that is encoded in a modified UTF-8 format. This format has a leading two byte sequence that contains the remaining number of bytes to read. This two byte sequence is read using the readUnsignedShort() method of this interface.
After the number of remaining bytes have been determined, these bytes are read an transformed into char values. These char values are encoded in the stream using either a one, two, or three byte format. The particular format in use can be determined by examining the first byte read.
If the first byte has a high order bit of 0, then that character consists on only one byte. This character value consists of seven bits that are at positions 0 through 6 of the byte. As an example, if byte1 is the byte read from the stream, it would be converted to a char like so:
(char)byte1
If the first byte has 110 as its high order bits, then the character consists of two bytes. The bits that make up the character value are in positions 0 through 4 of the first byte and bit positions 0 through 5 of the second byte. (The second byte should have 10 as its high order bits). These values are in most significant byte first (i.e., `big endian`) order.
As an example, if byte1 and byte2 are the first two bytes read respectively, and the high order bits of them match the patterns which indicate a two byte character encoding, then they would be converted to a Java char like so:
(char)(((byte1 & 0x1F) << 6) | (byte2 & 0x3F))
If the first byte has a 1110 as its high order bits, then the character consists of three bytes. The bits that make up the character value are in positions 0 through 3 of the first byte and bit positions 0 through 5 of the other two bytes. (The second and third bytes should have 10 as their high order bits). These values are in most significant byte first (i.e., `big endian`) order.
As an example, if byte1 byte2 and byte3 are the three bytes read, and the high order bits of them match the patterns which indicate a three byte character encoding, then they would be converted to a Java char like so:
(char)(((byte1 & 0x0F) << 12) | ((byte2 & 0x3F) << 6) | (byte3 & 0x3F))
Note that all characters are encoded in the method that requires the fewest number of bytes with the exception of the character with the value of &#92;u0000 which is encoded as two bytes. This is a modification of the UTF standard used to prevent C language style NUL values from appearing in the byte stream.
This method can read data that was written by an object implementing the writeUTF() method in DataOutput
Returns
The String read
Exceptions
EOFException If end of file is reached before reading the String
UTFDataFormatException If the data is not in UTF-8 format
IOException If any other error occurs
See also
DataOutput::writeUTF
Implements java::io::DataInput .
Definition at line 572 of file DataInputStream.java.
static final String java::io::DataInputStream::readUTF (DataInput in) throws IOException [inline, static]
This method reads a String encoded in UTF-8 format from the specified DataInput source.
Parameters
in The DataInput source to read from
Returns
The String read from the source
Exceptions
IOException If an error occurs
See also
DataInput::readUTF
Definition at line 589 of file DataInputStream.java.
References in.
synchronized void java::io::DataInputStream::reset () throws IOException [inline]
Resets the starting position in the input stream to the last marked one
Exceptions
IOException If any I/O error occurs
Definition at line 653 of file DataInputStream.java.
References in, and java::io::InputStream::reset().
long java::io::DataInputStream::skip (long n) throws IOException [inline]
Skips n bytes in the input stream
Parameters
n The bytes to be skipped
Returns
The actual number of bytes skipped
Exceptions
IOException If any I/O error occurs
Definition at line 611 of file DataInputStream.java.
References in, and java::io::InputStream::skip().
int java::io::DataInputStream::skipBytes (int n) throws IOException [inline]
This method attempts to skip and discard the specified number of bytes in the input stream. It may actually skip fewer bytes than requested. This method will not skip any bytes if passed a negative number of bytes to skip.
Parameters
n The requested number of bytes to skip.
Returns
The requested number of bytes to skip.
Exceptions
IOException If an error occurs.
Implements java::io::DataInput .
Definition at line 197 of file DataInputStream.java.
References in, and java::io::InputStream::skip().
Field Documentation
InputStream java::io::DataInputStream::in [protected]
The embedded InputStream object
Definition at line 65 of file DataInputStream.java.
Referenced by available(), close(), mark(), markSupported(), read(), readBoolean(), readByte(), readFully(), readUnsignedByte(), readUTF(), reset(), skip(), and skipBytes().
The documentation for this class was generated from the following file:
src/classpath/java/io/DataInputStream.java