java::io::DataOutputStream Class Reference
Public Member Functions
DataOutputStream (OutputStream out)
synchronized void write (int value) throws IOException
synchronized void write (byte[] buf) throws IOException
synchronized void write (byte[] buf, int offset, int len) throws IOException
void flush () throws IOException
void close () throws IOException
final void writeBoolean (boolean value) throws IOException
final void writeByte (int value) throws IOException
final synchronized void writeShort (int value) throws IOException
final synchronized void writeChar (int value) throws IOException
final synchronized void writeInt (int value) throws IOException
final synchronized void writeLong (long value) throws IOException
final void writeFloat (float value) throws IOException
final void writeDouble (double value) throws IOException
final void writeChars (String value) throws IOException
final synchronized void writeUTF (String value) throws IOException
Protected Attributes
OutputStream out
Detailed Description
This class provides a mechanism for writing primitive Java datatypes to an OutputStream in a portable way. Data written to a stream using this class can be read back in using the DataInputStream class on any platform.
See also
DataInputStream
Definition at line 51 of file DataOutputStream.java.
Constructor & Destructor Documentation
java::io::DataOutputStream::DataOutputStream (OutputStream out) [inline]
This method initializes an instance of DataOutputStream to write its data to the specified underlying OutputStream
Parameters
out The subordinate OutputStream to which this object will write
Definition at line 65 of file DataOutputStream.java.
Member Function Documentation
void java::io::DataOutputStream::close () throws IOException [inline]
Closes the output stream
Exceptions
IOException if any I/O error occurs
Definition at line 129 of file DataOutputStream.java.
References java::io::OutputStream::close(), and out.
void java::io::DataOutputStream::flush () throws IOException [inline]
This method flushes any unwritten bytes to the underlying stream.
Exceptions
IOException If an error occurs.
Definition at line 119 of file DataOutputStream.java.
References java::io::OutputStream::flush(), and out.
synchronized void java::io::DataOutputStream::write (byte[] buf) throws IOException [inline]
This method writes the specified byte array to the underlying output stream.
Parameters
buf The byte array to write from.
Exceptions
IOException If an error occurs.
Implements java::io::DataOutput .
Definition at line 91 of file DataOutputStream.java.
References write().
synchronized void java::io::DataOutputStream::write (int value) throws IOException [inline]
This method writes the specified byte (passed as an int) to the underlying output stream.
Parameters
value The byte to write, passed as an int.
Exceptions
IOException If an error occurs.
Implements java::io::DataOutput .
Definition at line 78 of file DataOutputStream.java.
References out, and java::io::OutputStream::write().
Referenced by write(), and writeUTF().
synchronized void java::io::DataOutputStream::write (byte[] buf, int offset, int len) throws IOException [inline]
This method writes len bytes from the specified byte array buf starting at position offset into the buffer to the underlying output stream.
Parameters
buf The byte array to write from.
offset The index into the byte array to start writing from.
len The number of bytes to write.
Exceptions
IOException If an error occurs.
Implements java::io::DataOutput .
Definition at line 108 of file DataOutputStream.java.
References out, and java::io::OutputStream::write().
final void java::io::DataOutputStream::writeBoolean (boolean value) throws IOException [inline]
This method writes a Java boolean value to an output stream. If value is true, a byte with the value of 1 will be written, otherwise a byte with the value of 0 will be written.
The value written can be read using the readBoolean method in DataInput.
Parameters
value The boolean value to write to the stream
Exceptions
IOException If an error occurs
See also
DataInput::readBoolean
Implements java::io::DataOutput .
Definition at line 149 of file DataOutputStream.java.
References out, and java::io::OutputStream::write().
final void java::io::DataOutputStream::writeByte (int value) throws IOException [inline]
This method writes a Java byte value to an output stream. The byte to be written will be in the lowest 8 bits of the int value passed.
The value written can be read using the readByte or readUnsignedByte methods in DataInput.
Parameters
value The byte to write to the stream, passed as the low eight bits of an int.
Exceptions
IOException If an error occurs
See also
DataInput::readByte
DataInput::readUnsignedByte
Implements java::io::DataOutput .
Definition at line 170 of file DataOutputStream.java.
References out, and java::io::OutputStream::write().
final synchronized void java::io::DataOutputStream::writeChar (int value) throws IOException [inline]
This method writes a Java char value to an output stream. The char to be written will be in the lowest 16 bits of the int value passed. These bytes will be written `big endian`. That is, with the high byte written first in the following manner:
byte0 = (byte)((value & 0xFF00) >> 8);
 byte1 = (byte)(value & 0x00FF);
The value written can be read using the readChar method in DataInput.
Parameters
value The char value to write, passed as an int.
Exceptions
IOException If an error occurs
See also
DataInput::readChar
Implements java::io::DataOutput .
Definition at line 222 of file DataOutputStream.java.
References out, and java::io::OutputStream::write().
Referenced by writeChars().
final void java::io::DataOutputStream::writeChars (String value) throws IOException [inline]
This method writes all the characters of a String to an output stream as an array of char's. Each character is written using the method specified in the writeChar method.
Parameters
value The String to write to the stream
Exceptions
IOException If an error occurs
Definition at line 350 of file DataOutputStream.java.
References writeChar().
final void java::io::DataOutputStream::writeDouble (double value) throws IOException [inline]
This method writes a Java double value to the stream. This value is written by first calling the method Double.doubleToLongBits to retrieve an long representing the floating point number, then writing this long value to the stream exactly the same as the writeLong() method does.
The value written can be read using the readDouble method in DataInput.
Parameters
value The double value to write to the stream
Exceptions
IOException If an error occurs
See also
writeLong(long)
DataInput::readDouble
Double::doubleToLongBits
Implements java::io::DataOutput .
Definition at line 335 of file DataOutputStream.java.
References writeLong().
final void java::io::DataOutputStream::writeFloat (float value) throws IOException [inline]
This method writes a Java float value to the stream. This value is written by first calling the method Float.floatToIntBits to retrieve an int representing the floating point number, then writing this int value to the stream exactly the same as the writeInt() method does.
The value written can be read using the readFloat method in DataInput.
Parameters
value The float value to write to the stream
Exceptions
IOException If an error occurs
See also
writeInt(int)
DataInput::readFloat
Float::floatToIntBits
Implements java::io::DataOutput .
Definition at line 311 of file DataOutputStream.java.
References writeInt().
final synchronized void java::io::DataOutputStream::writeInt (int value) throws IOException [inline]
This method writes a Java int value to an output stream. The 4 bytes of the passed value will be written `big endian`. That is, with the high byte written first in the following manner:
byte0 = (byte)((value & 0xFF000000) >> 24);
 byte1 = (byte)((value & 0x00FF0000) >> 16);
 byte2 = (byte)((value & 0x0000FF00) >> 8);
 byte3 = (byte)(value & 0x000000FF);
The value written can be read using the readInt method in DataInput.
Parameters
value The int value to write to the stream
Exceptions
IOException If an error occurs
See also
DataInput::readInt
Implements java::io::DataOutput .
Definition at line 248 of file DataOutputStream.java.
References out, and java::io::OutputStream::write().
Referenced by writeFloat().
final synchronized void java::io::DataOutputStream::writeLong (long value) throws IOException [inline]
This method writes a Java long value to an output stream. The 8 bytes of the passed value will be written `big endian`. That is, with the high byte written first in the following manner:
byte0 = (byte)((value & 0xFF00000000000000L) >> 56);
 byte1 = (byte)((value & 0x00FF000000000000L) >> 48);
 byte2 = (byte)((value & 0x0000FF0000000000L) >> 40);
 byte3 = (byte)((value & 0x000000FF00000000L) >> 32);
 byte4 = (byte)((value & 0x00000000FF000000L) >> 24);
 byte5 = (byte)((value & 0x0000000000FF0000L) >> 16);
 byte6 = (byte)((value & 0x000000000000FF00L) >> 8);
 byte7 = (byte)(value & 0x00000000000000FFL);
The value written can be read using the readLong method in DataInput.
Parameters
value The long value to write to the stream
Exceptions
IOException If an error occurs
See also
DataInput::readLong
Implements java::io::DataOutput .
Definition at line 280 of file DataOutputStream.java.
References out, and java::io::OutputStream::write().
Referenced by writeDouble().
final synchronized void java::io::DataOutputStream::writeShort (int value) throws IOException [inline]
This method writes a Java short value to an output stream. The char to be written will be in the lowest 16 bits of the int value passed. These bytes will be written `big endian`. That is, with the high byte written first in the following manner:
byte0 = (byte)((value & 0xFF00) >> 8);
 byte1 = (byte)(value & 0x00FF);
The value written can be read using the readShort and readUnsignedShort methods in DataInput.
Parameters
value The short value to write to the stream, passed as an int.
Exceptions
IOException If an error occurs
See also
DataInput::readShort
DataInput::readUnsignedShort
Implements java::io::DataOutput .
Definition at line 196 of file DataOutputStream.java.
References out, and java::io::OutputStream::write().
Referenced by writeUTF().
final synchronized void java::io::DataOutputStream::writeUTF (String value) throws IOException [inline]
This method writes a Java String to the stream in a modified UTF-8 format. First, two bytes are written to the stream indicating the number of bytes to follow. Note that this is the number of bytes in the encoded String not the String length. Next come the encoded characters. Each character in the String is encoded as either one, two or three bytes. For characters in the range of u0001 to u007F, one byte is used. The character value goes into bits 0-7 and bit eight is 0. For characters in the range of u0080 to u007FF, two bytes are used. Bits 6-10 of the character value are encoded bits 0-4 of the first byte, with the high bytes having a value of `110`. Bits 0-5 of the character value are stored in bits 0-5 of the second byte, with the high bits set to `10`. This type of encoding is also done for the null character u0000. This eliminates any C style NUL character values in the output. All remaining characters are stored as three bytes. Bits 12-15 of the character value are stored in bits 0-3 of the first byte. The high bits of the first bytes are set to `1110`. Bits 6-11 of the character value are stored in bits 0-5 of the second byte. The high bits of the second byte are set to `10`. And bits 0-5 of the character value are stored in bits 0-5 of byte three, with the high bits of that byte set to `10`.
The value written can be read using the readUTF method in DataInput.
Parameters
value The String to write to the output in UTF format
Exceptions
IOException If an error occurs
See also
DataInput::readUTF
Implements java::io::DataOutput .
Definition at line 390 of file DataOutputStream.java.
References write(), and writeShort().
Field Documentation
OutputStream java::io::DataOutputStream::out [protected]
The output stream
Definition at line 56 of file DataOutputStream.java.
Referenced by close(), flush(), write(), writeBoolean(), writeByte(), writeChar(), writeInt(), writeLong(), and writeShort().
The documentation for this class was generated from the following file:
src/classpath/java/io/DataOutputStream.java