src/jelatine/constantpool.c File Reference
#include `wrappers.h`
#include `class.h`
#include `constantpool.h`
#include `jstring.h`
#include `memory.h`
#include `utf8_string.h`
#include `util.h`
Functions
static const_pool_type_t tag_read (uint8_t *tags, uint32_t entry)
static void tag_write (uint8_t *tags, uint32_t entry, const_pool_type_t data)
const_pool_t * cp_create (class_t *cl, class_file_t *cf)
const_pool_t * cp_create_dummy (void)
const_pool_type_t cp_get_tag (const_pool_t *cp, uint16_t entry)
void cp_set_tag_and_data (const_pool_t *cp, uint16_t entry, uint8_t tag, void *data)
char * cp_get_class_name (const_pool_t *cp, uint16_t entry)
char * cp_get_string (const_pool_t *cp, uint16_t entry)
uintptr_t cp_get_ref (const_pool_t *cp, uint16_t entry)
int32_t cp_get_integer (const_pool_t *cp, uint16_t entry)
int64_t cp_get_long (const_pool_t *cp, uint16_t entry)
char * cp_get_name_and_type_name (const_pool_t *cp, uint16_t entry)
char * cp_get_name_and_type_type (const_pool_t *cp, uint16_t entry)
uint16_t cp_get_fieldref_class (const_pool_t *cp, uint16_t entry)
char * cp_get_fieldref_name (const_pool_t *cp, uint16_t entry)
char * cp_get_fieldref_type (const_pool_t *cp, uint16_t entry)
char * cp_get_methodref_name (const_pool_t *cp, uint16_t entry)
char * cp_get_methodref_descriptor (const_pool_t *cp, uint16_t entry)
uint16_t cp_get_methodref_class (const_pool_t *cp, uint16_t entry)
char * cp_get_interfacemethodref_name (const_pool_t *cp, uint16_t entry)
char * cp_get_interfacemethodref_descriptor (const_pool_t *cp, uint16_t entry)
uint16_t cp_get_interfacemethodref_class (const_pool_t *cp, uint16_t entry)
Variables
static const_pool_t dummy_cp = { 0, NULL, { 0 } }
Detailed Description
Constant pool functions implementation
Definition in file constantpool.c.
Function Documentation
const_pool_t* cp_create (class_t * cl, class_file_t * cf)
Creates a new constant-pool from the specified class-file
Parameters
cl A pointer to the class owning the constant pool
cf A pointer to an open class-file
Returns
A pointer to the newly created constant-pool
Definition at line 74 of file constantpool.c.
References c_throw, cf_load_u1(), cf_load_u2(), cf_load_u4(), CONSTANT_Class, CONSTANT_Double, CONSTANT_Fieldref, CONSTANT_Float, CONSTANT_Integer, CONSTANT_InterfaceMethodref, CONSTANT_Long, CONSTANT_Methodref, CONSTANT_NameAndType, CONSTANT_String, CONSTANT_Utf8, cp_data_get_ptr(), cp_data_get_uint16(), cp_data_set_double(), cp_data_set_fieldref_class(), cp_data_set_fieldref_name_and_type(), cp_data_set_float(), cp_data_set_int32(), cp_data_set_int64(), cp_data_set_name_and_type_descriptor(), cp_data_set_name_and_type_name(), cp_data_set_ptr(), cp_data_set_uint16(), cp_data_set_uintptr(), const_pool_t::data, const_pool_t::entries, gc_free(), gc_malloc(), gc_palloc(), JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_STRING_PTR2REF, jstring_create_literal(), size_div_inf(), tag_read(), tag_write(), const_pool_t::tags, utf8_check(), and utf8_intern().
Referenced by derive_class().
const_pool_t* cp_create_dummy (void)
Creates a dummy, empty constant pool used by array classes
Returns
A pointer to the dummy constant pool
Definition at line 248 of file constantpool.c.
Referenced by init_dummy_methods(), and load_class().
char* cp_get_class_name (const_pool_t * cp, uint16_t entry)
Gets the the name of a class, fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_Class
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The index of the class name contained in the specified entry
Definition at line 291 of file constantpool.c.
References c_throw, CONSTANT_Class, CONSTANT_Class_resolved, cp_data_get_ptr(), cp_data_get_uint16(), cp_get_string(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by bcl_link_opcode(), derive_class(), and resolve_class().
uint16_t cp_get_fieldref_class (const_pool_t * cp, uint16_t entry)
Gets the class index from a CONSTANT_Fieldref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The index of the class held by the specified entry
Definition at line 468 of file constantpool.c.
References c_throw, CONSTANT_Fieldref, cp_data_get_fieldref_class(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_instance_field(), and resolve_static_field().
char* cp_get_fieldref_name (const_pool_t * cp, uint16_t entry)
Gets the field name from a CONSTANT_Fieldref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the field held by the specified entry
Definition at line 485 of file constantpool.c.
References c_throw, CONSTANT_Fieldref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_name(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_instance_field(), and resolve_static_field().
char* cp_get_fieldref_type (const_pool_t * cp, uint16_t entry)
Gets the field descriptor from a CONSTANT_Fieldref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The descriptor of the field held by the specified entry
Definition at line 504 of file constantpool.c.
References c_throw, CONSTANT_Fieldref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_type(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_instance_field(), and resolve_static_field().
int32_t cp_get_integer (const_pool_t * cp, uint16_t entry)
Gets a CONSTANT_Integer value in the specified entry of the constant pool fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_Integer
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The value of the integer contained in the specified entry
Definition at line 352 of file constantpool.c.
References c_throw, CONSTANT_Integer, cp_data_get_int32(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by initialize_static_fields().
uint16_t cp_get_interfacemethodref_class (const_pool_t * cp, uint16_t entry)
Gets the class index from a CONSTANT_InterfaceMethodref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The entry corresponding to the method's class
Definition at line 615 of file constantpool.c.
References c_throw, CONSTANT_InterfaceMethodref, cp_data_get_fieldref_class(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_interfacemethodref_descriptor (const_pool_t * cp, uint16_t entry)
Gets the method descriptor from a CONSTANT_InterfaceMethodref structure
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The descriptor of the method held by the specified entry
Definition at line 596 of file constantpool.c.
References c_throw, CONSTANT_InterfaceMethodref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_type(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_interfacemethodref_name (const_pool_t * cp, uint16_t entry)
Gets the method name from a CONSTANT_InterfaceMethodref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the method held by the specified entry
Definition at line 577 of file constantpool.c.
References c_throw, CONSTANT_InterfaceMethodref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_name(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
int64_t cp_get_long (const_pool_t * cp, uint16_t entry)
Gets a constant long value in the specified entry of the constant pool fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_Long
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The value of the long contained in the specified entry
Definition at line 392 of file constantpool.c.
References c_throw, CONSTANT_Long, cp_data_get_int64(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by initialize_static_fields().
uint16_t cp_get_methodref_class (const_pool_t * cp, uint16_t entry)
Gets the class index from a CONSTANT_Methodref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The class index held by the specified entry
Definition at line 560 of file constantpool.c.
References c_throw, CONSTANT_Methodref, cp_data_get_fieldref_class(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_methodref_descriptor (const_pool_t * cp, uint16_t entry)
Gets the method descriptor from a CONSTANT_Methodref structure
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The descriptor of the method held by the specified entry
Definition at line 541 of file constantpool.c.
References c_throw, CONSTANT_Methodref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_type(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_methodref_name (const_pool_t * cp, uint16_t entry)
Gets the method name from a CONSTANT_Methodref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the method held by the specified entry
Definition at line 522 of file constantpool.c.
References c_throw, CONSTANT_Methodref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_name(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_name_and_type_name (const_pool_t * cp, uint16_t entry)
Gets the name from a CONSTANT_NameAndType entry
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the class held by the specified entry
Definition at line 430 of file constantpool.c.
References c_throw, CONSTANT_NameAndType, cp_data_get_name_and_type_name(), cp_get_string(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by cp_get_fieldref_name(), cp_get_interfacemethodref_name(), and cp_get_methodref_name().
char* cp_get_name_and_type_type (const_pool_t * cp, uint16_t entry)
Gets the descriptor from a CONSTANT_NameAndType entry
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the class held by the specified entry
Definition at line 449 of file constantpool.c.
References c_throw, CONSTANT_NameAndType, cp_data_get_name_and_type_descriptor(), cp_get_string(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by cp_get_fieldref_type(), cp_get_interfacemethodref_descriptor(), and cp_get_methodref_descriptor().
uintptr_t cp_get_ref (const_pool_t * cp, uint16_t entry)
Gets a CONSTANT_String or CONSTANT_Class value in the specified entry of the constant pool fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_String or CONSTANT_Class
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
A Java reference to the string
Definition at line 333 of file constantpool.c.
References c_throw, CONSTANT_Class, CONSTANT_String, cp_data_get_uintptr(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by initialize_static_fields().
char* cp_get_string (const_pool_t * cp, uint16_t entry)
Gets a string stored in the specified entry of the constant pool, fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_Utf8
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
A pointer to the string contained in the specified entry
Definition at line 315 of file constantpool.c.
References c_throw, CONSTANT_Utf8, cp_data_get_ptr(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by cp_get_class_name(), cp_get_name_and_type_name(), cp_get_name_and_type_type(), load_field_attributes(), load_field_info(), load_method_attributes(), and load_methods().
const_pool_type_t cp_get_tag (const_pool_t * cp, uint16_t entry)
Gets the tag of an element of the constant pool
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The tag of the specified constant pool entry
Definition at line 258 of file constantpool.c.
References c_throw, const_pool_t::entries, JAVA_LANG_NOCLASSDEFFOUNDERROR, tag_read(), and const_pool_t::tags.
Referenced by bcl_link_opcode(), cp_get_class_name(), cp_get_fieldref_class(), cp_get_fieldref_name(), cp_get_fieldref_type(), cp_get_integer(), cp_get_interfacemethodref_class(), cp_get_interfacemethodref_descriptor(), cp_get_interfacemethodref_name(), cp_get_long(), cp_get_methodref_class(), cp_get_methodref_descriptor(), cp_get_methodref_name(), cp_get_name_and_type_name(), cp_get_name_and_type_type(), cp_get_ref(), cp_get_resolved_class(), cp_get_resolved_instance_field(), cp_get_resolved_interfacemethod(), cp_get_resolved_method(), cp_get_resolved_static_field(), cp_get_string(), resolve_class(), resolve_instance_field(), resolve_method(), resolve_static_field(), and translate_bytecode().
void cp_set_tag_and_data (const_pool_t * cp, uint16_t entry, uint8_t tag, void * data)
Sets the tag and data of an element of the constant pool, the data is a generic pointer, this function is used for replacing index-based reference with direct pointers after resolution
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
tag The new tag
data The new data
Definition at line 276 of file constantpool.c.
References cp_data_set_ptr(), const_pool_t::data, tag_write(), and const_pool_t::tags.
Referenced by derive_class(), resolve_class(), resolve_instance_field(), resolve_method(), and resolve_static_field().
static const_pool_type_t tag_read (uint8_t * tags, uint32_t entry) [static]
Reads a tag from the tag array
Parameters
tags A pointer to the tag array
entry The entry to be read
Returns
The requested entry
Definition at line 49 of file constantpool.c.
Referenced by cp_create(), and cp_get_tag().
static void tag_write (uint8_t * tags, uint32_t entry, const_pool_type_t data) [static]
Writes a tag in the tag array
Parameters
tags A pointer to the tag array
entry The entry to be writtend to
data The new tag data
Definition at line 61 of file constantpool.c.
Referenced by cp_create(), and cp_set_tag_and_data().
Variable Documentation
const_pool_t dummy_cp = { 0, NULL, { 0 } } [static]
Dummy constant pool used by array classes
Definition at line 38 of file constantpool.c.