src/jelatine/constantpool.h File Reference
#include `wrappers.h`
#include `classfile.h`
#include `field.h`
#include `util.h`
Data Structures
struct fieldref_t
struct name_and_type_t
struct const_pool_t
Defines
#define JELATINE_CONSTANTPOOL_H (1)
Typedefs
typedef struct fieldref_t fieldref_t
typedef struct name_and_type_t name_and_type_t
typedef struct const_pool_t const_pool_t
Functions
const_pool_t * cp_create (struct class_t *, class_file_t *)
const_pool_t * cp_create_dummy (void)
const_pool_type_t cp_get_tag (const_pool_t *, uint16_t)
void cp_set_tag_and_data (const_pool_t *, uint16_t, uint8_t, void *)
char * cp_get_class_name (const_pool_t *, uint16_t)
char * cp_get_string (const_pool_t *, uint16_t)
uintptr_t cp_get_ref (const_pool_t *, uint16_t)
int32_t cp_get_integer (const_pool_t *, uint16_t)
int64_t cp_get_long (const_pool_t *, uint16_t)
char * cp_get_name_and_type_name (const_pool_t *, uint16_t)
char * cp_get_name_and_type_type (const_pool_t *, uint16_t)
uint16_t cp_get_fieldref_class (const_pool_t *, uint16_t)
char * cp_get_fieldref_name (const_pool_t *, uint16_t)
char * cp_get_fieldref_type (const_pool_t *, uint16_t)
uint16_t cp_get_methodref_class (const_pool_t *, uint16_t)
char * cp_get_methodref_name (const_pool_t *, uint16_t)
char * cp_get_methodref_descriptor (const_pool_t *, uint16_t)
uint16_t cp_get_interfacemethodref_class (const_pool_t *, uint16_t)
char * cp_get_interfacemethodref_name (const_pool_t *, uint16_t)
char * cp_get_interfacemethodref_descriptor (const_pool_t *, uint16_t)
static void cp_data_set_ptr (jword_t *data, size_t i, void *ptr)
static void * cp_data_get_ptr (const jword_t *data, size_t i)
static void cp_data_set_uintptr (jword_t *data, size_t i, uintptr_t ptr)
static uintptr_t cp_data_get_uintptr (const jword_t *data, size_t i)
static void cp_data_set_uint16 (jword_t *data, size_t i, uint16_t v)
static uint16_t cp_data_get_uint16 (const jword_t *data, size_t i)
static void cp_data_set_int32 (jword_t *data, size_t i, int32_t v)
static int32_t cp_data_get_int32 (const jword_t *data, size_t i)
static void cp_data_set_float (jword_t *data, size_t i, float v)
static float cp_data_get_float (const jword_t *data, size_t i)
static void cp_data_set_int64 (jword_t *data, size_t i, int64_t v)
static int64_t cp_data_get_int64 (const jword_t *data, size_t i)
static void cp_data_set_double (jword_t *data, size_t i, double v)
static double cp_data_get_double (const jword_t *data, size_t i)
static void cp_data_set_fieldref_class (jword_t *data, size_t i, uint16_t idx)
static uint16_t cp_data_get_fieldref_class (const jword_t *data, size_t i)
static void cp_data_set_fieldref_name_and_type (jword_t *data, size_t i, uint16_t idx)
static uint16_t cp_data_get_fieldref_name_and_type (const jword_t *data, size_t i)
static void cp_data_set_name_and_type_name (jword_t *data, size_t i, uint16_t idx)
static uint16_t cp_data_get_name_and_type_name (const jword_t *data, size_t i)
static void cp_data_set_name_and_type_descriptor (jword_t *data, size_t i, uint16_t idx)
static uint16_t cp_data_get_name_and_type_descriptor (const jword_t *data, size_t i)
static struct class_t * cp_get_class (const_pool_t *cp)
static struct class_t * cp_get_resolved_class (const_pool_t *cp, uint16_t entry)
static struct field_t * cp_get_resolved_instance_field (const_pool_t *cp, uint16_t entry)
static struct field_t * cp_get_resolved_static_field (const_pool_t *cp, uint16_t entry)
static struct method_t * cp_get_resolved_method (const_pool_t *cp, uint16_t entry)
static struct method_t * cp_get_resolved_interfacemethod (const_pool_t *cp, uint16_t entry)
Detailed Description
Constant pool definition and interface
Definition in file constantpool.h.
Define Documentation
#define JELATINE_CONSTANTPOOL_H (1)
constantpool.h inclusion macro
Definition at line 28 of file constantpool.h.
Typedef Documentation
typedef struct const_pool_t const_pool_t
Typedef for :struct const_pool_t
Definition at line 81 of file constantpool.h.
typedef struct fieldref_t fieldref_t
Typedef for struct fieldref_t
Definition at line 57 of file constantpool.h.
typedef struct name_and_type_t name_and_type_t
Typedef for struct name_and_type_t
Definition at line 67 of file constantpool.h.
Function Documentation
const_pool_t* cp_create (class_t * cl, class_file_t * cf)
Creates a new constant-pool from the specified class-file
Parameters
cl A pointer to the class owning the constant pool
cf A pointer to an open class-file
Returns
A pointer to the newly created constant-pool
Definition at line 74 of file constantpool.c.
References c_throw, cf_load_u1(), cf_load_u2(), cf_load_u4(), CONSTANT_Class, CONSTANT_Double, CONSTANT_Fieldref, CONSTANT_Float, CONSTANT_Integer, CONSTANT_InterfaceMethodref, CONSTANT_Long, CONSTANT_Methodref, CONSTANT_NameAndType, CONSTANT_String, CONSTANT_Utf8, cp_data_get_ptr(), cp_data_get_uint16(), cp_data_set_double(), cp_data_set_fieldref_class(), cp_data_set_fieldref_name_and_type(), cp_data_set_float(), cp_data_set_int32(), cp_data_set_int64(), cp_data_set_name_and_type_descriptor(), cp_data_set_name_and_type_name(), cp_data_set_ptr(), cp_data_set_uint16(), cp_data_set_uintptr(), const_pool_t::data, const_pool_t::entries, gc_free(), gc_malloc(), gc_palloc(), JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_STRING_PTR2REF, jstring_create_literal(), size_div_inf(), tag_read(), tag_write(), const_pool_t::tags, utf8_check(), and utf8_intern().
Referenced by derive_class().
const_pool_t* cp_create_dummy (void)
Creates a dummy, empty constant pool used by array classes
Returns
A pointer to the dummy constant pool
Definition at line 248 of file constantpool.c.
Referenced by init_dummy_methods(), and load_class().
static double cp_data_get_double (const jword_t * data, size_t i) [inline, static]
Reads a double value from the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
A double value
Definition at line 254 of file constantpool.h.
static uint16_t cp_data_get_fieldref_class (const jword_t * data, size_t i) [inline, static]
Reads the class index of a Fieldref entry
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
The class index of the Fieldref structure
Definition at line 275 of file constantpool.h.
Referenced by cp_get_fieldref_class(), cp_get_interfacemethodref_class(), and cp_get_methodref_class().
static uint16_t cp_data_get_fieldref_name_and_type (const jword_t * data, size_t i) [inline, static]
Reads the NameAndType index of a Fieldref entry
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
The name and type index
Definition at line 296 of file constantpool.h.
Referenced by cp_get_fieldref_name(), cp_get_fieldref_type(), cp_get_interfacemethodref_descriptor(), cp_get_interfacemethodref_name(), cp_get_methodref_descriptor(), and cp_get_methodref_name().
static float cp_data_get_float (const jword_t * data, size_t i) [inline, static]
Reads a float value from the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
A float value
Definition at line 214 of file constantpool.h.
static int32_t cp_data_get_int32 (const jword_t * data, size_t i) [inline, static]
Reads an int32_t value from the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
An int32_t value
Definition at line 194 of file constantpool.h.
Referenced by cp_get_integer(), and interpreter().
static int64_t cp_data_get_int64 (const jword_t * data, size_t i) [inline, static]
Reads an int64_t value from the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
An int64_t value
Definition at line 234 of file constantpool.h.
Referenced by cp_get_long(), and interpreter().
static uint16_t cp_data_get_name_and_type_descriptor (const jword_t * data, size_t i) [inline, static]
Reads the descriptor field of a NameAndType entry
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
The descriptor index
Definition at line 340 of file constantpool.h.
Referenced by cp_get_name_and_type_type().
static uint16_t cp_data_get_name_and_type_name (const jword_t * data, size_t i) [inline, static]
Reads the name field of a NameAndType entry
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
The name index
Definition at line 318 of file constantpool.h.
Referenced by cp_get_name_and_type_name().
static void* cp_data_get_ptr (const jword_t * data, size_t i) [inline, static]
Reads a pointer value from the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
A generic pointer
Definition at line 134 of file constantpool.h.
Referenced by cp_create(), cp_get_class(), cp_get_class_name(), cp_get_resolved_class(), cp_get_resolved_instance_field(), cp_get_resolved_interfacemethod(), cp_get_resolved_method(), cp_get_resolved_static_field(), cp_get_string(), and interpreter().
static uint16_t cp_data_get_uint16 (const jword_t * data, size_t i) [inline, static]
Reads an uint16_t value from the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
An uint16_t value
Definition at line 174 of file constantpool.h.
Referenced by cp_create(), and cp_get_class_name().
static uintptr_t cp_data_get_uintptr (const jword_t * data, size_t i) [inline, static]
Reads an uintptr_t value from the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
Returns
An uintptr_t value
Definition at line 154 of file constantpool.h.
Referenced by cp_get_ref(), and interpreter().
static void cp_data_set_double (jword_t * data, size_t i, double v) [inline, static]
Writes a double value in the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
v A double value
Definition at line 244 of file constantpool.h.
Referenced by cp_create().
static void cp_data_set_fieldref_class (jword_t * data, size_t i, uint16_t idx) [inline, static]
Sets the class index of a Fieldref entry
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
idx The new class index
Definition at line 264 of file constantpool.h.
Referenced by cp_create().
static void cp_data_set_fieldref_name_and_type (jword_t * data, size_t i, uint16_t idx) [inline, static]
Sets the NameAndType index of a Fieldref entry
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
idx The new name and type index
Definition at line 285 of file constantpool.h.
Referenced by cp_create().
static void cp_data_set_float (jword_t * data, size_t i, float v) [inline, static]
Writes a float value in the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
v A float value
Definition at line 204 of file constantpool.h.
Referenced by cp_create().
static void cp_data_set_int32 (jword_t * data, size_t i, int32_t v) [inline, static]
Writes an int32_t value in the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
v An int32_t value
Definition at line 184 of file constantpool.h.
Referenced by cp_create().
static void cp_data_set_int64 (jword_t * data, size_t i, int64_t v) [inline, static]
Writes an int64_t value in the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
v An int64_t value
Definition at line 224 of file constantpool.h.
Referenced by cp_create().
static void cp_data_set_name_and_type_descriptor (jword_t * data, size_t i, uint16_t idx) [inline, static]
Sets the descriptor field of a NameAndType entry
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
idx The new descriptor index
Definition at line 329 of file constantpool.h.
Referenced by cp_create().
static void cp_data_set_name_and_type_name (jword_t * data, size_t i, uint16_t idx) [inline, static]
Sets the name field of a NameAndType entry
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
idx The new name index
Definition at line 307 of file constantpool.h.
Referenced by cp_create().
static void cp_data_set_ptr (jword_t * data, size_t i, void * ptr) [inline, static]
Writes a pointer value in the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
ptr A generic pointer
Definition at line 124 of file constantpool.h.
Referenced by cp_create(), and cp_set_tag_and_data().
static void cp_data_set_uint16 (jword_t * data, size_t i, uint16_t v) [inline, static]
Writes an uint16_t value in the constant pool
Parameters
data A pointer to the constant pool data array
i An index
v An uint16_t value
Definition at line 164 of file constantpool.h.
Referenced by cp_create().
static void cp_data_set_uintptr (jword_t * data, size_t i, uintptr_t ptr) [inline, static]
Writes an uintptr_t value in the constant pool
Parameters
data A pointer to the constant pool data array
i An index in the constant pool
ptr An uintptr_t value
Definition at line 144 of file constantpool.h.
Referenced by cp_create().
static struct class_t* cp_get_class (const_pool_t * cp) [static, read]
Gets the class to which this constant pool belongs to
Parameters
cp A pointer to the constant pool
Returns
The class to which this constant pool belongs to
Definition at line 354 of file constantpool.h.
References cp_data_get_ptr(), and const_pool_t::data.
Referenced by bcl_link_method(), bcl_link_opcode(), interpreter(), and prepare_for_call().
char* cp_get_class_name (const_pool_t * cp, uint16_t entry)
Gets the the name of a class, fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_Class
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The index of the class name contained in the specified entry
Definition at line 291 of file constantpool.c.
References c_throw, CONSTANT_Class, CONSTANT_Class_resolved, cp_data_get_ptr(), cp_data_get_uint16(), cp_get_string(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by bcl_link_opcode(), derive_class(), and resolve_class().
uint16_t cp_get_fieldref_class (const_pool_t * cp, uint16_t entry)
Gets the class index from a CONSTANT_Fieldref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The index of the class held by the specified entry
Definition at line 468 of file constantpool.c.
References c_throw, CONSTANT_Fieldref, cp_data_get_fieldref_class(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_instance_field(), and resolve_static_field().
char* cp_get_fieldref_name (const_pool_t * cp, uint16_t entry)
Gets the field name from a CONSTANT_Fieldref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the field held by the specified entry
Definition at line 485 of file constantpool.c.
References c_throw, CONSTANT_Fieldref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_name(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_instance_field(), and resolve_static_field().
char* cp_get_fieldref_type (const_pool_t * cp, uint16_t entry)
Gets the field descriptor from a CONSTANT_Fieldref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The descriptor of the field held by the specified entry
Definition at line 504 of file constantpool.c.
References c_throw, CONSTANT_Fieldref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_type(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_instance_field(), and resolve_static_field().
int32_t cp_get_integer (const_pool_t * cp, uint16_t entry)
Gets a CONSTANT_Integer value in the specified entry of the constant pool fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_Integer
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The value of the integer contained in the specified entry
Definition at line 352 of file constantpool.c.
References c_throw, CONSTANT_Integer, cp_data_get_int32(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by initialize_static_fields().
uint16_t cp_get_interfacemethodref_class (const_pool_t * cp, uint16_t entry)
Gets the class index from a CONSTANT_InterfaceMethodref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The entry corresponding to the method's class
Definition at line 615 of file constantpool.c.
References c_throw, CONSTANT_InterfaceMethodref, cp_data_get_fieldref_class(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_interfacemethodref_descriptor (const_pool_t * cp, uint16_t entry)
Gets the method descriptor from a CONSTANT_InterfaceMethodref structure
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The descriptor of the method held by the specified entry
Definition at line 596 of file constantpool.c.
References c_throw, CONSTANT_InterfaceMethodref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_type(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_interfacemethodref_name (const_pool_t * cp, uint16_t entry)
Gets the method name from a CONSTANT_InterfaceMethodref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the method held by the specified entry
Definition at line 577 of file constantpool.c.
References c_throw, CONSTANT_InterfaceMethodref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_name(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
int64_t cp_get_long (const_pool_t * cp, uint16_t entry)
Gets a constant long value in the specified entry of the constant pool fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_Long
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The value of the long contained in the specified entry
Definition at line 392 of file constantpool.c.
References c_throw, CONSTANT_Long, cp_data_get_int64(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by initialize_static_fields().
uint16_t cp_get_methodref_class (const_pool_t * cp, uint16_t entry)
Gets the class index from a CONSTANT_Methodref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The class index held by the specified entry
Definition at line 560 of file constantpool.c.
References c_throw, CONSTANT_Methodref, cp_data_get_fieldref_class(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_methodref_descriptor (const_pool_t * cp, uint16_t entry)
Gets the method descriptor from a CONSTANT_Methodref structure
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The descriptor of the method held by the specified entry
Definition at line 541 of file constantpool.c.
References c_throw, CONSTANT_Methodref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_type(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_methodref_name (const_pool_t * cp, uint16_t entry)
Gets the method name from a CONSTANT_Methodref
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the method held by the specified entry
Definition at line 522 of file constantpool.c.
References c_throw, CONSTANT_Methodref, cp_data_get_fieldref_name_and_type(), cp_get_name_and_type_name(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by resolve_method().
char* cp_get_name_and_type_name (const_pool_t * cp, uint16_t entry)
Gets the name from a CONSTANT_NameAndType entry
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the class held by the specified entry
Definition at line 430 of file constantpool.c.
References c_throw, CONSTANT_NameAndType, cp_data_get_name_and_type_name(), cp_get_string(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by cp_get_fieldref_name(), cp_get_interfacemethodref_name(), and cp_get_methodref_name().
char* cp_get_name_and_type_type (const_pool_t * cp, uint16_t entry)
Gets the descriptor from a CONSTANT_NameAndType entry
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The name of the class held by the specified entry
Definition at line 449 of file constantpool.c.
References c_throw, CONSTANT_NameAndType, cp_data_get_name_and_type_descriptor(), cp_get_string(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by cp_get_fieldref_type(), cp_get_interfacemethodref_descriptor(), and cp_get_methodref_descriptor().
uintptr_t cp_get_ref (const_pool_t * cp, uint16_t entry)
Gets a CONSTANT_String or CONSTANT_Class value in the specified entry of the constant pool fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_String or CONSTANT_Class
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
A Java reference to the string
Definition at line 333 of file constantpool.c.
References c_throw, CONSTANT_Class, CONSTANT_String, cp_data_get_uintptr(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by initialize_static_fields().
static struct class_t* cp_get_resolved_class (const_pool_t * cp, uint16_t entry) [static, read]
Gets the pointer of a resolved reference to a class
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
A pointer to the requested class
Definition at line 364 of file constantpool.h.
References CONSTANT_Class_resolved, cp_data_get_ptr(), cp_get_tag(), and const_pool_t::data.
Referenced by bcl_link_opcode(), and resolve_class().
static struct field_t* cp_get_resolved_instance_field (const_pool_t * cp, uint16_t entry) [static, read]
Gets the pointer of a resolved reference to an instance field
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
A pointer to the requested field
Definition at line 378 of file constantpool.h.
References CONSTANT_Fieldref_resolved, cp_data_get_ptr(), cp_get_tag(), and const_pool_t::data.
Referenced by resolve_instance_field().
static struct method_t* cp_get_resolved_interfacemethod (const_pool_t * cp, uint16_t entry) [static, read]
Gets the pointer of a resolved reference to an interface method
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
A pointer to the requested method
Definition at line 424 of file constantpool.h.
References CONSTANT_InterfaceMethodref_resolved, cp_data_get_ptr(), cp_get_tag(), and const_pool_t::data.
Referenced by resolve_method().
static struct method_t* cp_get_resolved_method (const_pool_t * cp, uint16_t entry) [static, read]
Gets the pointer of a resolved reference to a method
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
A pointer to the requested method
Definition at line 410 of file constantpool.h.
References CONSTANT_Methodref_resolved, cp_data_get_ptr(), cp_get_tag(), and const_pool_t::data.
Referenced by resolve_method().
static struct field_t* cp_get_resolved_static_field (const_pool_t * cp, uint16_t entry) [static, read]
Gets the pointer of a resolved reference to a static field
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
A pointer to the requested field
Definition at line 392 of file constantpool.h.
References CONSTANT_Fieldref_resolved, cp_data_get_ptr(), cp_get_tag(), const_pool_t::data, and static_field_t::field.
Referenced by resolve_static_field().
char* cp_get_string (const_pool_t * cp, uint16_t entry)
Gets a string stored in the specified entry of the constant pool, fails if the entry parameter is out of range or if the relevant entry has a tag different from CONSTANT_Utf8
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
A pointer to the string contained in the specified entry
Definition at line 315 of file constantpool.c.
References c_throw, CONSTANT_Utf8, cp_data_get_ptr(), cp_get_tag(), const_pool_t::data, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by cp_get_class_name(), cp_get_name_and_type_name(), cp_get_name_and_type_type(), load_field_attributes(), load_field_info(), load_method_attributes(), and load_methods().
const_pool_type_t cp_get_tag (const_pool_t * cp, uint16_t entry)
Gets the tag of an element of the constant pool
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
Returns
The tag of the specified constant pool entry
Definition at line 258 of file constantpool.c.
References c_throw, const_pool_t::entries, JAVA_LANG_NOCLASSDEFFOUNDERROR, tag_read(), and const_pool_t::tags.
Referenced by bcl_link_opcode(), cp_get_class_name(), cp_get_fieldref_class(), cp_get_fieldref_name(), cp_get_fieldref_type(), cp_get_integer(), cp_get_interfacemethodref_class(), cp_get_interfacemethodref_descriptor(), cp_get_interfacemethodref_name(), cp_get_long(), cp_get_methodref_class(), cp_get_methodref_descriptor(), cp_get_methodref_name(), cp_get_name_and_type_name(), cp_get_name_and_type_type(), cp_get_ref(), cp_get_resolved_class(), cp_get_resolved_instance_field(), cp_get_resolved_interfacemethod(), cp_get_resolved_method(), cp_get_resolved_static_field(), cp_get_string(), resolve_class(), resolve_instance_field(), resolve_method(), resolve_static_field(), and translate_bytecode().
void cp_set_tag_and_data (const_pool_t * cp, uint16_t entry, uint8_t tag, void * data)
Sets the tag and data of an element of the constant pool, the data is a generic pointer, this function is used for replacing index-based reference with direct pointers after resolution
Parameters
cp A pointer to a valid constant pool object
entry The constant pool entry number
tag The new tag
data The new data
Definition at line 276 of file constantpool.c.
References cp_data_set_ptr(), const_pool_t::data, tag_write(), and const_pool_t::tags.
Referenced by derive_class(), resolve_class(), resolve_instance_field(), resolve_method(), and resolve_static_field().