src/jelatine/field.h File Reference
#include `wrappers.h`
#include `classfile.h`
Data Structures
struct field_t
struct static_field_t
struct field_iterator_t
Defines
#define JELATINE_FIELD_H (1)
Typedefs
typedef struct field_t field_t
typedef struct static_field_t static_field_t
typedef struct field_iterator_t field_iterator_t
Functions
size_t field_size (const field_t *)
void field_parse_descriptor (const char *)
uintptr_t static_field_data_ptr (static_field_t *)
static bool field_is_static (const field_t *field)
static bool field_is_private (const field_t *field)
static bool field_is_protected (const field_t *field)
static bool field_is_public (const field_t *field)
static bool field_is_reference (const field_t *field)
field_iterator_t field_itr (struct class_t *, bool)
field_t * field_itr_get_next (field_iterator_t *)
static field_iterator_t instance_field_itr (struct class_t *cl)
static field_iterator_t static_field_itr (struct class_t *cl)
static bool field_itr_has_next (field_iterator_t itr)
Detailed Description
Field structure and interface
Definition in file field.h.
Define Documentation
#define JELATINE_FIELD_H (1)
class.h inclusion macro
Definition at line 28 of file field.h.
Typedef Documentation
typedef struct field_iterator_t field_iterator_t
Typedef for the struct field_iterator_t
Definition at line 145 of file field.h.
typedef struct field_t field_t
Typedef for struct field_t
Definition at line 52 of file field.h.
typedef struct static_field_t static_field_t
Typedef for struct static_field_t
Definition at line 73 of file field.h.
Function Documentation
static bool field_is_private (const field_t * field) [inline, static]
Checks if a field is private
Parameters
field A pointer to a field_t structure
Returns
true if the field is private, false otherwise
Definition at line 100 of file field.h.
References field_t::access_flags.
Referenced by verify_field_access().
static bool field_is_protected (const field_t * field) [inline, static]
Checks if a field is protected
Parameters
field A pointer to a field_t structure
Returns
true if the field is protected, false otherwise
Definition at line 109 of file field.h.
References field_t::access_flags.
Referenced by verify_field_access().
static bool field_is_public (const field_t * field) [inline, static]
Checks if a field is public
Parameters
field A pointer to a field_t structure
Returns
true if the field is public, false otherwise
Definition at line 118 of file field.h.
References field_t::access_flags.
Referenced by verify_field_access().
static bool field_is_reference (const field_t * field) [inline, static]
Checks if a field is a reference to an object
Parameters
field A pointer to a field
Returns
true if the field holds a reference to an object, false otherwise
Definition at line 127 of file field.h.
References field_t::descriptor.
Referenced by bcl_mark().
static bool field_is_static (const field_t * field) [inline, static]
Checks if a field is static
Parameters
field A pointer to a field_t structure
Returns
true if the field is static, false otherwise
Definition at line 91 of file field.h.
References field_t::access_flags.
Referenced by class_add_field(), class_get_field(), field_itr_find_next(), KNI_GetFieldID(), and KNI_GetStaticFieldID().
field_iterator_t field_itr (class_t * cl, bool stat)
Returns an iterator for navigating the instance or static fields of a class depending on the value of stat
Parameters
cl A pointer to a class
stat true if a static field iterator is needed, false otherwise
Returns
An initialized iterator
Definition at line 224 of file field.c.
References field_iterator_t::end, field_itr_find_next(), class_t::fields, class_t::fields_n, field_iterator_t::next, and field_iterator_t::stat.
Referenced by instance_field_itr(), and static_field_itr().
field_t* field_itr_get_next (field_iterator_t * itr)
Returns the next field of this iteration
Parameters
itr A field iterator
Returns
The next field available
Definition at line 240 of file field.c.
References field_iterator_t::end, field_itr_find_next(), field_itr_has_next(), field_iterator_t::next, and field_iterator_t::stat.
Referenced by bcl_mark(), initialize_static_fields(), and layout_fields().
static bool field_itr_has_next (field_iterator_t itr) [inline, static]
Returns true if there are still fields which can be iterated over, false otherwise
Parameters
itr A field iterator
Definition at line 180 of file field.h.
References field_iterator_t::next.
Referenced by bcl_mark(), field_itr_get_next(), initialize_static_fields(), and layout_fields().
void field_parse_descriptor (const char * desc)
Checks if a field descriptor is valid
Parameters
desc A field descriptor
Definition at line 74 of file field.c.
References c_throw, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by verify_field().
size_t field_size (const field_t * field)
Returns the size in bytes of a field
Parameters
field A pointer to a field
Returns
The size in bytes of the field
Definition at line 38 of file field.c.
References dbg_unreachable, and field_t::descriptor.
static field_iterator_t instance_field_itr (struct class_t * cl) [inline, static]
Returns an iterator for navigating the instance fields of a class
Parameters
cl A pointer to a class
Returns
An initialized iterator
Definition at line 162 of file field.h.
References field_itr().
Referenced by layout_fields().
uintptr_t static_field_data_ptr (static_field_t * static_field)
Returns a pointer to the actual data of a static field
Parameters
static_field A pointer to a static field
Returns
The address of the static field data
Definition at line 174 of file field.c.
References static_field_t::data, dbg_unreachable, field_t::descriptor, and static_field_t::field.
Referenced by KNI_GetStaticFieldID(), and resolve_static_field().
static field_iterator_t static_field_itr (struct class_t * cl) [inline, static]
Returns an iterator for navigating the static fields of a class
Parameters
cl A pointer to a class
Returns
An initialized iterator
Definition at line 171 of file field.h.
References field_itr().
Referenced by bcl_mark(), and initialize_static_fields().