src/jelatine/kni.c File Reference
#include `wrappers.h`
#include `class.h`
#include `field.h`
#include `jstring.h`
#include `kni.h`
#include `loader.h`
#include `memory.h`
#include `vm.h`
#include `java_lang_String.h`
#include `java_lang_Throwable.h`
Functions
jint KNI_ThrowNew (const char *name, const char *message)
void KNI_FatalError (const char *message)
jfieldID KNI_GetFieldID (jclass classHandle, const char *name, const char *signature)
jfieldID KNI_GetStaticFieldID (jclass classHandle, const char *name, const char *signature)
void KNI_GetStringRegion (jstring stringHandle, jsize offset, jsize n, jchar *jcharbuf)
Detailed Description
CLDC native interface implementation
Definition in file kni.c.
Function Documentation
void KNI_FatalError (const char * message)
Prints an error message to the system’s standard error output, and terminates the execution of the virtual machine immediately
Parameters
message The error message as a UTF-8 string
Definition at line 77 of file kni.c.
References vm_fail().
jfieldID KNI_GetFieldID (jclass classHandle, const char * name, const char * signature)
Returns the field ID of an instance field of the class represented by classHandle. The field is specified by its name and signature. The Get<Type>Field and Set<Type>Field families of accessor functions use field IDs to retrieve the value of instance fields. The field must be accessible from the class referred to by classHandle
Parameters
classHandle A handle pointing to a class whose field ID will be retrieved
name The field name as a UTF-8 string
signature The field descriptor as a UTF-8 string
Returns
Returns a field ID or NULL if the lookup fails for any reason
Definition at line 98 of file kni.c.
References bcl_get_class_by_id(), class_get_field(), field_is_static(), JAVA_LANG_CLASS_REF2PTR, and field_t::offset.
jfieldID KNI_GetStaticFieldID (jclass classHandle, const char * name, const char * signature)
Returns the field ID of a static field of the class represented by classHandle. The field is specified by its name and signature. The GetStatic<Type>Field and SetStatic<Type>Field families of accessor functions use field IDs to retrieve the value of static fields. The field must be accessible from the class referred to by classHandle
Parameters
classHandle A handle pointing to a class whose field ID will be retrieved
name The field name as a UTF-8 string
signature The field descriptor as a UTF-8 string
Returns
Returns a field ID or NULL if the lookup fails for any reason
Definition at line 129 of file kni.c.
References bcl_get_class_by_id(), class_get_field(), field_is_static(), JAVA_LANG_CLASS_REF2PTR, field_t::offset, class_t::static_data, and static_field_data_ptr().
void KNI_GetStringRegion (jstring stringHandle, jsize offset, jsize n, jchar * jcharbuf)
Copies a number of Unicode characters from a java.lang.String object (denoted by stringHandle), beginning at offset, to the given buffer jcharbuf. No range checking is performed. It is the responsibility of the native function programmer to allocate the return buffer, and to make sure that it is large enough
Parameters
stringHandle A handle pointing to a java.lang.String object whose contents are to be copied
offset The offset within the string object at which to start copying (offset 0: first character in the Java string.)
n The number of 16-bit Unicode characters to copy
jcharbuf A pointer to a buffer to hold the Unicode characters
Definition at line 164 of file kni.c.
References array_get_data(), JAVA_LANG_STRING_REF2PTR, and java_lang_String_t::value.
jint KNI_ThrowNew (const char * name, const char * message)
Instantiates an exception object with the message specified by message, and causes that exception to be thrown. A thrown exception will be pending in the current thread, but does not immediately disrupt native code execution. The actual exception will be thrown when the program control returns from the native function back to the virtual machine. Note that KNI_ThrowNew does not run the constructor on the new exception object.
Parameters
name The name of a java.lang.Throwable class as a UTF-8 string
message The message used to construct the java.lang.Throwable object; represented as a UTF-8 string
Returns
KNI_OK on success; otherwise KNI_ERR
Definition at line 52 of file kni.c.
References bcl_resolve_class(), stack_frame_t::cl, java_lang_Throwable_t::detailMessage, thread_t::exception, thread_t::fp, gc_new(), JAVA_LANG_STRING_PTR2REF, JAVA_LANG_THROWABLE_REF2PTR, jstring_create_from_utf8(), and thread_self().
Referenced by arraycopy_ref(), java_lang_Class_forName(), java_lang_Class_isAssignableFrom(), java_lang_Object__wait(), java_lang_Object_notify(), java_lang_Object_notifyAll(), java_lang_System_arraycopy(), java_lang_Thread_sleep(), thread_join(), thread_sleep(), and thread_wait().