src/jelatine/kni.h File Reference
#include `wrappers.h`
#include `array.h`
#include `class.h`
#include `loader.h`
#include `thread.h`
#include `java_lang_String.h`
Defines
#define JELATINE_KNI_H (1)
#define KNI_RETURNTYPE_VOID void
#define KNI_RETURNTYPE_BOOLEAN int32_t
#define KNI_RETURNTYPE_BYTE int32_t
#define KNI_RETURNTYPE_CHAR int32_t
#define KNI_RETURNTYPE_SHORT int32_t
#define KNI_RETURNTYPE_INT int32_t
#define KNI_RETURNTYPE_LONG int64_t
#define KNI_RETURNTYPE_FLOAT float
#define KNI_RETURNTYPE_DOUBLE double
#define KNI_RETURNTYPE_OBJECT uintptr_t
#define KNI_FALSE (0)
#define KNI_TRUE (1)
#define KNI_OK (0)
#define KNI_ERR (-1)
#define KNI_ENOMEM (-4)
#define KNI_EINVAL (-6)
#define KNI_VERSION (0x00010000)
#define KNI_ReturnVoid() return
#define KNI_ReturnBoolean(value) return (value) ? 1 : 0
#define KNI_ReturnByte(value) return (jbyte) (value)
#define KNI_ReturnChar(value) return (jchar) (value)
#define KNI_ReturnShort(value) return (jshort) (value)
#define KNI_ReturnInt(value) return (jint) (value)
#define KNI_ReturnLong(value) return (jlong) (value)
#define KNI_StartHandles(n)
#define KNI_DeclareHandle(handle) jobject handle = _KNI_push_handle(&__handles__[__declared_count__++])
#define KNI_EndHandles()
#define KNI_EndHandlesAndReturnObject(objectHandle)
Typedefs
typedef uint8_t jboolean
typedef uint8_t jbyte
typedef uint16_t jchar
typedef int16_t jshort
typedef int32_t jint
typedef int64_t jlong
typedef float jfloat
typedef double jdouble
typedef jint jsize
typedef uintptr_t * jobject
typedef uintptr_t * jclass
typedef jobject jthrowable
typedef jobject jstring
typedef jobject jarray
typedef jarray jbooleanArray
typedef jarray jbyteArray
typedef jarray jcharArray
typedef jarray jshortArray
typedef jarray jintArray
typedef jarray jlongArray
typedef jarray jfloatArray
typedef jarray jdoubleArray
typedef jarray jobjectArray
typedef uintptr_t jfieldID
Functions
static jint KNI_GetVersion (void)
static void KNI_FindClass (const char *name, jclass classHandle)
static void KNI_GetSuperClass (jclass classHandle, jclass superClassHandle)
static jboolean KNI_IsAssignableFrom (jclass cl1, jclass cl2)
jint KNI_ThrowNew (const char *, const char *)
void KNI_FatalError (const char *)
static void KNI_GetObjectClass (jobject objectHandle, jclass classHandle)
static jboolean KNI_IsInstanceOf (jobject objectHandle, jclass classHandle)
jfieldID KNI_GetFieldID (jclass classHandle, const char *name, const char *signature)
static jboolean KNI_GetBooleanField (jobject objectHandle, jfieldID fieldID)
static jbyte KNI_GetByteField (jobject objectHandle, jfieldID fieldID)
static jchar KNI_GetCharField (jobject objectHandle, jfieldID fieldID)
static jshort KNI_GetShortField (jobject objectHandle, jfieldID fieldID)
static jint KNI_GetIntField (jobject objectHandle, jfieldID fieldID)
static jlong KNI_GetLongField (jobject objectHandle, jfieldID fieldID)
static void KNI_GetObjectField (jobject objectHandle, jfieldID fieldID, jobject toHandle)
static void KNI_SetBooleanField (jobject objectHandle, jfieldID fieldID, jboolean value)
static void KNI_SetByteField (jobject objectHandle, jfieldID fieldID, jbyte value)
static void KNI_SetCharField (jobject objectHandle, jfieldID fieldID, jchar value)
static void KNI_SetShortField (jobject objectHandle, jfieldID fieldID, jshort value)
static void KNI_SetIntField (jobject objectHandle, jfieldID fieldID, jint value)
static void KNI_SetLongField (jobject objectHandle, jfieldID fieldID, jlong value)
static void KNI_SetObjectField (jobject objectHandle, jfieldID fieldID, jobject fromHandle)
jfieldID KNI_GetStaticFieldID (jclass, const char *, const char *)
static jboolean KNI_GetStaticBooleanField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID)
static jbyte KNI_GetStaticByteField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID)
static jchar KNI_GetStaticCharField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID)
static jshort KNI_GetStaticShortField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID)
static jint KNI_GetStaticIntField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID)
static jlong KNI_GetStaticLongField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID)
static void KNI_GetStaticObjectField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jobject toHandle)
static void KNI_SetStaticBooleanField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jboolean value)
static void KNI_SetStaticByteField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jbyte value)
static void KNI_SetStaticCharField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jchar value)
static void KNI_SetStaticShortField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jshort value)
static void KNI_SetStaticIntField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jint value)
static void KNI_SetStaticLongField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jlong value)
static void KNI_SetStaticObjectField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jobject fromHandle)
static jsize KNI_GetStringLength (jstring stringHandle)
void KNI_GetStringRegion (jstring, jsize, jsize, jchar *)
static void KNI_NewString (const jchar *uchars, jsize length, jobject stringHandle)
static void KNI_NewStringUTF (const char *utf8chars, jobject stringHandle)
static jsize KNI_GetArrayLength (jarray array)
static jboolean KNI_GetBooleanArrayElement (jbooleanArray arrayHandle, jsize index)
static jbyte KNI_GetByteArrayElement (jbyteArray arrayHandle, jsize index)
static jchar KNI_GetCharArrayElement (jcharArray arrayHandle, jsize index)
static jshort KNI_GetShortArrayElement (jshortArray arrayHandle, jsize index)
static jint KNI_GetIntArrayElement (jintArray arrayHandle, jsize index)
static jlong KNI_GetLongArrayElement (jlongArray arrayHandle, jsize index)
static void KNI_GetObjectArrayElement (jobjectArray arrayHandle, jint index, jobject toHandle)
static void KNI_SetBooleanArrayElement (jbooleanArray arrayHandle, jsize index, jboolean value)
static void KNI_SetByteArrayElement (jbyteArray arrayHandle, jsize index, jbyte value)
static void KNI_SetCharArrayElement (jcharArray arrayHandle, jsize index, jchar value)
static void KNI_SetShortArrayElement (jshortArray arrayHandle, jsize index, jshort value)
static void KNI_SetIntArrayElement (jintArray arrayHandle, jsize index, jint value)
static void KNI_SetLongArrayElement (jlongArray arrayHandle, jsize index, jlong value)
static void KNI_SetObjectArrayElement (jobjectArray arrayHandle, jint index, jobject fromHandle)
static void KNI_GetRawArrayRegion (jarray arrayHandle, jsize offset, jsize n, jbyte *dstBuffer)
static void KNI_SetRawArrayRegion (jarray arrayHandle, jsize offset, jsize n, const jbyte *srcBuffer)
static jboolean KNI_GetParameterAsBoolean (jint index)
static jbyte KNI_GetParameterAsByte (jint index)
static jchar KNI_GetParameterAsChar (jint index)
static jshort KNI_GetParameterAsShort (jint index)
static jint KNI_GetParameterAsInt (jint index)
static jlong KNI_GetParameterAsLong (jint index)
static void KNI_GetParameterAsObject (jint index, jobject toHandle)
static void KNI_GetThisPointer (jobject toHandle)
static void KNI_GetClassPointer (jclass toHandle)
static jobject _KNI_push_handle (jobject handle)
static jboolean KNI_IsNullHandle (jobject handle)
static jboolean KNI_IsSameObject (jobject obj1, jobject obj2)
static void KNI_ReleaseHandle (jobject handle)
Detailed Description
CLDC native interface
Definition in file kni.h.
Define Documentation
#define JELATINE_KNI_H (1)
kni.h inclusion macro
Definition at line 28 of file kni.h.
#define KNI_DeclareHandle(handle) jobject handle = _KNI_push_handle(&__handles__[__declared_count__++])
Declares a handle that can be used as an input, output, or in/out parameter to an appropriate KNI function. The initial value of the handle is unspecified. If the programmer has not allocated enough space for the handle in the preceding call to KNI_StartHandles, the behavior of this function is unspecified
Parameters
handle The name by which the handle will be identified between the calls to KNI_StartHandles and KNI_EndHandles / KNI_EndHandlesAndReturnObject
Definition at line 1481 of file kni.h.
Referenced by java_lang_Class_forName(), java_lang_Class_getInternalName(), java_lang_Class_isAssignableFrom(), java_lang_Class_isInstance(), java_lang_Class_newInstance(), java_lang_Object__wait(), java_lang_Object_getClass(), java_lang_Object_notify(), java_lang_Object_notifyAll(), java_lang_ref_WeakReference_addToWeakReferenceList(), java_lang_String_intern(), java_lang_System_arraycopy(), java_lang_System_identityHashCode(), java_lang_Thread_currentThread(), java_lang_Thread_interrupt(), java_lang_Thread_join(), and java_lang_Thread_start().
#define KNI_EINVAL (-6)
Failure due to incorrect arguments
Definition at line 181 of file kni.h.
#define KNI_EndHandles()
Value:
while (__declared_count__--)
        thread_pop_root();
Undeclares and unallocates the handles defined after the preceding KNI_StartHandles() call
Definition at line 1516 of file kni.h.
Referenced by java_lang_Class_isAssignableFrom(), java_lang_Class_isInstance(), java_lang_Object__wait(), java_lang_Object_notify(), java_lang_Object_notifyAll(), java_lang_ref_WeakReference_addToWeakReferenceList(), java_lang_System_arraycopy(), java_lang_System_identityHashCode(), java_lang_Thread_interrupt(), java_lang_Thread_join(), and java_lang_Thread_start().
#define KNI_EndHandlesAndReturnObject(objectHandle)
Value:
while (__declared_count__--)
        thread_pop_root();
    return (uintptr_t) *objectHandle;
Undeclares and unallocates the handles defined after the preceding KNI_StartHandles call. At the same time, this function will terminate the execution of the native function immediately and return an object reference back to the caller
Parameters
objectHandle The handle from which the result value will be read
Definition at line 1528 of file kni.h.
Referenced by java_lang_Class_forName(), java_lang_Class_getInternalName(), java_lang_Class_newInstance(), java_lang_Object_getClass(), java_lang_String_intern(), and java_lang_Thread_currentThread().
#define KNI_ENOMEM (-4)
Failure due to lack of available memory
Definition at line 180 of file kni.h.
#define KNI_ERR (-1)
Generic failure return value for a KNI function
Definition at line 179 of file kni.h.
#define KNI_FALSE (0)
'false' value of a java 'boolean'
Definition at line 163 of file kni.h.
#define KNI_OK (0)
Success return value for a KNI function
Definition at line 178 of file kni.h.
#define KNI_ReturnBoolean(value) return (value) ? 1 : 0
Returns a boolean value from a native function. Calling the function will terminate the execution of the native function immediately
Parameters
value The result value of the native method
Definition at line 1399 of file kni.h.
Referenced by java_lang_Class_isAssignableFrom(), and java_lang_Class_isInstance().
#define KNI_ReturnByte(value) return (jbyte) (value)
Returns a byte value from a native function. Calling the function will terminate execution of the native function immediately
Parameters
value The result value of the native method
Definition at line 1405 of file kni.h.
#define KNI_ReturnChar(value) return (jchar) (value)
Returns a char value from a native function. Calling the function will terminate execution of the native function immediately
Parameters
value The result value of the native method
Definition at line 1411 of file kni.h.
#define KNI_ReturnInt(value) return (jint) (value)
Returns an int value from a native function. Calling the function will terminate execution of the native function immediately
Parameters
value The result value of the native method
Definition at line 1423 of file kni.h.
Referenced by java_lang_System_identityHashCode(), and java_lang_Thread_activeCount().
#define KNI_ReturnLong(value) return (jlong) (value)
Returns a long value from a native function. Calling the function will terminate execution of the native function immediately
Parameters
value The result value of the native method
Definition at line 1429 of file kni.h.
Referenced by java_lang_Runtime_freeMemory(), java_lang_Runtime_totalMemory(), and java_lang_System_currentTimeMillis().
#define KNI_ReturnShort(value) return (jshort) (value)
Returns a short value from a native function. Calling the function will terminate execution of the native function immediately
Parameters
value The result value of the native method
Definition at line 1417 of file kni.h.
#define KNI_RETURNTYPE_BOOLEAN int32_t
KNI return type for functions returning booleans
Definition at line 127 of file kni.h.
#define KNI_RETURNTYPE_BYTE int32_t
KNI return type for functions returning bytes
Definition at line 130 of file kni.h.
#define KNI_RETURNTYPE_CHAR int32_t
KNI return type for functions returning chars
Definition at line 133 of file kni.h.
#define KNI_RETURNTYPE_DOUBLE double
KNI return type for functions returning doubles
Definition at line 148 of file kni.h.
#define KNI_RETURNTYPE_FLOAT float
KNI return type for functions returning floats
Definition at line 145 of file kni.h.
#define KNI_RETURNTYPE_INT int32_t
KNI return type for functions returning ints
Definition at line 139 of file kni.h.
#define KNI_RETURNTYPE_LONG int64_t
KNI return type for functions returning longs
Definition at line 142 of file kni.h.
#define KNI_RETURNTYPE_OBJECT uintptr_t
KNI return type for functions returning object handles
Definition at line 151 of file kni.h.
#define KNI_RETURNTYPE_SHORT int32_t
KNI return type for functions returning shorts
Definition at line 136 of file kni.h.
#define KNI_RETURNTYPE_VOID void
KNI return type for functions returning void
Definition at line 124 of file kni.h.
#define KNI_ReturnVoid() return
Returns a void value from a native function. Calling this function terminates the execution of the native function immediately
Definition at line 1393 of file kni.h.
Referenced by java_lang_Object__wait(), java_lang_Object_notify(), java_lang_Object_notifyAll(), java_lang_ref_WeakReference_addToWeakReferenceList(), java_lang_Runtime_gc(), java_lang_Thread_interrupt(), java_lang_Thread_join(), java_lang_Thread_sleep(), java_lang_Thread_start(), java_lang_Thread_yield(), and java_lang_Throwable_printStackTrace().
#define KNI_StartHandles(n)
Value:
    size_t __declared_count__ = 0;
    uintptr_t __handles__[n]
Allocates enough space for n handles for the current native method
Parameters
n A positive integer specifying the number of handles to allocate
Definition at line 1467 of file kni.h.
Referenced by java_lang_Class_forName(), java_lang_Class_getInternalName(), java_lang_Class_isAssignableFrom(), java_lang_Class_isInstance(), java_lang_Class_newInstance(), java_lang_Object__wait(), java_lang_Object_getClass(), java_lang_Object_notify(), java_lang_Object_notifyAll(), java_lang_ref_WeakReference_addToWeakReferenceList(), java_lang_String_intern(), java_lang_System_arraycopy(), java_lang_System_identityHashCode(), java_lang_Thread_currentThread(), java_lang_Thread_interrupt(), java_lang_Thread_join(), and java_lang_Thread_start().
#define KNI_TRUE (1)
'true' value of a java ' boolean'
Definition at line 164 of file kni.h.
Referenced by KNI_IsAssignableFrom(), and KNI_IsInstanceOf().
#define KNI_VERSION (0x00010000)
KNI version. Currently 1.0
Definition at line 188 of file kni.h.
Typedef Documentation
typedef jobject jarray
Untyped java array reference
Definition at line 87 of file kni.h.
typedef uint8_t jboolean
Java 'boolean' type
Definition at line 44 of file kni.h.
typedef jarray jbooleanArray
boolean array reference
Definition at line 90 of file kni.h.
typedef uint8_t jbyte
Java 'byte' type
Definition at line 47 of file kni.h.
typedef jarray jbyteArray
byte array reference
Definition at line 93 of file kni.h.
typedef uint16_t jchar
Java 'char' type
Definition at line 50 of file kni.h.
typedef jarray jcharArray
char array reference
Definition at line 96 of file kni.h.
typedef uintptr_t* jclass
java.lang.Class reference
Definition at line 78 of file kni.h.
typedef double jdouble
Java 'double' type
Definition at line 65 of file kni.h.
typedef jarray jdoubleArray
double array reference
Definition at line 111 of file kni.h.
typedef uintptr_t jfieldID
Reference to a field
Definition at line 117 of file kni.h.
typedef float jfloat
Java 'float' type
Definition at line 62 of file kni.h.
typedef jarray jfloatArray
float array reference
Definition at line 108 of file kni.h.
typedef int32_t jint
Java 'int' type
Definition at line 56 of file kni.h.
typedef jarray jintArray
int array reference
Definition at line 102 of file kni.h.
typedef int64_t jlong
Java 'long' type
Definition at line 59 of file kni.h.
typedef jarray jlongArray
long array reference
Definition at line 105 of file kni.h.
typedef uintptr_t* jobject
java.lang.Object reference
Definition at line 75 of file kni.h.
typedef jarray jobjectArray
Array of object references
Definition at line 114 of file kni.h.
typedef int16_t jshort
Java 'short' type
Definition at line 53 of file kni.h.
typedef jarray jshortArray
short array reference
Definition at line 99 of file kni.h.
typedef jint jsize
Size type (string length, etc...)
Definition at line 68 of file kni.h.
typedef jobject jstring
java.lang.String reference
Definition at line 84 of file kni.h.
typedef jobject jthrowable
java.lang.Throwable reference
Definition at line 81 of file kni.h.
Function Documentation
static jobject _KNI_push_handle (jobject handle) [inline, static]
Internal function used for recording the new handles as temporary roots while declaring them. This function also clears the passed handle so that the garbage collector will not see a garbage reference
Parameters
handle A KNI object handle
Returns
The handle argument
Definition at line 1457 of file kni.h.
References thread_push_root().
void KNI_FatalError (const char * message)
Prints an error message to the system’s standard error output, and terminates the execution of the virtual machine immediately
Parameters
message The error message as a UTF-8 string
Definition at line 77 of file kni.c.
References vm_fail().
static void KNI_FindClass (const char * name, jclass classHandle) [inline, static]
Initializes a handle with a reference to the named class or interface. The function assumes that the class has already been loaded to the system and properly initialized. If this is not the case, or if no class is found, the handle will be initialized to NULL
Parameters
name The descriptor of the class or interface to be returned. The name is represented as a UTF-8 string
classHandle A handle in which the class pointer will be returned
Definition at line 210 of file kni.h.
References bcl_find_class(), and class_get_object().
static jsize KNI_GetArrayLength (jarray array) [inline, static]
Returns the number of elements in a given Java array object. The array argument may denote an array of any element type, including primitive types or reference types. If the given array handle is NULL, the function returns -1
Parameters
array A handle pointing to an array object whose length is to be determined
Returns
Returns the number of elements in the array, or -1 if the given array handle is NULL
Definition at line 878 of file kni.h.
static jboolean KNI_GetBooleanArrayElement (jbooleanArray arrayHandle, jsize index) [inline, static]
Returns an element of an array of booleans. The given array reference must not be NULL. No array type checking or index range checking is performed
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
Returns
Returns the element at position index of an array of booleans
Definition at line 894 of file kni.h.
References array_get_data().
static jboolean KNI_GetBooleanField (jobject objectHandle, jfieldID fieldID) [inline, static]
Returns the value of an instance field of type boolean. The field to access is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be accessed
fieldID The field ID of the given instance field
Returns
The value of the specified instance field
Definition at line 322 of file kni.h.
static jbyte KNI_GetByteArrayElement (jbyteArray arrayHandle, jsize index) [inline, static]
Returns an element of an array of bytes. The given array reference must not be NULL. No array type checking or index range checking is performed
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
Returns
Returns the element at position index of an array of bytes
Definition at line 910 of file kni.h.
References array_get_data().
static jbyte KNI_GetByteField (jobject objectHandle, jfieldID fieldID) [inline, static]
Returns the value of an instance field of type byte. The field to access is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be accessed
fieldID The field ID of the given instance field
Returns
The value of the specified instance field
Definition at line 337 of file kni.h.
static jchar KNI_GetCharArrayElement (jcharArray arrayHandle, jsize index) [inline, static]
Returns an element of an array of chars. The given array reference must not be NULL. No array type checking or index range checking is performed
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
Returns
Returns the element at position index of an array of chars
Definition at line 925 of file kni.h.
References array_get_data().
static jchar KNI_GetCharField (jobject objectHandle, jfieldID fieldID) [inline, static]
Returns the value of an instance field of type char. The field to access is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be accessed
fieldID The field ID of the given instance field
Returns
The value of the specified instance field
Definition at line 349 of file kni.h.
static void KNI_GetClassPointer (jclass toHandle) [inline, static]
Reads the value of the class pointer in the current stack frame of a static native method, and stores the value in the handle toHandle
Parameters
toHandle A handle to contain the class pointer
Definition at line 1385 of file kni.h.
References class_get_object(), and thread_self().
jfieldID KNI_GetFieldID (jclass classHandle, const char * name, const char * signature)
Returns the field ID of an instance field of the class represented by classHandle. The field is specified by its name and signature. The Get<Type>Field and Set<Type>Field families of accessor functions use field IDs to retrieve the value of instance fields. The field must be accessible from the class referred to by classHandle
Parameters
classHandle A handle pointing to a class whose field ID will be retrieved
name The field name as a UTF-8 string
signature The field descriptor as a UTF-8 string
Returns
Returns a field ID or NULL if the lookup fails for any reason
Definition at line 98 of file kni.c.
References bcl_get_class_by_id(), class_get_field(), field_is_static(), JAVA_LANG_CLASS_REF2PTR, and field_t::offset.
static jint KNI_GetIntArrayElement (jintArray arrayHandle, jsize index) [inline, static]
Returns an element of an array of ints. The given array reference must not be NULL. No array type checking or index range checking is performed
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
Returns
Returns the element at position index of an array of ints
Definition at line 956 of file kni.h.
References array_get_data().
static jint KNI_GetIntField (jobject objectHandle, jfieldID fieldID) [inline, static]
Returns the value of an instance field of type int. The field to access is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be accessed
fieldID The field ID of the given instance field
Returns
The value of the specified instance field
Definition at line 373 of file kni.h.
static jlong KNI_GetLongArrayElement (jlongArray arrayHandle, jsize index) [inline, static]
Returns an element of an array of longs. The given array reference must not be NULL. No array type checking or index range checking is performed
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
Returns
Returns the element at position index of an array of longs
Definition at line 971 of file kni.h.
References array_get_data().
static jlong KNI_GetLongField (jobject objectHandle, jfieldID fieldID) [inline, static]
Returns the value of an instance field of type long. The field to access is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be accessed
fieldID The field ID of the given instance field
Returns
The value of the specified instance field
Definition at line 385 of file kni.h.
static void KNI_GetObjectArrayElement (jobjectArray arrayHandle, jint index, jobject toHandle) [inline, static]
Returns an element of an array of a reference type. The given array handle must not be NULL. No array type checking or index range checking is performed
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
toHandle A handle to which the return value will be assigned
Definition at line 1023 of file kni.h.
References array_ref_get_data().
static void KNI_GetObjectClass (jobject objectHandle, jclass classHandle) [inline, static]
Sets the handle classHandle to point to the class of the object represented by objectHandle
Parameters
objectHandle A handle pointing to an object whose class is being sought
classHandle A handle which, upon return of this function, will contain a reference to the class of this object
Definition at line 278 of file kni.h.
References class_get_object(), and header_get_class().
static void KNI_GetObjectField (jobject objectHandle, jfieldID fieldID, jobject toHandle) [inline, static]
Returns the value of a field of a reference type, and assigns it to the handle toHandle. The field to access is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose whose field is to be accessed
fieldID The field ID of the given instance field
toHandle A handle to which the return value will be assigned
Definition at line 425 of file kni.h.
static jboolean KNI_GetParameterAsBoolean (jint index) [inline, static]
Returns the value of a parameter of type boolean at physical location specified by index. Parameter indices are mapped from left to right. Index value 1 refers to the leftmost parameter that has been passed on to the native method. Remember that parameters of type long or double take up two entries on the operand stack. No type checking or index range checking is performed.
Parameters
index The index of a parameter of a primitive type to the native method. Index value 1 refers to the leftmost parameter in the Java method.
Returns
Returns the argument of a primitive type at position index in the list of arguments to the native method.
Definition at line 1236 of file kni.h.
References thread_t::fp, stack_frame_t::locals, and thread_self().
static jbyte KNI_GetParameterAsByte (jint index) [inline, static]
Returns the value of a parameter of type byte at physical location specified by index. Parameter indices are mapped from left to right. Index value 1 refers to the leftmost parameter that has been passed on to the native method. Remember that parameters of type long or double take up two entries on the operand stack. No type checking or index range checking is performed.
Parameters
index The index of a parameter of a primitive type to the native method. Index value 1 refers to the leftmost parameter in the Java method.
Returns
Returns the argument of a primitive type at position index in the list of arguments to the native method.
Definition at line 1252 of file kni.h.
References thread_t::fp, stack_frame_t::locals, and thread_self().
Referenced by jelatine_VMOutputStream_write_to_stderr(), and jelatine_VMOutputStream_write_to_stdout().
static jchar KNI_GetParameterAsChar (jint index) [inline, static]
Returns the value of a parameter of type char at physical location specified by index. Parameter indices are mapped from left to right. Index value 1 refers to the leftmost parameter that has been passed on to the native method. Remember that parameters of type long or double take up two entries on the operand stack. No type checking or index range checking is performed.
Parameters
index The index of a parameter of a primitive type to the native method. Index value 1 refers to the leftmost parameter in the Java method.
Returns
Returns the argument of a primitive type at position index in the list of arguments to the native method.
Definition at line 1268 of file kni.h.
References thread_t::fp, stack_frame_t::locals, and thread_self().
static jint KNI_GetParameterAsInt (jint index) [inline, static]
Returns the value of a parameter of type long at physical location specified by index. Parameter indices are mapped from left to right. Index value 1 refers to the leftmost parameter that has been passed on to the native method. Remember that parameters of type long or double take up two entries on the operand stack. No type checking or index range checking is performed.
Parameters
index The index of a parameter of a primitive type to the native method. Index value 1 refers to the leftmost parameter in the Java method.
Returns
Returns the argument of a primitive type at position index in the list of arguments to the native method.
Definition at line 1300 of file kni.h.
References thread_t::fp, stack_frame_t::locals, and thread_self().
Referenced by java_lang_Object__wait(), java_lang_Runtime_exit(), and java_lang_System_arraycopy().
static jlong KNI_GetParameterAsLong (jint index) [inline, static]
Returns the value of a parameter of type long at physical location specified by index. Parameter indices are mapped from left to right. Index value 1 refers to the leftmost parameter that has been passed on to the native method. Remember that parameters of type long or double take up two entries on the operand stack. No type checking or index range checking is performed.
Parameters
index The index of a parameter of a primitive type to the native method. Index value 1 refers to the leftmost parameter in the Java method.
Returns
Returns the argument of a primitive type at position index in the list of arguments to the native method.
Definition at line 1316 of file kni.h.
References thread_t::fp, stack_frame_t::locals, and thread_self().
Referenced by java_lang_Object__wait(), and java_lang_Thread_sleep().
static void KNI_GetParameterAsObject (jint index, jobject toHandle) [inline, static]
Reads the value (object reference) of the parameter specified by index, and stores it in the handle toHandle. Parameter indices are mapped from left to right. Index value 1 refers to the leftmost parameter that has been passed on to the native method. No type checking or index range checking is performed
Parameters
index The index of a parameter of a reference type to the native method. Index value 1 refers to the leftmost parameter in the Java method
toHandle A handle to to which the return value will be assigned
Definition at line 1366 of file kni.h.
References thread_t::fp, stack_frame_t::locals, and thread_self().
Referenced by java_lang_Class_forName(), java_lang_Class_isAssignableFrom(), java_lang_Class_isInstance(), java_lang_ref_WeakReference_addToWeakReferenceList(), java_lang_System_arraycopy(), and java_lang_System_identityHashCode().
static jshort KNI_GetParameterAsShort (jint index) [inline, static]
Returns the value of a parameter of type short at physical location specified by index. Parameter indices are mapped from left to right. Index value 1 refers to the leftmost parameter that has been passed on to the native method. Remember that parameters of type long or double take up two entries on the operand stack. No type checking or index range checking is performed.
Parameters
index The index of a parameter of a primitive type to the native method. Index value 1 refers to the leftmost parameter in the Java method.
Returns
Returns the argument of a primitive type at position index in the list of arguments to the native method.
Definition at line 1284 of file kni.h.
References thread_t::fp, stack_frame_t::locals, and thread_self().
static void KNI_GetRawArrayRegion (jarray arrayHandle, jsize offset, jsize n, jbyte * dstBuffer) [inline, static]
Gets a region of n bytes of an array of a primitive type. The given array handle must not be NULL. No array type checking or range checking is performed
Parameters
arrayHandle A handle initialized with the array reference
offset A byte offset within the array
n The number of bytes of raw data to get
dstBuffer The destination of the data as bytes
Definition at line 1193 of file kni.h.
References array_get_data().
static jshort KNI_GetShortArrayElement (jshortArray arrayHandle, jsize index) [inline, static]
Returns an element of an array of shorts. The given array reference must not be NULL. No array type checking or index range checking is performed
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
Returns
Returns the element at position index of an array of shorts
Definition at line 940 of file kni.h.
References array_get_data().
static jshort KNI_GetShortField (jobject objectHandle, jfieldID fieldID) [inline, static]
Returns the value of an instance field of type short. The field to access is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be accessed
fieldID The field ID of the given instance field
Returns
The value of the specified instance field
Definition at line 361 of file kni.h.
static jboolean KNI_GetStaticBooleanField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID) [inline, static]
Returns the value of a static field of boolean type. The field to access is denoted by fieldID.
Parameters
classHandle A handle pointing to a class or interface whose static field is to be accessed
fieldID A field ID of the given class
Returns
Returns the value of the specified static field
Definition at line 571 of file kni.h.
static jbyte KNI_GetStaticByteField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID) [inline, static]
Returns the value of a static field of byte type. The field to access is denoted by fieldID.
Parameters
classHandle A handle pointing to a class or interface whose static field is to be accessed
fieldID A field ID of the given class
Returns
Returns the value of the specified static field
Definition at line 584 of file kni.h.
static jchar KNI_GetStaticCharField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID) [inline, static]
Returns the value of a static field of char type. The field to access is denoted by fieldID.
Parameters
classHandle A handle pointing to a class or interface whose static field is to be accessed
fieldID A field ID of the given class
Returns
Returns the value of the specified static field
Definition at line 597 of file kni.h.
jfieldID KNI_GetStaticFieldID (jclass classHandle, const char * name, const char * signature)
Returns the field ID of a static field of the class represented by classHandle. The field is specified by its name and signature. The GetStatic<Type>Field and SetStatic<Type>Field families of accessor functions use field IDs to retrieve the value of static fields. The field must be accessible from the class referred to by classHandle
Parameters
classHandle A handle pointing to a class whose field ID will be retrieved
name The field name as a UTF-8 string
signature The field descriptor as a UTF-8 string
Returns
Returns a field ID or NULL if the lookup fails for any reason
Definition at line 129 of file kni.c.
References bcl_get_class_by_id(), class_get_field(), field_is_static(), JAVA_LANG_CLASS_REF2PTR, field_t::offset, class_t::static_data, and static_field_data_ptr().
static jint KNI_GetStaticIntField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID) [inline, static]
Returns the value of a static field of int type. The field to access is denoted by fieldID.
Parameters
classHandle A handle pointing to a class or interface whose static field is to be accessed
fieldID A field ID of the given class
Returns
Returns the value of the specified static field
Definition at line 623 of file kni.h.
static jlong KNI_GetStaticLongField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID) [inline, static]
Returns the value of a static field of long type. The field to access is denoted by fieldID.
Parameters
classHandle A handle pointing to a class or interface whose static field is to be accessed
fieldID A field ID of the given class
Returns
Returns the value of the specified static field
Definition at line 636 of file kni.h.
static void KNI_GetStaticObjectField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jobject toHandle) [inline, static]
Returns the value of a static field of a reference type, and assigns it to the handle toHandle. The field to access is denoted by fieldID
Parameters
classHandle A handle pointing to a class or interface whose static field is to be accessed
fieldID A field ID of the given class
toHandle A handle to which the return value will be assigned
Definition at line 679 of file kni.h.
static jshort KNI_GetStaticShortField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID) [inline, static]
Returns the value of a static field of short type. The field to access is denoted by fieldID.
Parameters
classHandle A handle pointing to a class or interface whose static field is to be accessed
fieldID A field ID of the given class
Returns
Returns the value of the specified static field
Definition at line 610 of file kni.h.
static jsize KNI_GetStringLength (jstring stringHandle) [inline, static]
Returns the number of Unicode characters in a java.lang.String object. If the given string handle is NULL, the function returns -1
Parameters
stringHandle A handle pointing to a java.lang.String string object whose length is to be determined
Returns
The length of the string, or -1 if the given string handle is NULL
Definition at line 819 of file kni.h.
References JAVA_LANG_STRING_REF2PTR.
void KNI_GetStringRegion (jstring stringHandle, jsize offset, jsize n, jchar * jcharbuf)
Copies a number of Unicode characters from a java.lang.String object (denoted by stringHandle), beginning at offset, to the given buffer jcharbuf. No range checking is performed. It is the responsibility of the native function programmer to allocate the return buffer, and to make sure that it is large enough
Parameters
stringHandle A handle pointing to a java.lang.String object whose contents are to be copied
offset The offset within the string object at which to start copying (offset 0: first character in the Java string.)
n The number of 16-bit Unicode characters to copy
jcharbuf A pointer to a buffer to hold the Unicode characters
Definition at line 164 of file kni.c.
References array_get_data(), JAVA_LANG_STRING_REF2PTR, and java_lang_String_t::value.
static void KNI_GetSuperClass (jclass classHandle, jclass superClassHandle) [inline, static]
Initializes the parent handle to contain a pointer to the superclass of the given class (represented by cl). If cl represents the class java.lang.Object, then the function sets the parent handle to NULL
Parameters
classHandle A handle initialized with a reference to the class object whose superclass is to be determined
superClassHandle A handle which, upon return from this function, will contain a reference to the superclass object
Definition at line 229 of file kni.h.
References bcl_get_class_by_id(), class_get_object(), class_get_parent(), JAVA_LANG_CLASS_REF2PTR, and class_t::parent.
static void KNI_GetThisPointer (jobject toHandle) [inline, static]
Reads the value of the 'this' pointer in the current stack frame of an instance (non-static) native method, and stores the value in the handle toHandle
Parameters
toHandle A handle to contain the 'this' pointer
Definition at line 1376 of file kni.h.
References thread_t::fp, stack_frame_t::locals, and thread_self().
Referenced by java_lang_Class_getInternalName(), java_lang_Class_isAssignableFrom(), java_lang_Class_isInstance(), java_lang_Class_newInstance(), java_lang_Object__wait(), java_lang_Object_getClass(), java_lang_Object_notify(), java_lang_Object_notifyAll(), java_lang_String_intern(), java_lang_Thread_interrupt(), java_lang_Thread_join(), and java_lang_Thread_start().
static jint KNI_GetVersion (void) [inline, static]
Return the version information
Returns
The native interface version
Definition at line 193 of file kni.h.
static jboolean KNI_IsAssignableFrom (jclass cl1, jclass cl2) [inline, static]
Determines whether an object of class or interface cl1 can be safely cast to a class or interface cl2
Parameters
cl1 Handle initialized with a reference to the first class or interface argument
cl2 Handle initialized with a reference to the second class or interface argument
Returns
KNI_TRUE if any of the following is true: the first and second argument refer to the same class or interface, the first argument refers to a subclass of the second argument, the first argument refers to a class that has the second argument as one of its interfaces or the first and second arguments both refer to array of classes with element types X and Y, and KNI_IsAssignableFrom(X, Y) is KNI_TRUE. Otherwise KNI_FALSE
Definition at line 252 of file kni.h.
References bcl_get_class_by_id(), bcl_is_assignable(), JAVA_LANG_CLASS_REF2PTR, and KNI_TRUE.
Referenced by java_lang_Class_isAssignableFrom().
static jboolean KNI_IsInstanceOf (jobject objectHandle, jclass classHandle) [inline, static]
Tests whether an object represented by objectHandle is an instance of a class or interface represented by classHandle
Parameters
objectHandle A handle pointing to an object
classHandle A handle pointing to a class or interface
Returns
Returns KNI_TRUE if the given object is an instance of given class, KNI_FALSE otherwise
Definition at line 297 of file kni.h.
References bcl_get_class_by_id(), bcl_is_assignable(), header_get_class(), JAVA_LANG_CLASS_REF2PTR, KNI_TRUE, and class_t::obj.
Referenced by java_lang_Class_isInstance().
static jboolean KNI_IsNullHandle (jobject handle) [inline, static]
Checks if the given handle is NULL
Parameters
handle The handle whose contents will be examined
Returns
KNI_TRUE if the handle is NULL, KNI_FALSE otherwise
Definition at line 1488 of file kni.h.
Referenced by java_lang_Class_forName(), java_lang_Class_isAssignableFrom(), and java_lang_System_arraycopy().
static jboolean KNI_IsSameObject (jobject obj1, jobject obj2) [inline, static]
Checks if the given two handles refer to the same object. No parameter type checking is performed
Parameters
obj1 A handle pointing to an object
obj2 A handle pointing to an object
Returns
KNI_TRUE if the handles refer to the same object, KNI_FALSE otherwise
Definition at line 1500 of file kni.h.
static void KNI_NewString (const jchar * uchars, jsize length, jobject stringHandle) [inline, static]
Creates a java.lang.String object from the given Unicode sequence. The resulting object is returned to the caller via the stringHandle handle
Parameters
uchars A Unicode sequence that will make up the contents of the new string object
length The length of the string
stringHandle A handle to hold the reference to the new java.lang.String object
Definition at line 841 of file kni.h.
References JAVA_LANG_STRING_PTR2REF, and jstring_create_from_unicode().
static void KNI_NewStringUTF (const char * utf8chars, jobject stringHandle) [inline, static]
Creates a java.lang.String object from the given UTF-8 string. The resulting object is returned to the caller via the stringHandle handle
Parameters
utf8chars A UTF-8 string that will make up the contents of the new string object
stringHandle A handle to hold the reference to the new java.lang.String object
Definition at line 857 of file kni.h.
References JAVA_LANG_STRING_PTR2REF, and jstring_create_from_utf8().
static void KNI_ReleaseHandle (jobject handle) [inline, static]
Sets the value of the given handle to NULL
Parameters
handle The handle whose value will be set to NULL
Definition at line 1508 of file kni.h.
static void KNI_SetBooleanArrayElement (jbooleanArray arrayHandle, jsize index, jboolean value) [inline, static]
Sets an element of an array of booleans. The given array handle must not be NULL. No array type checking or index range checking is performed.
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
value The value that will be stored in the array
Definition at line 1039 of file kni.h.
References array_get_data().
static void KNI_SetBooleanField (jobject objectHandle, jfieldID fieldID, jboolean value) [inline, static]
Sets the value of an instance field of boolean type. The field to modify is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be modified
fieldID The field ID of the given instance field
value The value to set to the instance field
Definition at line 438 of file kni.h.
static void KNI_SetByteArrayElement (jbyteArray arrayHandle, jsize index, jbyte value) [inline, static]
Sets an element of an array of bytes. The given array handle must not be NULL. No array type checking or index range checking is performed.
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
value The value that will be stored in the array
Definition at line 1059 of file kni.h.
References array_get_data().
static void KNI_SetByteField (jobject objectHandle, jfieldID fieldID, jbyte value) [inline, static]
Sets the value of an instance field of byte type. The field to modify is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be modified
fieldID The field ID of the given instance field
value The value to set to the instance field
Definition at line 456 of file kni.h.
static void KNI_SetCharArrayElement (jcharArray arrayHandle, jsize index, jchar value) [inline, static]
Sets an element of an array of chars. The given array handle must not be NULL. No array type checking or index range checking is performed.
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
value The value that will be stored in the array
Definition at line 1075 of file kni.h.
References array_get_data().
static void KNI_SetCharField (jobject objectHandle, jfieldID fieldID, jchar value) [inline, static]
Sets the value of an instance field of char type. The field to modify is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be modified
fieldID The field ID of the given instance field
value The value to set to the instance field
Definition at line 469 of file kni.h.
static void KNI_SetIntArrayElement (jintArray arrayHandle, jsize index, jint value) [inline, static]
Sets an element of an array of ints. The given array handle must not be NULL. No array type checking or index range checking is performed.
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
value The value that will be stored in the array
Definition at line 1107 of file kni.h.
References array_get_data().
static void KNI_SetIntField (jobject objectHandle, jfieldID fieldID, jint value) [inline, static]
Sets the value of an instance field of int type. The field to modify is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be modified
fieldID The field ID of the given instance field
value The value to set to the instance field
Definition at line 495 of file kni.h.
static void KNI_SetLongArrayElement (jlongArray arrayHandle, jsize index, jlong value) [inline, static]
Sets an element of an array of longs. The given array handle must not be NULL. No array type checking or index range checking is performed.
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
value The value that will be stored in the array
Definition at line 1123 of file kni.h.
References array_get_data().
static void KNI_SetLongField (jobject objectHandle, jfieldID fieldID, jlong value) [inline, static]
Sets the value of an instance field of long type. The field to modify is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be modified
fieldID The field ID of the given instance field
value The value to set to the instance field
Definition at line 508 of file kni.h.
static void KNI_SetObjectArrayElement (jobjectArray arrayHandle, jint index, jobject fromHandle) [inline, static]
Sets an element of an array of a reference type. The given array handle must not be NULL. No array type checking or index range checking is performed
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
fromHandle A handle from which value will be read
Definition at line 1176 of file kni.h.
References array_ref_get_data().
static void KNI_SetObjectField (jobject objectHandle, jfieldID fieldID, jobject fromHandle) [inline, static]
Sets the value of an instance field of a reference type. The field to modify is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be modified
fieldID The field ID of the given instance field
fromHandle A handle pointing to an object that will be assigned to the field
Definition at line 552 of file kni.h.
static void KNI_SetRawArrayRegion (jarray arrayHandle, jsize offset, jsize n, const jbyte * srcBuffer) [inline, static]
Sets a region of n bytes of an array of a primitive type. The given array handle must not be NULL. No array type checking or range checking is performed
Parameters
arrayHandle A handle initialized with the array reference
offset A byte offset within the array
n The number of bytes of raw data to change
srcBuffer The source of the data as bytes
Definition at line 1211 of file kni.h.
References array_get_data().
static void KNI_SetShortArrayElement (jshortArray arrayHandle, jsize index, jshort value) [inline, static]
Sets an element of an array of shorts. The given array handle must not be NULL. No array type checking or index range checking is performed.
Parameters
arrayHandle A handle pointing to an array object
index The index of the element in the array. Index 0 denotes the first element in the array
value The value that will be stored in the array
Definition at line 1091 of file kni.h.
References array_get_data().
static void KNI_SetShortField (jobject objectHandle, jfieldID fieldID, jshort value) [inline, static]
Sets the value of an instance field of short type. The field to modify is denoted by fieldID
Parameters
objectHandle A handle pointing to an object whose field is to be modified
fieldID The field ID of the given instance field
value The value to set to the instance field
Definition at line 482 of file kni.h.
static void KNI_SetStaticBooleanField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jboolean value) [inline, static]
Sets the value of a static field of boolean type. The field to modify is denoted by fieldID
Parameters
classHandle A handle pointing to the class or interface whose static field is to be modified
fieldID A field ID of the given class
value The value to set to the static field
Definition at line 692 of file kni.h.
static void KNI_SetStaticByteField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jbyte value) [inline, static]
Sets the value of a static field of byte type. The field to modify is denoted by fieldID
Parameters
classHandle A handle pointing to the class or interface whose static field is to be modified
fieldID A field ID of the given class
value The value to set to the static field
Definition at line 705 of file kni.h.
static void KNI_SetStaticCharField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jchar value) [inline, static]
Sets the value of a static field of char type. The field to modify is denoted by fieldID
Parameters
classHandle A handle pointing to the class or interface whose static field is to be modified
fieldID A field ID of the given class
value The value to set to the static field
Definition at line 718 of file kni.h.
static void KNI_SetStaticIntField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jint value) [inline, static]
Sets the value of a static field of int type. The field to modify is denoted by fieldID
Parameters
classHandle A handle pointing to the class or interface whose static field is to be modified
fieldID A field ID of the given class
value The value to set to the static field
Definition at line 744 of file kni.h.
static void KNI_SetStaticLongField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jlong value) [inline, static]
Sets the value of a static field of long type. The field to modify is denoted by fieldID
Parameters
classHandle A handle pointing to the class or interface whose static field is to be modified
fieldID A field ID of the given class
value The value to set to the static field
Definition at line 757 of file kni.h.
static void KNI_SetStaticObjectField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jobject fromHandle) [inline, static]
Sets the value of a static field of a reference type. The field to modify is denoted by fieldID
Parameters
classHandle A handle pointing to the class or interface whose whose static field is to be modified
fieldID A field ID of the given class
fromHandle A handle pointing to an object that will assigned to the field
Definition at line 801 of file kni.h.
static void KNI_SetStaticShortField (jclass classHandle ATTRIBUTE_UNUSED, jfieldID fieldID, jshort value) [inline, static]
Sets the value of a static field of short type. The field to modify is denoted by fieldID
Parameters
classHandle A handle pointing to the class or interface whose static field is to be modified
fieldID A field ID of the given class
value The value to set to the static field
Definition at line 731 of file kni.h.
jint KNI_ThrowNew (const char * name, const char * message)
Instantiates an exception object with the message specified by message, and causes that exception to be thrown. A thrown exception will be pending in the current thread, but does not immediately disrupt native code execution. The actual exception will be thrown when the program control returns from the native function back to the virtual machine. Note that KNI_ThrowNew does not run the constructor on the new exception object.
Parameters
name The name of a java.lang.Throwable class as a UTF-8 string
message The message used to construct the java.lang.Throwable object; represented as a UTF-8 string
Returns
KNI_OK on success; otherwise KNI_ERR
Definition at line 52 of file kni.c.
References bcl_resolve_class(), stack_frame_t::cl, java_lang_Throwable_t::detailMessage, thread_t::exception, thread_t::fp, gc_new(), JAVA_LANG_STRING_PTR2REF, JAVA_LANG_THROWABLE_REF2PTR, jstring_create_from_utf8(), and thread_self().
Referenced by arraycopy_ref(), java_lang_Class_forName(), java_lang_Class_isAssignableFrom(), java_lang_Object__wait(), java_lang_Object_notify(), java_lang_Object_notifyAll(), java_lang_System_arraycopy(), java_lang_Thread_sleep(), thread_join(), thread_sleep(), and thread_wait().