src/jelatine/memory.h File Reference
#include `wrappers.h`
#include `opcodes.h`
#include `header.h`
#include `java_lang_ref_WeakReference.h`
Defines
#define JELATINE_MEMORY_H (1)
Functions
void gc_init (size_t)
void gc_teardown (void)
void gc_enable (bool)
void gc_collect (size_t)
size_t gc_free_memory (void)
size_t gc_total_memory (void)
void gc_mark_potential (uintptr_t)
void gc_mark_reference (uintptr_t)
uintptr_t gc_new (struct class_t *)
uintptr_t gc_new_array_nonref (array_type_t, int32_t)
uintptr_t gc_new_array_ref (struct class_t *, int32_t)
uintptr_t gc_new_multiarray (struct class_t *, uint8_t, jword_t *)
void gc_register_weak_ref (java_lang_ref_WeakReference_t *)
void * gc_malloc (size_t)
void * gc_palloc (size_t)
void gc_free (void *)
Detailed Description
Garbage-collector and allocator type definitions and interface
Definition in file memory.h.
Define Documentation
#define JELATINE_MEMORY_H (1)
memory.h inclusion macro
Definition at line 28 of file memory.h.
Function Documentation
void gc_collect (size_t grow)
Launches the garbage collector on the provided heap structure
Parameters
grow If non null, specifies the amount of bytes of the next allocation, the heap will be grown after the collection to accomodate it if not enough free space was reclaimed
Definition at line 485 of file memory.c.
References heap_t::collect, heap_t::end, gc_grow(), gc_mark(), gc_mark_finalizable(), gc_purge_bin(), gc_purge_weakref_list(), gc_sweep(), jsm_purge(), tm_lock(), tm_purge(), tm_stop_the_world(), and tm_unlock().
Referenced by gc_alloc(), and java_lang_Runtime_gc().
void gc_enable (bool enable)
Enables or disables the collector
Parameters
enable new status of the collector
Definition at line 227 of file memory.c.
References heap_t::collect.
Referenced by vm_run().
void gc_free (void * ptr)
Frees a previously allocated C object.
If ptr is NULL no action is taken
Parameters
ptr A pointer to the object to be fred
Definition at line 1076 of file memory.c.
References header_get_size(), heap_t::perm, put_chunk(), heap_t::start, tm_lock(), and tm_unlock().
Referenced by bcl_link_opcode(), c_clear_exception(), cf_close(), cf_open_with_classpath(), cp_create(), grow_class_table(), im_add(), im_flatten(), java_lang_Class_forName(), jsm_rehash(), jsm_rehash_literals(), load_class(), load_method_attribute_Exceptions(), method_purge(), string_manager_rehash(), thread_create_main(), thread_launch(), thread_push_root(), thread_start(), tm_purge(), and tm_rehash().
size_t gc_free_memory (void)
Helper function used for implementing Runtime.freeMemory(), returns the amount of free memory in bytes
Returns
The amount of free memory in bytes
Definition at line 521 of file memory.c.
References heap_t::bin, heap_t::large_bin, large_chunk_t::next, small_chunk_t::next, large_chunk_t::size, heap_t::size, tm_lock(), and tm_unlock().
Referenced by java_lang_Runtime_freeMemory().
void gc_init (size_t size)
Initializes the heap, throws an exception upon failure
Note that if a heap of less than 32 KiB is requested the function will default to 32 KiB anyway as mandated by the CLDC configuration. If you want to use a heap smaller than 32 KiB you have to explicitely change this function, do it at your own risk. All the pointers in the heap structure are explicitely aligned to 4 or 8-bytes boundaries depending on the target machine
Parameters
size Size in bytes of the unified heap
Definition at line 163 of file memory.c.
References heap_t::bin, BIN_ENTRIES, heap_t::bitmap, heap_t::collect, dbg_error, heap_t::end, HEAP_INIT_FRACTION, heap_t::large_bin, heap_t::max_size, heap_t::memory, heap_t::perm, put_chunk(), heap_t::size, size_ceil(), size_floor(), heap_t::start, vm_fail(), and heap_t::weakref_list.
Referenced by vm_init().
void* gc_malloc (size_t size)
Allocates a chunk of memory for holding C objects, throws an exception upon failure, the returned memory has already been zeroed.
If the allocation size is zero the function will return a NULL pointer. The allocation size is rounded to a multiple of 4 or 8 bytes depending on the target
Parameters
size The size in bytes of the chunk to be allocated
Returns
A pointer to the newly allocated memory
Definition at line 1002 of file memory.c.
References gc_alloc(), header_create_c(), size_ceil(), tm_lock(), and tm_unlock().
Referenced by bcl_init(), bcl_link_opcode(), c_throw_dbg(), cf_open_with_classpath(), cp_create(), gc_palloc(), grow_class_table(), im_add(), java_to_utf8(), jsm_init(), jsm_rehash(), jsm_rehash_literals(), load_bytecode(), load_class(), load_exception_handlers(), load_method_attribute_Exceptions(), monitor_init(), string_manager_init(), string_manager_rehash(), thread_create_main(), thread_launch(), thread_push_root(), thread_start(), thread_wait(), tm_rehash(), and vm_run().
void gc_mark_potential (uintptr_t ref)
Check if a reference is a pointer and recursively gc_mark it if it is
Parameters
ref A reference to a Java object
Definition at line 563 of file memory.c.
References bitmap_get(), heap_t::end, gc_mark_reference(), and heap_t::start.
Referenced by tm_mark().
void gc_mark_reference (uintptr_t ref)
Marks the object pointed by ref and recursively all the objects pointed by the references it contains
Parameters
ref A reference to a Java object
Definition at line 593 of file memory.c.
References array_get_ref_n(), class_get_ref_n(), class_is_array(), class_t::elem_type, gc_mark_reference(), header_get_class(), header_is_marked(), header_is_object(), header_set_mark(), and PT_REFERENCE.
Referenced by bcl_mark(), gc_mark_finalizable(), gc_mark_potential(), gc_mark_reference(), jsm_mark(), and tm_mark().
uintptr_t gc_new (class_t * cl)
Allocates a managed object of the specified class
If not enough memory is avaible an exception is thrown, note that the returned reference points to the object header, not to the first word of the object.
Parameters
cl A pointer to the object class
Returns
A reference to the newly created object, throws an exception upon failure
Definition at line 242 of file memory.c.
References bitmap_set(), class_get_nref_size(), class_get_ref_n(), gc_alloc(), header_create_object(), heap_t::size, size_ceil(), tm_lock(), and tm_unlock().
Referenced by interpreter(), java_lang_Class_newInstance(), jstring_create_from_unicode(), jstring_create_from_utf8(), jstring_create_literal(), KNI_ThrowNew(), load_class(), thread_create_main(), and vm_run().
uintptr_t gc_new_array_nonref (array_type_t type, int32_t count)
Creates a new array of the specified type
Parameters
type The basic array class type requested
count The number of elements
Returns
A reference to the newly created array
Definition at line 284 of file memory.c.
References array_elem_size(), bcl_array_class(), bitmap_set(), gc_alloc(), array_t::header, header_create_object(), array_t::length, heap_t::size, size_ceil(), size_div_inf(), tm_lock(), and tm_unlock().
Referenced by gc_new_multiarray(), interpreter(), jstring_create_from_unicode(), jstring_create_from_utf8(), and jstring_create_literal().
uintptr_t gc_new_array_ref (class_t * cl, int32_t count)
Creates a new array of references
Parameters
cl A pointer to the corresponding class
count The number of elements
Returns
A pointer to the newly created array
Definition at line 320 of file memory.c.
References bitmap_set(), gc_alloc(), ref_array_t::header, header_create_object(), ref_array_t::length, heap_t::size, size_ceil(), tm_lock(), and tm_unlock().
Referenced by arraycopy_ref(), gc_new_multiarray(), interpreter(), and vm_run().
uintptr_t gc_new_multiarray (class_t * cl, uint8_t dimensions, jword_t * counts)
Helper function used for creating multi-dimensional arrays
Parameters
cl A pointer to the corresponding class
dimensions The number of dimensions to be created
counts A pointer to the element counts
Returns
A pointer to the newly created array
Definition at line 357 of file memory.c.
References array_ref_get_data(), class_t::elem_class, class_t::elem_type, gc_new_array_nonref(), gc_new_array_ref(), gc_new_multiarray(), prim_to_array_type(), PT_REFERENCE, thread_pop_root(), and thread_push_root().
Referenced by gc_new_multiarray(), and interpreter().
void* gc_palloc (size_t size)
Allocates a chunk of permanent memory for holding C objects, throws an exception upon failure, the returned memory has already been zeroed.
The memory allocated with this function cannot be fred with gc_free()
Parameters
size The size in bytes of the chunk to be allocated
Returns
A pointer to the newly allocated memory
Definition at line 1037 of file memory.c.
References heap_t::end, gc_malloc(), heap_t::perm, size_ceil(), tm_lock(), and tm_unlock().
Referenced by bcl_resolve_class(), class_alloc_fields(), classpath_init(), cp_create(), create_dispatch_table(), create_interface_dispatch_table(), im_create(), im_flatten(), initialize_static_fields(), mm_create(), preload_class(), and utf8_intern().
void gc_register_weak_ref (java_lang_ref_WeakReference_t * ref)
Adds a new object to the weak reference list
Parameters
ref A reference to the object to be added to the weak reference list
Definition at line 452 of file memory.c.
References java_lang_ref_WeakReference_t::next, tm_lock(), tm_unlock(), and heap_t::weakref_list.
Referenced by java_lang_ref_WeakReference_addToWeakReferenceList().
void gc_teardown (void)
Disposes the unified heap
Definition at line 219 of file memory.c.
References heap_t::memory.
Referenced by vm_teardown().
size_t gc_total_memory (void)
Helper function used for implementing Runtime.totalMemory(), returns the amount of memory available to the VM in bytes
Returns
The amount of memory available to the VM in bytes
Definition at line 555 of file memory.c.
References heap_t::size.
Referenced by java_lang_Runtime_totalMemory().