src/jelatine/method.c File Reference
#include `wrappers.h`
#include `class.h`
#include `classfile.h`
#include `constantpool.h`
#include `loader.h`
#include `method.h`
#include `memory.h`
#include `native.h`
#include `opcodes.h`
#include `util.h`
Functions
void init_dummy_methods (void)
method_manager_t * mm_create (uint32_t count)
static void parse_method_descriptor (method_t *method)
static void method_check_access_flags (method_t *method)
void mm_add (method_manager_t *mm, char *name, char *descriptor, uint16_t access_flags, const_pool_t *cp, method_attributes_t *attr)
method_t * mm_get (method_manager_t *mm, char *name, char *descriptor)
uint32_t mm_get_count (method_manager_t *mm)
uint16_t method_create_packed_index (const method_t *method)
bool method_is_init (const method_t *method)
uint32_t method_get_code_length (const method_t *method)
bool method_compare (const method_t *method1, const method_t *method2)
void method_link_native (method_t *method, char *class_name)
void method_purge (method_t *method)
Variables
uint8_t halt_method_code [] = { WIDE, HALT, WIDE, HALT }
exception_handler_t halt_exception_handler
method_t halt_method
static uint8_t abstract_method_code [] = { WIDE, METHOD_ABSTRACT }
static uint8_t load_method_code [] = { WIDE, METHOD_LOAD }
static uint8_t native_method_code [] = { WIDE, INVOKE_NATIVE }
Detailed Description
Method handling implementation
Definition in file method.c.
Function Documentation
void init_dummy_methods (void)
Initializes the dummy methods used by the interpreter
Definition at line 85 of file method.c.
References bcl_resolve_class(), exception_handler_t::catch_type, method_t::cp, cp_create_dummy(), method_t::data, and method_t::handlers.
Referenced by vm_run().
static void method_check_access_flags (method_t * method) [static]
Checks the access flags of a method
Parameters
method The method to be checked
Definition at line 281 of file method.c.
References ACC_ABSTRACT, ACC_FINAL, ACC_NATIVE, ACC_PRIVATE, ACC_PROTECTED, ACC_PUBLIC, ACC_STATIC, ACC_STRICT, ACC_SYNCHRONIZED, method_t::access_flags, class_t::access_flags, c_throw, JAVA_LANG_NOCLASSDEFFOUNDERROR, and method_is_init().
Referenced by mm_add().
bool method_compare (const method_t * method1, const method_t * method2)
Compares two methods signatures
Parameters
method1 A pointer to a method structure
method2 A pointer to a method structure
Returns
true if the method signatures match, false otherwise
Definition at line 461 of file method.c.
References method_t::descriptor, and method_t::name.
Referenced by create_dispatch_table(), and create_interface_dispatch_table().
uint16_t method_create_packed_index (const method_t * method)
Creates the packed index of a method
Parameters
method A pointer to a method
Returns
The packed index
Definition at line 423 of file method.c.
References method_t::args_size, method_t::index, and METHOD_ARGUMENTS_BITS.
Referenced by bcl_link_opcode().
uint32_t method_get_code_length (const method_t * method)
Gets the length of a method code, the length is automatically adjusted if extra opcodes were added by the translator
Parameters
method A pointer to a method structure
Returns
The length of the bytecode in bytes
Definition at line 447 of file method.c.
References method_t::code_length, and method_is_synchronized().
Referenced by load_bytecode(), and translate_bytecode().
bool method_is_init (const method_t * method)
Returns true if the method is an initialization method
Parameters
method A pointer to a method
Returns
true if an initialization method was passed to the function, false otherwise
Definition at line 433 of file method.c.
References method_t::name.
Referenced by bcl_link_opcode(), create_dispatch_table(), method_check_access_flags(), and resolve_method().
void method_link_native (method_t * method, char * class_name)
Link a native method
Parameters
method A pointer to the method
class_name The name of the class the method belongs to
Definition at line 476 of file method.c.
References method_t::access_flags, c_throw, method_t::code, method_t::data, dbg_unreachable, method_t::descriptor, method_t::function, JAVA_LANG_NOCLASSDEFFOUNDERROR, method_t::name, native_method_code, native_method_lookup(), and method_t::return_type.
Referenced by load_methods().
void method_purge (method_t * method)
Frees the code and exception handlers of a method
Parameters
method A pointer to the method
Definition at line 516 of file method.c.
References method_t::code, method_t::data, gc_free(), and method_t::handlers.
Referenced by class_purge_initializer().
void mm_add (method_manager_t * mm, char * name, char * descriptor, uint16_t access_flags, const_pool_t * cp, method_attributes_t * attr)
Adds a new method to the method manager
Parameters
mm The method manager
name The method name
descriptor The method descriptor
access_flags Access flags of the method
cp The method's constant pool
attr The method attributes
Definition at line 324 of file method.c.
References abstract_method_code, ACC_ABSTRACT, ACC_NATIVE, method_t::access_flags, c_throw, method_t::code, method_attributes_t::code_found, method_attributes_t::code_length, method_t::code_length, method_attributes_t::code_offset, method_t::cp, method_t::data, method_t::descriptor, method_manager_t::entries, method_attributes_t::exception_table_length, method_t::exception_table_length, method_t::handlers, JAVA_LANG_NOCLASSDEFFOUNDERROR, load_method_code, method_attributes_t::max_locals, method_t::max_locals, method_attributes_t::max_stack, method_t::max_stack, method_check_access_flags(), method_manager_t::methods, mm_get(), method_t::name, method_t::offset, parse_method_descriptor(), and method_manager_t::reserved.
Referenced by load_methods().
method_manager_t* mm_create (uint32_t count)
Creates a method manager
Parameters
count The number of methods the manager will hold
Returns
A pointer to the newly created method manager
Definition at line 98 of file method.c.
References gc_palloc(), method_manager_t::methods, and method_manager_t::reserved.
Referenced by load_methods().
method_t* mm_get (method_manager_t * mm, char * name, char * descriptor)
Finds a method by its name and descriptor, returns NULL if the method is not found
Parameters
mm A pointer to the method manager
name The method name
descriptor The method descriptor
Returns
A pointer to the method if it was found, NULL otherwise
Definition at line 397 of file method.c.
References method_t::descriptor, method_manager_t::entries, method_manager_t::methods, and method_t::name.
Referenced by class_purge_initializer(), initialize_class(), java_lang_Class_newInstance(), java_lang_Thread_start(), mm_add(), resolve_method(), and vm_run().
uint32_t mm_get_count (method_manager_t * mm)
Returns the number of methods in the manager
Parameters
mm A pointer to the method manager
Returns
The number of methods in the manager
Definition at line 414 of file method.c.
References method_manager_t::entries.
Referenced by create_interface_dispatch_table().
static void parse_method_descriptor (method_t * method) [static]
Parses a method's descriptor, throws an exception upon failure
Parameters
method A pointer to the relevant method
Definition at line 113 of file method.c.
References method_t::args_size, c_throw, method_t::descriptor, class_t::dimensions, JAVA_LANG_NOCLASSDEFFOUNDERROR, METHOD_ARGUMENTS_MAX, and method_is_static().
Referenced by mm_add().
Variable Documentation
uint8_t abstract_method_code[] = { WIDE, METHOD_ABSTRACT } [static]
Holds the dummy code of an abstract method
Definition at line 71 of file method.c.
Referenced by mm_add().
exception_handler_t halt_exception_handler
Initial value:
 
    0,
    4,
    halt_method_code,
    NULL
Dummy exception handler used by the halt method
Definition at line 45 of file method.c.
method_t halt_method
Initial value:
 
    "halt_method",
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    RET_VOID,
    4,
    1,
    halt_method_code,
     NULL
Halt method structure
Definition at line 54 of file method.c.
Referenced by interpreter(), and prepare_for_call().
uint8_t halt_method_code[] = { WIDE, HALT, WIDE, HALT }
Dummy variable used to hold the halt method's bytecode
Definition at line 41 of file method.c.
uint8_t load_method_code[] = { WIDE, METHOD_LOAD } [static]
Holds the dummy code of a not-yet-linked method
Definition at line 74 of file method.c.
Referenced by mm_add().
uint8_t native_method_code[] = { WIDE, INVOKE_NATIVE } [static]
Holds the dummy code of a native method
Definition at line 77 of file method.c.
Referenced by method_link_native().