src/jelatine/utf8_string.c File Reference
#include `wrappers.h`
#include `memory.h`
#include `thread.h`
#include `utf8_string.h`
#include `util.h`
#include `vm.h`
Data Structures
struct utf8_string_t
struct string_manager_t
Typedefs
typedef struct utf8_string_t utf8_string_t
typedef struct string_manager_t string_manager_t
Functions
static void string_manager_rehash (size_t)
static uint32_t utf8_hash (const char *, size_t)
void string_manager_init (size_t log2cap, size_t load)
bool utf8_check (const char *src)
char * utf8_intern (const char *src, size_t len)
size_t utf8_to_java_length (const char *str)
void utf8_to_java (uint16_t *dst, const char *src)
char * java_to_utf8 (const uint16_t *data, size_t length)
char * utf8_slashify (char *src)
size_t string_manager_size (void)
void string_manager_print (void)
Variables
static string_manager_t sm
Detailed Description
UTF8 string manager implementation
Definition in file utf8_string.c.
Typedef Documentation
typedef struct string_manager_t string_manager_t
Typedef for the struct string_manager_t
Definition at line 65 of file utf8_string.c.
typedef struct utf8_string_t utf8_string_t
Typedef for struct utf8_string_t
Definition at line 52 of file utf8_string.c.
Function Documentation
char* java_to_utf8 (const uint16_t * data, size_t length)
Converts a Java string into an UTF-8 string.
Parameters
data The string's data
length The string length
Returns
A newly created UTF-8 string allocated from the memory heap
Definition at line 313 of file utf8_string.c.
References gc_malloc().
Referenced by java_lang_Class_forName().
void string_manager_init (size_t log2cap, size_t load)
Creates and initializes the string manager with an initial capacity of 2^(log2cap) entries and load load
Parameters
log2cap The binary logarythm of the initial capacity
load The allowed load on the manager
Definition at line 90 of file utf8_string.c.
References string_manager_t::buckets, string_manager_t::capacity, string_manager_t::entries, gc_malloc(), string_manager_t::load, and string_manager_t::threshold.
Referenced by vm_init().
void string_manager_print (void)
Prints out the contents of the UTF8 string manager
Definition at line 414 of file utf8_string.c.
References string_manager_t::buckets, string_manager_t::capacity, utf8_string_t::data, string_manager_t::entries, string_manager_t::load, utf8_string_t::next, and string_manager_t::threshold.
static void string_manager_rehash (size_t capacity) [static]
Rehashes the string manager pointed by sm
Parameters
capacity The new capacity
Definition at line 107 of file utf8_string.c.
References string_manager_t::buckets, string_manager_t::capacity, utf8_string_t::data, gc_free(), gc_malloc(), utf8_string_t::next, and utf8_hash().
Referenced by utf8_intern().
size_t string_manager_size (void)
Prints the total memory consumption of the UTF8 string manager
Definition at line 390 of file utf8_string.c.
References string_manager_t::buckets, string_manager_t::capacity, utf8_string_t::data, utf8_string_t::next, and size_ceil().
bool utf8_check (const char * src)
Checks if a string in the Java class file modified UTF8 format is valid, i.e. checks if the length of the string matches the given one and that the string doesn't contain invalid characters
Parameters
src A pointer to the string to be checked
Returns
True if the string is valid, false otherwise
Definition at line 145 of file utf8_string.c.
Referenced by cp_create(), jstring_create_from_utf8(), jstring_create_literal(), and vm_run().
static uint32_t utf8_hash (const char * data, size_t len) [static]
Calculates the hash value of an UTF-8 string
Parameters
data The string's data
len The number of characters in the string
Definition at line 375 of file utf8_string.c.
Referenced by string_manager_rehash(), and utf8_intern().
char* utf8_intern (const char * src, size_t len)
Interns a string in the UTF8 format in the string manager and returns a pointer to the interned string.
Empty strings may be interned by specifying a NULL pointer for src and a 0 value for len. Strings in the Java class file modified format are treated as plain UTF8 strings.
Parameters
src A pointer to an array of bytes, may be NULL
len The string length
Returns
A pointer to the newly created string
Definition at line 201 of file utf8_string.c.
References string_manager_t::buckets, string_manager_t::capacity, utf8_string_t::data, string_manager_t::entries, gc_palloc(), string_manager_t::load, utf8_string_t::next, string_manager_rehash(), tm_lock(), tm_unlock(), and utf8_hash().
Referenced by bcl_resolve_class(), cp_create(), preload_class(), and vm_run().
char* utf8_slashify (char * src)
Turns a class or package name in the classfile internal format
Parameters
src The source string
Returns
The pointer passed to this function
Definition at line 358 of file utf8_string.c.
Referenced by java_lang_Class_forName().
void utf8_to_java (uint16_t * dst, const char * src)
Converts a string in the Java class file modified UTF8 format into a Java string. The java chars of the resulting string are written in dst.
Parameters
dst A pointer to an array of Java chars
src A pointer to a string in the Java class file modified UTF8 format
Definition at line 279 of file utf8_string.c.
Referenced by jstring_create_from_utf8(), and jstring_create_literal().
size_t utf8_to_java_length (const char * str)
Calculates the length of a string in the Java class file modified UTF8 format when converted to its Java representation. The functions excepts the source string to be valid.
Parameters
str A pointer to a string in the Java class file modified UTF8 format
Returns
The length of the string once converted
Definition at line 251 of file utf8_string.c.
Referenced by jstring_create_from_utf8(), and jstring_create_literal().
Variable Documentation
string_manager_t sm [static]
Global string manager
Definition at line 72 of file utf8_string.c.