src/jelatine/vm.c File Reference
#include `wrappers.h`
#include `class.h`
#include `jstring.h`
#include `interpreter.h`
#include `loader.h`
#include `memory.h`
#include `method.h`
#include `thread.h`
#include `utf8_string.h`
#include `util.h`
#include `vm.h`
#include `java_lang_Thread.h`
Data Structures
struct virtual_machine_t
Typedefs
typedef struct virtual_machine_t virtual_machine_t
Functions
static void vm_init (void)
static void vm_teardown (void)
void vm_run (void)
Variables
options_t options
virtual_machine_t vm
Detailed Description
Virtual machine object implementation
Definition in file vm.c.
Typedef Documentation
typedef struct virtual_machine_t virtual_machine_t
Typedef for the struct virtual_machine_t
Definition at line 58 of file vm.c.
Function Documentation
static void vm_init (void) [static]
Initializes the basic subsystems of the virtual machine
Definition at line 229 of file vm.c.
References bcl_init(), classpath_init(), gc_init(), jsm_init(), monitor_init(), opts_get_heap_size(), and string_manager_init().
Referenced by vm_run().
void vm_run (void)
Launches the JVM
Definition at line 106 of file vm.c.
References method_t::access_flags, array_ref_get_data(), bcl_preload_bootstrap_classes(), bcl_resolve_class(), c_catch, c_throw, c_try, thread_t::capacity, gc_enable(), gc_malloc(), gc_new(), gc_new_array_ref(), init_dummy_methods(), JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_STRING_PTR2REF, JAVA_LANG_THREAD_REF2PTR, JAVA_LANG_VIRTUALMACHINEERROR, jstring_create_literal(), method_is_native(), method_is_public(), method_is_static(), class_t::method_manager, mm_get(), opts_get_jargs(), opts_get_jargs_n(), opts_get_main_class(), thread_t::pointers, thread_t::roots, thread_create_main(), thread_init(), thread_launch(), thread_pop_root(), thread_push_root(), THREAD_TMP_ROOTS, tm_init(), tm_register(), tm_teardown(), utf8_check(), utf8_intern(), vm_fail(), vm_init(), and vm_teardown().
static void vm_teardown (void) [static]
Destroys the virtual machine instance
Definition at line 245 of file vm.c.
References classpath_teardown(), and gc_teardown().
Referenced by vm_run().
Variable Documentation
options_t options
Initial value:
 
    ".",
    JEL_CLASSPATH_DIR,
    128 * 1024,
    4096,
    NULL,
    NULL,
    0,
 
 
    false,
    false
Global options of the VM
Definition at line 66 of file vm.c.
Referenced by opts_get_boot_classpath(), opts_get_classpath(), opts_get_heap_size(), opts_get_help(), opts_get_jargs(), opts_get_jargs_n(), opts_get_main_class(), opts_get_stack_size(), opts_get_version(), opts_set_boot_classpath(), opts_set_classpath(), opts_set_heap_size(), opts_set_help(), opts_set_jargs(), opts_set_jargs_n(), opts_set_main_class(), opts_set_stack_size(), and opts_set_version().
virtual_machine_t vm
Global virtual-machine pointer
Definition at line 91 of file vm.c.