/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShowMessage */

#ifndef _Included_ShowMessage
#define _Included_ShowMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShowMessage
 * Method:    ShowMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ShowMessage_ShowMessage__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ShowMessage
 * Method:    ShowMessage
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ShowMessage_ShowMessage__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ShowMessage
 * Method:    ShowMessage
 * Signature: (Ljava/lang/String;IJ)V
 */
JNIEXPORT void JNICALL Java_ShowMessage_ShowMessage__Ljava_lang_String_2IJ
  (JNIEnv *, jclass, jstring, jint, jlong);

/*
 * Class:     ShowMessage
 * Method:    print
 * Signature: (Ljava/lang/String;IJ)V
 */
JNIEXPORT void JNICALL Java_ShowMessage_print
  (JNIEnv *, jobject, jstring, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
