# Generated automatically from Makefile.in by configure.
# Testing
#
# Copyright (c) 1996 Systems Architecture Research Centre,
#		   City University, London, UK.
#
# See the file "license.terms" for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
# Written by Tim Wilkinson <tim@sarc.city.ac.uk>, March 1996.

all:

test:
		@echo "Testing not current supported."

clean:

distclean:
		rm -f Makefile

install:
