//Base of this source been was generated by jni_interfaces_generator.py

#include "wrappers.h"

#include "interpreter.h"
#include "jstring.h"
#include "kni.h"
#include "loader.h"
#include "native.h"
#include "thread.h"
#include "utf8_string.h"
#include "util.h"
#include "vm.h"

#include "java_lang_String.h"
#include "java_lang_Thread.h"

	
#include "native_exts/lejos_nxj_ext.h"

#include "native_exts/nxj_font.c"
#include "native_exts/sdl_shared.c"
//from NXT "poll.[h & c]"

#define MAX_EVENTS 16
//#define WAITING 1
#define SET 2
#define SYSTEM_EVENT 7
#define SHUTDOWN 1
NXTEvent *events[MAX_EVENTS];
int eventCnt;
jint no_event(jint filter) { return 0; }
jint buttons_check_event(jint filter) {
	jint ret=lejos_nxt_Button_getButtons();
	return ret;
	return 0; 
}
static jint (* const eventCheckers[])(jint) = 
{
	no_event, //None=0
	NULL,//bt_event_check,//	BLUETOOTH=1 
	NULL,//udp_event_check, //USB=2
	NULL, //RS485=3
	NULL,//sp_check_event, //ANALOG_PORTS=4
	NULL,//i2c_event_check, //I2C_PORTS=5
	NULL,//buttons_check_event, //BUTTONS=6
	no_event
};

/**
 * Initialize the event system. At startup we are not monitoring for any events.
 */
void init_events()
{
  int i;
  for(i = 0; i < MAX_EVENTS; i++)
    events[i] = NULL;
  eventCnt = 0;
}

/**
 * register a new event object. After this the system will check for these
 * events, and notify the Java code if any fire.
 */
int register_event(NXTEvent *event)
{
  if (eventCnt >= MAX_EVENTS) return -1;
  events[eventCnt++] = event;
  return 1;
}

/**
 * remove an event object from being monitored. Following this the event will
 * no longer be checked by the system.
 */
int unregister_event(NXTEvent *event)
{
  int i;
  for(i = 0; i < eventCnt; i++)
    if (events[i] == event)
    {
      while(++i < eventCnt)
        events[i-1] = events[i];
      eventCnt--;
      return 1;
    }
  return -1;
}

/**
 * set and/or clear events.
 */
 #if 0
int change_event(NXTEvent *event, JINT set, JINT clear)
{
  event->userEvents &= ~clear;
  event->userEvents |= set;
  // deliver event now if it matches the filter and someone is waiting
  set &= event->filter;
  if (set && event->sync->state == WAITING && get_monitor_count(&(event->sync->_super.sync)) == 0)
  {
    event->eventData |= set;
    event->sync->state |= SET;
    monitor_notify_unchecked(&event->sync->_super, 1);
    schedule_request(REQUEST_SWITCH_THREAD);
  }
  return event->userEvents;
}
#endif

/**
 * Check all active event objects. If an event is detected, notify the 
 * associated waiting Java thread.
 */
void check_events()
{
  int i;
  for(i = 0; i < eventCnt; i++)
  {
    NXTEvent *event = events[i];
    NXTEvent *sync = event->sync;
    // Is this event being waited on, and has the event check period expired?
    if (sync->state != 0 && (--event->updateCnt <= 0)//&& get_monitor_count(&(sync->_super.sync)) == 0
		)
    {
      // Check to see if we have anything of interest
      int changed = ((*(eventCheckers[event->typ]))(event->filter) | event->userEvents | event->eventData) & event->filter;
      event->eventData |= changed;
      // notify the user thread
      if (changed && (sync->state == NXT_EVENT_WAITING))
      { 
        // Don't notify this thread again.
        sync->state |= SET;
        //monitor_notify_unchecked(&sync->_super, 1);
        //schedule_request(REQUEST_SWITCH_THREAD);
      }
      // Reste the check period counter
      event->updateCnt = event->updatePeriod;
    }
  }
}

void dump_nxt_event(NXTEvent* event)
{
	printf("\nNXTEvent={\nsync=0x%x",event->sync);
	printf("\nheader=0x%x",event->header);
	printf("\nstate=0x%x",event->state);
	printf("\nupdatePeriod=0x%x",event->updatePeriod);
	printf("\nupdateCnt=0x%x",event->updateCnt);
	printf("\ntyp=0x%x",event->typ);
	printf("\nfilter=0x%x",event->filter);
	printf("\neventData=0x%x",event->eventData);
	printf("\nuserEvents=0x%x}\n",event->userEvents);
}
//JNIFunc={  static long java/lang/Double:: doubleToRawLongBits (double d);}
//public static native long doubleToRawLongBits(double d)
KNI_RETURNTYPE_LONG java_lang_Double_doubleToRawLongBits(void)
{
	jlong ret;
	jdouble d;
	d=KNI_GetParameterAsDouble(1);

	fprintf(stdout,"\nIn java_lang_Double_doubleToRawLongBits!");
	
	KNI_ReturnLong(ret);

}
//JNIFunc={  static double java/lang/Double:: longBitsToDouble (long l);}
//public static native double longBitsToDouble(long l)
KNI_RETURNTYPE_DOUBLE java_lang_Double_longBitsToDouble(void)
{
	jdouble ret;
	jlong l;
	l=KNI_GetParameterAsLong(1);

	fprintf(stdout,"\nIn java_lang_Double_longBitsToDouble!");
	
	KNI_ReturnDouble(ret);

}
//JNIFunc={  static int java/lang/Float:: floatToRawIntBits (float value);}
//public static native int floatToRawIntBits(float value)
KNI_RETURNTYPE_INT java_lang_Float_floatToRawIntBits(void)
{
	jint ret;
	jfloat value;
	value=KNI_GetParameterAsFloat(1);

	fprintf(stdout,"\nIn java_lang_Float_floatToRawIntBits!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static float java/lang/Float:: intBitsToFloat (int value);}
//public static native float intBitsToFloat(int value)
KNI_RETURNTYPE_FLOAT java_lang_Float_intBitsToFloat(void)
{
	jfloat ret;
	jint value;
	value=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn java_lang_Float_intBitsToFloat!");
	
	KNI_ReturnFloat(ret);

}
//JNIFunc={  static Object java/lang/Object:: cloneObject (Object old);}
//private static final native Object cloneObject(Object old)
KNI_RETURNTYPE_OBJECT java_lang_Object_cloneObject(void)
{
	KNI_StartHandles(2);
	KNI_DeclareHandle(obj_ref);
	
	KNI_DeclareHandle(old);
	KNI_GetParameterAsObject(1,old);

	fprintf(stdout,"\nIn java_lang_Object_cloneObject!");
	//
	KNI_EndHandlesAndReturnObject(obj_ref);
}
//JNIFunc={  void java/lang/Object:: notify ();}
//public final native void notify()
KNI_RETURNTYPE_VOID java_lang_Object_notify(void)
{
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Object_notify!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  void java/lang/Object:: notifyAll ();}
//public final native void notifyAll()
KNI_RETURNTYPE_VOID java_lang_Object_notifyAll(void)
{
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Object_notifyAll!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  void java/lang/Object:: wait ();}
//public final native void wait() throws InterruptedException
KNI_RETURNTYPE_VOID java_lang_Object_wait(void)
{
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Object_wait!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  void java/lang/Object:: wait (long timeout);}
//public final native void wait(long timeout) throws InterruptedException
KNI_RETURNTYPE_VOID java_lang_Object_wait2(void)
{
	jlong timeout;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);
	timeout=KNI_GetParameterAsLong(1);

	fprintf(stdout,"\nIn java_lang_Object_wait!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  long java/lang/Runtime:: freeMemory ();}
//public native long freeMemory()
KNI_RETURNTYPE_LONG java_lang_Runtime_freeMemory(void)
{
	jlong ret;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Runtime_freeMemory!");
	KNI_EndHandles();
	
	KNI_ReturnLong(ret);

}
//JNIFunc={  long java/lang/Runtime:: totalMemory ();}
//public native long totalMemory()
KNI_RETURNTYPE_LONG java_lang_Runtime_totalMemory(void)
{
	jlong ret;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Runtime_totalMemory!");
	KNI_EndHandles();
	
	KNI_ReturnLong(ret);

}
//JNIFunc={  static void java/lang/Shutdown:: halt (int code);}
//public static native void halt(int code)
KNI_RETURNTYPE_VOID java_lang_Shutdown_halt(void)
{
	jint code;
	code=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn java_lang_Shutdown_halt!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void java/lang/Shutdown:: shutdown ();}
//private static native void shutdown()
KNI_RETURNTYPE_VOID java_lang_Shutdown_shutdown(void)
{

	fprintf(stdout,"\nIn java_lang_Shutdown_shutdown!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void java/lang/System:: arraycopy (Object src,int srcOffset,Object dest,int destOffset,int length);}
//public static native void arraycopy (Object src, int srcOffset, Object dest, int destOffset, int length)
KNI_RETURNTYPE_VOID java_lang_System_arraycopy(void)
{
	jint srcOffset;
	jint destOffset;
	jint length;
	KNI_StartHandles(2);
	
	KNI_DeclareHandle(src);
	
	KNI_DeclareHandle(dest);
	KNI_GetParameterAsObject(1,src);
	srcOffset=KNI_GetParameterAsInt(2);
	KNI_GetParameterAsObject(3,dest);
	destOffset=KNI_GetParameterAsInt(4);
	length=KNI_GetParameterAsInt(5);

	fprintf(stdout,"\nIn java_lang_System_arraycopy!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static long java/lang/System:: currentTimeMillis ();}
//public static native long currentTimeMillis()
KNI_RETURNTYPE_LONG java_lang_System_currentTimeMillis(void)
{
	jlong ret;

	fprintf(stdout,"\nIn java_lang_System_currentTimeMillis!");
	
	KNI_ReturnLong(ret);

}
//JNIFunc={  static int java/lang/System:: getDataAddress (Object obj);}
//private native static int getDataAddress (Object obj)
KNI_RETURNTYPE_INT java_lang_System_getDataAddress(void)
{
	jint ret;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(obj);
	KNI_GetParameterAsObject(1,obj);

	fprintf(stdout,"\nIn java_lang_System_getDataAddress!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void java/lang/System:: gc ();}
//public static native void gc()
KNI_RETURNTYPE_VOID java_lang_System_gc(void)
{

	fprintf(stdout,"\nIn java_lang_System_gc!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static long java/lang/System:: nanoTime ();}
//public static native long nanoTime()
KNI_RETURNTYPE_LONG java_lang_System_nanoTime(void)
{
	jlong ret;

	fprintf(stdout,"\nIn java_lang_System_nanoTime!");
	
	KNI_ReturnLong(ret);

}
//JNIFunc={  void java/lang/Thread:: start ();}
//public final native void start()
KNI_RETURNTYPE_VOID java_lang_Thread_start(void)
{
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Thread_start!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void java/lang/Thread:: yield ();}
//public static native void yield()
KNI_RETURNTYPE_VOID java_lang_Thread_yield(void)
{

	fprintf(stdout,"\nIn java_lang_Thread_yield!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void java/lang/Thread:: sleep (long aMilliseconds);}
//public static native void sleep (long aMilliseconds) throws InterruptedException
KNI_RETURNTYPE_VOID java_lang_Thread_sleep(void)
{
	jlong aMilliseconds;
	aMilliseconds=KNI_GetParameterAsLong(1);

	fprintf(stdout,"\nIn java_lang_Thread_sleep!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static Thread java/lang/Thread:: currentThread ();}
//public static native Thread currentThread()
KNI_RETURNTYPE_OBJECT java_lang_Thread_currentThread(void)
{
	KNI_StartHandles(1);
	KNI_DeclareHandle(thread_ref);

	fprintf(stdout,"\nIn java_lang_Thread_currentThread!");
	KNI_EndHandlesAndReturnObject(thread_ref);
}
//JNIFunc={  int java/lang/Thread:: getPriority ();}
//public final native int getPriority()
KNI_RETURNTYPE_INT java_lang_Thread_getPriority(void)
{
	jint ret;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Thread_getPriority!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  void java/lang/Thread:: setPriority (int priority);}
//public final native void setPriority(int priority)
KNI_RETURNTYPE_VOID java_lang_Thread_setPriority(void)
{
	jint priority;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);
	priority=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn java_lang_Thread_setPriority!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  void java/lang/Thread:: interrupt ();}
//public native void interrupt()
KNI_RETURNTYPE_VOID java_lang_Thread_interrupt(void)
{
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Thread_interrupt!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static boolean java/lang/Thread:: interrupted ();}
//public static native boolean interrupted()
KNI_RETURNTYPE_BOOLEAN java_lang_Thread_interrupted(void)
{
	jboolean ret;

	fprintf(stdout,"\nIn java_lang_Thread_interrupted!");
	
	KNI_ReturnBoolean(ret);

}
//JNIFunc={  boolean java/lang/Thread:: isInterrupted ();}
//public final native boolean isInterrupted()
KNI_RETURNTYPE_BOOLEAN java_lang_Thread_isInterrupted(void)
{
	jboolean ret;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Thread_isInterrupted!");
	KNI_EndHandles();
	
	KNI_ReturnBoolean(ret);

}
//JNIFunc={  boolean java/lang/Thread:: isDaemon ();}
//public final native boolean isDaemon()
KNI_RETURNTYPE_BOOLEAN java_lang_Thread_isDaemon(void)
{
	jboolean ret;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Thread_isDaemon!");
	KNI_EndHandles();
	
	KNI_ReturnBoolean(ret);

}
//JNIFunc={  void java/lang/Thread:: setDaemon (boolean on);}
//public final native void setDaemon(boolean on)
KNI_RETURNTYPE_VOID java_lang_Thread_setDaemon(void)
{
	jboolean on;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);
	on=KNI_GetParameterAsBoolean(1);

	fprintf(stdout,"\nIn java_lang_Thread_setDaemon!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  void java/lang/Thread:: join ();}
//public final native void join() throws InterruptedException
KNI_RETURNTYPE_VOID java_lang_Thread_join0(void)
{
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn java_lang_Thread_join!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  void java/lang/Thread:: join (long timeout);}
//public final native void join(long timeout) throws InterruptedException
KNI_RETURNTYPE_VOID java_lang_Thread_join1(void)
{
	jlong timeout;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);
	timeout=KNI_GetParameterAsLong(1);

	fprintf(stdout,"\nIn java_lang_Thread_join!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void java/lang/Thread:: exitThread ();}
//private final static native void exitThread()
KNI_RETURNTYPE_VOID java_lang_Thread_exitThread(void)
{

	fprintf(stdout,"\nIn java_lang_Thread_exitThread!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/Battery:: getBatteryStatus ();}
//private static native int getBatteryStatus()
KNI_RETURNTYPE_INT lejos_nxt_Battery_getBatteryStatus(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_Battery_getBatteryStatus!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/Button:: getButtons ();}
//private static native int getButtons()
KNI_RETURNTYPE_INT lejos_nxt_Button_getButtons(void)
{
	jint ret;
	SDL_Event event;
	fprintf(stdout,"\nIn lejos_nxt_Button_getButtons!");
	ret=0;
	if (sdl_is_init>=1){
		if (SDL_PollEvent(&event)){
			switch(event.type){
				case SDL_KEYDOWN:
					switch(event.key.keysym.sym//scancode
							)
					{
						case SDLK_a:
						case SDLK_LEFT:
							ret=ID_LEFT;
							break;
						case SDLK_d:
						case SDLK_RIGHT:
							ret=ID_RIGHT;
							break;
						case SDLK_RETURN:
							ret=ID_ENTER;
							break;
						case SDLK_ESCAPE:
							ret=ID_ESCAPE;
							break;
						
					}
				break;
			}
		}
	}
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/Flash:: flashReadPage (byte[] buf,int pageNum);}
//static native int flashReadPage(byte[] buf, int pageNum)
KNI_RETURNTYPE_INT lejos_nxt_Flash_flashReadPage(void)
{
	jint ret;
	jint pageNum;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);
	pageNum=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_Flash_flashReadPage!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/Flash:: flashWritePage (byte[] buf,int pageNum);}
//static native int flashWritePage(byte[] buf, int pageNum)
KNI_RETURNTYPE_INT lejos_nxt_Flash_flashWritePage(void)
{
	jint ret;
	jint pageNum;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);
	pageNum=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_Flash_flashWritePage!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/Flash:: flashExec (int pageNum,int size);}
//static native int flashExec(int pageNum, int size)
KNI_RETURNTYPE_INT lejos_nxt_Flash_flashExec(void)
{
	jint ret;
	jint pageNum;
	jint size;
	pageNum=KNI_GetParameterAsInt(1);
	size=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_Flash_flashExec!");
	
	KNI_ReturnInt(ret);

}

static header_t display_font_cont=0;
static jobject display_font_bytes=&display_font_cont;//[2]={ NULL,NULL};

static header_t display_ram_cont=0;

static jobject display_ram_bytes=&display_ram_cont;

//JNIFunc={  static void lejos/nxt/LCD:: drawString (String str,int x,int y);}
//public static native void drawString(String str, int x, int y)
KNI_RETURNTYPE_VOID lejos_nxt_LCD_drawString(void)
{
	jint x;
	jint y;
	java_lang_String_t *c_obj_str;
	array_t * array;

	KNI_StartHandles(1);
	
	KNI_DeclareHandle(str);
	KNI_GetParameterAsObject(1,str);
	x=KNI_GetParameterAsInt(2);
	y=KNI_GetParameterAsInt(3);
	fprintf(stdout,"\nIn lejos_nxt_LCD_drawString!");
	
	c_obj_str = JAVA_LANG_STRING_REF2PTR(*str);
	if (c_obj_str && c_obj_str->value){
		int cx,cy;
		cx=x*6;
		cy=y*8;
		wchar_t *data=array_get_data(c_obj_str->value);
		
		for (int i=0;i<c_obj_str->count;i++){
			putchar(data[i]);
			nxj_draw_char((unsigned char)data[i],cx,cy);
			cx+=6;
		}
	}
	fprintf(stdout,"\nOK In lejos_nxt_LCD_drawString!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/LCD:: drawInt (int i,int x,int y);}
//public static native void drawInt(int i, int x, int y)
KNI_RETURNTYPE_VOID lejos_nxt_LCD_drawInt3(void)
{
	jint i;
	jint x;
	jint y;
	char buf[16];
	int ix;
	i=KNI_GetParameterAsInt(1);
	x=KNI_GetParameterAsInt(2);
	y=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_LCD_drawInt3!");
	sprintf(buf,"%i",i);
	y=y*8;
	x=x*6;
	for(ix=0;buf[ix]!=0;ix++){
		nxj_draw_char((unsigned char)buf[i],x,y);
		x+=6;
	}
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/LCD:: drawInt (int i,int places,int x,int y);}
//public static native void drawInt(int i, int places, int x, int y)
KNI_RETURNTYPE_VOID lejos_nxt_LCD_drawInt4(void)
{
	jint i;
	jint places;
	jint x;
	jint y;
	char buf[16];
	int ix;
	i=KNI_GetParameterAsInt(1);
	places=KNI_GetParameterAsInt(2);
	x=KNI_GetParameterAsInt(3);
	y=KNI_GetParameterAsInt(4);

	fprintf(stdout,"\nIn lejos_nxt_LCD_drawInt4!");
	//places???
	sprintf(buf,"%i",i);
	y=y*8;
	x=x*6;
	for(ix=0;buf[ix]!=0;ix++){
		nxj_draw_char((unsigned char)buf[i],x,y);
		x+=6;
	}
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/LCD:: asyncRefresh ();}
//public static native void asyncRefresh()
KNI_RETURNTYPE_VOID lejos_nxt_LCD_asyncRefresh(void)
{
	int ret;
	SDL_Rect rect={0,0,239,319};
	fprintf(stdout,"\nIn lejos_nxt_LCD_asyncRefresh!");
	//SDL_LockSurface(screen_surface);
	ret=SDL_BlitSurface(nxj_lcd_screen, &rect, screen_surface, &rect);
	if (ret!=0){
		fprintf(stderr,"\nError blit surface!ret=%i\nErrMsg:%s",ret,SDL_GetError());
	};
	//SDL_UnlockSurface(screen_surface);
	ret=SDL_Flip(screen_surface);
	//ret=SDL_Filp(nxj_lcd_screen);
	if (ret!=0){
		fprintf(stderr,"\nError flip main surface!ret=%i\nErrMsg:%s",ret,SDL_GetError());
	}
	KNI_ReturnVoid();
}

//JNIFunc={  static int lejos/nxt/LCD:: getRefreshCompleteTime ();}
//public static native int getRefreshCompleteTime()
KNI_RETURNTYPE_INT lejos_nxt_LCD_getRefreshCompleteTime(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_LCD_getRefreshCompleteTime!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/LCD:: clear ();}
//public static native void clear()
KNI_RETURNTYPE_VOID lejos_nxt_LCD_clear(void)
{

	fprintf(stdout,"\nIn lejos_nxt_LCD_clear!");
	//memset
	if (sdl_is_init>=2){
		SDL_Rect rect={0,0,239,319};
		SDL_LockSurface(nxj_lcd_screen);
		SDL_FillRect(nxj_lcd_screen,&rect,0);
		SDL_UnlockSurface(nxj_lcd_screen);
	};
	KNI_ReturnVoid();
}

//JNIFunc={  static byte[] lejos/nxt/LCD:: getDisplay ();}
//public static native byte[] getDisplay()
KNI_RETURNTYPE_OBJECT lejos_nxt_LCD_getDisplay(void)
{
	int i;
	KNI_StartHandles(1);
	KNI_DeclareHandle(byte_array_ref);
	
	fprintf(stdout,"\nIn lejos_nxt_LCD_getDisplay!");
	if (sdl_is_init<1) sdlg_init_nxj_screen();
	if (*display_ram_bytes==JNULL){
		*display_ram_bytes=gc_new_array_nonref(T_BYTE,(240*320)/8 //2048
		);
	}
	
	if (*display_ram_bytes){
		fprintf(stdout,"\nIn lejos_nxt_LCD_getDisplay!Ok Alloced");
		for (i=0;i<256;i++){
			//fprintf(stdout,"\ni:%i",i);
			*((char*)array_get_data((array_t*)*display_ram_bytes))=(char)i;
		}
		}
	*byte_array_ref=*display_ram_bytes;
	//return *display_ram_bytes;
	KNI_EndHandlesAndReturnObject(byte_array_ref);
}



//JNIFunc={  static byte[] lejos/nxt/LCD:: getSystemFont ();}
//public static native byte[] getSystemFont()


KNI_RETURNTYPE_OBJECT lejos_nxt_LCD_getSystemFont(void)
{
	int i;
	unsigned char *font_ptr,*font_ptr_dst;
	array_type_t byte_ar_type;
	KNI_StartHandles(1);
	KNI_DeclareHandle(byte_array_ref);
	fprintf(stdout,"\nIn lejos_nxt_LCD_getSystemFont!");
	//byte_ar_type=prim_to_array_type(T_BYTE);
	//void* ptr=*display_font;
	if (*display_font_bytes==JNULL)
	{
		*display_font_bytes=gc_new_array_nonref(T_BYTE,2048);
		//*display_font=malloc(sizeof(array_t)+512);
	}
	
	if (*display_font_bytes){
		fprintf(stdout,"\nIn lejos_nxt_LCD_getSystemFont!Ok Alloced");
		font_ptr=&nxj_font[0][0];
		font_ptr_dst=(unsigned char*)array_get_data((array_t*)*display_font_bytes);
		for (i=0;i>sizeof(nxj_font);i++){
			font_ptr_dst[i]=font_ptr[i];
			//*((char*))
			
		}
		/*
		for (i=0;i<256;i++){
			//fprintf(stdout,"\ni:%i",i);
			*((char*)array_get_data((array_t*)*display_font_bytes))=(char)i;
		}*/
	}
	*byte_array_ref=*display_font_bytes;
	//return *display_font_bytes;
	KNI_EndHandlesAndReturnObject(byte_array_ref);
}
//JNIFunc={  static int lejos/nxt/LCD:: setAutoRefreshPeriod (int period);}
//public static native int setAutoRefreshPeriod(int period)
KNI_RETURNTYPE_INT lejos_nxt_LCD_setAutoRefreshPeriod(void)
{
	jint ret;
	jint period;
	period=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_LCD_setAutoRefreshPeriod!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/LCD:: bitBlt (byte[] src,int sw,int sh,int sx,int sy,byte[] dst,int dw,int dh,int dx,int dy,int w,int h,int rop);}
//public native static void bitBlt(byte[] src, int sw, int sh, int sx, int sy, byte dst[], int dw, int dh, int dx, int dy, int w, int h, int rop)
KNI_RETURNTYPE_VOID lejos_nxt_LCD_bitBlt(void)
{
	jint sw;
	jint sh;
	jint sx;
	jint sy;
	jint dw;
	jint dh;
	jint dx;
	jint dy;
	jint w;
	jint h;
	jint rop;
	KNI_StartHandles(2);
	
	KNI_DeclareHandle(src);
	
	KNI_DeclareHandle(dst);
	KNI_GetParameterAsObject(1,src);
	sw=KNI_GetParameterAsInt(2);
	sh=KNI_GetParameterAsInt(3);
	sx=KNI_GetParameterAsInt(4);
	sy=KNI_GetParameterAsInt(5);
	KNI_GetParameterAsObject(6,dst);
	dw=KNI_GetParameterAsInt(7);
	dh=KNI_GetParameterAsInt(8);
	dx=KNI_GetParameterAsInt(9);
	dy=KNI_GetParameterAsInt(10);
	w=KNI_GetParameterAsInt(11);
	h=KNI_GetParameterAsInt(12);
	rop=KNI_GetParameterAsInt(13);

	fprintf(stdout,"\nIn lejos_nxt_LCD_bitBlt!");
	 nxj_blit_bits_to_array((array_t*)  src,
                          sw,
                          sh,
                          sx,
                          sy,
                         (array_t*)  dst,
						   dw,
                           dh,
                            dx,
                            dy,
                          w,
                          h,
                          rop,
						 ((*dst==*display_font_bytes)));
	if (*dst==*display_font_bytes){
		//need refresh
	}
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/LCD:: setContrast (int contrast);}
//public native static void setContrast(int contrast)
KNI_RETURNTYPE_VOID lejos_nxt_LCD_setContrast(void)
{
	jint contrast;
	contrast=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_LCD_setContrast!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/MotorPort:: controlMotorById (int id,int power,int mode);}
//private static synchronized native void controlMotorById(int id, int power, int mode)
KNI_RETURNTYPE_VOID lejos_nxt_MotorPort_controlMotorById(void)
{
	jint id;
	jint power;
	jint mode;
	id=KNI_GetParameterAsInt(1);
	power=KNI_GetParameterAsInt(2);
	mode=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_MotorPort_controlMotorById!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/MotorPort:: getTachoCountById (int aMotor);}
//private static native int getTachoCountById(int aMotor)
KNI_RETURNTYPE_INT lejos_nxt_MotorPort_getTachoCountById(void)
{
	jint ret;
	jint aMotor;
	aMotor=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_MotorPort_getTachoCountById!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/MotorPort:: resetTachoCountById (int aMotor);}
//private static synchronized native void resetTachoCountById(int aMotor)
KNI_RETURNTYPE_VOID lejos_nxt_MotorPort_resetTachoCountById(void)
{
	jint aMotor;
	aMotor=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_MotorPort_resetTachoCountById!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/NXT:: shutDown ();}
//public static native void shutDown()
KNI_RETURNTYPE_VOID lejos_nxt_NXT_shutDown(void)
{

	fprintf(stdout,"\nIn lejos_nxt_NXT_shutDown!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/NXT:: boot ();}
//public static native void boot()
KNI_RETURNTYPE_VOID lejos_nxt_NXT_boot(void)
{

	fprintf(stdout,"\nIn lejos_nxt_NXT_boot!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/NXT:: getProgramExecutionsCount ();}
//public static native int getProgramExecutionsCount()
KNI_RETURNTYPE_INT lejos_nxt_NXT_getProgramExecutionsCount(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_NXT_getProgramExecutionsCount!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/NXT:: getFirmwareRawVersion ();}
//public static native int getFirmwareRawVersion()
KNI_RETURNTYPE_INT lejos_nxt_NXT_getFirmwareRawVersion(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_NXT_getFirmwareRawVersion!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/NXT:: getFirmwareRevision ();}
//public static native int getFirmwareRevision()
KNI_RETURNTYPE_INT lejos_nxt_NXT_getFirmwareRevision(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_NXT_getFirmwareRevision!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/NXT:: getUserPages ();}
//public static native int getUserPages()
KNI_RETURNTYPE_INT lejos_nxt_NXT_getUserPages(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_NXT_getUserPages!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  int lejos/nxt/NXTEvent:: registerEvent ();}
//public native int registerEvent()
KNI_RETURNTYPE_INT lejos_nxt_NXTEvent_registerEvent(void)
{
	jint ret;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn lejos_nxt_NXTEvent_registerEvent!");
	NXTEvent*event=NXTEvent_REF2PTR(*this_ref);
	dump_nxt_event(event);
	register_event(event);
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  int lejos/nxt/NXTEvent:: unregisterEvent ();}
//public native int unregisterEvent()
KNI_RETURNTYPE_INT lejos_nxt_NXTEvent_unregisterEvent(void)
{
	jint ret;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn lejos_nxt_NXTEvent_unregisterEvent!");
	NXTEvent*event=NXTEvent_REF2PTR(*this_ref);
	dump_nxt_event(event);
	unregister_event(event);
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  int lejos/nxt/NXTEvent:: changeEvent (int set,int clear);}
//private native int changeEvent(int set, int clear)
KNI_RETURNTYPE_INT lejos_nxt_NXTEvent_changeEvent(void)
{
	jint ret;
	jint set;
	jint clear;
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);
	set=KNI_GetParameterAsInt(1);
	clear=KNI_GetParameterAsInt(2);

	//fprintf(stdout,"\nIn lejos_nxt_NXTEvent_changeEvent!");
	NXTEvent*event=NXTEvent_REF2PTR(*this_ref);
	//dump_nxt_event(event);
	event->userEvents &= ~clear;
	event->userEvents |= set;
	// deliver event now if it matches the filter and someone is waiting
	set &= event->filter;
	if (set && event->sync->state == NXT_EVENT_WAITING //&& get_monitor_count(&(event->sync->_super.sync)) == 0
		)
	{
		printf("\nFix me!require schedule_request(REQUEST_SWITCH_THREAD)!");
		event->eventData |= set;
		event->sync->state |= SET;
		//monitor_notify_unchecked(&event->sync->_super, 1);
		//schedule_request(REQUEST_SWITCH_THREAD);
	}
	ret=event->userEvents;
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/SensorPort:: readSensorValue (int aPortId);}
//private static native int readSensorValue(int aPortId)
KNI_RETURNTYPE_INT lejos_nxt_SensorPort_readSensorValue(void)
{
	jint ret;
	jint aPortId;
	aPortId=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_readSensorValue!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/SensorPort:: setPowerTypeById (int aPortId,int aPortType);}
//private static native void setPowerTypeById(int aPortId, int aPortType)
KNI_RETURNTYPE_VOID lejos_nxt_SensorPort_setPowerTypeById(void)
{
	jint aPortId;
	jint aPortType;
	aPortId=KNI_GetParameterAsInt(1);
	aPortType=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_setPowerTypeById!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/SensorPort:: i2cEnableById (int aPortId,int mode);}
//private static native void i2cEnableById(int aPortId, int mode)
KNI_RETURNTYPE_VOID lejos_nxt_SensorPort_i2cEnableById(void)
{
	jint aPortId;
	jint mode;
	aPortId=KNI_GetParameterAsInt(1);
	mode=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_i2cEnableById!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/SensorPort:: i2cDisableById (int aPortId);}
//private static native void i2cDisableById(int aPortId)
KNI_RETURNTYPE_VOID lejos_nxt_SensorPort_i2cDisableById(void)
{
	jint aPortId;
	aPortId=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_i2cDisableById!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/SensorPort:: i2cStatusById (int aPortId);}
//private static native int i2cStatusById(int aPortId)
KNI_RETURNTYPE_INT lejos_nxt_SensorPort_i2cStatusById(void)
{
	jint ret;
	jint aPortId;
	aPortId=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_i2cStatusById!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/SensorPort:: i2cStartById (int aPortId,int address,byte[] writeBuffer,int writeOffset,int writeLen,int readLen);}
//private static native int i2cStartById(int aPortId, int address,byte[] writeBuffer, int writeOffset, int writeLen, int readLen)
KNI_RETURNTYPE_INT lejos_nxt_SensorPort_i2cStartById(void)
{
	jint ret;
	jint aPortId;
	jint address;
	jint writeOffset;
	jint writeLen;
	jint readLen;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(writeBuffer);
	aPortId=KNI_GetParameterAsInt(1);
	address=KNI_GetParameterAsInt(2);
	KNI_GetParameterAsObject(3,writeBuffer);
	writeOffset=KNI_GetParameterAsInt(4);
	writeLen=KNI_GetParameterAsInt(5);
	readLen=KNI_GetParameterAsInt(6);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_i2cStartById!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/SensorPort:: i2cCompleteById (int aPortId,byte[] readBuffer,int offset,int readLen);}
//private static native int i2cCompleteById(int aPortId, byte[] readBuffer, int offset, int readLen)
KNI_RETURNTYPE_INT lejos_nxt_SensorPort_i2cCompleteById(void)
{
	jint ret;
	jint aPortId;
	jint offset;
	jint readLen;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(readBuffer);
	aPortId=KNI_GetParameterAsInt(1);
	KNI_GetParameterAsObject(2,readBuffer);
	offset=KNI_GetParameterAsInt(3);
	readLen=KNI_GetParameterAsInt(4);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_i2cCompleteById!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/SensorPort:: setSensorPinMode (int port,int pin,int mode);}
//private static native void setSensorPinMode(int port, int pin, int mode)
KNI_RETURNTYPE_VOID lejos_nxt_SensorPort_setSensorPinMode(void)
{
	jint port;
	jint pin;
	jint mode;
	port=KNI_GetParameterAsInt(1);
	pin=KNI_GetParameterAsInt(2);
	mode=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_setSensorPinMode!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/SensorPort:: setSensorPin (int port,int pin,int val);}
//private static native void setSensorPin(int port, int pin, int val)
KNI_RETURNTYPE_VOID lejos_nxt_SensorPort_setSensorPin(void)
{
	jint port;
	jint pin;
	jint val;
	port=KNI_GetParameterAsInt(1);
	pin=KNI_GetParameterAsInt(2);
	val=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_setSensorPin!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/SensorPort:: getSensorPin (int port,int pin);}
//private static native int getSensorPin(int port, int pin)
KNI_RETURNTYPE_INT lejos_nxt_SensorPort_getSensorPin(void)
{
	jint ret;
	jint port;
	jint pin;
	port=KNI_GetParameterAsInt(1);
	pin=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_getSensorPin!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/SensorPort:: readSensorPin (int port,int pin);}
//private static native int readSensorPin(int port, int pin)
KNI_RETURNTYPE_INT lejos_nxt_SensorPort_readSensorPin(void)
{
	jint ret;
	jint port;
	jint pin;
	port=KNI_GetParameterAsInt(1);
	pin=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_SensorPort_readSensorPin!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/Sound:: getTime ();}
//public static native int getTime()
KNI_RETURNTYPE_INT lejos_nxt_Sound_getTime(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_Sound_getTime!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/Sound:: playFreq (int aFrequency,int aDuration,int aVolume);}
//static native void playFreq(int aFrequency, int aDuration, int aVolume)
KNI_RETURNTYPE_VOID lejos_nxt_Sound_playFreq(void)
{
	jint aFrequency;
	jint aDuration;
	jint aVolume;
	aFrequency=KNI_GetParameterAsInt(1);
	aDuration=KNI_GetParameterAsInt(2);
	aVolume=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_Sound_playFreq!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/Sound:: playSample (int page,int offset,int len,int freq,int vol);}
//static native void playSample(int page, int offset, int len, int freq, int vol)
KNI_RETURNTYPE_VOID lejos_nxt_Sound_playSample(void)
{
	jint page;
	jint offset;
	jint len;
	jint freq;
	jint vol;
	page=KNI_GetParameterAsInt(1);
	offset=KNI_GetParameterAsInt(2);
	len=KNI_GetParameterAsInt(3);
	freq=KNI_GetParameterAsInt(4);
	vol=KNI_GetParameterAsInt(5);

	fprintf(stdout,"\nIn lejos_nxt_Sound_playSample!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/Sound:: playQueuedSample (byte[] ,int offset,int len,int freq,int vol);}
//static native int playQueuedSample(byte [] data, int offset, int len, int freq, int vol)
KNI_RETURNTYPE_INT lejos_nxt_Sound_playQueuedSample(void)
{
	jint ret;
	jint offset;
	jint len;
	jint freq;
	jint vol;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(data);
	KNI_GetParameterAsObject(1,data);
	offset=KNI_GetParameterAsInt(2);
	len=KNI_GetParameterAsInt(3);
	freq=KNI_GetParameterAsInt(4);
	vol=KNI_GetParameterAsInt(5);

	fprintf(stdout,"\nIn lejos_nxt_Sound_playQueuedSample!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/VM:: memPeek (int base,int offset,int typ);}
//private static native int memPeek(int base, int offset, int typ)
KNI_RETURNTYPE_INT lejos_nxt_VM_memPeek(void)
{
	jint ret;
	jint base;
	jint offset;
	jint typ;
	base=KNI_GetParameterAsInt(1);
	offset=KNI_GetParameterAsInt(2);
	typ=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_VM_memPeek!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/VM:: memCopy (Object obj,int objoffset,int base,int offset,int len);}
//private static native void memCopy(Object obj, int objoffset, int base, int offset, int len)
KNI_RETURNTYPE_VOID lejos_nxt_VM_memCopy(void)
{
	jint objoffset;
	jint base;
	jint offset;
	jint len;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(obj);
	KNI_GetParameterAsObject(1,obj);
	objoffset=KNI_GetParameterAsInt(2);
	base=KNI_GetParameterAsInt(3);
	offset=KNI_GetParameterAsInt(4);
	len=KNI_GetParameterAsInt(5);

	fprintf(stdout,"\nIn lejos_nxt_VM_memCopy!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/VM:: getDataAddress (Object obj);}
//private native static int getDataAddress (Object obj)
KNI_RETURNTYPE_INT lejos_nxt_VM_getDataAddress(void)
{
	jint ret;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(obj);
	KNI_GetParameterAsObject(1,obj);

	fprintf(stdout,"\nIn lejos_nxt_VM_getDataAddress!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/VM:: getObjectAddress (Object obj);}
//private native static int getObjectAddress(Object obj)
KNI_RETURNTYPE_INT lejos_nxt_VM_getObjectAddress(void)
{
	jint ret;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(obj);
	KNI_GetParameterAsObject(1,obj);

	fprintf(stdout,"\nIn lejos_nxt_VM_getObjectAddress!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static Object lejos/nxt/VM:: memGetReference (int base,int offset);}
//private native static Object memGetReference(int base, int offset)
KNI_RETURNTYPE_OBJECT lejos_nxt_VM_memGetReference(void)
{
	jint base;
	jint offset;
	KNI_StartHandles(1);
	KNI_DeclareHandle(obj_ref);
	base=KNI_GetParameterAsInt(1);
	offset=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_VM_memGetReference!");
	//
	KNI_EndHandlesAndReturnObject(obj_ref);
}
//JNIFunc={  static boolean lejos/nxt/VM:: isAssignable (int src,int dst);}
//private static native boolean isAssignable(int src, int dst)
KNI_RETURNTYPE_BOOLEAN lejos_nxt_VM_isAssignable(void)
{
	jboolean ret;
	jint src;
	jint dst;
	src=KNI_GetParameterAsInt(1);
	dst=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_VM_isAssignable!");
	
	KNI_ReturnBoolean(ret);

}
//JNIFunc={  static void lejos/nxt/VM:: suspendThread (Object thread);}
//public native static final void suspendThread(Object thread)
KNI_RETURNTYPE_VOID lejos_nxt_VM_suspendThread(void)
{
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(thread);
	KNI_GetParameterAsObject(1,thread);

	fprintf(stdout,"\nIn lejos_nxt_VM_suspendThread!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/VM:: resumeThread (Object thread);}
//public native static final void resumeThread(Object thread)
KNI_RETURNTYPE_VOID lejos_nxt_VM_resumeThread(void)
{
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(thread);
	KNI_GetParameterAsObject(1,thread);

	fprintf(stdout,"\nIn lejos_nxt_VM_resumeThread!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/VM:: executeProgram (int progNo);}
//public native static final void executeProgram(int progNo)
KNI_RETURNTYPE_VOID lejos_nxt_VM_executeProgram(void)
{
	jint progNo;
	progNo=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_VM_executeProgram!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/VM:: setVMOptions (int options);}
//public static final native void setVMOptions(int options)
KNI_RETURNTYPE_VOID lejos_nxt_VM_setVMOptions(void)
{
	jint options;
	options=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_VM_setVMOptions!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/VM:: getVMOptions ();}
//public static final native int getVMOptions()
KNI_RETURNTYPE_INT lejos_nxt_VM_getVMOptions(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_VM_getVMOptions!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int[] lejos/nxt/VM:: createStackTrace (Thread thread,Object ignore);}
//public static native int[] createStackTrace(Thread thread, Object ignore)
KNI_RETURNTYPE_OBJECT lejos_nxt_VM_createStackTrace(void)
{
	KNI_StartHandles(3);
	KNI_DeclareHandle(int_array_ref);
	
	KNI_DeclareHandle(thread);
	
	KNI_DeclareHandle(ignore);
	KNI_GetParameterAsObject(1,thread);
	KNI_GetParameterAsObject(2,ignore);

	fprintf(stdout,"\nIn lejos_nxt_VM_createStackTrace!");
	KNI_EndHandlesAndReturnObject(int_array_ref);
}
//JNIFunc={  static void lejos/nxt/VM:: firmwareExceptionHandler (Throwable exception,int method,int pc);}
//public static native void firmwareExceptionHandler(Throwable exception, int method, int pc)
KNI_RETURNTYPE_VOID lejos_nxt_VM_firmwareExceptionHandler(void)
{
	jint method;
	jint pc;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(exception);
	KNI_GetParameterAsObject(1,exception);
	method=KNI_GetParameterAsInt(2);
	pc=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_VM_firmwareExceptionHandler!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/comm/Bluetooth:: btWrite (byte[] buf,int off,int len);}
//public static native int btWrite(byte[] buf, int off, int len)
KNI_RETURNTYPE_INT lejos_nxt_comm_Bluetooth_btWrite(void)
{
	jint ret;
	jint off;
	jint len;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);
	off=KNI_GetParameterAsInt(2);
	len=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btWrite!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/comm/Bluetooth:: btRead (byte[] buf,int off,int len);}
//public static native int btRead(byte[] buf, int off, int len)
KNI_RETURNTYPE_INT lejos_nxt_comm_Bluetooth_btRead(void)
{
	jint ret;
	jint off;
	jint len;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);
	off=KNI_GetParameterAsInt(2);
	len=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btRead!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/comm/Bluetooth:: btPending ();}
//public static native int btPending()
KNI_RETURNTYPE_INT lejos_nxt_comm_Bluetooth_btPending(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btPending!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/comm/Bluetooth:: btSetArmCmdMode (int mode);}
//public static native void btSetArmCmdMode(int mode)
KNI_RETURNTYPE_VOID lejos_nxt_comm_Bluetooth_btSetArmCmdMode(void)
{
	jint mode;
	mode=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btSetArmCmdMode!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/comm/Bluetooth:: btGetBC4CmdMode ();}
//public static native int btGetBC4CmdMode()
KNI_RETURNTYPE_INT lejos_nxt_comm_Bluetooth_btGetBC4CmdMode(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btGetBC4CmdMode!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/comm/Bluetooth:: btSetResetLow ();}
//public static native void btSetResetLow()
KNI_RETURNTYPE_VOID lejos_nxt_comm_Bluetooth_btSetResetLow(void)
{

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btSetResetLow!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/comm/Bluetooth:: btSetResetHigh ();}
//public static native void btSetResetHigh()
KNI_RETURNTYPE_VOID lejos_nxt_comm_Bluetooth_btSetResetHigh(void)
{

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btSetResetHigh!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/comm/Bluetooth:: btSend (byte[] buf,int len);}
//public static native void btSend(byte[] buf, int len)
KNI_RETURNTYPE_VOID lejos_nxt_comm_Bluetooth_btSend(void)
{
	jint len;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);
	len=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btSend!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/comm/Bluetooth:: btReceive (byte[] buf);}
//public static native void btReceive(byte[] buf)
KNI_RETURNTYPE_VOID lejos_nxt_comm_Bluetooth_btReceive(void)
{
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btReceive!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/comm/Bluetooth:: btEnable ();}
//public static native void btEnable()
KNI_RETURNTYPE_VOID lejos_nxt_comm_Bluetooth_btEnable(void)
{

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btEnable!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/comm/Bluetooth:: btDisable ();}
//public static native void btDisable()
KNI_RETURNTYPE_VOID lejos_nxt_comm_Bluetooth_btDisable(void)
{

	fprintf(stdout,"\nIn lejos_nxt_comm_Bluetooth_btDisable!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/comm/RS485:: hsSend (byte address,byte control,byte[] data,int offset,int len,char[] crc);}
//static native int hsSend(byte address, byte control, byte[]data, int offset, int len, char[]crc)
KNI_RETURNTYPE_INT lejos_nxt_comm_RS485_hsSend(void)
{
	jint ret;
	jbyte address;
	jbyte control;
	jint offset;
	jint len;
	KNI_StartHandles(2);
	
	KNI_DeclareHandle(data);
	
	KNI_DeclareHandle(crc);
	address=KNI_GetParameterAsByte(1);
	control=KNI_GetParameterAsByte(2);
	KNI_GetParameterAsObject(3,data);
	offset=KNI_GetParameterAsInt(4);
	len=KNI_GetParameterAsInt(5);
	KNI_GetParameterAsObject(6,crc);

	fprintf(stdout,"\nIn lejos_nxt_comm_RS485_hsSend!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/comm/RS485:: hsRecv (byte[] data,int len,char[] crc,int reset);}
//static native int hsRecv(byte[]data, int len, char[]crc, int reset)
KNI_RETURNTYPE_INT lejos_nxt_comm_RS485_hsRecv(void)
{
	jint ret;
	jint len;
	jint reset;
	KNI_StartHandles(2);
	
	KNI_DeclareHandle(data);
	
	KNI_DeclareHandle(crc);
	KNI_GetParameterAsObject(1,data);
	len=KNI_GetParameterAsInt(2);
	KNI_GetParameterAsObject(3,crc);
	reset=KNI_GetParameterAsInt(4);

	fprintf(stdout,"\nIn lejos_nxt_comm_RS485_hsRecv!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/comm/RS485:: hsEnable (int baudRate,int bufferSize);}
//public static native void hsEnable(int baudRate, int bufferSize)
KNI_RETURNTYPE_VOID lejos_nxt_comm_RS485_hsEnable(void)
{
	jint baudRate;
	jint bufferSize;
	baudRate=KNI_GetParameterAsInt(1);
	bufferSize=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_comm_RS485_hsEnable!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/comm/RS485:: hsDisable ();}
//public static native void hsDisable()
KNI_RETURNTYPE_VOID lejos_nxt_comm_RS485_hsDisable(void)
{

	fprintf(stdout,"\nIn lejos_nxt_comm_RS485_hsDisable!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/comm/RS485:: hsRead (byte[] ,int offset,int len);}
//public static native int hsRead(byte [] buf, int offset, int len)
KNI_RETURNTYPE_INT lejos_nxt_comm_RS485_hsRead(void)
{
	jint ret;
	jint offset;
	jint len;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);
	offset=KNI_GetParameterAsInt(2);
	len=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_comm_RS485_hsRead!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/comm/RS485:: hsWrite (byte[] buf,int offset,int len);}
//public static native int hsWrite(byte[] buf, int offset, int len)
KNI_RETURNTYPE_INT lejos_nxt_comm_RS485_hsWrite(void)
{
	jint ret;
	jint offset;
	jint len;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);
	offset=KNI_GetParameterAsInt(2);
	len=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_comm_RS485_hsWrite!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/comm/USB:: usbEnable (int reset);}
//public static native void usbEnable(int reset)
KNI_RETURNTYPE_VOID lejos_nxt_comm_USB_usbEnable(void)
{
	jint reset;
	reset=KNI_GetParameterAsInt(1);

	fprintf(stdout,"\nIn lejos_nxt_comm_USB_usbEnable!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/comm/USB:: usbDisable ();}
//public static native void usbDisable()
KNI_RETURNTYPE_VOID lejos_nxt_comm_USB_usbDisable(void)
{

	fprintf(stdout,"\nIn lejos_nxt_comm_USB_usbDisable!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/comm/USB:: usbReset ();}
//public static native void usbReset()
KNI_RETURNTYPE_VOID lejos_nxt_comm_USB_usbReset(void)
{

	fprintf(stdout,"\nIn lejos_nxt_comm_USB_usbReset!");
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/comm/USB:: usbRead (byte[] ,int off,int len);}
//public static native int usbRead(byte [] buf, int off, int len)
KNI_RETURNTYPE_INT lejos_nxt_comm_USB_usbRead(void)
{
	jint ret;
	jint off;
	jint len;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);
	off=KNI_GetParameterAsInt(2);
	len=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_comm_USB_usbRead!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/comm/USB:: usbWrite (byte[] ,int off,int len);}
//public static native int usbWrite(byte [] buf, int off, int len)
KNI_RETURNTYPE_INT lejos_nxt_comm_USB_usbWrite(void)
{
	jint ret;
	jint off;
	jint len;
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(buf);
	KNI_GetParameterAsObject(1,buf);
	off=KNI_GetParameterAsInt(2);
	len=KNI_GetParameterAsInt(3);

	fprintf(stdout,"\nIn lejos_nxt_comm_USB_usbWrite!");
	KNI_EndHandles();
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static int lejos/nxt/comm/USB:: usbStatus ();}
//public static native int usbStatus()
KNI_RETURNTYPE_INT lejos_nxt_comm_USB_usbStatus(void)
{
	jint ret;

	fprintf(stdout,"\nIn lejos_nxt_comm_USB_usbStatus!");
	
	KNI_ReturnInt(ret);

}
//JNIFunc={  static void lejos/nxt/comm/USB:: usbSetSerialNo (String serNo);}
//public static native void usbSetSerialNo(String serNo)
KNI_RETURNTYPE_VOID lejos_nxt_comm_USB_usbSetSerialNo(void)
{
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(serNo);
	KNI_GetParameterAsObject(1,serNo);

	fprintf(stdout,"\nIn lejos_nxt_comm_USB_usbSetSerialNo!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static void lejos/nxt/comm/USB:: usbSetName (String name);}
//public static native void usbSetName(String name)
KNI_RETURNTYPE_VOID lejos_nxt_comm_USB_usbSetName(void)
{
	KNI_StartHandles(1);
	
	KNI_DeclareHandle(name);
	KNI_GetParameterAsObject(1,name);

	fprintf(stdout,"\nIn lejos_nxt_comm_USB_usbSetName!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  void lejos/nxt/debug/DebugInterface:: setDebug ();}
//private native final void setDebug()
KNI_RETURNTYPE_VOID lejos_nxt_debug_DebugInterface_setDebug(void)
{
	KNI_StartHandles(1);
	KNI_DeclareHandle(this_ref);
	

	KNI_GetThisPointer(this_ref);

	fprintf(stdout,"\nIn lejos_nxt_debug_DebugInterface_setDebug!");
	KNI_EndHandles();
	
	KNI_ReturnVoid();
}
//JNIFunc={  static int lejos/nxt/debug/DebugInterface:: eventOptions (int event,int option);}
//private native static final int eventOptions(int event, int option)
KNI_RETURNTYPE_INT lejos_nxt_debug_DebugInterface_eventOptions(void)
{
	jint ret;
	jint event;
	jint option;
	event=KNI_GetParameterAsInt(1);
	option=KNI_GetParameterAsInt(2);

	fprintf(stdout,"\nIn lejos_nxt_debug_DebugInterface_eventOptions!");
	
	KNI_ReturnInt(ret);

}
