array.h File Reference
#include `wrappers.h`
#include `classfile.h`
#include `header.h`
#include `opcodes.h`
Data Structures
struct array_t
struct ref_array_t
Defines
#define JELATINE_ARRAY_H (1)
Typedefs
typedef struct array_t array_t
typedef struct ref_array_t ref_array_t
Functions
void arraycopy_ref (array_t *, int32_t, array_t *, int32_t, int32_t)
size_t array_get_nref_size (array_t *)
size_t array_get_ref_n (array_t *)
static void * array_get_data (array_t *p)
static uintptr_t * array_ref_get_data (array_t *p)
static uint32_t array_length (array_t *p)
static const char * array_name (array_type_t t)
static uint32_t array_elem_size (array_type_t t)
static array_type_t prim_to_array_type (primitive_type_t t)
Variables
const char * array_names []
uint8_t array_elem_sizes []
uint8_t prim_to_array_types []
Detailed Description
Array declaration and interface
Definition in file array.h.
Define Documentation
#define JELATINE_ARRAY_H (1)
array.h inclusion macro
Definition at line 28 of file array.h.
Typedef Documentation
typedef struct array_t array_t
Typedef for struct array_t
Definition at line 84 of file array.h.
typedef struct ref_array_t ref_array_t
Typedef for struct ref_array_t
Definition at line 99 of file array.h.
Function Documentation
static uint32_t array_elem_size (array_type_t t) [inline, static]
Returns the size of an element of the specified basic array type
Parameters
t The basic array type
Returns
The size in bytes of the basic array type
Definition at line 158 of file array.h.
References array_elem_sizes.
Referenced by array_get_nref_size(), gc_new_array_nonref(), and java_lang_System_arraycopy().
static void* array_get_data (array_t * p) [inline, static]
Gets a pointer to the actual array data
Parameters
p A pointer to an array header
Definition at line 124 of file array.h.
Referenced by interpreter(), java_lang_Class_forName(), java_lang_System_arraycopy(), jstring_create_from_unicode(), jstring_create_from_utf8(), jstring_create_literal(), jstring_equals(), jstring_intern(), KNI_GetBooleanArrayElement(), KNI_GetByteArrayElement(), KNI_GetCharArrayElement(), KNI_GetIntArrayElement(), KNI_GetLongArrayElement(), KNI_GetRawArrayRegion(), KNI_GetShortArrayElement(), KNI_GetStringRegion(), KNI_SetBooleanArrayElement(), KNI_SetByteArrayElement(), KNI_SetCharArrayElement(), KNI_SetIntArrayElement(), KNI_SetLongArrayElement(), KNI_SetRawArrayRegion(), and KNI_SetShortArrayElement().
size_t array_get_nref_size (array_t * array)
Gets the size (in bytes) of the non-reference area of an array
Parameters
array A pointer to the array header
Returns
The size (in bytes) of the array's non-reference area
Definition at line 88 of file array.c.
References array_elem_size(), class_t::elem_type, array_t::header, header_get_class(), array_t::length, prim_to_array_type(), PT_BOOL, PT_REFERENCE, and size_div_inf().
Referenced by gc_sweep().
size_t array_get_ref_n (array_t * array)
Gets the number of references in an array
Parameters
array A pointer to an array header
Returns
The number of references in the array
Definition at line 113 of file array.c.
References class_is_array(), class_t::elem_type, array_t::header, header_get_class(), array_t::length, and PT_REFERENCE.
Referenced by gc_mark_reference(), and gc_sweep().
static uint32_t array_length (array_t * p) [inline, static]
Returns the number of elements in an array
Parameters
p A pointer to an array header
Definition at line 140 of file array.h.
References array_t::length.
Referenced by interpreter().
static const char* array_name (array_type_t t) [inline, static]
Returns the name of a basic array type
Parameters
t The basic array type
Returns
A string holding the name of the array class
Definition at line 149 of file array.h.
References array_names.
Referenced by bcl_link_opcode().
static uintptr_t* array_ref_get_data (array_t * p) [inline, static]
Gets a pointer to the actual array data for reference arrays
Parameters
p A pointer to an array header
Definition at line 132 of file array.h.
Referenced by arraycopy_ref(), gc_new_multiarray(), interpreter(), KNI_GetObjectArrayElement(), KNI_SetObjectArrayElement(), and vm_run().
void arraycopy_ref (array_t * src, int32_t src_offset, array_t * dest, int32_t dest_offset, int32_t length)
C implementation of java.lang.System.arraycopy() for reference arrays. If an element is found not to be compatible with the destination array an ArrayStoreException is thrown
Parameters
src A pointer to the source array
src_offset The offset in the source array
dest A pointer to the destination array
dest_offset The offset in the destination array
length The number of elements to copy
Definition at line 135 of file array.c.
References array_ref_get_data(), bcl_is_assignable(), class_t::elem_class, gc_new_array_ref(), array_t::header, header_get_class(), and KNI_ThrowNew().
Referenced by java_lang_System_arraycopy().
static array_type_t prim_to_array_type (primitive_type_t t) [inline, static]
Returns the array type derived from a primitive type
Parameters
t The primitive type
Returns
The array type corresponding to the primitive type
Definition at line 167 of file array.h.
References prim_to_array_types.
Referenced by array_get_nref_size(), gc_new_multiarray(), java_lang_System_arraycopy(), and load_class().
Variable Documentation
uint8_t array_elem_sizes[]
This array holds the size in bytes of the basic array element types. T_BOOLEAN is a special case as it set as having an element size of 1 byte per element when in fact it uses 1 bit per element
Definition at line 55 of file array.c.
Referenced by array_elem_size().
const char* array_names[]
This array holds the names of the primitive-type arrays
Definition at line 40 of file array.c.
Referenced by array_name().
uint8_t prim_to_array_types[]
This array holds an array_type_t value for each primitive_type_t element which can be used in a non-reference array
Definition at line 69 of file array.c.
Referenced by prim_to_array_type().