bytecode.h File Reference
#include `class.h`
#include `method.h`
Defines
#define JELATINE_BYTECODE_H (1)
Functions
void translate_bytecode (class_t *, method_t *, uint8_t *, exception_handler_t *)
Detailed Description
Bytecode manipulation functions interface
Definition in file bytecode.h.
Define Documentation
#define JELATINE_BYTECODE_H (1)
bytecode.h inclusion macro
Definition at line 28 of file bytecode.h.
Function Documentation
void translate_bytecode (class_t * cl, method_t * method, uint8_t * code, exception_handler_t * handlers)
Translates regular Java bytecode into the internal version used by the VM, bytecode verification could be done here too
Note that during bytecode translation constants larger than a single byte are turned to the machines native endian format (for unaligned constants only if the machine supports unaligned accesses). Static constraints in the bytecode are enforced here and partial verification happens too.
Parameters
cl A pointer to the class owning the method
method A pointer to the method to be translated
code The method code
handlers The method exception handlers
Definition at line 48 of file bytecode.c.
References c_throw, class_t::const_pool, CONSTANT_Class, CONSTANT_Double, CONSTANT_Float, CONSTANT_Integer, CONSTANT_Long, CONSTANT_String, cp_get_tag(), method_t::exception_table_length, JAVA_AALOAD, JAVA_AASTORE, JAVA_ACONST_NULL, JAVA_ALOAD, JAVA_ALOAD_0, JAVA_ALOAD_1, JAVA_ALOAD_2, JAVA_ALOAD_3, JAVA_ANEWARRAY, JAVA_ARETURN, JAVA_ARRAYLENGTH, JAVA_ASTORE, JAVA_ASTORE_0, JAVA_ASTORE_1, JAVA_ASTORE_2, JAVA_ASTORE_3, JAVA_ATHROW, JAVA_BALOAD, JAVA_BASTORE, JAVA_BIPUSH, JAVA_CALOAD, JAVA_CASTORE, JAVA_CHECKCAST, JAVA_D2F, JAVA_D2I, JAVA_D2L, JAVA_DADD, JAVA_DALOAD, JAVA_DASTORE, JAVA_DCMPG, JAVA_DCMPL, JAVA_DCONST_0, JAVA_DCONST_1, JAVA_DDIV, JAVA_DLOAD, JAVA_DLOAD_0, JAVA_DLOAD_1, JAVA_DLOAD_2, JAVA_DLOAD_3, JAVA_DMUL, JAVA_DNEG, JAVA_DREM, JAVA_DRETURN, JAVA_DSTORE, JAVA_DSTORE_0, JAVA_DSTORE_1, JAVA_DSTORE_2, JAVA_DSTORE_3, JAVA_DSUB, JAVA_DUP, JAVA_DUP2, JAVA_DUP2_X1, JAVA_DUP2_X2, JAVA_DUP_X1, JAVA_DUP_X2, JAVA_F2D, JAVA_F2I, JAVA_F2L, JAVA_FADD, JAVA_FALOAD, JAVA_FASTORE, JAVA_FCMPG, JAVA_FCMPL, JAVA_FCONST_0, JAVA_FCONST_1, JAVA_FCONST_2, JAVA_FDIV, JAVA_FLOAD, JAVA_FLOAD_0, JAVA_FLOAD_1, JAVA_FLOAD_2, JAVA_FLOAD_3, JAVA_FMUL, JAVA_FNEG, JAVA_FREM, JAVA_FRETURN, JAVA_FSTORE, JAVA_FSTORE_0, JAVA_FSTORE_1, JAVA_FSTORE_2, JAVA_FSTORE_3, JAVA_FSUB, JAVA_GETFIELD, JAVA_GETSTATIC, JAVA_GOTO, JAVA_GOTO_W, JAVA_I2B, JAVA_I2C, JAVA_I2D, JAVA_I2F, JAVA_I2L, JAVA_I2S, JAVA_IADD, JAVA_IALOAD, JAVA_IAND, JAVA_IASTORE, JAVA_ICONST_0, JAVA_ICONST_1, JAVA_ICONST_2, JAVA_ICONST_3, JAVA_ICONST_4, JAVA_ICONST_5, JAVA_ICONST_M1, JAVA_IDIV, JAVA_IF_ACMPEQ, JAVA_IF_ACMPNE, JAVA_IF_ICMPEQ, JAVA_IF_ICMPGE, JAVA_IF_ICMPGT, JAVA_IF_ICMPLE, JAVA_IF_ICMPLT, JAVA_IF_ICMPNE, JAVA_IFEQ, JAVA_IFGE, JAVA_IFGT, JAVA_IFLE, JAVA_IFLT, JAVA_IFNE, JAVA_IFNONNULL, JAVA_IFNULL, JAVA_IINC, JAVA_ILOAD, JAVA_ILOAD_0, JAVA_ILOAD_1, JAVA_ILOAD_2, JAVA_ILOAD_3, JAVA_IMUL, JAVA_INEG, JAVA_INSTANCEOF, JAVA_INVOKEINTERFACE, JAVA_INVOKESPECIAL, JAVA_INVOKESTATIC, JAVA_INVOKEVIRTUAL, JAVA_IOR, JAVA_IREM, JAVA_IRETURN, JAVA_ISHL, JAVA_ISHR, JAVA_ISTORE, JAVA_ISTORE_0, JAVA_ISTORE_1, JAVA_ISTORE_2, JAVA_ISTORE_3, JAVA_ISUB, JAVA_IUSHR, JAVA_IXOR, JAVA_JSR, JAVA_JSR_W, JAVA_L2D, JAVA_L2F, JAVA_L2I, JAVA_LADD, JAVA_LALOAD, JAVA_LAND, JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LASTORE, JAVA_LCMP, JAVA_LCONST_0, JAVA_LCONST_1, JAVA_LDC, JAVA_LDC2_W, JAVA_LDC_W, JAVA_LDIV, JAVA_LLOAD, JAVA_LLOAD_0, JAVA_LLOAD_1, JAVA_LLOAD_2, JAVA_LLOAD_3, JAVA_LMUL, JAVA_LNEG, JAVA_LOOKUPSWITCH, JAVA_LOR, JAVA_LREM, JAVA_LRETURN, JAVA_LSHL, JAVA_LSHR, JAVA_LSTORE, JAVA_LSTORE_0, JAVA_LSTORE_1, JAVA_LSTORE_2, JAVA_LSTORE_3, JAVA_LSUB, JAVA_LUSHR, JAVA_LXOR, JAVA_MONITORENTER, JAVA_MONITOREXIT, JAVA_MULTIANEWARRAY, JAVA_NEW, JAVA_NEWARRAY, JAVA_NOP, JAVA_POP, JAVA_POP2, JAVA_PUTFIELD, JAVA_PUTSTATIC, JAVA_RET, JAVA_RETURN, JAVA_SALOAD, JAVA_SASTORE, JAVA_SIPUSH, JAVA_SWAP, JAVA_TABLESWITCH, JAVA_WIDE, method_t::max_locals, method_get_code_length(), method_is_static(), method_is_synchronized(), size_ceil(), store_int16_un, store_int32_un, T_BOOLEAN, T_BYTE, T_CHAR, T_INT, T_LONG, and T_SHORT.
Referenced by bcl_link_method().