field.c File Reference
#include `wrappers.h`
#include `class.h`
#include `field.h`
#include `util.h`
Functions
size_t field_size (const field_t *field)
void field_parse_descriptor (const char *desc)
uintptr_t static_field_data_ptr (static_field_t *static_field)
static field_t * field_itr_find_next (field_t *curr, field_t *end, bool stat)
field_iterator_t field_itr (class_t *cl, bool stat)
field_t * field_itr_get_next (field_iterator_t *itr)
Detailed Description
Field structure implementation
Definition in file field.c.
Function Documentation
field_iterator_t field_itr (class_t * cl, bool stat)
Returns an iterator for navigating the instance or static fields of a class depending on the value of stat
Parameters
cl A pointer to a class
stat true if a static field iterator is needed, false otherwise
Returns
An initialized iterator
Definition at line 224 of file field.c.
References field_iterator_t::end, field_itr_find_next(), class_t::fields, class_t::fields_n, field_iterator_t::next, and field_iterator_t::stat.
Referenced by instance_field_itr(), and static_field_itr().
static field_t* field_itr_find_next (field_t * curr, field_t * end, bool stat) [static]
Find the next field to iterate on unless there are no more available
Parameters
curr The current field
end A pointer past the last field
stat true if a static field is wanted, false otherwise returns A pointer to the next field or NULL if no more are available
Definition at line 205 of file field.c.
References field_is_static().
Referenced by field_itr(), and field_itr_get_next().
field_t* field_itr_get_next (field_iterator_t * itr)
Returns the next field of this iteration
Parameters
itr A field iterator
Returns
The next field available
Definition at line 240 of file field.c.
References field_iterator_t::end, field_itr_find_next(), field_itr_has_next(), field_iterator_t::next, and field_iterator_t::stat.
Referenced by bcl_mark(), initialize_static_fields(), and layout_fields().
void field_parse_descriptor (const char * desc)
Checks if a field descriptor is valid
Parameters
desc A field descriptor
Definition at line 74 of file field.c.
References c_throw, and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by verify_field().
size_t field_size (const field_t * field)
Returns the size in bytes of a field
Parameters
field A pointer to a field
Returns
The size in bytes of the field
Definition at line 38 of file field.c.
References dbg_unreachable, and field_t::descriptor.
uintptr_t static_field_data_ptr (static_field_t * static_field)
Returns a pointer to the actual data of a static field
Parameters
static_field A pointer to a static field
Returns
The address of the static field data
Definition at line 174 of file field.c.
References static_field_t::data, dbg_unreachable, field_t::descriptor, and static_field_t::field.
Referenced by KNI_GetStaticFieldID(), and resolve_static_field().