header.h File Reference
#include `wrappers.h`
Defines
#define JELATINE_HEADER_H (1)
#define HEADER_RESERVED (2)
#define HEADER_MARK_SHIFT (0)
#define HEADER_JAVA_OBJECT_SHIFT (1)
#define HEADER_PCP_MASK (~(((uintptr_t) 1 << HEADER_RESERVED) - 1))
#define HEADER_SIZE_MASK HEADER_PCP_MASK
Typedefs
typedef uintptr_t header_t
Functions
static bool header_is_object (header_t *header)
static header_t header_create_object (struct class_t *cl)
static header_t header_create_c (size_t size)
static struct class_t * header_get_class (header_t *header)
static size_t header_get_size (header_t *header)
static bool header_is_marked (header_t *header)
static void header_set_mark (header_t *header)
static void header_clear_mark (header_t *header)
Detailed Description
Object header related definitions and type declarations
Definition in file header.h.
Define Documentation
#define HEADER_JAVA_OBJECT_SHIFT (1)
Shift value used to obtain the C object bit
Definition at line 77 of file header.h.
Referenced by header_is_object().
#define HEADER_MARK_SHIFT (0)
Shift value used to obtain the mark bit
Definition at line 74 of file header.h.
Referenced by header_clear_mark(), and header_is_marked().
#define HEADER_PCP_MASK (~(((uintptr_t) 1 << HEADER_RESERVED) - 1))
Mask used to extract the packed class pointer from the header
Definition at line 80 of file header.h.
#define HEADER_RESERVED (2)
Reserved bits in the header a Java object or C allocation
At the moment 2 bits are reserved, bit 31 is set if the object is marked and bit 30 is set if this is a Java object. The mark bit is always set for C objects
Definition at line 69 of file header.h.
Referenced by gc_sweep(), header_create_c(), and header_create_object().
#define HEADER_SIZE_MASK HEADER_PCP_MASK
Mask used to extract the size of an allocation from the header
Definition at line 83 of file header.h.
#define JELATINE_HEADER_H (1)
header.h inclusion macro
Definition at line 28 of file header.h.
Typedef Documentation
typedef uintptr_t header_t
Represents the meta-data added to an object including the object description and the extra fields used by the gc
Definition at line 34 of file header.h.
Function Documentation
static void header_clear_mark (header_t * header) [inline, static]
Clears the mark bit of an object's header
Parameters
header A pointer to an object header
Definition at line 171 of file header.h.
References HEADER_MARK_SHIFT.
Referenced by gc_sweep().
static header_t header_create_c (size_t size) [inline, static]
Creates a C object header of the specified size
Parameters
size The size of the C object
Returns
A Java object header
Definition at line 125 of file header.h.
References HEADER_RESERVED.
Referenced by gc_malloc().
static header_t header_create_object (struct class_t * cl) [inline, static]
Creates a Java object header from the pointer to the class the object belongs to
Parameters
cl A pointer to a class_t structuer
Returns
A Java object header
Definition at line 115 of file header.h.
References HEADER_RESERVED.
Referenced by gc_new(), gc_new_array_nonref(), and gc_new_array_ref().
static struct class_t* header_get_class (header_t * header) [static, read]
Extracts the class pointer from an object header
Parameters
header pointer to an object header
Returns
The class pointer embedded in the header
Definition at line 135 of file header.h.
References header_is_object().
Referenced by array_get_nref_size(), array_get_ref_n(), arraycopy_ref(), gc_mark_reference(), gc_sweep(), interpreter(), java_lang_Object_getClass(), java_lang_System_arraycopy(), java_lang_Thread_start(), KNI_GetObjectClass(), and KNI_IsInstanceOf().
static size_t header_get_size (header_t * header) [inline, static]
Extracts the size of a C object from an object header
Parameters
header A pointer to an object header
Returns
The size of the C object
Definition at line 145 of file header.h.
References header_is_object().
Referenced by gc_free(), and gc_sweep().
static bool header_is_marked (header_t * header) [inline, static]
Checks if the header's 'marked' bit is set
Parameters
header A pointer to an object header
Returns
True if the header is marked, false otherwise
Definition at line 155 of file header.h.
References HEADER_MARK_SHIFT.
Referenced by gc_mark_finalizable(), gc_mark_reference(), gc_purge_weakref_list(), gc_sweep(), jsm_purge(), and tm_purge().
static bool header_is_object (header_t * header) [inline, static]
Checks if the header's 'Java object' bit is set
Parameters
header A pointer to an object header
Returns
True if the header belongs to a Java object, false otherwise
Definition at line 105 of file header.h.
References HEADER_JAVA_OBJECT_SHIFT.
Referenced by gc_mark_reference(), gc_sweep(), header_get_class(), and header_get_size().
static void header_set_mark (header_t * header) [inline, static]
Sets the mark bit of an object's header
Parameters
header A pointer to an object header
Definition at line 163 of file header.h.
Referenced by gc_mark_reference(), and gc_sweep().