interpreter.h File Reference
#include `wrappers.h`
#include `method.h`
Defines
#define JELATINE_INTERPRETER_H (1)
#define PRINT_OPCODE()
#define INTERPRETER_PROLOG
#define INTERPRETER_EPILOG
#define OPCODE(x)
#define DISPATCH goto dispatch
Functions
void interpreter (method_t *)
Detailed Description
Bytecode interpreter interface
Definition in file interpreter.h.
Define Documentation
#define DISPATCH goto dispatch
Dispatches the next interpreter, jumps back to the interpreter prolog or straight to the next opcode
Definition at line 92 of file interpreter.h.
#define INTERPRETER_EPILOG
Value:
return;
As for the prolog, closes the switch statement or does nothing
Definition at line 68 of file interpreter.h.
Referenced by interpreter().
#define INTERPRETER_PROLOG
Value:
dispatch:
    switch (*pc)
Macro used for creating the prolog of the interpreter, expands into the head of a switch statement if the labels-as-values extension is not available, into a direct jump otherwise
Definition at line 56 of file interpreter.h.
Referenced by interpreter().
#define JELATINE_INTERPRETER_H (1)
interpreter.h inclusion macro
Definition at line 28 of file interpreter.h.
#define OPCODE(x)
Value:
case x:
    PRINT_OPCODE();
Declares an opcode, expands into a case statement or into a label
Definition at line 81 of file interpreter.h.
Referenced by interpreter().
#define PRINT_OPCODE()
Macro used in the OPCODE macro to print out an opcode when it is executed
Definition at line 44 of file interpreter.h.
Function Documentation
void interpreter (method_t * main_method)
Launches the interpreter
Parameters
main_method The entry point
Definition at line 98 of file interpreter.c.
References AALOAD, AASTORE, ACONST_NULL, ALOAD, ALOAD_0, ALOAD_1, ALOAD_2, ALOAD_3, ANEWARRAY, ANEWARRAY_PRELINK, ARETURN, ARETURN_MONITOREXIT, method_t::args_size, array_get_data(), array_length(), array_ref_get_data(), ARRAYLENGTH, ASTORE, ASTORE_0, ASTORE_1, ASTORE_2, ASTORE_3, ATHROW, BALOAD, BASTORE, bcl_get_class_by_id(), bcl_is_assignable(), bcl_link_method(), bcl_link_opcode(), bcl_resolve_class(), BIPUSH, c_throw, CALOAD, CASTORE, exception_handler_t::catch_type, CHECKCAST, CHECKCAST_PRELINK, stack_frame_t::cl, class_get_object(), class_is_parent(), method_t::code, method_t::cp, cp_data_get_int32(), cp_data_get_int64(), cp_data_get_ptr(), cp_data_get_uintptr(), cp_get_class(), D2F, D2I, D2L, DADD, DALOAD, DASTORE, method_t::data, const_pool_t::data, dbg_unreachable, DCMPG, DCMPL, DCONST_0, DCONST_1, DDIV, class_t::dimensions, DLOAD, DLOAD_0, DLOAD_1, DLOAD_2, DLOAD_3, DMUL, DNEG, DREM, DRETURN, DRETURN_MONITOREXIT, DSTORE, DSTORE_0, DSTORE_1, DSTORE_2, DSTORE_3, DSUB, class_t::dtable, DUP, DUP2, DUP2_X1, DUP2_X2, DUP_X1, DUP_X2, class_t::elem_class, class_t::elem_type, thread_t::exception, method_t::exception_table_length, F2D, F2I, F2L, FADD, FALOAD, FASTORE, FCMPG, FCMPL, FCONST_0, FCONST_1, FCONST_2, FDIV, FLOAD, FLOAD_0, FLOAD_1, FLOAD_2, FLOAD_3, FMUL, FNEG, thread_t::fp, FREM, FRETURN, FRETURN_MONITOREXIT, FSTORE, FSTORE_0, FSTORE_1, FSTORE_2, FSTORE_3, FSUB, method_t::function, gc_new(), gc_new_array_nonref(), gc_new_array_ref(), gc_new_multiarray(), GETFIELD_BOOL, GETFIELD_BYTE, GETFIELD_CHAR, GETFIELD_DOUBLE, GETFIELD_FLOAT, GETFIELD_INT, GETFIELD_LONG, GETFIELD_PRELINK, GETFIELD_REFERENCE, GETFIELD_SHORT, GETSTATIC_BYTE, GETSTATIC_CHAR, GETSTATIC_DOUBLE, GETSTATIC_FLOAT, GETSTATIC_INT, GETSTATIC_LONG, GETSTATIC_PRELINK, GETSTATIC_REFERENCE, GETSTATIC_SHORT, GOTO, GOTO_W, HALT, halt_method, exception_handler_t::handler_pc, method_t::handlers, array_t::header, header_get_class(), I2B, I2C, I2D, I2F, I2L, I2S, IADD, IALOAD, IAND, IASTORE, ICONST_0, ICONST_1, ICONST_2, ICONST_3, ICONST_4, ICONST_5, ICONST_M1, IDIV, IF_ACMPEQ, IF_ACMPNE, IF_ICMPEQ, IF_ICMPGE, IF_ICMPGT, IF_ICMPLE, IF_ICMPLT, IF_ICMPNE, IFEQ, IFGE, IFGT, IFLE, IFLT, IFNE, IFNONNULL, IFNULL, IINC, ILOAD, ILOAD_0, ILOAD_1, ILOAD_2, ILOAD_3, IMUL, class_t::inames, INEG, INSTANCEOF, INSTANCEOF_PRELINK, INTERPRETER_EPILOG, INTERPRETER_PROLOG, INVOKE_NATIVE, INVOKEINTERFACE, INVOKEINTERFACE_PRELINK, INVOKESPECIAL, INVOKESPECIAL_PRELINK, INVOKESTATIC, INVOKESTATIC_PRELINK, INVOKESUPER, INVOKEVIRTUAL, INVOKEVIRTUAL_PRELINK, IOR, IREM, IRETURN, IRETURN_MONITOREXIT, ISHL, ISHR, ISTORE, ISTORE_0, ISTORE_1, ISTORE_2, ISTORE_3, ISUB, class_t::itable, class_t::itable_count, IUSHR, IXOR, JAVA_LANG_VIRTUALMACHINEERROR, L2D, L2F, L2I, LADD, LALOAD, LAND, LASTORE, LCMP, LCONST_0, LCONST_1, LDC, LDC2_W, LDC_PRELINK, LDC_REF, LDC_W, LDC_W_PRELINK, LDC_W_REF, LDIV, LLOAD, LLOAD_0, LLOAD_1, LLOAD_2, LLOAD_3, LMUL, LNEG, load_int16_un, load_int32_un, load_uint16_un, stack_frame_t::locals, LOOKUPSWITCH, LOR, LREM, LRETURN, LRETURN_MONITOREXIT, LSHL, LSHR, LSTORE, LSTORE_0, LSTORE_1, LSTORE_2, LSTORE_3, LSUB, LUSHR, LXOR, method_t::max_locals, method_t::max_stack, stack_frame_t::method, METHOD_ABSTRACT, method_is_static(), method_is_synchronized(), METHOD_LOAD, method_unpack_arguments(), method_unpack_index(), monitor_enter(), monitor_exit(), MONITORENTER, MONITORENTER_SPECIAL, MONITORENTER_SPECIAL_STATIC, MONITOREXIT, MULTIANEWARRAY, MULTIANEWARRAY_PRELINK, class_t::name, NEW, NEW_FINALIZER, NEW_PRELINK, NEWARRAY, NEWARRAY_PRELINK, NOP, OPCODE, class_t::parent, stack_frame_t::pc, POP, POP2, prepare_for_call(), print_method_call, print_method_ret, print_method_unwind, PT_BYTE, PUTFIELD_BOOL, PUTFIELD_BYTE, PUTFIELD_CHAR, PUTFIELD_DOUBLE, PUTFIELD_FLOAT, PUTFIELD_INT, PUTFIELD_LONG, PUTFIELD_PRELINK, PUTFIELD_REFERENCE, PUTSTATIC_BOOL, PUTSTATIC_BYTE, PUTSTATIC_CHAR, PUTSTATIC_DOUBLE, PUTSTATIC_FLOAT, PUTSTATIC_INT, PUTSTATIC_LONG, PUTSTATIC_PRELINK, PUTSTATIC_REFERENCE, RET_DOUBLE, RET_FLOAT, RET_INT, RET_LONG, RET_OBJECT, RET_VOID, RETURN, RETURN_MONITOREXIT, method_t::return_type, SALOAD, SASTORE, SAVE_STATE, SIPUSH, size_ceil(), thread_t::sp, SWAP, TABLESWITCH, thread_self(), and WIDE.
Referenced by initialize_class(), java_lang_Class_newInstance(), thread_create_main(), and thread_start().