jstring.h File Reference
#include `wrappers.h`
#include `array.h`
#include `header.h`
#include `util.h`
#include `java_lang_String.h`
Defines
#define JELATINE_JSTRING_H (1)
Functions
void jsm_init (uint32_t, uint32_t)
void jsm_set_classes (struct class_t *, struct class_t *)
void jsm_mark (void)
void jsm_purge (void)
java_lang_String_t * jstring_intern (java_lang_String_t *)
java_lang_String_t * jstring_create_literal (const char *)
java_lang_String_t * jstring_create_from_utf8 (const char *)
java_lang_String_t * jstring_create_from_unicode (const uint16_t *, uint32_t)
Detailed Description
Java Strings manager definition and interface
Definition in file jstring.h.
Define Documentation
#define JELATINE_JSTRING_H (1)
jstring.h inclusion macro
Definition at line 28 of file jstring.h.
Function Documentation
void jsm_init (uint32_t log2cap, uint32_t load)
Creates and initializes the Java string manager with an initial capacity of 2 ^ log2cap capacity entries
Parameters
log2cap The binary logarythm of the initial capacity
load Maximum load before a rehash is needed
Definition at line 86 of file jstring.c.
References jstring_manager_t::buckets, jstring_manager_t::capacity, jstring_manager_t::entries, gc_malloc(), jstring_manager_t::init_capacity, jstring_manager_t::lit_buckets, jstring_manager_t::lit_capacity, jstring_manager_t::lit_entries, jstring_manager_t::lit_init_capacity, jstring_manager_t::lit_load, and jstring_manager_t::load.
Referenced by vm_init().
void jsm_mark (void)
Marks the Java literals present in the manager. This function doesn't acquire the VM lock as it can be called only when all the threads have been stopped
Definition at line 122 of file jstring.c.
References gc_mark_reference(), JAVA_LANG_STRING_PTR2REF, jstring_manager_t::lit_buckets, jstring_manager_t::lit_capacity, and java_lang_String_t::next.
Referenced by gc_mark().
void jsm_purge (void)
Purge the Java string manager from all the unused Java strings. This function must be called after jsm_mark(). This function doesn't acquire the VM lock as it can be called only when all the threads have been stopped
Definition at line 141 of file jstring.c.
References jstring_manager_t::buckets, jstring_manager_t::capacity, jstring_manager_t::entries, java_lang_String_t::header, header_is_marked(), and java_lang_String_t::next.
Referenced by gc_collect().
void jsm_set_classes (class_t * str_cl, class_t * char_array_cl)
Passes the pointers to the java.lang.String class and the [C array class to the Java string manager, the manager is not really functional until this second initialization step has been done
Parameters
str_cl A pointer to the java.lang.String class
char_array_cl A pointer to the [C class
Definition at line 112 of file jstring.c.
References jstring_manager_t::char_array_cl, and jstring_manager_t::str_cl.
Referenced by bcl_preload_bootstrap_classes().
java_lang_String_t* jstring_create_from_unicode (const uint16_t * uchar, uint32_t length)
Creates a new Java string from an Unicode array
Parameters
uchar A pointer to the source array
length The string length
Returns
A Java reference to the newly created string
Definition at line 429 of file jstring.c.
References array_get_data(), java_lang_String_t::cachedHashCode, java_lang_String_t::count, gc_new(), gc_new_array_nonref(), JAVA_LANG_STRING_REF2PTR, java_lang_String_t::next, java_lang_String_t::offset, jstring_manager_t::str_cl, T_CHAR, thread_pop_root(), thread_push_root(), and java_lang_String_t::value.
Referenced by KNI_NewString().
java_lang_String_t* jstring_create_from_utf8 (const char * src)
Creates a new Java string from an utf8 string
Parameters
src A pointer to the source string
Returns
A Java reference to the newly created string
Definition at line 387 of file jstring.c.
References array_get_data(), c_throw, java_lang_String_t::cachedHashCode, java_lang_String_t::count, gc_new(), gc_new_array_nonref(), JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_STRING_REF2PTR, java_lang_String_t::next, java_lang_String_t::offset, jstring_manager_t::str_cl, T_CHAR, thread_pop_root(), thread_push_root(), utf8_check(), utf8_to_java(), utf8_to_java_length(), and java_lang_String_t::value.
Referenced by java_lang_Class_getInternalName(), KNI_NewStringUTF(), KNI_ThrowNew(), and thread_create_main().
java_lang_String_t* jstring_create_literal (const char * src)
Creates a new Java string literal from an utf8 string and interns it in the literal hash-table
Parameters
src A pointer to the source string
Returns
A Java reference to the newly created string
Definition at line 318 of file jstring.c.
References array_get_data(), c_throw, gc_new(), gc_new_array_nonref(), JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_STRING_REF2PTR, jsm_rehash_literals(), jstring_hash(), jstring_manager_t::lit_buckets, jstring_manager_t::lit_capacity, jstring_manager_t::lit_entries, jstring_manager_t::lit_init_capacity, jstring_manager_t::str_cl, T_CHAR, thread_pop_root(), thread_push_root(), tm_lock(), tm_unlock(), utf8_check(), utf8_to_java(), and utf8_to_java_length().
Referenced by cp_create(), and vm_run().
java_lang_String_t* jstring_intern (java_lang_String_t * jstr)
Interns a java.lang.String object, helper function used for implementing java.lang.String.intern()
Parameters
jstr A pointer to a java.lang.String object
Returns
A pointer to the interned string
Definition at line 247 of file jstring.c.
References array_get_data(), jstring_manager_t::buckets, java_lang_String_t::cachedHashCode, jstring_manager_t::capacity, java_lang_String_t::count, jstring_manager_t::entries, jstring_manager_t::init_capacity, jsm_rehash(), jstring_equals(), jstring_hash(), jstring_manager_t::lit_buckets, jstring_manager_t::lit_capacity, jstring_manager_t::load, java_lang_String_t::next, java_lang_String_t::offset, tm_lock(), tm_unlock(), and java_lang_String_t::value.
Referenced by java_lang_String_intern().