jstring.c File Reference
#include `wrappers.h`
#include `class.h`
#include `jstring.h`
#include `memory.h`
#include `thread.h`
#include `utf8_string.h`
#include `util.h`
Data Structures
struct jstring_manager_t
Typedefs
typedef struct jstring_manager_t jstring_manager_t
Functions
static void jsm_rehash (uint32_t)
static void jsm_rehash_literals (uint32_t)
static uint32_t jstring_hash (const uint16_t *, uint32_t, uint32_t)
static bool jstring_equals (const java_lang_String_t *, const java_lang_String_t *)
void jsm_init (uint32_t log2cap, uint32_t load)
void jsm_set_classes (class_t *str_cl, class_t *char_array_cl)
void jsm_mark (void)
void jsm_purge (void)
java_lang_String_t * jstring_intern (java_lang_String_t *jstr)
java_lang_String_t * jstring_create_literal (const char *src)
java_lang_String_t * jstring_create_from_utf8 (const char *src)
java_lang_String_t * jstring_create_from_unicode (const uint16_t *uchar, uint32_t length)
Variables
static jstring_manager_t jsm
Detailed Description
Java String manager implementation
Definition in file jstring.c.
Typedef Documentation
typedef struct jstring_manager_t jstring_manager_t
Typedef for struct jstring_manager_t
Definition at line 57 of file jstring.c.
Function Documentation
void jsm_init (uint32_t log2cap, uint32_t load)
Creates and initializes the Java string manager with an initial capacity of 2 ^ log2cap capacity entries
Parameters
log2cap The binary logarythm of the initial capacity
load Maximum load before a rehash is needed
Definition at line 86 of file jstring.c.
References jstring_manager_t::buckets, jstring_manager_t::capacity, jstring_manager_t::entries, gc_malloc(), jstring_manager_t::init_capacity, jstring_manager_t::lit_buckets, jstring_manager_t::lit_capacity, jstring_manager_t::lit_entries, jstring_manager_t::lit_init_capacity, jstring_manager_t::lit_load, and jstring_manager_t::load.
Referenced by vm_init().
void jsm_mark (void)
Marks the Java literals present in the manager. This function doesn't acquire the VM lock as it can be called only when all the threads have been stopped
Definition at line 122 of file jstring.c.
References gc_mark_reference(), JAVA_LANG_STRING_PTR2REF, jstring_manager_t::lit_buckets, jstring_manager_t::lit_capacity, and java_lang_String_t::next.
Referenced by gc_mark().
void jsm_purge (void)
Purge the Java string manager from all the unused Java strings. This function must be called after jsm_mark(). This function doesn't acquire the VM lock as it can be called only when all the threads have been stopped
Definition at line 141 of file jstring.c.
References jstring_manager_t::buckets, jstring_manager_t::capacity, jstring_manager_t::entries, java_lang_String_t::header, header_is_marked(), and java_lang_String_t::next.
Referenced by gc_collect().
static void jsm_rehash (uint32_t capacity) [static]
Rehashes the Java string manager. This function doesn't acquire the VM lock as it can be called only when all the threads have been stopped
Parameters
capacity The new capacity
Definition at line 174 of file jstring.c.
References jstring_manager_t::buckets, java_lang_String_t::cachedHashCode, jstring_manager_t::capacity, gc_free(), gc_malloc(), and java_lang_String_t::next.
Referenced by jstring_intern().
static void jsm_rehash_literals (uint32_t capacity) [static]
Rehashes the Java string manager literals hash-table. This function doesn't acquire the VM lock as it can be called only when all the threads have been stopped
Parameters
capacity The new capacity
Definition at line 210 of file jstring.c.
References jstring_manager_t::buckets, java_lang_String_t::cachedHashCode, gc_free(), gc_malloc(), jstring_manager_t::lit_buckets, jstring_manager_t::lit_capacity, and java_lang_String_t::next.
Referenced by jstring_create_literal().
void jsm_set_classes (class_t * str_cl, class_t * char_array_cl)
Passes the pointers to the java.lang.String class and the [C array class to the Java string manager, the manager is not really functional until this second initialization step has been done
Parameters
str_cl A pointer to the java.lang.String class
char_array_cl A pointer to the [C class
Definition at line 112 of file jstring.c.
References jstring_manager_t::char_array_cl, and jstring_manager_t::str_cl.
Referenced by bcl_preload_bootstrap_classes().
java_lang_String_t* jstring_create_from_unicode (const uint16_t * uchar, uint32_t length)
Creates a new Java string from an Unicode array
Parameters
uchar A pointer to the source array
length The string length
Returns
A Java reference to the newly created string
Definition at line 429 of file jstring.c.
References array_get_data(), java_lang_String_t::cachedHashCode, java_lang_String_t::count, gc_new(), gc_new_array_nonref(), JAVA_LANG_STRING_REF2PTR, java_lang_String_t::next, java_lang_String_t::offset, jstring_manager_t::str_cl, T_CHAR, thread_pop_root(), thread_push_root(), and java_lang_String_t::value.
Referenced by KNI_NewString().
java_lang_String_t* jstring_create_from_utf8 (const char * src)
Creates a new Java string from an utf8 string
Parameters
src A pointer to the source string
Returns
A Java reference to the newly created string
Definition at line 387 of file jstring.c.
References array_get_data(), c_throw, java_lang_String_t::cachedHashCode, java_lang_String_t::count, gc_new(), gc_new_array_nonref(), JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_STRING_REF2PTR, java_lang_String_t::next, java_lang_String_t::offset, jstring_manager_t::str_cl, T_CHAR, thread_pop_root(), thread_push_root(), utf8_check(), utf8_to_java(), utf8_to_java_length(), and java_lang_String_t::value.
Referenced by java_lang_Class_getInternalName(), KNI_NewStringUTF(), KNI_ThrowNew(), and thread_create_main().
java_lang_String_t* jstring_create_literal (const char * src)
Creates a new Java string literal from an utf8 string and interns it in the literal hash-table
Parameters
src A pointer to the source string
Returns
A Java reference to the newly created string
Definition at line 318 of file jstring.c.
References array_get_data(), c_throw, gc_new(), gc_new_array_nonref(), JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_STRING_REF2PTR, jsm_rehash_literals(), jstring_hash(), jstring_manager_t::lit_buckets, jstring_manager_t::lit_capacity, jstring_manager_t::lit_entries, jstring_manager_t::lit_init_capacity, jstring_manager_t::str_cl, T_CHAR, thread_pop_root(), thread_push_root(), tm_lock(), tm_unlock(), utf8_check(), utf8_to_java(), and utf8_to_java_length().
Referenced by cp_create(), and vm_run().
static bool jstring_equals (const java_lang_String_t * str1, const java_lang_String_t * str2) [static]
Compares two java strings
Parameters
str1 A pointer to a Java string
str2 A pointer to a Java string
Definition at line 481 of file jstring.c.
References array_get_data(), java_lang_String_t::count, java_lang_String_t::offset, and java_lang_String_t::value.
Referenced by jstring_intern().
static uint32_t jstring_hash (const uint16_t * data, uint32_t offset, uint32_t count) [static]
Calculates the hash of a Java string
Parameters
data The source array with the string character's
offset The offset
count The length
Returns
The computed hash for this string
Definition at line 464 of file jstring.c.
Referenced by jstring_create_literal(), and jstring_intern().
java_lang_String_t* jstring_intern (java_lang_String_t * jstr)
Interns a java.lang.String object, helper function used for implementing java.lang.String.intern()
Parameters
jstr A pointer to a java.lang.String object
Returns
A pointer to the interned string
Definition at line 247 of file jstring.c.
References array_get_data(), jstring_manager_t::buckets, java_lang_String_t::cachedHashCode, jstring_manager_t::capacity, java_lang_String_t::count, jstring_manager_t::entries, jstring_manager_t::init_capacity, jsm_rehash(), jstring_equals(), jstring_hash(), jstring_manager_t::lit_buckets, jstring_manager_t::lit_capacity, jstring_manager_t::load, java_lang_String_t::next, java_lang_String_t::offset, tm_lock(), tm_unlock(), and java_lang_String_t::value.
Referenced by java_lang_String_intern().
Variable Documentation
jstring_manager_t jsm [static]
Global Java strings manager
Definition at line 64 of file jstring.c.