loader.h File Reference
#include `wrappers.h`
#include `array.h`
#include `class.h`
#include `opcodes.h`
#include `util.h`
Defines
#define JELATINE_LOADER_H (1)
Functions
void bcl_init (void)
class_t * bcl_get_class_by_id (uint32_t)
void bcl_mark (void)
bool bcl_is_assignable (class_t *, class_t *)
void bcl_preload_bootstrap_classes (void)
class_t * bcl_resolve_class (class_t *, const char *)
class_t * bcl_find_class (const char *)
void bcl_link_method (class_t *, method_t *)
const uint8_t * bcl_link_opcode (const method_t *, const uint8_t *, internal_opcode_t)
static class_t * bcl_array_class (array_type_t type)
static void bcl_set_array_class (array_type_t type, class_t *cl)
Variables
class_t * array_classes []
Detailed Description
Bootstrap class-loader definition
Definition in file loader.h.
Define Documentation
#define JELATINE_LOADER_H (1)
loader.h inclusion macro
Definition at line 28 of file loader.h.
Function Documentation
static class_t* bcl_array_class (array_type_t type) [inline, static]
Return the class of a basic array type. The class must have already been resolved otherwise this function will return a NULL pointer
Parameters
type The basic array type
Returns
The array class associated with this basic type
Definition at line 68 of file loader.h.
References T_BOOLEAN, and T_LONG.
Referenced by gc_new_array_nonref().
class_t* bcl_find_class (const char * name)
Finds a class by its name
Parameters
name The class' name
Returns
A pointer to the class or NULL if none is found
Definition at line 955 of file loader.c.
References loader_t::class_table, class_t::name, tm_lock(), tm_unlock(), and loader_t::used.
Referenced by bcl_resolve_class(), KNI_FindClass(), load_class(), and thread_create_main().
class_t* bcl_get_class_by_id (uint32_t id)
Returns a pointer to the class corresponding to the given id
Parameters
id The id of the class
Returns
A pointer to the class corresponding to id
Definition at line 158 of file loader.c.
References loader_t::class_table, tm_lock(), and tm_unlock().
Referenced by gc_sweep(), interpreter(), java_lang_Class_getInternalName(), java_lang_Class_newInstance(), KNI_GetFieldID(), KNI_GetStaticFieldID(), KNI_GetSuperClass(), KNI_IsAssignableFrom(), and KNI_IsInstanceOf().
void bcl_init (void)
Initializes the bootstrap class loader
Definition at line 146 of file loader.c.
References loader_t::capacity, loader_t::class_table, CLASS_TABLE_INIT, gc_malloc(), loader_t::interface_methods, and loader_t::used.
Referenced by vm_init().
bool bcl_is_assignable (class_t * src, class_t * dest)
Checks if the class src may be assigned to the class dest
Parameters
src A pointer to the source class
dest A pointer to the destination class
Returns
True if the types are assignable, false otherwise
Definition at line 208 of file loader.c.
References bcl_is_assignable(), class_is_array(), class_is_interface(), class_is_object(), class_t::elem_class, class_t::elem_type, im_is_present(), class_t::interface_manager, class_t::parent, and PT_REFERENCE.
Referenced by arraycopy_ref(), bcl_is_assignable(), interpreter(), KNI_IsAssignableFrom(), and KNI_IsInstanceOf().
void bcl_link_method (class_t * cl, method_t * method)
Executes the actual linking of a method, implements the METHOD_LOAD field
Parameters
cl The class owning the requesting method
method The method to be linked
Definition at line 2077 of file loader.c.
References method_t::code, method_t::cp, cp_get_class(), method_t::data, method_t::handlers, initialize_class(), load_bytecode(), load_exception_handlers(), method_is_linked(), method_is_main(), method_set_linked(), thread_self(), tm_lock(), tm_unlock(), and translate_bytecode().
Referenced by interpreter().
const uint8_t* bcl_link_opcode (const method_t * method, const uint8_t * lpc, internal_opcode_t opcode)
Link a *_PRELINK opcode. The function behaviour changes depending on the opcode however all that is needed for the opcode to be linked properly is done in this function (for example class initialization). The function returns the same program counter it receives, this is done to 'cast away the constness' of the program counter
Parameters
method The method holding the opcode to be processed
lpc The program-counter pointing to the opcode to be linked
opcode The opcode value, this is used at the contents of the memory pointed by the program-counter may change if more than one thread tries to link it at the same time
Returns
The program counter pointing to the linked opcode
Definition at line 2244 of file loader.c.
References ANEWARRAY_PRELINK, array_name(), bcl_resolve_class(), c_throw, CHECKCAST_PRELINK, class_get_dimensions(), class_get_id(), class_is_abstract(), class_is_parent(), class_is_super(), method_t::code, CONSTANT_Class, CONSTANT_Class_resolved, method_t::cp, cp_get_class(), cp_get_class_name(), cp_get_resolved_class(), cp_get_tag(), dbg_unreachable, field_t::descriptor, gc_free(), gc_malloc(), get_type_specific_opcode(), GETFIELD_PRELINK, GETSTATIC_PRELINK, initialize_class(), INSTANCEOF_PRELINK, INVOKEINTERFACE_PRELINK, INVOKESPECIAL_PRELINK, INVOKESTATIC_PRELINK, INVOKEVIRTUAL_PRELINK, JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_VIRTUALMACHINEERROR, LDC_PRELINK, LDC_W_PRELINK, method_create_packed_index(), method_is_init(), method_is_static(), MULTIANEWARRAY_PRELINK, class_t::name, method_t::name, NEW_FINALIZER, NEW_PRELINK, NEWARRAY_PRELINK, field_t::offset, PUTFIELD_PRELINK, PUTSTATIC_PRELINK, resolve_class(), resolve_instance_field(), resolve_method(), resolve_static_field(), store_int16_un, thread_self(), tm_lock(), and tm_unlock().
Referenced by interpreter().
void bcl_mark (void)
Asks the class loader to mark all its internal structures allocated on the Java heap or holding Java references
Definition at line 171 of file loader.c.
References class_get_object(), loader_t::class_table, static_field_t::data, field_is_reference(), field_itr_get_next(), field_itr_has_next(), gc_mark_reference(), field_t::offset, class_t::static_data, static_field_itr(), and loader_t::used.
Referenced by gc_mark().
void bcl_preload_bootstrap_classes (void)
Preload the classes needed during the bootstrap process
Definition at line 484 of file loader.c.
References bcl_set_array_class(), JAVA_LANG_CLASS_NREF_SIZE, JAVA_LANG_CLASS_REF_N, JAVA_LANG_STRING_NREF_SIZE, JAVA_LANG_STRING_REF_N, JAVA_LANG_THREAD_NREF_SIZE, JAVA_LANG_THREAD_REF_N, jsm_set_classes(), preload_class(), and T_CHAR.
Referenced by vm_run().
class_t* bcl_resolve_class (class_t * orig, const char * name)
Resolves a class
Parameters
orig The originating class
name The class' name
Returns
A pointer to the class
Definition at line 513 of file loader.c.
References bcl_find_class(), c_catch, c_rethrow, c_throw, c_try, class_is_array(), class_is_being_linked(), class_is_preloaded(), class_is_public(), loader_t::class_table, class_t::elem_class, gc_palloc(), get_new_class_id(), class_t::id, JAVA_LANG_NOCLASSDEFFOUNDERROR, load_class(), class_t::name, same_package(), tm_lock(), tm_unlock(), and utf8_intern().
Referenced by bcl_link_opcode(), init_dummy_methods(), interpreter(), java_lang_Class_forName(), KNI_ThrowNew(), load_class(), load_exception_handlers(), resolve_class(), and vm_run().
static void bcl_set_array_class (array_type_t type, class_t * cl) [inline, static]
Sets the class for the specified basic array type
Parameters
type The basic array type
cl A pointer to the array class
Definition at line 80 of file loader.h.
References T_BOOLEAN, and T_LONG.
Referenced by bcl_preload_bootstrap_classes(), and load_class().
Variable Documentation
class_t* array_classes[]
Basic array classes
Definition at line 80 of file loader.c.