loader.c File Reference
#include `wrappers.h`
#include `bytecode.h`
#include `class.h`
#include `classfile.h`
#include `constantpool.h`
#include `field.h`
#include `jstring.h`
#include `interpreter.h`
#include `loader.h`
#include `memory.h`
#include `method.h`
#include `opcodes.h`
#include `utf8_string.h`
#include `util.h`
#include `verifier.h`
#include `java_lang_Class.h`
#include `java_lang_ref_Reference.h`
#include `java_lang_ref_WeakReference.h`
#include `java_lang_String.h`
#include `java_lang_Thread.h`
#include `java_lang_Throwable.h`
#include `jelatine_VMResourceStream.h`
Data Structures
struct loader_t
Defines
#define CLASS_TABLE_INIT (16)
#define CLASS_TABLE_INC (16)
Typedefs
typedef struct loader_t loader_t
Functions
static void load_class (class_t *)
static uint32_t get_new_class_id (void)
static class_t * resolve_class (class_t *, uint16_t)
static class_t * preload_class (const char *, size_t, size_t)
static void initialize_static_fields (class_t *)
static void initialize_class (thread_t *, class_t *)
static void derive_class (class_t *, class_file_t *)
static void load_interfaces (class_t *, class_file_t *)
static void load_attributes (class_t *, class_file_t *)
static void grow_class_table (void)
static uint32_t next_interface_id (void)
static void load_methods (class_t *, class_file_t *, bool *)
static void load_method_attributes (class_t *, class_file_t *, method_attributes_t *)
static void load_method_attribute_Code (class_t *, class_file_t *, method_attributes_t *)
static void load_attribute_Code_attributes (class_t *, class_file_t *, method_attributes_t *)
static void load_method_attribute_Exceptions (class_t *, class_file_t *, method_attributes_t *)
static void assign_interface_indexes (method_manager_t *)
static void create_dispatch_table (class_t *)
static void create_interface_dispatch_table (class_t *)
static method_t * resolve_method (class_t *, uint16_t, bool)
static uint8_t * load_bytecode (class_t *, method_t *)
static exception_handler_t * load_exception_handlers (class_t *, method_t *, uint8_t *)
static void load_fields (class_t *, class_file_t *)
static void load_field_info (class_t *, class_file_t *, field_info_t *)
static void load_field_attributes (class_t *, class_file_t *, field_attributes_t *)
static void load_field_attribute_ConstantValue (class_t *, class_file_t *, field_attributes_t *)
static void layout_fields (class_t *)
static field_t * lookup_field (class_t **, const char *, const char *, bool)
static field_t * resolve_instance_field (class_t *, uint16_t)
static field_t * resolve_static_field (class_t *, uint16_t)
static uint8_t get_type_specific_opcode (uint8_t, const char *)
void bcl_init (void)
class_t * bcl_get_class_by_id (uint32_t id)
void bcl_mark (void)
bool bcl_is_assignable (class_t *src, class_t *dest)
void bcl_preload_bootstrap_classes (void)
class_t * bcl_resolve_class (class_t *orig, const char *name)
static void load_attributes (class_t *cl ATTRIBUTE_UNUSED, class_file_t *cf)
class_t * bcl_find_class (const char *name)
static void load_attribute_Code_attributes (class_t *cl ATTRIBUTE_UNUSED, class_file_t *cf, method_attributes_t *attr ATTRIBUTE_UNUSED)
static void load_method_attribute_Exceptions (class_t *cl ATTRIBUTE_UNUSED, class_file_t *cf, method_attributes_t *attr ATTRIBUTE_UNUSED)
static void load_field_attribute_ConstantValue (class_t *cl ATTRIBUTE_UNUSED, class_file_t *cf, field_attributes_t *attr)
void bcl_link_method (class_t *cl, method_t *method)
const uint8_t * bcl_link_opcode (const method_t *method, const uint8_t *lpc, internal_opcode_t opcode)
Variables
static loader_t bcl
class_t * array_classes [8] = { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }
Detailed Description
Bootstrap class-loader implementation
Definition in file loader.c.
Define Documentation
#define CLASS_TABLE_INC (16)
Increment of the class-table entries
Definition at line 57 of file loader.c.
#define CLASS_TABLE_INIT (16)
Number of entries in the class table after startup
Definition at line 54 of file loader.c.
Referenced by bcl_init().
Typedef Documentation
typedef struct loader_t loader_t
Typedef for struct loader_t
Definition at line 70 of file loader.c.
Function Documentation
static void assign_interface_indexes (method_manager_t * mm) [static]
Assigns the interface indexes to an interface methods'
Parameters
mm A pointer to the method manager
Definition at line 1263 of file loader.c.
References method_itr(), method_itr_get_next(), method_itr_has_next(), method_set_index(), and next_interface_id().
Referenced by derive_class().
class_t* bcl_find_class (const char * name)
Finds a class by its name
Parameters
name The class' name
Returns
A pointer to the class or NULL if none is found
Definition at line 955 of file loader.c.
References loader_t::class_table, class_t::name, tm_lock(), tm_unlock(), and loader_t::used.
Referenced by bcl_resolve_class(), KNI_FindClass(), load_class(), and thread_create_main().
class_t* bcl_get_class_by_id (uint32_t id)
Returns a pointer to the class corresponding to the given id
Parameters
id The id of the class
Returns
A pointer to the class corresponding to id
Definition at line 158 of file loader.c.
References loader_t::class_table, tm_lock(), and tm_unlock().
Referenced by gc_sweep(), interpreter(), java_lang_Class_getInternalName(), java_lang_Class_newInstance(), KNI_GetFieldID(), KNI_GetStaticFieldID(), KNI_GetSuperClass(), KNI_IsAssignableFrom(), and KNI_IsInstanceOf().
void bcl_init (void)
Initializes the bootstrap class loader
Definition at line 146 of file loader.c.
References loader_t::capacity, loader_t::class_table, CLASS_TABLE_INIT, gc_malloc(), loader_t::interface_methods, and loader_t::used.
Referenced by vm_init().
bool bcl_is_assignable (class_t * src, class_t * dest)
Checks if the class src may be assigned to the class dest
Parameters
src A pointer to the source class
dest A pointer to the destination class
Returns
True if the types are assignable, false otherwise
Definition at line 208 of file loader.c.
References bcl_is_assignable(), class_is_array(), class_is_interface(), class_is_object(), class_t::elem_class, class_t::elem_type, im_is_present(), class_t::interface_manager, class_t::parent, and PT_REFERENCE.
Referenced by arraycopy_ref(), bcl_is_assignable(), interpreter(), KNI_IsAssignableFrom(), and KNI_IsInstanceOf().
void bcl_link_method (class_t * cl, method_t * method)
Executes the actual linking of a method, implements the METHOD_LOAD field
Parameters
cl The class owning the requesting method
method The method to be linked
Definition at line 2077 of file loader.c.
References method_t::code, method_t::cp, cp_get_class(), method_t::data, method_t::handlers, initialize_class(), load_bytecode(), load_exception_handlers(), method_is_linked(), method_is_main(), method_set_linked(), thread_self(), tm_lock(), tm_unlock(), and translate_bytecode().
Referenced by interpreter().
const uint8_t* bcl_link_opcode (const method_t * method, const uint8_t * lpc, internal_opcode_t opcode)
Link a *_PRELINK opcode. The function behaviour changes depending on the opcode however all that is needed for the opcode to be linked properly is done in this function (for example class initialization). The function returns the same program counter it receives, this is done to 'cast away the constness' of the program counter
Parameters
method The method holding the opcode to be processed
lpc The program-counter pointing to the opcode to be linked
opcode The opcode value, this is used at the contents of the memory pointed by the program-counter may change if more than one thread tries to link it at the same time
Returns
The program counter pointing to the linked opcode
Definition at line 2244 of file loader.c.
References ANEWARRAY_PRELINK, array_name(), bcl_resolve_class(), c_throw, CHECKCAST_PRELINK, class_get_dimensions(), class_get_id(), class_is_abstract(), class_is_parent(), class_is_super(), method_t::code, CONSTANT_Class, CONSTANT_Class_resolved, method_t::cp, cp_get_class(), cp_get_class_name(), cp_get_resolved_class(), cp_get_tag(), dbg_unreachable, field_t::descriptor, gc_free(), gc_malloc(), get_type_specific_opcode(), GETFIELD_PRELINK, GETSTATIC_PRELINK, initialize_class(), INSTANCEOF_PRELINK, INVOKEINTERFACE_PRELINK, INVOKESPECIAL_PRELINK, INVOKESTATIC_PRELINK, INVOKEVIRTUAL_PRELINK, JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_VIRTUALMACHINEERROR, LDC_PRELINK, LDC_W_PRELINK, method_create_packed_index(), method_is_init(), method_is_static(), MULTIANEWARRAY_PRELINK, class_t::name, method_t::name, NEW_FINALIZER, NEW_PRELINK, NEWARRAY_PRELINK, field_t::offset, PUTFIELD_PRELINK, PUTSTATIC_PRELINK, resolve_class(), resolve_instance_field(), resolve_method(), resolve_static_field(), store_int16_un, thread_self(), tm_lock(), and tm_unlock().
Referenced by interpreter().
void bcl_mark (void)
Asks the class loader to mark all its internal structures allocated on the Java heap or holding Java references
Definition at line 171 of file loader.c.
References class_get_object(), loader_t::class_table, static_field_t::data, field_is_reference(), field_itr_get_next(), field_itr_has_next(), gc_mark_reference(), field_t::offset, class_t::static_data, static_field_itr(), and loader_t::used.
Referenced by gc_mark().
void bcl_preload_bootstrap_classes (void)
Preload the classes needed during the bootstrap process
Definition at line 484 of file loader.c.
References bcl_set_array_class(), JAVA_LANG_CLASS_NREF_SIZE, JAVA_LANG_CLASS_REF_N, JAVA_LANG_STRING_NREF_SIZE, JAVA_LANG_STRING_REF_N, JAVA_LANG_THREAD_NREF_SIZE, JAVA_LANG_THREAD_REF_N, jsm_set_classes(), preload_class(), and T_CHAR.
Referenced by vm_run().
class_t* bcl_resolve_class (class_t * orig, const char * name)
Resolves a class
Parameters
orig The originating class
name The class' name
Returns
A pointer to the class
Definition at line 513 of file loader.c.
References bcl_find_class(), c_catch, c_rethrow, c_throw, c_try, class_is_array(), class_is_being_linked(), class_is_preloaded(), class_is_public(), loader_t::class_table, class_t::elem_class, gc_palloc(), get_new_class_id(), class_t::id, JAVA_LANG_NOCLASSDEFFOUNDERROR, load_class(), class_t::name, same_package(), tm_lock(), tm_unlock(), and utf8_intern().
Referenced by bcl_link_opcode(), init_dummy_methods(), interpreter(), java_lang_Class_forName(), KNI_ThrowNew(), load_class(), load_exception_handlers(), resolve_class(), and vm_run().
static void create_dispatch_table (class_t * cl) [static]
Creates the virtual dispatch table
Parameters
cl A pointer to the current class
Definition at line 1277 of file loader.c.
References c_throw, class_t::dtable, class_t::dtable_count, gc_palloc(), JAVA_LANG_NOCLASSDEFFOUNDERROR, method_compare(), method_get_index(), method_is_final(), method_is_init(), method_is_private(), method_is_protected(), method_is_public(), method_is_static(), method_itr(), method_itr_get_next(), method_itr_has_next(), class_t::method_manager, method_set_index(), and class_t::parent.
Referenced by derive_class().
static void create_interface_dispatch_table (class_t * cl) [static]
Creates the interface dispatch table of a class
Parameters
cl A pointer to the current class
Definition at line 1372 of file loader.c.
References class_t::dtable, class_t::dtable_count, gc_palloc(), class_t::inames, method_t::index, interface_itr(), interface_itr_get_next(), interface_itr_has_next(), class_t::interface_manager, class_t::itable, class_t::itable_count, method_compare(), method_itr(), method_itr_get_next(), method_itr_has_next(), class_t::method_manager, mm_get_count(), and sort_asc_uint16_ptrs().
Referenced by derive_class().
static void derive_class (class_t * cl, class_file_t * cf) [static]
Derives the provided class structure from a class file
Parameters
cl The class structure which will hold the new class
cf The class-file of the class
Definition at line 742 of file loader.c.
References class_t::access_flags, assign_interface_indexes(), c_throw, cf_load_u2(), cf_load_u4(), class_is_abstract(), class_is_array(), class_is_final(), class_is_interface(), class_is_object(), class_is_public(), class_t::const_pool, cp_create(), cp_get_class_name(), cp_set_tag_and_data(), create_dispatch_table(), create_interface_dispatch_table(), JAVA_LANG_NOCLASSDEFFOUNDERROR, layout_fields(), load_attributes(), load_fields(), load_interfaces(), load_methods(), class_t::method_manager, class_t::name, class_t::parent, and resolve_class().
Referenced by load_class().
static uint32_t get_new_class_id (void) [static]
Get a new id for use in a class, also pre-allocate the corresponding entry in the class table
Returns
A new class id
Definition at line 425 of file loader.c.
References loader_t::capacity, grow_class_table(), and loader_t::used.
Referenced by bcl_resolve_class(), and preload_class().
static uint8_t get_type_specific_opcode (uint8_t opcode, const char * descriptor) [static]
Turns a non-typed GETSTATIC_PRELINK, PUTSTATIC_PRELINK, GETFIELD_PRELINK or PUTFIELD_PRELINK opcode into its typed version
Parameters
opcode The source opcode, either GETSTATIC_PRELINK, PUTSTATIC_PRELINK, GETFIELD_PRELINK or PUTFIELD_PRELINK
descriptor The field descriptor
Returns
The new opcode
Definition at line 2113 of file loader.c.
References dbg_unreachable, GETFIELD_PRELINK, GETSTATIC_PRELINK, PUTFIELD_PRELINK, and PUTSTATIC_PRELINK.
Referenced by bcl_link_opcode().
static void grow_class_table (void) [static]
Grows the class, dispatch and interface dispatch table and updates all the threads cached table pointers
Definition at line 977 of file loader.c.
References loader_t::capacity, loader_t::class_table, gc_free(), gc_malloc(), and loader_t::used.
Referenced by get_new_class_id().
static void initialize_class (thread_t * thread, class_t * cl) [static]
Executes the static initialization of class
Parameters
thread The thread trying to initialize the class
cl The class which will be initialized
Definition at line 667 of file loader.c.
References class_get_object(), class_is_being_initialized(), class_is_initialized(), class_is_object(), class_purge_initializer(), class_set_state(), CS_ERRONEOUS, CS_INITIALIZED, CS_INITIALIZING, thread_t::exception, class_t::init_thread, initialize_static_fields(), interpreter(), class_t::method_manager, mm_get(), monitor_enter(), monitor_exit(), class_t::parent, thread_notify(), and thread_wait().
Referenced by bcl_link_method(), bcl_link_opcode(), resolve_method(), and resolve_static_field().
static void initialize_static_fields (class_t * cl) [static]
Lays out and initializes the static fields of a class
Parameters
cl A class being initialized
Definition at line 581 of file loader.c.
References class_t::const_pool, cp_get_integer(), cp_get_long(), cp_get_ref(), static_field_t::data, dbg_unreachable, field_t::descriptor, static_field_t::field, field_itr_get_next(), field_itr_has_next(), gc_palloc(), field_t::offset, class_t::static_data, and static_field_itr().
Referenced by initialize_class().
static void layout_fields (class_t * cl) [static]
Layout the instance fields
Parameters
cl A pointer to the class structure
Definition at line 1756 of file loader.c.
References c_throw, class_get_nref_size(), class_get_ref_n(), dbg_unreachable, field_t::descriptor, field_itr_get_next(), field_itr_has_next(), class_t::fields, instance_field_itr(), JAVA_LANG_NOCLASSDEFFOUNDERROR, field_t::name, class_t::name, class_t::nref_size, field_t::offset, class_t::parent, class_t::ref_n, and size_ceil().
Referenced by derive_class().
static void load_attribute_Code_attributes (class_t *cl ATTRIBUTE_UNUSED, class_file_t * cf, method_attributes_t *attr ATTRIBUTE_UNUSED) [static]
Loads the attributes of a 'Code' attribute
Parameters
cl A pointer to the current class
cf A pointer to the class file
attr A pointer to a method_attributes_t structure used to hold the attribute data
Definition at line 1208 of file loader.c.
References c_throw, cf_load_u2(), cf_load_u4(), cf_seek(), cf_tell(), and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by load_method_attribute_Code().
static void load_attributes (class_t *cl ATTRIBUTE_UNUSED, class_file_t * cf) [static]
Loads a class attributes
All class attributes are ignored ATM
Parameters
cl A pointer to a class structure
cf A pointer to the class file
Definition at line 926 of file loader.c.
References c_throw, cf_load_u2(), cf_load_u4(), cf_seek(), cf_tell(), and JAVA_LANG_NOCLASSDEFFOUNDERROR.
Referenced by derive_class().
static uint8_t * load_bytecode (class_t * cl, method_t * method) [static]
Loads the bytecode of a method (and the exception handlers too) and return it
Parameters
cl A pointer to the class owning the method
method A pointer to the method to be loaded
Returns
The bytecode of the method
Definition at line 1574 of file loader.c.
References cf_close(), cf_load_u1(), cf_open(), cf_seek(), method_t::data, gc_malloc(), method_get_code_length(), method_is_synchronized(), class_t::name, and method_t::offset.
Referenced by bcl_link_method().
static void load_class (class_t * cl) [static]
Loads and links a class
Parameters
cl A pointer to the class to be loaded
Definition at line 302 of file loader.c.
References ACC_ABSTRACT, ACC_FINAL, ACC_PUBLIC, class_t::access_flags, bcl_find_class(), bcl_resolve_class(), bcl_set_array_class(), c_throw, cf_close(), cf_open(), class_is_array(), class_is_interface(), class_set_state(), class_t::const_pool, cp_create_dummy(), CS_LINKED, CS_LINKING, derive_class(), class_t::dimensions, class_t::dtable, class_t::elem_class, class_t::elem_type, class_t::fields, class_t::fields_n, gc_free(), gc_malloc(), gc_new(), class_t::id, java_lang_Class_t::id, class_t::inames, class_t::interface_manager, java_lang_Class_t::is_array, java_lang_Class_t::is_interface, class_t::itable, class_t::itable_count, JAVA_LANG_CLASS_REF2PTR, JAVA_LANG_NOCLASSDEFFOUNDERROR, class_t::method_manager, class_t::name, class_t::nref_size, class_t::obj, class_t::parent, prim_to_array_type(), and class_t::ref_n.
Referenced by bcl_resolve_class().
static exception_handler_t * load_exception_handlers (class_t * cl, method_t * method, uint8_t * code) [static]
Loads the exception handlers of a method
Parameters
cl A pointer to the class owning the method
method A pointer to the method to be loaded
code A pointer to the method code
Returns
The exception handlers of the method
Definition at line 1608 of file loader.c.
References bcl_resolve_class(), exception_handler_t::catch_type, cf_close(), cf_load_u2(), cf_open(), cf_seek(), method_t::code_length, method_t::data, exception_handler_t::end_pc, method_t::exception_table_length, gc_malloc(), exception_handler_t::handler_pc, method_is_synchronized(), class_t::name, method_t::offset, resolve_class(), and exception_handler_t::start_pc.
Referenced by bcl_link_method().
static void load_field_attribute_ConstantValue (class_t *cl ATTRIBUTE_UNUSED, class_file_t * cf, field_attributes_t * attr) [static]
Loads the field's ConstantValue attribute
Parameters
cl A pointer to the current class
cf A pointer to the class file
attr A pointer to a field_attributes_t structure used for storing the attribute data
Definition at line 1746 of file loader.c.
References cf_load_u2(), and field_attributes_t::constant_value_index.
Referenced by load_field_attributes().
static void load_field_attributes (class_t * cl, class_file_t * cf, field_attributes_t * attr) [static]
Loads a field's attributes
Parameters
cl A pointer to the class being loaded
cf A pointer to the class file from which to read the structure
attr A pointer to a field_attributes structure to be filled
The function stores the loaded attributes in the relevant fields of the attr parameter
Definition at line 1696 of file loader.c.
References c_throw, cf_load_u2(), cf_load_u4(), cf_seek(), cf_tell(), class_t::const_pool, field_attributes_t::constant_value_found, cp_get_string(), JAVA_LANG_NOCLASSDEFFOUNDERROR, and load_field_attribute_ConstantValue().
Referenced by load_fields().
static void load_field_info (class_t * cl, class_file_t * cf, field_info_t * info) [static]
Load a field_info structure from the class file pointed by cf
Parameters
cl A pointer to the class being loaded
cf A pointer to the class file from which to read the structure
info The file_info structure to be filled
Definition at line 1677 of file loader.c.
References field_info_t::access_flags, cf_load_u2(), class_t::const_pool, cp_get_string(), field_info_t::descriptor, and field_info_t::name.
Referenced by load_fields().
static void load_fields (class_t * cl, class_file_t * cf) [static]
Loads the class fields
Parameters
cl A pointer to a class being loaded
cf A pointer to the corresponding class file
Definition at line 1656 of file loader.c.
References cf_load_u2(), class_add_field(), class_alloc_fields(), load_field_attributes(), load_field_info(), and verify_field().
Referenced by derive_class().
static void load_interfaces (class_t * cl, class_file_t * cf) [static]
Loads and verifies the consistency of the interfaces from the specified class-file
Parameters
cl A pointer to a class structure
cf A pointer to the class-file representing the class
Definition at line 876 of file loader.c.
References c_throw, cf_load_u2(), class_is_interface(), im_add(), im_create(), im_flatten(), interface_itr(), interface_itr_get_next(), interface_itr_has_next(), class_t::interface_manager, JAVA_LANG_NOCLASSDEFFOUNDERROR, class_t::parent, and resolve_class().
Referenced by derive_class().
static void load_method_attribute_Code (class_t * cl, class_file_t * cf, method_attributes_t * attr) [static]
Load a method's 'Code' attribute
Parameters
cl A pointer to the current class
cf A pointer to the class file
attr A pointer to method_attributes_t structure used to store the attribute data
Definition at line 1171 of file loader.c.
References c_throw, cf_load_u2(), cf_load_u4(), cf_seek(), cf_tell(), method_attributes_t::code_length, method_attributes_t::code_offset, method_attributes_t::exception_table_length, JAVA_LANG_NOCLASSDEFFOUNDERROR, load_attribute_Code_attributes(), method_attributes_t::max_locals, and method_attributes_t::max_stack.
Referenced by load_method_attributes().
static void load_method_attribute_Exceptions (class_t *cl ATTRIBUTE_UNUSED, class_file_t * cf, method_attributes_t *attr ATTRIBUTE_UNUSED) [static]
Loads the Exceptions attribute of a method
Jelatine doesn't use this attribute actually even if it recognizes it as the virtual machine specification mentions that only the compiler should check which exceptions are thrown and which aren't
Parameters
cl A pointer to the current class
cf A pointer to the class file
attr A pointer to a method_attributes_t structure used to store the attribute data
Definition at line 1244 of file loader.c.
References cf_load_u2(), gc_free(), and gc_malloc().
Referenced by load_method_attributes().
static void load_method_attributes (class_t * cl, class_file_t * cf, method_attributes_t * attr) [static]
Load a method attributes
The function stores the retrieved attribute data in the structure pointed by the attr parameter
Parameters
cl A pointer to the class being loaded
cf A pointer to the class file
attr A pointer to an method_attribute_t structure
Definition at line 1112 of file loader.c.
References c_throw, cf_load_u2(), cf_load_u4(), cf_seek(), cf_tell(), method_attributes_t::code_found, class_t::const_pool, cp_get_string(), method_attributes_t::exceptions_found, JAVA_LANG_NOCLASSDEFFOUNDERROR, load_method_attribute_Code(), and load_method_attribute_Exceptions().
Referenced by load_methods().
static void load_methods (class_t * cl, class_file_t * cf, bool * finalizer) [static]
Creates the method table from the class-file representation
Parameters
cl A pointer to the class structure
cf A pointer to the class file
finalizer The pointed variable will hold true if the class has a finalizer, false otherwise
Definition at line 1013 of file loader.c.
References c_throw, cf_load_u2(), class_is_interface(), class_t::const_pool, cp_get_string(), method_t::descriptor, JAVA_LANG_NOCLASSDEFFOUNDERROR, load_method_attributes(), method_is_abstract(), method_is_native(), method_is_public(), method_is_static(), method_itr(), method_itr_get_next(), method_itr_has_next(), method_link_native(), class_t::method_manager, mm_add(), mm_create(), method_t::name, and class_t::name.
Referenced by derive_class().
static field_t * lookup_field (class_t ** pcl, const char * name, const char * descriptor, bool stat) [static]
Do a field lookup as described in the VM spec §5.4.3.2
Parameters
pcl A pointer to the class from which the lookup shall begin, filled with the class to which the field belongs when returning
name The field name
descriptor The field descriptor
stat true if the field is a static field, false otherwise
Returns
The requested field or NULL if the field could not be found, if the field is found but is not accessible from acl the function will throw an exception
Definition at line 1968 of file loader.c.
References class_get_field(), class_is_object(), interface_itr(), interface_itr_get_next(), interface_itr_has_next(), class_t::interface_manager, and class_t::parent.
Referenced by resolve_instance_field(), and resolve_static_field().
static uint32_t next_interface_id (void) [static]
Returns the next index for an interface method
Returns
The next index for an interface method
Definition at line 998 of file loader.c.
References loader_t::interface_methods.
Referenced by assign_interface_indexes().
static class_t * preload_class (const char * name, size_t ref_n, size_t nref_size) [static]
Preloads a class, the class structure is allocated and initialized only with its name, id and layout information. This is enough to enable the memory allocator to create new objects of the said class. Note that this function doesn't take the class lock, hence it can be used only during the bootstrap phase, all subsequent classes will be loaded using bcl_resolve_class()
Parameters
name The name of the class
ref_n The number of references of a class' instance
nref_size The size of the non-reference area of a class' instance
Returns
A pointer to the preloaded class
Definition at line 466 of file loader.c.
References class_set_state(), loader_t::class_table, CS_PRELOADED, gc_palloc(), get_new_class_id(), class_t::id, class_t::name, class_t::nref_size, class_t::ref_n, and utf8_intern().
Referenced by bcl_preload_bootstrap_classes().
static class_t * resolve_class (class_t * orig, uint16_t index) [static]
Resolves a class reference
Parameters
orig The originating class
index Indes in the constant-pool were the class descriptor lies
Returns
A pointer to the class
Definition at line 439 of file loader.c.
References bcl_resolve_class(), class_t::const_pool, CONSTANT_Class_resolved, cp_get_class_name(), cp_get_resolved_class(), cp_get_tag(), and cp_set_tag_and_data().
Referenced by bcl_link_opcode(), derive_class(), load_exception_handlers(), load_interfaces(), resolve_instance_field(), resolve_method(), and resolve_static_field().
static field_t * resolve_instance_field (class_t * acl, uint16_t index) [static]
Resolves an instance field
Parameters
acl A pointer to the class requesting the resolution
index An index in the class' constant pool holding the CONSTANT_Fieldref structure describing the field to be resolved
Returns
A pointer to the field, throws an exception if the field cannot be resolved or isn't found
Definition at line 2013 of file loader.c.
References class_t::const_pool, CONSTANT_Fieldref_resolved, cp_get_fieldref_class(), cp_get_fieldref_name(), cp_get_fieldref_type(), cp_get_resolved_instance_field(), cp_get_tag(), cp_set_tag_and_data(), lookup_field(), resolve_class(), and verify_field_access().
Referenced by bcl_link_opcode().
static method_t * resolve_method (class_t * src, uint16_t index, bool interface) [static]
Resolves a method if it wasn't already done
Parameters
src A pointer to the class requesting the resolution
index An index in the class' constant pool holding the CONSTANT_Methodref or CONSTANT_InterfaceMethodsref structure describing the method to be resolved
interface Set to true if the requested method belongs to an interface
Returns
A pointer to the method, throws an exception if the method cannot be resolved or isn't found
Definition at line 1438 of file loader.c.
References c_throw, class_is_abstract(), class_is_interface(), class_is_object(), class_is_parent(), class_t::const_pool, CONSTANT_InterfaceMethodref_resolved, CONSTANT_Methodref_resolved, cp_get_interfacemethodref_class(), cp_get_interfacemethodref_descriptor(), cp_get_interfacemethodref_name(), cp_get_methodref_class(), cp_get_methodref_descriptor(), cp_get_methodref_name(), cp_get_resolved_interfacemethod(), cp_get_resolved_method(), cp_get_tag(), cp_set_tag_and_data(), initialize_class(), interface_itr(), interface_itr_get_next(), interface_itr_has_next(), class_t::interface_manager, JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_VIRTUALMACHINEERROR, method_is_abstract(), method_is_init(), method_is_private(), method_is_protected(), method_is_public(), class_t::method_manager, mm_get(), class_t::parent, resolve_class(), same_package(), and thread_self().
Referenced by bcl_link_opcode().
static field_t * resolve_static_field (class_t * acl, uint16_t index) [static]
Resolves a static field
Parameters
acl A pointer to the class requesting the resolution
index An index in the class' constant pool holding the CONSTANT_Fieldref structure describing the field to be resolved
Returns
A pointer to the field, throws an exception if the field cannot be resolved or isn't found
Definition at line 2043 of file loader.c.
References class_t::const_pool, CONSTANT_Fieldref_resolved, cp_get_fieldref_class(), cp_get_fieldref_name(), cp_get_fieldref_type(), cp_get_resolved_static_field(), cp_get_tag(), cp_set_tag_and_data(), initialize_class(), lookup_field(), field_t::offset, resolve_class(), class_t::static_data, static_field_data_ptr(), thread_self(), and verify_field_access().
Referenced by bcl_link_opcode().
Variable Documentation
class_t* array_classes[8] = { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }
Basic array classes
Definition at line 80 of file loader.c.
loader_t bcl [static]
Bootstrap class loader
Definition at line 77 of file loader.c.