memory.c File Reference
#include `wrappers.h`
#include `class.h`
#include `header.h`
#include `loader.h`
#include `memory.h`
#include `thread.h`
#include `util.h`
#include `vm.h`
#include `java_lang_ref_WeakReference.h`
Data Structures
struct finalizable_t
struct small_chunk_t
struct large_chunk_t
struct heap_t
Defines
#define BIN_ENTRIES (16)
#define BIN_MAX_SIZE (BIN_ENTRIES * sizeof(jword_t))
#define HEAP_INIT_FRACTION (16)
#define TEMP_ROOT_INC (4)
Typedefs
typedef struct finalizable_t finalizable_t
typedef struct small_chunk_t small_chunk_t
typedef struct large_chunk_t large_chunk_t
typedef struct heap_t heap_t
Functions
static uintptr_t gc_alloc (size_t)
static void gc_purge_bin (void)
static void gc_mark (void)
static void gc_mark_finalizable (void)
static void gc_sweep (size_t)
static void gc_purge_weakref_list (void)
static void gc_grow (uintptr_t, size_t)
static void bitmap_set (uintptr_t)
static void bitmap_clear (uintptr_t)
static bool bitmap_get (uintptr_t)
static uintptr_t get_chunk (size_t)
static void put_chunk (uintptr_t, size_t)
void print_bin (void)
void gc_init (size_t size)
void gc_teardown (void)
void gc_enable (bool enable)
uintptr_t gc_new (class_t *cl)
uintptr_t gc_new_array_nonref (array_type_t type, int32_t count)
uintptr_t gc_new_array_ref (class_t *cl, int32_t count)
uintptr_t gc_new_multiarray (class_t *cl, uint8_t dimensions, jword_t *counts)
void gc_register_weak_ref (java_lang_ref_WeakReference_t *ref)
void gc_collect (size_t grow)
size_t gc_free_memory (void)
size_t gc_total_memory (void)
void gc_mark_potential (uintptr_t ref)
void gc_mark_reference (uintptr_t ref)
void * gc_malloc (size_t size)
void * gc_palloc (size_t size)
void gc_free (void *ptr)
Variables
static heap_t heap
Detailed Description
Garbage-collector and allocator implementation
Definition in file memory.c.
Define Documentation
#define BIN_ENTRIES (16)
Defines the number of entries in the chunk-bin
Definition at line 70 of file memory.c.
Referenced by gc_init(), and get_chunk().
#define BIN_MAX_SIZE (BIN_ENTRIES * sizeof(jword_t))
Defines the size of the largest chunk belonging to the small bin
Definition at line 73 of file memory.c.
Referenced by get_chunk(), and put_chunk().
#define HEAP_INIT_FRACTION (16)
Initial fraction of the provided heap to use
Definition at line 76 of file memory.c.
Referenced by gc_init().
#define TEMP_ROOT_INC (4)
Number of slots to add to the temporary root stack when growing it
Definition at line 79 of file memory.c.
Typedef Documentation
typedef struct finalizable_t finalizable_t
Typedef for the struct finalizable_t
Definition at line 48 of file memory.c.
typedef struct heap_t heap_t
Typedef for the struct heap_t
Definition at line 112 of file memory.c.
typedef struct large_chunk_t large_chunk_t
Typedef for the struct large_chunk_t
Definition at line 67 of file memory.c.
typedef struct small_chunk_t small_chunk_t
Typedef for the struct small_chunk_t
Definition at line 57 of file memory.c.
Function Documentation
static void bitmap_clear (uintptr_t ptr) [inline, static]
Clear an entry in the bitmap
Parameters
ptr A pointer in the garbage collected heap
Definition at line 1149 of file memory.c.
References heap_t::bitmap, and heap_t::start.
Referenced by gc_sweep().
static bool bitmap_get (uintptr_t ptr) [inline, static]
Read an entry of the bitmap
Parameters
ptr A pointer in the garbage collected heap
Definition at line 1159 of file memory.c.
References heap_t::bitmap, and heap_t::start.
Referenced by gc_mark_potential(), and gc_sweep().
static void bitmap_set (uintptr_t ptr) [inline, static]
Set an entry in the bitmap to 1
Parameters
ptr A pointer in the garbage collected heap
Definition at line 1139 of file memory.c.
References heap_t::bitmap, and heap_t::start.
Referenced by gc_new(), gc_new_array_nonref(), and gc_new_array_ref().
static uintptr_t gc_alloc (size_t size) [static]
Allocates a chunk of the specified size (in jwords) from the bin, calls the garbage collector if necessary and throws an exception if unable to satisfy the request. The returned memory will have already been cleared
Parameters
size The chunk size in jwords
Returns
A chunk of memory carved from the garbage collected heap
Definition at line 745 of file memory.c.
References dbg_error, gc_collect(), get_chunk(), and vm_fail().
Referenced by gc_malloc(), gc_new(), gc_new_array_nonref(), and gc_new_array_ref().
void gc_collect (size_t grow)
Launches the garbage collector on the provided heap structure
Parameters
grow If non null, specifies the amount of bytes of the next allocation, the heap will be grown after the collection to accomodate it if not enough free space was reclaimed
Definition at line 485 of file memory.c.
References heap_t::collect, heap_t::end, gc_grow(), gc_mark(), gc_mark_finalizable(), gc_purge_bin(), gc_purge_weakref_list(), gc_sweep(), jsm_purge(), tm_lock(), tm_purge(), tm_stop_the_world(), and tm_unlock().
Referenced by gc_alloc(), and java_lang_Runtime_gc().
void gc_enable (bool enable)
Enables or disables the collector
Parameters
enable new status of the collector
Definition at line 227 of file memory.c.
References heap_t::collect.
Referenced by vm_run().
void gc_free (void * ptr)
Frees a previously allocated C object.
If ptr is NULL no action is taken
Parameters
ptr A pointer to the object to be fred
Definition at line 1076 of file memory.c.
References header_get_size(), heap_t::perm, put_chunk(), heap_t::start, tm_lock(), and tm_unlock().
Referenced by bcl_link_opcode(), c_clear_exception(), cf_close(), cf_open_with_classpath(), cp_create(), grow_class_table(), im_add(), im_flatten(), java_lang_Class_forName(), jsm_rehash(), jsm_rehash_literals(), load_class(), load_method_attribute_Exceptions(), method_purge(), string_manager_rehash(), thread_create_main(), thread_launch(), thread_push_root(), thread_start(), tm_purge(), and tm_rehash().
size_t gc_free_memory (void)
Helper function used for implementing Runtime.freeMemory(), returns the amount of free memory in bytes
Returns
The amount of free memory in bytes
Definition at line 521 of file memory.c.
References heap_t::bin, heap_t::large_bin, large_chunk_t::next, small_chunk_t::next, large_chunk_t::size, heap_t::size, tm_lock(), and tm_unlock().
Referenced by java_lang_Runtime_freeMemory().
void gc_grow (uintptr_t end, size_t size) [static]
Grow the heap by size bytes (if possible).
A new chunk will be added to the chunk bin holding the new memory area starting from end. end might be different from the current heap end so that the last free chunk can be grown directly
Parameters
end A pointer to the last free chunk of memory
size The amount of bytes to be added to the heap
Definition at line 468 of file memory.c.
References heap_t::end, heap_t::perm, put_chunk(), heap_t::size, and heap_t::start.
Referenced by gc_collect(), and gc_sweep().
void gc_init (size_t size)
Initializes the heap, throws an exception upon failure
Note that if a heap of less than 32 KiB is requested the function will default to 32 KiB anyway as mandated by the CLDC configuration. If you want to use a heap smaller than 32 KiB you have to explicitely change this function, do it at your own risk. All the pointers in the heap structure are explicitely aligned to 4 or 8-bytes boundaries depending on the target machine
Parameters
size Size in bytes of the unified heap
Definition at line 163 of file memory.c.
References heap_t::bin, BIN_ENTRIES, heap_t::bitmap, heap_t::collect, dbg_error, heap_t::end, HEAP_INIT_FRACTION, heap_t::large_bin, heap_t::max_size, heap_t::memory, heap_t::perm, put_chunk(), heap_t::size, size_ceil(), size_floor(), heap_t::start, vm_fail(), and heap_t::weakref_list.
Referenced by vm_init().
void* gc_malloc (size_t size)
Allocates a chunk of memory for holding C objects, throws an exception upon failure, the returned memory has already been zeroed.
If the allocation size is zero the function will return a NULL pointer. The allocation size is rounded to a multiple of 4 or 8 bytes depending on the target
Parameters
size The size in bytes of the chunk to be allocated
Returns
A pointer to the newly allocated memory
Definition at line 1002 of file memory.c.
References gc_alloc(), header_create_c(), size_ceil(), tm_lock(), and tm_unlock().
Referenced by bcl_init(), bcl_link_opcode(), c_throw_dbg(), cf_open_with_classpath(), cp_create(), gc_palloc(), grow_class_table(), im_add(), java_to_utf8(), jsm_init(), jsm_rehash(), jsm_rehash_literals(), load_bytecode(), load_class(), load_exception_handlers(), load_method_attribute_Exceptions(), monitor_init(), string_manager_init(), string_manager_rehash(), thread_create_main(), thread_launch(), thread_push_root(), thread_start(), thread_wait(), tm_rehash(), and vm_run().
static void gc_mark (void) [static]
Executes the 'gc_mark' phase of the garbage collector
The gc_mark phase consists in scanning the root objects (threads and stacks basically) for references to objects in the heap. Each of these object is then marked as live and its references explored in turn and so on until all the live objects are found and marked. The recursive descent algorythm uses the pointer-reversal trick to avoid using an implicit/explicit stack, the gc is thus completely self-contained and cannot fail due to a stack overflow
Definition at line 813 of file memory.c.
References bcl_mark(), jsm_mark(), and tm_mark().
Referenced by gc_collect().
static void gc_mark_finalizable (void) [static]
After the gc_mark phase executed checks the finalizable obejcts. The ones which haven't been marked and thus are dead are 'resurrected' by marking them and moved to the list of objects to be finalized. Once the finalizer thread has processed them they will be lost forever
Definition at line 825 of file memory.c.
References gc_mark_reference(), header_is_marked(), monitor_enter(), monitor_exit(), finalizable_t::next, finalizable_t::ref, thread_notify(), and thread_self().
Referenced by gc_collect().
void gc_mark_potential (uintptr_t ref)
Check if a reference is a pointer and recursively gc_mark it if it is
Parameters
ref A reference to a Java object
Definition at line 563 of file memory.c.
References bitmap_get(), heap_t::end, gc_mark_reference(), and heap_t::start.
Referenced by tm_mark().
void gc_mark_reference (uintptr_t ref)
Marks the object pointed by ref and recursively all the objects pointed by the references it contains
Parameters
ref A reference to a Java object
Definition at line 593 of file memory.c.
References array_get_ref_n(), class_get_ref_n(), class_is_array(), class_t::elem_type, gc_mark_reference(), header_get_class(), header_is_marked(), header_is_object(), header_set_mark(), and PT_REFERENCE.
Referenced by bcl_mark(), gc_mark_finalizable(), gc_mark_potential(), gc_mark_reference(), jsm_mark(), and tm_mark().
uintptr_t gc_new (class_t * cl)
Allocates a managed object of the specified class
If not enough memory is avaible an exception is thrown, note that the returned reference points to the object header, not to the first word of the object.
Parameters
cl A pointer to the object class
Returns
A reference to the newly created object, throws an exception upon failure
Definition at line 242 of file memory.c.
References bitmap_set(), class_get_nref_size(), class_get_ref_n(), gc_alloc(), header_create_object(), heap_t::size, size_ceil(), tm_lock(), and tm_unlock().
Referenced by interpreter(), java_lang_Class_newInstance(), jstring_create_from_unicode(), jstring_create_from_utf8(), jstring_create_literal(), KNI_ThrowNew(), load_class(), thread_create_main(), and vm_run().
uintptr_t gc_new_array_nonref (array_type_t type, int32_t count)
Creates a new array of the specified type
Parameters
type The basic array class type requested
count The number of elements
Returns
A reference to the newly created array
Definition at line 284 of file memory.c.
References array_elem_size(), bcl_array_class(), bitmap_set(), gc_alloc(), array_t::header, header_create_object(), array_t::length, heap_t::size, size_ceil(), size_div_inf(), T_BOOLEAN, tm_lock(), and tm_unlock().
Referenced by gc_new_multiarray(), interpreter(), jstring_create_from_unicode(), jstring_create_from_utf8(), and jstring_create_literal().
uintptr_t gc_new_array_ref (class_t * cl, int32_t count)
Creates a new array of references
Parameters
cl A pointer to the corresponding class
count The number of elements
Returns
A pointer to the newly created array
Definition at line 320 of file memory.c.
References bitmap_set(), gc_alloc(), ref_array_t::header, header_create_object(), ref_array_t::length, heap_t::size, size_ceil(), tm_lock(), and tm_unlock().
Referenced by arraycopy_ref(), gc_new_multiarray(), interpreter(), and vm_run().
uintptr_t gc_new_multiarray (class_t * cl, uint8_t dimensions, jword_t * counts)
Helper function used for creating multi-dimensional arrays
Parameters
cl A pointer to the corresponding class
dimensions The number of dimensions to be created
counts A pointer to the element counts
Returns
A pointer to the newly created array
Definition at line 357 of file memory.c.
References array_ref_get_data(), class_t::elem_class, class_t::elem_type, gc_new_array_nonref(), gc_new_array_ref(), gc_new_multiarray(), prim_to_array_type(), PT_REFERENCE, thread_pop_root(), and thread_push_root().
Referenced by gc_new_multiarray(), and interpreter().
void* gc_palloc (size_t size)
Allocates a chunk of permanent memory for holding C objects, throws an exception upon failure, the returned memory has already been zeroed.
The memory allocated with this function cannot be fred with gc_free()
Parameters
size The size in bytes of the chunk to be allocated
Returns
A pointer to the newly allocated memory
Definition at line 1037 of file memory.c.
References heap_t::end, gc_malloc(), heap_t::perm, size_ceil(), tm_lock(), and tm_unlock().
Referenced by bcl_resolve_class(), class_alloc_fields(), classpath_init(), cp_create(), create_dispatch_table(), create_interface_dispatch_table(), im_create(), im_flatten(), initialize_static_fields(), mm_create(), preload_class(), and utf8_intern().
static void gc_purge_bin (void) [static]
Purges the free chunks bin
This function also clears the free chunks left in the bin so that the garbage collector can reclaim the space they hold and aggregate them with other potentially free chunks surrounding them
Definition at line 771 of file memory.c.
References heap_t::bin, heap_t::large_bin, large_chunk_t::next, small_chunk_t::next, and large_chunk_t::size.
Referenced by gc_collect().
static void gc_purge_weakref_list (void) [static]
Purges the weak reference list by cleaning all the weak references which point to weakly reachable (or non-reachable) objects and removing all the non-reachable weak references
Definition at line 1102 of file memory.c.
References java_lang_ref_WeakReference_t::header, header_is_marked(), java_lang_ref_WeakReference_t::next, java_lang_ref_WeakReference_t::referent, and heap_t::weakref_list.
Referenced by gc_collect().
void gc_register_weak_ref (java_lang_ref_WeakReference_t * ref)
Adds a new object to the weak reference list
Parameters
ref A reference to the object to be added to the weak reference list
Definition at line 452 of file memory.c.
References java_lang_ref_WeakReference_t::next, tm_lock(), tm_unlock(), and heap_t::weakref_list.
Referenced by java_lang_ref_WeakReference_addToWeakReferenceList().
static void gc_sweep (size_t size) [static]
Scans the heap for live objects and reclaims dead ones replenishing the free list
Parameters
size The size of the allocation which triggered the collection, if no chunk of free space larger or equal to this value is fred the heap must be grown of at least this value
Definition at line 875 of file memory.c.
References array_get_nref_size(), array_get_ref_n(), bcl_get_class_by_id(), bitmap_clear(), bitmap_get(), class_get_nref_size(), class_get_ref_n(), class_is_array(), heap_t::end, gc_grow(), header_clear_mark(), header_get_class(), header_get_size(), header_is_marked(), header_is_object(), HEADER_RESERVED, header_set_mark(), heap_t::max_size, put_chunk(), size_ceil(), size_max(), and heap_t::start.
Referenced by gc_collect().
void gc_teardown (void)
Disposes the unified heap
Definition at line 219 of file memory.c.
References heap_t::memory.
Referenced by vm_teardown().
size_t gc_total_memory (void)
Helper function used for implementing Runtime.totalMemory(), returns the amount of memory available to the VM in bytes
Returns
The amount of memory available to the VM in bytes
Definition at line 555 of file memory.c.
References heap_t::size.
Referenced by java_lang_Runtime_totalMemory().
static uintptr_t get_chunk (size_t size) [static]
Pulls a chunk from the bin
Parameters
size The minimum size (in words) requested
Returns
A chunk if one large enough is avaible, otherwise NULL
Definition at line 1170 of file memory.c.
References heap_t::bin, BIN_ENTRIES, BIN_MAX_SIZE, heap_t::large_bin, large_chunk_t::next, small_chunk_t::next, put_chunk(), and large_chunk_t::size.
Referenced by gc_alloc().
void print_bin (void)
Prints information on the free chunk's bin, used for debug purposes
Definition at line 1261 of file memory.c.
References heap_t::bin, heap_t::large_bin, large_chunk_t::next, small_chunk_t::next, and large_chunk_t::size.
static void put_chunk (uintptr_t chunk, size_t size) [static]
Put a free memory chunk in the bin
Parameters
chunk A pointer to the memory chunk to be put in the bin
size The size of the chunk, can be zero in which case the function won't do anything
Definition at line 1234 of file memory.c.
References heap_t::bin, BIN_MAX_SIZE, heap_t::large_bin, large_chunk_t::next, small_chunk_t::next, and large_chunk_t::size.
Referenced by gc_free(), gc_grow(), gc_init(), gc_sweep(), and get_chunk().
Variable Documentation
heap_t heap [static]
The virtual machine heap
Definition at line 146 of file memory.c.