method.h File Reference
#include `wrappers.h`
#include `constantpool.h`
#include `util.h`
Data Structures
struct exception_handler_t
struct method_t
struct method_manager_t
struct method_iterator_t
Defines
#define JELATINE_METHOD_H (1)
#define METHOD_ARGUMENTS_BITS (4)
#define METHOD_ARGUMENTS_MAX (1 << METHOD_ARGUMENTS_BITS)
#define METHOD_ARGUMENTS_MASK (METHOD_ARGUMENTS_MAX - 1)
#define METHOD_INDEX_BITS (12)
#define METHOD_INDEX_MAX (1 << METHOD_INDEX_BITS)
#define METHOD_INDEX_SHIFT (METHOD_ARGUMENTS_BITS)
Typedefs
typedef enum return_value_t return_value_t
typedef struct exception_handler_t exception_handler_t
typedef void(* native_proto_t)(void)
typedef struct method_t method_t
typedef struct method_manager_t method_manager_t
typedef struct method_iterator_t method_iterator_t
Enumerations
enum return_value_t {
RET_VOID = 0,
RET_INT = 1,
RET_LONG = 2,
RET_OBJECT = 3,
RET_FLOAT = 4,
RET_DOUBLE = 5
 }
Functions
method_manager_t * mm_create (uint32_t)
method_t * mm_get (method_manager_t *, char *, char *)
uint32_t mm_get_count (method_manager_t *)
void mm_add (method_manager_t *, char *, char *, uint16_t, const_pool_t *, method_attributes_t *)
void init_dummy_methods (void)
bool method_compare (const method_t *, const method_t *)
void method_link_native (method_t *, char *)
void method_purge (method_t *)
uint32_t method_get_code_length (const method_t *)
bool method_is_init (const method_t *)
uint16_t method_create_packed_index (const method_t *)
static uint16_t method_unpack_arguments (uint16_t m)
static uint16_t method_unpack_index (uint16_t m)
static bool method_is_public (const method_t *m)
static bool method_is_protected (const method_t *m)
static bool method_is_private (const method_t *m)
static bool method_is_native (const method_t *m)
static bool method_is_static (const method_t *m)
static bool method_is_final (const method_t *m)
static bool method_is_synchronized (const method_t *m)
static bool method_is_abstract (const method_t *m)
static void method_set_linked (method_t *m)
static bool method_is_linked (const method_t *m)
static bool method_is_main (const method_t *m)
static void method_set_index (method_t *method, uint16_t index)
static uint16_t method_get_index (const method_t *method)
static method_iterator_t method_itr (method_manager_t *mm)
static bool method_itr_has_next (method_iterator_t itr)
static method_t * method_itr_get_next (method_iterator_t *itr)
Variables
method_t halt_method
Detailed Description
Method structure and interface
Definition in file method.h.
Define Documentation
#define JELATINE_METHOD_H (1)
method.h inclusion macro
Definition at line 28 of file method.h.
#define METHOD_ARGUMENTS_BITS (4)
Defines the number of bits of a method index used for encoding the number of arguments the method accepts
Definition at line 45 of file method.h.
Referenced by method_create_packed_index().
#define METHOD_ARGUMENTS_MASK (METHOD_ARGUMENTS_MAX - 1)
Defines a bit mask to extract the number of arguments of a method
Definition at line 51 of file method.h.
#define METHOD_ARGUMENTS_MAX (1 << METHOD_ARGUMENTS_BITS)
Defines the maximum number of arguments accepted by a method
Definition at line 48 of file method.h.
Referenced by parse_method_descriptor().
#define METHOD_INDEX_BITS (12)
Defines the number of bits of a method index used for encoding the actual index in the dispatch table
Definition at line 55 of file method.h.
#define METHOD_INDEX_MAX (1 << METHOD_INDEX_BITS)
Defines the maximum number of methods which can be declared by a class
Definition at line 58 of file method.h.
#define METHOD_INDEX_SHIFT (METHOD_ARGUMENTS_BITS)
Defines the shift value used to extract the actual method index from the index encoded in the bytecode
Definition at line 62 of file method.h.
Typedef Documentation
typedef struct exception_handler_t exception_handler_t
Typedef for struct exception_handler_t
Definition at line 89 of file method.h.
typedef struct method_iterator_t method_iterator_t
Typedef for the struct method_iterator_t type
Definition at line 313 of file method.h.
typedef struct method_manager_t method_manager_t
Typedef for struct method_manager_t
Definition at line 131 of file method.h.
typedef struct method_t method_t
Typedef for struct method_t
Definition at line 118 of file method.h.
typedef void(* native_proto_t)(void)
Native methods function pointer type
Definition at line 92 of file method.h.
typedef enum return_value_t return_value_t
Typedef for the enum return_value_t type
Definition at line 77 of file method.h.
Enumeration Type Documentation
enum return_value_t
Represents the basic return type of a method, currently used only for native methods
Enumerator:
RET_VOID
 No return value.
RET_INT
 boolean, byte, char, short or int return value
RET_LONG
 long return value
RET_OBJECT
 Object reference return value.
RET_FLOAT
 Float return value.
RET_DOUBLE
 Double return value.
Definition at line 67 of file method.h.
Function Documentation
void init_dummy_methods (void)
Initializes the dummy methods used by the interpreter
Definition at line 85 of file method.c.
References bcl_resolve_class(), exception_handler_t::catch_type, method_t::cp, cp_create_dummy(), method_t::data, and method_t::handlers.
Referenced by vm_run().
bool method_compare (const method_t * method1, const method_t * method2)
Compares two methods signatures
Parameters
method1 A pointer to a method structure
method2 A pointer to a method structure
Returns
true if the method signatures match, false otherwise
Definition at line 461 of file method.c.
References method_t::descriptor, and method_t::name.
Referenced by create_dispatch_table(), and create_interface_dispatch_table().
uint16_t method_create_packed_index (const method_t * method)
Creates the packed index of a method
Parameters
method A pointer to a method
Returns
The packed index
Definition at line 423 of file method.c.
References method_t::args_size, method_t::index, and METHOD_ARGUMENTS_BITS.
Referenced by bcl_link_opcode().
uint32_t method_get_code_length (const method_t * method)
Gets the length of a method code, the length is automatically adjusted if extra opcodes were added by the translator
Parameters
method A pointer to a method structure
Returns
The length of the bytecode in bytes
Definition at line 447 of file method.c.
References method_t::code_length, and method_is_synchronized().
Referenced by load_bytecode(), and translate_bytecode().
static uint16_t method_get_index (const method_t * method) [inline, static]
Gets the index of a method
Parameters
method A pointer to a method structure
Definition at line 295 of file method.h.
References method_t::index.
Referenced by create_dispatch_table().
static bool method_is_abstract (const method_t * m) [inline, static]
Checks if a method is abstract
Parameters
m A pointer to a method
Returns
true if the method is abstract, false otherwise
Definition at line 252 of file method.h.
References method_t::access_flags.
Referenced by load_methods(), and resolve_method().
static bool method_is_final (const method_t * m) [inline, static]
Checks if a method is final
Parameters
m A pointer to a method
Returns
true if the method is final, false otherwise
Definition at line 234 of file method.h.
References method_t::access_flags.
Referenced by create_dispatch_table().
bool method_is_init (const method_t * method)
Returns true if the method is an initialization method
Parameters
method A pointer to a method
Returns
true if an initialization method was passed to the function, false otherwise
Definition at line 433 of file method.c.
References method_t::name.
Referenced by bcl_link_opcode(), create_dispatch_table(), method_check_access_flags(), and resolve_method().
static bool method_is_linked (const method_t * m) [inline, static]
Checks if a method has been linked
Parameters
m A pointer to a method
Returns
true if the method has been linked, false otherwise
Definition at line 269 of file method.h.
References method_t::access_flags.
Referenced by bcl_link_method().
static bool method_is_main (const method_t * m) [inline, static]
Checks if a method is the main() method
Parameters
m A pointer to a method
Returns
true if the method is the main() method, false otherwise
Definition at line 278 of file method.h.
References method_t::access_flags.
Referenced by bcl_link_method().
static bool method_is_native (const method_t * m) [inline, static]
Checks if a method is native
Parameters
m A pointer to a method
Returns
true if the method is native, false otherwise
Definition at line 216 of file method.h.
References method_t::access_flags.
Referenced by load_methods(), and vm_run().
static bool method_is_private (const method_t * m) [inline, static]
Checks if a method is private
Parameters
m A pointer to a method
Returns
true if the method is private, false otherwise
Definition at line 207 of file method.h.
References method_t::access_flags.
Referenced by create_dispatch_table(), and resolve_method().
static bool method_is_protected (const method_t * m) [inline, static]
Checks if a method is protected
Parameters
m A pointer to a method
Returns
true if the method is protected, false otherwise
Definition at line 198 of file method.h.
References method_t::access_flags.
Referenced by create_dispatch_table(), and resolve_method().
static bool method_is_public (const method_t * m) [inline, static]
Checks if a method is public
Parameters
m A pointer to a method
Returns
true if the method is public, false otherwise
Definition at line 189 of file method.h.
References method_t::access_flags.
Referenced by create_dispatch_table(), load_methods(), resolve_method(), and vm_run().
static bool method_is_static (const method_t * m) [inline, static]
Checks if a method is static
Parameters
m A pointer to a method
Returns
true if the method is static, false otherwise
Definition at line 225 of file method.h.
References method_t::access_flags.
Referenced by bcl_link_opcode(), create_dispatch_table(), interpreter(), load_methods(), parse_method_descriptor(), translate_bytecode(), and vm_run().
static bool method_is_synchronized (const method_t * m) [inline, static]
Checks if a method is synchronized
Parameters
m A pointer to a method
Returns
true if the method is synchronized, false otherwise
Definition at line 243 of file method.h.
References method_t::access_flags.
Referenced by interpreter(), load_bytecode(), load_exception_handlers(), method_get_code_length(), and translate_bytecode().
static method_iterator_t method_itr (method_manager_t * mm) [inline, static]
Creates a method iterator from the method manager mm
Parameters
mm A pointer to the method manager
Returns
An initialized method iterator
Definition at line 319 of file method.h.
References method_manager_t::entries, method_iterator_t::entries, method_iterator_t::index, method_manager_t::methods, and method_iterator_t::methods.
Referenced by assign_interface_indexes(), create_dispatch_table(), create_interface_dispatch_table(), and load_methods().
static method_t* method_itr_get_next (method_iterator_t * itr) [inline, static]
Returns the next method, if the iterator has just been created it returns the data of the first field (if it is present)
Parameters
itr A pointer to the field iterator
Returns
A pointer to an instance field
Definition at line 344 of file method.h.
References method_iterator_t::index, method_itr_has_next(), and method_iterator_t::methods.
Referenced by assign_interface_indexes(), create_dispatch_table(), create_interface_dispatch_table(), and load_methods().
static bool method_itr_has_next (method_iterator_t itr) [inline, static]
Returns true if another method is available
Parameters
itr A method iterator
Returns
true if there are more methods, false otherwise
Definition at line 334 of file method.h.
References method_iterator_t::entries, and method_iterator_t::index.
Referenced by assign_interface_indexes(), create_dispatch_table(), create_interface_dispatch_table(), load_methods(), and method_itr_get_next().
void method_link_native (method_t * method, char * class_name)
Link a native method
Parameters
method A pointer to the method
class_name The name of the class the method belongs to
Definition at line 476 of file method.c.
References method_t::access_flags, c_throw, method_t::code, method_t::data, dbg_unreachable, method_t::descriptor, method_t::function, JAVA_LANG_NOCLASSDEFFOUNDERROR, method_t::name, native_method_code, native_method_lookup(), and method_t::return_type.
Referenced by load_methods().
void method_purge (method_t * method)
Frees the code and exception handlers of a method
Parameters
method A pointer to the method
Definition at line 516 of file method.c.
References method_t::code, method_t::data, gc_free(), and method_t::handlers.
Referenced by class_purge_initializer().
static void method_set_index (method_t * method, uint16_t index) [inline, static]
Sets the index of a method
Parameters
method A pointer to a method structure
index The method index
Definition at line 287 of file method.h.
References method_t::index.
Referenced by assign_interface_indexes(), and create_dispatch_table().
static void method_set_linked (method_t * m) [inline, static]
Sets the ACC_LINKED flag of a method
Parameters
m A pointer to a method
Definition at line 260 of file method.h.
References method_t::access_flags.
Referenced by bcl_link_method().
static uint16_t method_unpack_arguments (uint16_t m) [inline, static]
Gets the size in stack slots of the arguments packed into the translated bytecode
Parameters
m The packed method index as found in the translated bytecode
Returns
The size in stack slots of the arguments
Definition at line 171 of file method.h.
Referenced by interpreter().
static uint16_t method_unpack_index (uint16_t m) [inline, static]
Gets the index of a method packed into the translated bytecode
Parameters
m The packed method index as found in the translated bytecode
Returns
The actual method index
Definition at line 180 of file method.h.
Referenced by interpreter().
void mm_add (method_manager_t * mm, char * name, char * descriptor, uint16_t access_flags, const_pool_t * cp, method_attributes_t * attr)
Adds a new method to the method manager
Parameters
mm The method manager
name The method name
descriptor The method descriptor
access_flags Access flags of the method
cp The method's constant pool
attr The method attributes
Definition at line 324 of file method.c.
References abstract_method_code, ACC_ABSTRACT, ACC_NATIVE, method_t::access_flags, c_throw, method_t::code, method_attributes_t::code_found, method_attributes_t::code_length, method_t::code_length, method_attributes_t::code_offset, method_t::cp, method_t::data, method_t::descriptor, method_manager_t::entries, method_attributes_t::exception_table_length, method_t::exception_table_length, method_t::handlers, JAVA_LANG_NOCLASSDEFFOUNDERROR, load_method_code, method_attributes_t::max_locals, method_t::max_locals, method_attributes_t::max_stack, method_t::max_stack, method_check_access_flags(), method_manager_t::methods, mm_get(), method_t::name, method_t::offset, parse_method_descriptor(), and method_manager_t::reserved.
Referenced by load_methods().
method_manager_t* mm_create (uint32_t count)
Creates a method manager
Parameters
count The number of methods the manager will hold
Returns
A pointer to the newly created method manager
Definition at line 98 of file method.c.
References gc_palloc(), method_manager_t::methods, and method_manager_t::reserved.
Referenced by load_methods().
method_t* mm_get (method_manager_t * mm, char * name, char * descriptor)
Finds a method by its name and descriptor, returns NULL if the method is not found
Parameters
mm A pointer to the method manager
name The method name
descriptor The method descriptor
Returns
A pointer to the method if it was found, NULL otherwise
Definition at line 397 of file method.c.
References method_t::descriptor, method_manager_t::entries, method_manager_t::methods, and method_t::name.
Referenced by class_purge_initializer(), initialize_class(), java_lang_Class_newInstance(), java_lang_Thread_start(), mm_add(), resolve_method(), and vm_run().
uint32_t mm_get_count (method_manager_t * mm)
Returns the number of methods in the manager
Parameters
mm A pointer to the method manager
Returns
The number of methods in the manager
Definition at line 414 of file method.c.
References method_manager_t::entries.
Referenced by create_interface_dispatch_table().
Variable Documentation
method_t halt_method
Dummy method used to halt the interpreter
Basically the main() method of the first thread (or the run() method of user-created threads) return to this method when they are done and this method halts the interpreter execution. This method also contains a fake exception handler which catches all possible exceptions and then deals with them as uncatched exceptions
Halt method structure
Definition at line 54 of file method.c.
Referenced by interpreter(), and prepare_for_call().