native.c File Reference
#include `wrappers.h`
#include `interpreter.h`
#include `jstring.h`
#include `kni.h`
#include `loader.h`
#include `native.h`
#include `thread.h`
#include `utf8_string.h`
#include `util.h`
#include `vm.h`
#include `java_lang_String.h`
#include `java_lang_Thread.h`
#include `native_exts/lejos_nxj_ext.h`
#include `native_exts/lejos_nxj_ext_astruct.h`
Data Structures
struct native_method_desc_t
Typedefs
typedef struct native_method_desc_t native_method_desc_t
Functions
static KNI_RETURNTYPE_OBJECT java_lang_Class_forName (void)
static KNI_RETURNTYPE_OBJECT java_lang_Class_getInternalName (void)
static KNI_RETURNTYPE_OBJECT java_lang_Class_newInstance (void)
static KNI_RETURNTYPE_BOOLEAN java_lang_Class_isInstance (void)
static KNI_RETURNTYPE_BOOLEAN java_lang_Class_isAssignableFrom (void)
static KNI_RETURNTYPE_OBJECT java_lang_Object_getClass (void)
static KNI_RETURNTYPE_VOID java_lang_Object_notify (void)
static KNI_RETURNTYPE_VOID java_lang_Object_notifyAll (void)
static KNI_RETURNTYPE_VOID java_lang_Object__wait (void)
static KNI_RETURNTYPE_VOID java_lang_Runtime_exit (void)
static KNI_RETURNTYPE_LONG java_lang_Runtime_freeMemory (void)
static KNI_RETURNTYPE_LONG java_lang_Runtime_totalMemory (void)
static KNI_RETURNTYPE_VOID java_lang_Runtime_gc (void)
static KNI_RETURNTYPE_OBJECT java_lang_String_intern (void)
static KNI_RETURNTYPE_LONG java_lang_System_currentTimeMillis (void)
static KNI_RETURNTYPE_VOID java_lang_System_arraycopy (void)
static KNI_RETURNTYPE_INT java_lang_System_identityHashCode (void)
static KNI_RETURNTYPE_OBJECT java_lang_Thread_currentThread (void)
static KNI_RETURNTYPE_VOID java_lang_Thread_yield (void)
static KNI_RETURNTYPE_VOID java_lang_Thread_sleep (void)
static KNI_RETURNTYPE_VOID java_lang_Thread_start (void)
static KNI_RETURNTYPE_INT java_lang_Thread_activeCount (void)
static KNI_RETURNTYPE_VOID java_lang_Thread_join (void)
static KNI_RETURNTYPE_VOID java_lang_Thread_interrupt (void)
static KNI_RETURNTYPE_VOID java_lang_Throwable_printStackTrace (void)
static KNI_RETURNTYPE_VOID java_lang_ref_WeakReference_addToWeakReferenceList (void)
static KNI_RETURNTYPE_VOID jelatine_VMOutputStream_write_to_stderr (void)
static KNI_RETURNTYPE_VOID jelatine_VMOutputStream_write_to_stdout (void)
native_proto_t native_method_lookup (const char *cl_name, const char *name, const char *desc)
Variables
native_method_desc_t native_desc []
Detailed Description
Native methods' implementation
Definition in file native.c.
Typedef Documentation
typedef struct native_method_desc_t native_method_desc_t
Typedef for struct native_method_desc_t
Definition at line 65 of file native.c.
Function Documentation
static KNI_RETURNTYPE_OBJECT java_lang_Class_forName (void) [static]
Implementation of java.lang.Class.forName()
Definition at line 561 of file native.c.
References array_get_data(), bcl_resolve_class(), c_catch, c_clear_exception(), c_rethrow, c_try, class_get_object(), gc_free(), JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_STRING_REF2PTR, java_to_utf8(), KNI_DeclareHandle, KNI_EndHandlesAndReturnObject, KNI_GetParameterAsObject(), KNI_IsNullHandle(), KNI_StartHandles, KNI_ThrowNew(), thread_pop_root(), and utf8_slashify().
static KNI_RETURNTYPE_OBJECT java_lang_Class_getInternalName (void) [static]
Implementation of java.lang.Class.getInternalName()
Definition at line 611 of file native.c.
References bcl_get_class_by_id(), JAVA_LANG_CLASS_REF2PTR, JAVA_LANG_STRING_PTR2REF, jstring_create_from_utf8(), KNI_DeclareHandle, KNI_EndHandlesAndReturnObject, KNI_GetThisPointer(), KNI_StartHandles, and class_t::name.
static KNI_RETURNTYPE_BOOLEAN java_lang_Class_isAssignableFrom (void) [static]
Implementation of java.lang.Class.isAssignableFrom()
Definition at line 667 of file native.c.
References KNI_DeclareHandle, KNI_EndHandles, KNI_GetParameterAsObject(), KNI_GetThisPointer(), KNI_IsAssignableFrom(), KNI_IsNullHandle(), KNI_ReturnBoolean, KNI_StartHandles, and KNI_ThrowNew().
static KNI_RETURNTYPE_BOOLEAN java_lang_Class_isInstance (void) [static]
Implementation of java.lang.Class.isInstance()
Definition at line 650 of file native.c.
References KNI_DeclareHandle, KNI_EndHandles, KNI_GetParameterAsObject(), KNI_GetThisPointer(), KNI_IsInstanceOf(), KNI_ReturnBoolean, and KNI_StartHandles.
static KNI_RETURNTYPE_OBJECT java_lang_Class_newInstance (void) [static]
Implementation of java.lang.Class.newInstance()
Definition at line 627 of file native.c.
References bcl_get_class_by_id(), gc_new(), interpreter(), JAVA_LANG_CLASS_REF2PTR, KNI_DeclareHandle, KNI_EndHandlesAndReturnObject, KNI_GetThisPointer(), KNI_StartHandles, class_t::method_manager, mm_get(), thread_t::sp, and thread_self().
static KNI_RETURNTYPE_VOID java_lang_Object__wait (void) [static]
Implementation of java.lang.Object._wait()
Definition at line 939 of file native.c.
References KNI_DeclareHandle, KNI_EndHandles, KNI_GetParameterAsInt(), KNI_GetParameterAsLong(), KNI_GetThisPointer(), KNI_ReturnVoid, KNI_StartHandles, KNI_ThrowNew(), and thread_wait().
static KNI_RETURNTYPE_OBJECT java_lang_Object_getClass (void) [static]
Implementation of java.lang.Object.getClass()
Definition at line 884 of file native.c.
References class_get_object(), header_get_class(), KNI_DeclareHandle, KNI_EndHandlesAndReturnObject, KNI_GetThisPointer(), and KNI_StartHandles.
static KNI_RETURNTYPE_VOID java_lang_Object_notify (void) [static]
Implementation of java.lang.Object.notify()
Definition at line 897 of file native.c.
References KNI_DeclareHandle, KNI_EndHandles, KNI_GetThisPointer(), KNI_ReturnVoid, KNI_StartHandles, KNI_ThrowNew(), and thread_notify().
static KNI_RETURNTYPE_VOID java_lang_Object_notifyAll (void) [static]
Implementation of java.lang.Object.notifyAll()
Definition at line 918 of file native.c.
References KNI_DeclareHandle, KNI_EndHandles, KNI_GetThisPointer(), KNI_ReturnVoid, KNI_StartHandles, KNI_ThrowNew(), and thread_notify().
static KNI_RETURNTYPE_VOID java_lang_ref_WeakReference_addToWeakReferenceList (void) [static]
Implementation of java.lang.ref.WeakReference.addToWeakReferenceList()
Definition at line 1239 of file native.c.
References gc_register_weak_ref(), JAVA_LANG_REF_WEAKREFERENCE_REF2PTR, KNI_DeclareHandle, KNI_EndHandles, KNI_GetParameterAsObject(), KNI_ReturnVoid, and KNI_StartHandles.
static KNI_RETURNTYPE_VOID java_lang_Runtime_exit (void) [static]
Implementation of java.lang.Runtime.exit()
Definition at line 965 of file native.c.
References KNI_GetParameterAsInt().
static KNI_RETURNTYPE_LONG java_lang_Runtime_freeMemory (void) [static]
Implementation of java.lang.Runtime.freeMemory()
Definition at line 972 of file native.c.
References gc_free_memory(), and KNI_ReturnLong.
static KNI_RETURNTYPE_VOID java_lang_Runtime_gc (void) [static]
Implementation of java.lang.Runtime.gc()
Definition at line 986 of file native.c.
References gc_collect(), and KNI_ReturnVoid.
static KNI_RETURNTYPE_LONG java_lang_Runtime_totalMemory (void) [static]
Implementation of java_lang_Runtime.totalMemory()
Definition at line 979 of file native.c.
References gc_total_memory(), and KNI_ReturnLong.
static KNI_RETURNTYPE_OBJECT java_lang_String_intern (void) [static]
Implementation of java.lang.String.intern()
Definition at line 994 of file native.c.
References JAVA_LANG_STRING_PTR2REF, JAVA_LANG_STRING_REF2PTR, jstring_intern(), KNI_DeclareHandle, KNI_EndHandlesAndReturnObject, KNI_GetThisPointer(), and KNI_StartHandles.
static KNI_RETURNTYPE_VOID java_lang_System_arraycopy (void) [static]
Implementation of java.lang.System.arraycopy()
Definition at line 1021 of file native.c.
References array_elem_size(), array_get_data(), arraycopy_ref(), class_is_array(), class_t::elem_type, header_get_class(), KNI_DeclareHandle, KNI_EndHandles, KNI_GetParameterAsInt(), KNI_GetParameterAsObject(), KNI_IsNullHandle(), KNI_StartHandles, KNI_ThrowNew(), array_t::length, prim_to_array_type(), PT_BOOL, and PT_REFERENCE.
static KNI_RETURNTYPE_LONG java_lang_System_currentTimeMillis (void) [static]
Implementation of java.lang.System.currentTimeMillis()
Definition at line 1009 of file native.c.
References get_time_with_offset(), and KNI_ReturnLong.
static KNI_RETURNTYPE_INT java_lang_System_identityHashCode (void) [static]
Implementation of java.lang.System.identityHashCode()
Definition at line 1121 of file native.c.
References KNI_DeclareHandle, KNI_EndHandles, KNI_GetParameterAsObject(), KNI_ReturnInt, and KNI_StartHandles.
static KNI_RETURNTYPE_INT java_lang_Thread_activeCount (void) [static]
Implementation of java.lang.Thread.activeCount()
Definition at line 1191 of file native.c.
References KNI_ReturnInt, and tm_active().
static KNI_RETURNTYPE_OBJECT java_lang_Thread_currentThread (void) [static]
Implementation of java.lang.Thread.currentThread()
Definition at line 1136 of file native.c.
References KNI_DeclareHandle, KNI_EndHandlesAndReturnObject, KNI_StartHandles, thread_t::obj, and thread_self().
static KNI_RETURNTYPE_VOID java_lang_Thread_interrupt (void) [static]
Implementation of java.lang.Thread.interrupt()
Definition at line 1214 of file native.c.
References JAVA_LANG_THREAD_REF2PTR, KNI_DeclareHandle, KNI_EndHandles, KNI_GetThisPointer(), KNI_ReturnVoid, KNI_StartHandles, and thread_interrupt().
static KNI_RETURNTYPE_VOID java_lang_Thread_join (void) [static]
Implementation of java.lang.Thread.join()
Definition at line 1198 of file native.c.
References KNI_DeclareHandle, KNI_EndHandles, KNI_GetThisPointer(), KNI_ReturnVoid, KNI_StartHandles, and thread_join().
static KNI_RETURNTYPE_VOID java_lang_Thread_sleep (void) [static]
Implementation of java.lang.Thread.sleep()
Definition at line 1155 of file native.c.
References KNI_GetParameterAsLong(), KNI_ReturnVoid, KNI_ThrowNew(), and thread_sleep().
static KNI_RETURNTYPE_VOID java_lang_Thread_start (void) [static]
Implementation of java.lang.Thread.start()
Definition at line 1170 of file native.c.
References header_get_class(), KNI_DeclareHandle, KNI_EndHandles, KNI_GetThisPointer(), KNI_ReturnVoid, KNI_StartHandles, class_t::method_manager, mm_get(), and thread_launch().
static KNI_RETURNTYPE_VOID java_lang_Thread_yield (void) [static]
Implementation of java.lang.Thread.yield()
Definition at line 1147 of file native.c.
References KNI_ReturnVoid, and thread_yield().
static KNI_RETURNTYPE_VOID java_lang_Throwable_printStackTrace (void) [static]
Implementation of java.lang.Throwable.printStackTrace()
Definition at line 1231 of file native.c.
References KNI_ReturnVoid.
static KNI_RETURNTYPE_VOID jelatine_VMOutputStream_write_to_stderr (void) [static]
Implementation of jelatine.VMOutputStream.write_to_stderr()
Definition at line 1270 of file native.c.
References KNI_GetParameterAsByte().
static KNI_RETURNTYPE_VOID jelatine_VMOutputStream_write_to_stdout (void) [static]
Implementation of jelatine.VMOutputStream.write_to_stdout()
Definition at line 1277 of file native.c.
References KNI_GetParameterAsByte().
native_proto_t native_method_lookup (const char * cl_name, const char * name, const char * desc)
Searches for a native method using the provided class name, method name and signature
Parameters
cl_name Name of the class
name Name of the method
desc Descriptor of the method
Returns
A pointer to a native method structure or NULL if none is found matching the specified criteria
Definition at line 544 of file native.c.
References native_method_desc_t::class_name, native_method_desc_t::descriptor, and native_method_desc_t::func.
Referenced by method_link_native().
Variable Documentation
native_method_desc_t native_desc[]
Names and descriptions of the native methods
Definition at line 168 of file native.c.