thread.c File Reference
#include `wrappers.h`
#include `class.h`
#include `interpreter.h`
#include `kni.h`
#include `loader.h`
#include `memory.h`
#include `thread.h`
#include `vm.h`
#include `java_lang_Thread.h`
Data Structures
struct thread_payload_t
struct monitor_t
struct thread_manager_t
Defines
#define TM_CAPACITY (4)
#define PTH_SWITCH_N (500)
Typedefs
typedef struct thread_payload_t thread_payload_t
typedef struct monitor_t monitor_t
typedef struct thread_manager_t thread_manager_t
Functions
static void native_key_create (native_key_t *)
static void native_key_dispose (native_key_t)
static void native_thread_create (native_thread_t *, void *(*start)(void *), void *)
static void native_thread_exit (void)
static void native_thread_yield (void)
static void native_mutex_create (native_mutex_t *)
static void native_mutex_dispose (native_mutex_t *)
static void native_mutex_lock (native_mutex_t *)
static void native_mutex_unlock (native_mutex_t *)
static void native_cond_create (native_cond_t *)
static void native_cond_dispose (native_cond_t *)
static void native_cond_wait (native_cond_t *, native_mutex_t *)
static void native_cond_timed_wait (native_cond_t *, native_mutex_t *, uint64_t, uint32_t)
static void native_cond_signal (native_cond_t *)
static void native_cond_broadcast (native_cond_t *)
void tm_init (void)
void tm_teardown (void)
void tm_register (thread_t *thread)
void tm_unregister (thread_t *thread)
uint32_t tm_active (void)
void tm_mark (void)
static size_t tm_hash (uintptr_t ref)
void tm_purge (void)
static void tm_rehash (bool grow)
void tm_lock (void)
void tm_unlock (void)
void tm_stop_the_world (void)
void monitor_init (void)
void monitor_enter (thread_t *thread, uintptr_t ref)
bool monitor_exit (thread_t *thread, uintptr_t ref)
static void thread_set_self (thread_t *thread)
void thread_push_root (uintptr_t *ref)
void thread_pop_root (void)
void thread_init (thread_t *thread)
uintptr_t thread_create_main (thread_t *thread, method_t *run, uintptr_t *args)
void thread_sleep (int64_t ms)
static void * thread_start (void *arg)
void thread_launch (uintptr_t *ref, method_t *run)
void thread_may_block (void)
void thread_resumes (void)
void thread_interrupt (thread_t *thread)
void thread_yield (void)
void thread_join (uintptr_t *thread)
bool thread_wait (uintptr_t ref, uint64_t millis, uint32_t nanos)
bool thread_notify (uintptr_t ref, bool broadcast)
Variables
JEL_TLS native_key_t self
static thread_manager_t tm
Detailed Description
Implementation of the virtual machine thread
Definition in file thread.c.
Define Documentation
#define PTH_SWITCH_N (500)
Number of global lock acquisition/release couples before yielding when using GNU/Pth
Definition at line 386 of file thread.c.
#define TM_CAPACITY (4)
Define the minimum capacity (i.e. number of buckets) of the monitor table
Definition at line 350 of file thread.c.
Referenced by monitor_init().
Typedef Documentation
typedef struct monitor_t monitor_t
Typedef for the struct monitor_t type
Definition at line 347 of file thread.c.
typedef struct thread_manager_t thread_manager_t
Typedef for the struct thread_manager_t type
Definition at line 368 of file thread.c.
typedef struct thread_payload_t thread_payload_t
Typedef for the struct thread_payload_t type
Definition at line 334 of file thread.c.
Function Documentation
void monitor_enter (thread_t * thread, uintptr_t ref)
Implements the MONITOR_ENTER opcode
Parameters
thread The thread requesting the monitor
ref A Java object reference
Definition at line 728 of file thread.c.
References thread_manager_t::buckets, thread_manager_t::capacity, monitor_t::count, thread_manager_t::entries, monitor_t::next, monitor_t::owner, monitor_t::ref, thread_yield(), tm_hash(), tm_lock(), tm_rehash(), and tm_unlock().
Referenced by gc_mark_finalizable(), initialize_class(), interpreter(), and thread_wait().
bool monitor_exit (thread_t * thread, uintptr_t ref)
Implements the MONITOR_EXIT opcode
Parameters
thread A pointer to the thread relinquishing the monitor
ref The object on which the monitor was taken
Returns
true if everything went well, false if thread didn't own the monitor and thus MONITOR_EXIT would fail
Definition at line 801 of file thread.c.
References thread_manager_t::buckets, thread_manager_t::capacity, monitor_t::count, monitor_t::next, monitor_t::owner, monitor_t::ref, tm_hash(), tm_lock(), and tm_unlock().
Referenced by gc_mark_finalizable(), initialize_class(), and interpreter().
void monitor_init (void)
Initialization of the Java monitors subsystem
Definition at line 718 of file thread.c.
References thread_manager_t::buckets, thread_manager_t::capacity, gc_malloc(), and TM_CAPACITY.
Referenced by vm_init().
static void native_cond_broadcast (native_cond_t * cond) [static]
Signals all the threads waiting on a native condition variable
Parameters
cond A pointer to the native condition variable
Definition at line 310 of file thread.c.
Referenced by thread_create_main(), thread_notify(), and thread_start().
static void native_cond_create (native_cond_t * cond) [static]
Creates a native condition variable
Parameters
cond A pointer to the native condition variable structure
Definition at line 212 of file thread.c.
Referenced by thread_init(), thread_launch(), thread_sleep(), and thread_wait().
static void native_cond_dispose (native_cond_t * cond) [static]
Disposes of a native condition variable
Parameters
cond A pointer to the native condition variable structure
Definition at line 224 of file thread.c.
Referenced by thread_launch(), thread_start(), and tm_purge().
static void native_cond_signal (native_cond_t * cond) [static]
Signal a thread waiting on a native condition variable
Parameters
cond A pointer to a native condition variable
Definition at line 298 of file thread.c.
Referenced by thread_interrupt(), thread_notify(), and thread_start().
static void native_cond_timed_wait (native_cond_t * cond, native_mutex_t * mutex, uint64_t millis, uint32_t nanos) [static]
Wait on the specified native condition variable until the variable is signaled or the specified timout expires
Parameters
cond A pointer to a native condition variable
mutex A pointer to a native mutex structure
millis The timeout in milliseconds
nanos The timeout in nanoseconds
Definition at line 260 of file thread.c.
References get_time_with_offset().
Referenced by thread_sleep(), and thread_wait().
static void native_cond_wait (native_cond_t * cond, native_mutex_t * mutex) [static]
Wait on the specified native condition variable until the variable is signaled
Parameters
cond A pointer to a native condition variable
mutex A pointer to a native mutex structure
Definition at line 244 of file thread.c.
Referenced by thread_join(), thread_launch(), and thread_wait().
static void native_key_create (native_key_t * key) [static]
Creates a new native thread-local storage key
Parameters
key The address of the key to be initialized
Definition at line 69 of file thread.c.
Referenced by tm_init().
static void native_key_dispose (native_key_t key) [static]
Disposes of a native thread-local storage key
Parameters
key The key to be disposed of
Definition at line 81 of file thread.c.
Referenced by tm_teardown().
static void native_mutex_create (native_mutex_t * mutex) [static]
Creates a new recursive native mutex
Parameters
mutex A pointer to a native mutex structure
Definition at line 161 of file thread.c.
Referenced by tm_init().
static void native_mutex_dispose (native_mutex_t * mutex) [static]
Disposes of a native mutex
Parameters
mutex A pointer to the native mutex structure
Definition at line 178 of file thread.c.
Referenced by tm_teardown().
static void native_mutex_lock (native_mutex_t * mutex) [static]
Acquire the lock on a native mutex
Parameters
mutex A pointer to the native mutex structure
Definition at line 188 of file thread.c.
Referenced by thread_resumes(), and tm_lock().
static void native_mutex_unlock (native_mutex_t * mutex) [static]
Release the lock on a native mutex
Parameters
mutex A pointer to the native mutex structure
Definition at line 200 of file thread.c.
Referenced by thread_resumes(), and tm_unlock().
static void native_thread_create (native_thread_t * thread, void *(*)(void *) start, void * arg) [static]
Spawn a new native thread
Parameters
thread A pointer to the native thread structure
start The new thread entry point
arg A pointer to be passed to the new thread
Definition at line 95 of file thread.c.
References dbg_error, and vm_fail().
Referenced by thread_launch().
static void native_thread_exit (void) [static]
Terminates the calling native thread
Definition at line 132 of file thread.c.
Referenced by thread_start().
static void native_thread_yield (void) [static]
Yield execution of the current native thread
Definition at line 143 of file thread.c.
Referenced by thread_yield().
uintptr_t thread_create_main (thread_t * thread, method_t * run, uintptr_t * args)
Creates the main thread. This function doesn't return until the main thread has finished execution as it uses the current native/green thread instead of creating a new one
Parameters
thread The main thread pre-allocated structure
run The main method
args A pointer to a reference to the arguments array
Returns
The reference to an uncaught exception if the main method terminated abruptly or JNULL
Definition at line 896 of file thread.c.
References bcl_find_class(), thread_t::cond, thread_t::exception, thread_t::fp, gc_free(), gc_malloc(), gc_new(), interpreter(), JAVA_LANG_STRING_PTR2REF, JAVA_LANG_THREAD_REF2PTR, jstring_create_from_utf8(), native_cond_broadcast(), thread_t::obj, opts_get_stack_size(), thread_t::pointers, thread_t::roots, thread_t::sp, thread_t::stack, tm_lock(), tm_unlock(), and tm_unregister().
Referenced by vm_run().
void thread_init (thread_t * thread)
Initializes all the thread-local structures required for normal operation of a thread including the thread's self reference
Parameters
thread A pointer to the thread's own structure
Definition at line 880 of file thread.c.
References thread_t::cond, native_cond_create(), and thread_set_self().
Referenced by thread_start(), and vm_run().
void thread_interrupt (thread_t * thread)
Interrupts a thread. This function is used for implementing the java.lang.Thread.interrupt() method and can interrupt immediately the java.lang.Object.wait() and java.lang.Thread.sleep() methods but only asynchronously the java.lang.Thread.join() method
Parameters
thread A pointer to the thread to be interrupted
Definition at line 1130 of file thread.c.
References thread_t::cond_int, thread_t::interrupted, native_cond_signal(), tm_lock(), and tm_unlock().
Referenced by java_lang_Thread_interrupt().
void thread_join (uintptr_t * thread)
Joins on the passed thread
Parameters
thread A pointer to the reference to the Java thread the function will join on
Definition at line 1155 of file thread.c.
References thread_t::cond, JAVA_LANG_THREAD_REF2PTR, KNI_ThrowNew(), thread_manager_t::lock, native_cond_wait(), self, thread_may_block(), thread_resumes(), thread_self(), tm_lock(), and tm_unlock().
Referenced by java_lang_Thread_join().
void thread_launch (uintptr_t * ref, method_t * run)
Creates a new thread executing the provided method
Parameters
ref The java.lang.Thread object associated with this thread
run The first method executed by this thread
Definition at line 1053 of file thread.c.
References thread_payload_t::cond, gc_free(), gc_malloc(), thread_manager_t::lock, native_cond_create(), native_cond_dispose(), native_cond_wait(), native_thread_create(), thread_payload_t::ref, thread_payload_t::run, thread_payload_t::thread, thread_may_block(), thread_resumes(), thread_start(), tm_lock(), and tm_unlock().
Referenced by java_lang_Thread_start(), and vm_run().
void thread_may_block (void)
Flags the calling thread as potentially blocked. This function must be called every time a thread might block for a long time in order to avoid livelocks. Two examples might be when the thread takes a lock or when it calls a blocking native method like recv(). When the thread has finished the blocking operation thread_resumes() must be called
Definition at line 1086 of file thread.c.
References self, and thread_self().
Referenced by thread_join(), thread_launch(), thread_sleep(), thread_wait(), and tm_lock().
bool thread_notify (uintptr_t ref, bool broadcast)
Implements the functionliaty required by java.lang.Object.notify()
Parameters
ref The object used for the notification
broadcast If true, wake up all the threads waiting on this object, otherwise wake up only one thread
Returns
true if everything goes well, false if the monitor associated with ref was not owned by thread. In the latter case an IllegalMonitorStateException should be thrown
Definition at line 1255 of file thread.c.
References thread_manager_t::buckets, thread_manager_t::capacity, monitor_t::cond, native_cond_broadcast(), native_cond_signal(), monitor_t::next, monitor_t::owner, monitor_t::ref, thread_self(), tm_hash(), tm_lock(), and tm_unlock().
Referenced by gc_mark_finalizable(), initialize_class(), java_lang_Object_notify(), and java_lang_Object_notifyAll().
void thread_pop_root (void)
Pop a temporary root from a thread's stack
Definition at line 871 of file thread.c.
References thread_t::roots, thread_self(), and thread_t::used.
Referenced by gc_new_multiarray(), java_lang_Class_forName(), jstring_create_from_unicode(), jstring_create_from_utf8(), jstring_create_literal(), and vm_run().
void thread_push_root (uintptr_t * ref)
Push a temporary root on the current thread's stack
Parameters
ref A pointer to an object reference to be pushed on the temporary root stack
Definition at line 849 of file thread.c.
References thread_t::capacity, gc_free(), gc_malloc(), thread_t::pointers, thread_t::roots, thread_self(), and thread_t::used.
Referenced by _KNI_push_handle(), gc_new_multiarray(), jstring_create_from_unicode(), jstring_create_from_utf8(), jstring_create_literal(), and vm_run().
void thread_resumes (void)
Restores a thread to its steady state after a blocking operation. Before returning however this function checks if a global stop-the-world has been requested, if so it waits until it is asked to resume execution. This function must be always called after a blocking operation and coupled with a previous call to thread_may_block()
Definition at line 1100 of file thread.c.
References thread_manager_t::lock, native_mutex_lock(), native_mutex_unlock(), self, and thread_self().
Referenced by thread_join(), thread_launch(), thread_sleep(), thread_wait(), and tm_lock().
static void thread_set_self (thread_t * thread) [static]
Sets the thread's own thread_t structure
Parameters
thread A pointer to the thread's own structure
Definition at line 840 of file thread.c.
References native_key_set().
Referenced by thread_init().
void thread_sleep (int64_t ms)
Implements the functionality required by the java.lang.Thread.sleep() method, waiting for the number of milliseconds specified by ms
Parameters
ms The number of milliseconds to wait
Definition at line 941 of file thread.c.
References KNI_ThrowNew(), thread_manager_t::lock, native_cond_create(), native_cond_timed_wait(), self, thread_may_block(), thread_resumes(), thread_self(), tm_lock(), and tm_unlock().
Referenced by java_lang_Thread_sleep().
static void* thread_start (void * arg) [static]
Startup function used as the entry point of a new thread. Both the payload passed in arg and the new thread structures (including the stack) will be fred by this function upon ending execution
Parameters
arg A pointer to the thread payload structure
Returns
Nothing important
Definition at line 974 of file thread.c.
References c_catch, c_clear_exception(), c_print_exception(), c_try, thread_t::capacity, thread_t::cond, thread_payload_t::cond, dbg_error, thread_t::exception, thread_t::fp, gc_free(), gc_malloc(), interpreter(), JAVA_LANG_THREAD_REF2PTR, thread_t::native, native_cond_broadcast(), native_cond_dispose(), native_cond_signal(), native_thread_exit(), thread_t::obj, opts_get_stack_size(), thread_t::pointers, thread_payload_t::ref, thread_t::roots, thread_payload_t::run, thread_t::sp, thread_t::stack, thread_payload_t::thread, thread_init(), THREAD_TMP_ROOTS, tm_lock(), tm_register(), tm_unlock(), tm_unregister(), and vm_fail().
Referenced by thread_launch().
bool thread_wait (uintptr_t ref, uint64_t millis, uint32_t nanos)
Implements the functionality required by java.lang.Object.wait() and friends, waiting on an object until it is notified by notify() or notifyAll() or until a timeout occurs (if nanos or millis or both ar non-zero)
Parameters
ref The object on which to wait
millis Number of milliseconds before a timeout occurs
nanos Number of nanoseconds before a timeout occurs
Returns
true if everything goes well, false if the monitor associated with ref was not owned thread. In the latter case an IllegalMonitorStateException should be thrown
Definition at line 1192 of file thread.c.
References thread_manager_t::buckets, thread_manager_t::capacity, monitor_t::cond, monitor_t::count, gc_malloc(), KNI_ThrowNew(), thread_manager_t::lock, monitor_enter(), native_cond_create(), native_cond_timed_wait(), native_cond_wait(), monitor_t::next, monitor_t::owner, monitor_t::ref, self, thread_may_block(), thread_resumes(), thread_self(), tm_hash(), tm_lock(), and tm_unlock().
Referenced by initialize_class(), and java_lang_Object__wait().
void thread_yield (void)
Causes the currently executing thread object to temporarily pause and allow other threads to execute
Definition at line 1145 of file thread.c.
References native_thread_yield().
Referenced by java_lang_Thread_yield(), monitor_enter(), and tm_stop_the_world().
uint32_t tm_active (void)
Returns the number of active threads in the system
Returns
Returns the number of active threads
Definition at line 475 of file thread.c.
References thread_manager_t::active.
Referenced by java_lang_Thread_activeCount().
static size_t tm_hash (uintptr_t ref) [static]
Hash function used for object references
Parameters
ref A reference to a Java object
Definition at line 514 of file thread.c.
Referenced by monitor_enter(), monitor_exit(), thread_notify(), thread_wait(), tm_purge(), and tm_rehash().
void tm_init (void)
Initialize the thread manager, this does not include the initialization of the Java monitors subsystem because the thread manager is initialized before the heap manager
Definition at line 392 of file thread.c.
References thread_manager_t::lock, native_key_create(), native_mutex_create(), and vm_fail().
Referenced by vm_run().
void tm_lock (void)
Try to gain the ownership of the machine-wide lock. This function will return only when the caller has the ownership of the lock in the meantime the calling thread is considered blocked. It is safe to call this function repeatedly from the same thread as long as tm_unlock() is called the same number of times to release the lock
Definition at line 659 of file thread.c.
References thread_manager_t::lock, native_mutex_lock(), thread_may_block(), and thread_resumes().
Referenced by bcl_find_class(), bcl_get_class_by_id(), bcl_link_method(), bcl_link_opcode(), bcl_resolve_class(), gc_collect(), gc_free(), gc_free_memory(), gc_malloc(), gc_new(), gc_new_array_nonref(), gc_new_array_ref(), gc_palloc(), gc_register_weak_ref(), jstring_create_literal(), jstring_intern(), monitor_enter(), monitor_exit(), thread_create_main(), thread_interrupt(), thread_join(), thread_launch(), thread_notify(), thread_sleep(), thread_start(), thread_wait(), tm_teardown(), and utf8_intern().
void tm_mark (void)
Marks all the references reacheable from the threads
Definition at line 486 of file thread.c.
References thread_t::exception, gc_mark_potential(), gc_mark_reference(), thread_t::next, thread_t::obj, thread_t::pointers, thread_manager_t::queue, thread_t::roots, thread_t::stack, and thread_t::used.
Referenced by gc_mark().
void tm_purge (void)
Purge the monitor table by clearing the entries associated with dead objects, also purge the associated conditions
Definition at line 526 of file thread.c.
References thread_manager_t::buckets, thread_manager_t::capacity, monitor_t::cond, thread_manager_t::entries, gc_free(), header_is_marked(), native_cond_dispose(), monitor_t::next, monitor_t::ref, and tm_hash().
Referenced by gc_collect().
void tm_register (thread_t * thread)
Register a new thread in the thread manager
Parameters
thread A pointer to the new thread
Definition at line 441 of file thread.c.
References thread_manager_t::active, thread_t::next, and thread_manager_t::queue.
Referenced by thread_start(), and vm_run().
static void tm_rehash (bool grow) [static]
Rehash the monitor table, growing or shrinking it
Parameters
grow true if the table must be grown, false if it must be shrinked
Definition at line 607 of file thread.c.
References thread_manager_t::buckets, thread_manager_t::capacity, monitor_t::cond, monitor_t::count, gc_free(), gc_malloc(), monitor_t::next, monitor_t::owner, monitor_t::ref, and tm_hash().
Referenced by monitor_enter().
void tm_stop_the_world (void)
Waits for all threads to stop. The calling thread must have taken the VM lock for this to happen safely
Definition at line 683 of file thread.c.
References thread_t::blocked, thread_t::next, thread_manager_t::queue, thread_t::stopped, thread_self(), and thread_yield().
Referenced by gc_collect(), and tm_teardown().
void tm_teardown (void)
Tears down the thread manager
Definition at line 412 of file thread.c.
References thread_manager_t::lock, thread_t::native, native_key_dispose(), native_mutex_dispose(), thread_t::next, thread_manager_t::queue, tm_lock(), tm_stop_the_world(), and tm_unlock().
Referenced by vm_run().
void tm_unlock (void)
Release the ownership of the machine-wide lock
Definition at line 668 of file thread.c.
References thread_manager_t::lock, and native_mutex_unlock().
Referenced by bcl_find_class(), bcl_get_class_by_id(), bcl_link_method(), bcl_link_opcode(), bcl_resolve_class(), gc_collect(), gc_free(), gc_free_memory(), gc_malloc(), gc_new(), gc_new_array_nonref(), gc_new_array_ref(), gc_palloc(), gc_register_weak_ref(), jstring_create_literal(), jstring_intern(), monitor_enter(), monitor_exit(), thread_create_main(), thread_interrupt(), thread_join(), thread_launch(), thread_notify(), thread_sleep(), thread_start(), thread_wait(), tm_teardown(), and utf8_intern().
void tm_unregister (thread_t * thread)
Unregister a dying thread
Parameters
thread A thread which has finished execution
Definition at line 451 of file thread.c.
References thread_manager_t::active, thread_t::next, and thread_manager_t::queue.
Referenced by thread_create_main(), and thread_start().
Variable Documentation
JEL_TLS native_key_t self
Thread-local self pointer of a thread
Definition at line 375 of file thread.c.
Referenced by c_clear_exception(), c_print_exception(), c_throw_dbg(), thread_join(), thread_may_block(), thread_resumes(), thread_sleep(), and thread_wait().
thread_manager_t tm [static]
Thread manager singleton
Definition at line 378 of file thread.c.