util.c File Reference
#include `wrappers.h`
#include `class.h`
#include `memory.h`
#include `util.h`
#include `vm.h`
Functions
void dbg_warning_internal (const char *filename, int lineno, const char *format,...)
void dbg_error_internal (const char *filename, int lineno, const char *format,...)
void dbg_printf_internal (const char *filename, int lineno, const char *format,...)
void dbg_unreachable_internal (const char *filename, int lineno)
char * cstrchrnul (const char *s, int c)
void sort_asc_uint16_ptrs (uint16_t *array, void **ptrs, uint32_t len)
void c_throw_dbg (const char *file, int line, int exc, const char *desc,...)
void c_clear_exception (void)
void c_print_exception (int exc)
struct timespec get_time_with_offset (uint64_t ms, uint32_t nanos)
Detailed Description
Utility functions implementation
Definition in file util.c.
Function Documentation
void c_clear_exception (void)
Clear the current exception. This frees the exception description
Definition at line 262 of file util.c.
References gc_free(), self, and thread_self().
Referenced by java_lang_Class_forName(), thread_start(), and vm_run().
void c_print_exception (int exc)
Print the exception of type exc currently held by the calling thread
Parameters
exc An exception type
Definition at line 273 of file util.c.
References self, and thread_self().
Referenced by thread_start(), and vm_run().
void c_throw_dbg (const char * file, int line, int exc, const char * desc, ...)
Throw a C pseudo-exception in debug mode
Parameters
file The file were the exception was thrown
line The line were the exception was thrown
exc The exception number / type
desc A printf()-like formatted string holding a description of the thrown exception
Definition at line 197 of file util.c.
References gc_malloc(), self, and thread_self().
char* cstrchrnul (const char * s, int c)
Replacement function for strchrnul() which is a GNU extension
Parameters
s String to search for the character c
c The character to look for
Returns
A pointer to the first instance of c or a pointer to the nul terminator if c is not found in the string
Definition at line 116 of file util.c.
Referenced by classpath_init().
void dbg_error_internal (const char * filename, int lineno, const char * format, ...)
Prints a formatted string to the stderr stream, notifying the user of an error condition and aborts
Parameters
filename The name of the source file in which this function was called
lineno The line where this function was called
format A format string using the printf() guidelines
Definition at line 62 of file util.c.
void dbg_printf_internal (const char * filename, int lineno, const char * format, ...)
Prints a formatted string to the stderr stream, the function prepends the filename and line where the function was called and appends a newline
Parameters
filename The name of the file from which the function was called
lineno The number of the line in which the function was called
format A format string using the printf() guidelines
Definition at line 80 of file util.c.
void dbg_unreachable_internal (const char * filename, int lineno)
Aborts execution and emits a warning that the code has reached a point which shouldn't be reachable under normal conditions
Parameters
filename The name of the file from which the function was called
lineno The number of the line in which the function was called
Definition at line 97 of file util.c.
void dbg_warning_internal (const char * filename, int lineno, const char * format, ...)
Prints a formatted string to the stderr stream, warning the user about abnormal situations which do not prevent the program from continuing execution
Parameters
filename The name of the source file in which this function was called
lineno The line where this function was called
format A format string using the printf() guidelines
Definition at line 44 of file util.c.
struct timespec get_time_with_offset (uint64_t ms, uint32_t nanos) [read]
Returns a timespec structure filled with the current time plus the offset specified by ms and nanos
Parameters
ms An offset in microseconds
nanos An offset in nanoseconds
Returns
The current time plus the specified offset
Definition at line 310 of file util.c.
Referenced by java_lang_System_currentTimeMillis(), and native_cond_timed_wait().
void sort_asc_uint16_ptrs (uint16_t * array, void ** ptrs, uint32_t len)
Sorts an uint16 array and a pointer array using the integer array as the reference. This function is used to sort the interface table
Parameters
array A pointer to an uint16 array
ptrs A pointer to an array of pointers
len The length of the arrays
Definition at line 135 of file util.c.
Referenced by create_interface_dispatch_table().