verifier.h File Reference
#include `wrappers.h`
#include `class.h`
#include `classfile.h`
Defines
#define JELATINE_VERIFIER_H (1)
Functions
bool same_package (const class_t *, const class_t *)
void verify_field (const class_t *, const field_info_t *, const field_attributes_t *)
void verify_field_access (const class_t *, const class_t *, const field_t *)
Detailed Description
Bytecode and class file verification interface
Definition in file verifier.h.
Define Documentation
#define JELATINE_VERIFIER_H (1)
verifier.h inclusion macro
Definition at line 28 of file verifier.h.
Function Documentation
bool same_package (const class_t * cl1, const class_t * cl2)
Checks if two classes belong to the same package
Parameters
cl1 A class pointer
cl2 A class pointer
Returns
True if both classes belong to the same package
Definition at line 40 of file verifier.c.
References class_t::name.
Referenced by bcl_resolve_class(), resolve_method(), and verify_field_access().
void verify_field (const class_t * cl, const field_info_t * info, const field_attributes_t * attr)
Verify the validity of a field
If the verification of the field fails this function will throw a verification exception
Parameters
cl A pointer to the class to which the field belongs
info A pointer to the field_info structure representing the field
attr A pointer to the field_attributes structure holding the field attributes
Definition at line 88 of file verifier.c.
References ACC_FINAL, ACC_PRIVATE, ACC_PROTECTED, ACC_PUBLIC, ACC_STATIC, ACC_TRANSIENT, ACC_VOLATILE, field_info_t::access_flags, c_throw, class_is_interface(), field_attributes_t::constant_value_found, field_t::descriptor, field_info_t::descriptor, field_parse_descriptor(), class_t::fields, class_t::fields_n, JAVA_LANG_NOCLASSDEFFOUNDERROR, field_t::name, and field_info_t::name.
Referenced by load_fields().
void verify_field_access (const class_t * acl, const class_t * cl, const field_t * field)
Check if the field field of class dst is accessible from class src
This function throws a verification exception if the field is not accessible
Parameters
acl The class trying to access the field
cl The class to which the field belongs
field The field to be accessed
Definition at line 160 of file verifier.c.
References c_throw, class_is_parent(), field_is_private(), field_is_protected(), field_is_public(), JAVA_LANG_NOCLASSDEFFOUNDERROR, and same_package().
Referenced by resolve_instance_field(), and resolve_static_field().