vm.h File Reference
#include `wrappers.h`
#include `class.h`
#include `memory.h`
#include `thread.h`
Data Structures
struct options_t
Defines
#define JELATINE_VM_H (1)
Typedefs
typedef struct options_t options_t
Functions
void vm_run (void)
static void vm_fail (void)
static void opts_set_classpath (char *classpath)
static char * opts_get_classpath (void)
static void opts_set_boot_classpath (char *boot_classpath)
static char * opts_get_boot_classpath (void)
static void opts_set_heap_size (size_t size)
static size_t opts_get_heap_size (void)
static void opts_set_stack_size (size_t size)
static size_t opts_get_stack_size (void)
static void opts_set_main_class (char *class_name)
static char * opts_get_main_class (void)
static void opts_set_jargs (char **jargs)
static char ** opts_get_jargs (void)
static void opts_set_jargs_n (int n)
static int opts_get_jargs_n (void)
static void opts_set_version (bool enable)
static bool opts_get_version (void)
static void opts_set_help (bool enable)
static bool opts_get_help (void)
Variables
options_t options
Detailed Description
Virtual machine definition and interface
Definition in file vm.h.
Define Documentation
#define JELATINE_VM_H (1)
vm.h inclusion macro
Definition at line 28 of file vm.h.
Typedef Documentation
typedef struct options_t options_t
Typedef for the struct options_t
Definition at line 95 of file vm.h.
Function Documentation
static char* opts_get_boot_classpath (void) [inline, static]
Gets the global option 'boot classpath'
Returns
The boot classpath string
Definition at line 132 of file vm.h.
References options_t::boot_classpath, and options.
Referenced by classpath_init().
static char* opts_get_classpath (void) [inline, static]
Gets the global option 'classpath'
Returns
The classpath string
Definition at line 115 of file vm.h.
References options_t::classpath, and options.
Referenced by classpath_init().
static size_t opts_get_heap_size (void) [inline, static]
Gets the global option 'heap size'
Returns
The maximum size of the heap
Definition at line 148 of file vm.h.
References options_t::heap_size, and options.
Referenced by vm_init().
static bool opts_get_help (void) [inline, static]
Gets the global option 'help'
Returns
true if help information must be displayed, false otherwise
Definition at line 335 of file vm.h.
References options_t::help, and options.
Referenced by main().
static char** opts_get_jargs (void) [inline, static]
Gets the global option 'jargs'
Returns
An array of strings holding the arguments passed to the Java application
Definition at line 199 of file vm.h.
References options_t::jargs, and options.
Referenced by main(), and vm_run().
static int opts_get_jargs_n (void) [inline, static]
Gets the global option 'jargs_n'
Returns
The number of arguments passed to the Java application
Definition at line 215 of file vm.h.
References options_t::jargs_n, and options.
Referenced by vm_run().
static char* opts_get_main_class (void) [inline, static]
Gets the global option 'main class'
Returns
A string holding the name of the main class
Definition at line 181 of file vm.h.
References options_t::main_class, and options.
Referenced by main(), and vm_run().
static size_t opts_get_stack_size (void) [inline, static]
Gets the global option 'stack size'
Returns
size The default size of a thread's stack
Definition at line 164 of file vm.h.
References options, and options_t::stack_size.
Referenced by thread_create_main(), and thread_start().
static bool opts_get_version (void) [inline, static]
Gets the global option 'version'
Returns
true if version information must be displayed, false otherwise
Definition at line 319 of file vm.h.
References options, and options_t::version.
Referenced by main().
static void opts_set_boot_classpath (char * boot_classpath) [inline, static]
Sets the global option 'default classpath'
Parameters
boot_classpath A pointer to a string holding the new value of the boot classpath
Definition at line 124 of file vm.h.
References options_t::boot_classpath, and options.
Referenced by parse_command_line_args().
static void opts_set_classpath (char * classpath) [inline, static]
Sets the global option 'classpath'
Parameters
classpath A pointer to a string holding the new value of the classpath
Definition at line 107 of file vm.h.
References options_t::classpath, and options.
Referenced by parse_command_line_args().
static void opts_set_heap_size (size_t size) [inline, static]
Sets the global option 'heap size'
Parameters
size The maximum size of the heap
Definition at line 140 of file vm.h.
References options_t::heap_size, and options.
Referenced by parse_command_line_args().
static void opts_set_help (bool enable) [inline, static]
Sets the global option 'help'
Parameters
enable true if help information must be displayed, false otherwise
Definition at line 327 of file vm.h.
References options_t::help, and options.
Referenced by parse_command_line_args().
static void opts_set_jargs (char ** jargs) [inline, static]
Sets the global option 'jargs'
Parameters
jargs A pointer to an array of strings holding the parameters passed to the Java application
Definition at line 190 of file vm.h.
References options_t::jargs, and options.
Referenced by parse_command_line_args().
static void opts_set_jargs_n (int n) [inline, static]
Sets the global option 'jargs_n'
Parameters
n The number of arguments passed to the Java application
Definition at line 207 of file vm.h.
References options_t::jargs_n, and options.
Referenced by main(), and parse_command_line_args().
static void opts_set_main_class (char * class_name) [inline, static]
Sets the global option 'main class'
Parameters
class_name A string holding the name of the class which main method should be called by the virtual machine
Definition at line 173 of file vm.h.
References options_t::main_class, and options.
Referenced by parse_command_line_args().
static void opts_set_stack_size (size_t size) [inline, static]
Sets the global option 'stack size'
Parameters
size The default size of a thread's stack
Definition at line 156 of file vm.h.
References options, and options_t::stack_size.
Referenced by parse_command_line_args().
static void opts_set_version (bool enable) [inline, static]
Sets the global option 'version'
Parameters
enable true if version information must be displayed, false otherwise
Definition at line 311 of file vm.h.
References options, and options_t::version.
Referenced by parse_command_line_args().
static void vm_fail (void) [inline, static]
Terminates abruptly the VM
Definition at line 57 of file vm.h.
Referenced by gc_alloc(), gc_init(), KNI_FatalError(), native_thread_create(), thread_start(), tm_init(), and vm_run().
void vm_run (void)
Launches the JVM
Definition at line 106 of file vm.c.
References method_t::access_flags, array_ref_get_data(), bcl_preload_bootstrap_classes(), bcl_resolve_class(), c_catch, c_clear_exception(), c_print_exception(), c_throw, c_try, thread_t::capacity, gc_enable(), gc_malloc(), gc_new(), gc_new_array_ref(), init_dummy_methods(), JAVA_LANG_NOCLASSDEFFOUNDERROR, JAVA_LANG_STRING_PTR2REF, JAVA_LANG_THREAD_REF2PTR, JAVA_LANG_VIRTUALMACHINEERROR, jstring_create_literal(), method_is_native(), method_is_public(), method_is_static(), class_t::method_manager, mm_get(), opts_get_jargs(), opts_get_jargs_n(), opts_get_main_class(), thread_t::pointers, thread_t::roots, thread_create_main(), thread_init(), thread_launch(), thread_pop_root(), thread_push_root(), THREAD_TMP_ROOTS, tm_init(), tm_register(), tm_teardown(), utf8_check(), utf8_intern(), vm_fail(), vm_init(), and vm_teardown().
Referenced by main().
Variable Documentation
options_t options
Global options of the VM
Definition at line 66 of file vm.c.
Referenced by opts_get_boot_classpath(), opts_get_classpath(), opts_get_heap_size(), opts_get_help(), opts_get_jargs(), opts_get_jargs_n(), opts_get_main_class(), opts_get_stack_size(), opts_get_version(), opts_set_boot_classpath(), opts_set_classpath(), opts_set_heap_size(), opts_set_help(), opts_set_jargs(), opts_set_jargs_n(), opts_set_main_class(), opts_set_stack_size(), and opts_set_version().