/* confdefs.h */
#define PACKAGE_NAME "Jelatine"
#define PACKAGE_TARNAME "jelatine"
#define PACKAGE_VERSION "0.9.4"
#define PACKAGE_STRING "Jelatine 0.9.4 for Kolibri OS"
#define PACKAGE_BUGREPORT "gabriele.svelto@gmail.com"
#define PACKAGE_URL "http://jelatine.sourceforge.net"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _GNU_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define STDC_HEADERS 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_ARPA_INET_H 1
#define HAVE_DIRENT_H 1
#define HAVE_FCNTL_H 1
#define HAVE_ICONV_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LANGINFO_H 1
#define HAVE_MATH_H 1
#define HAVE_SCHED_H 1
#define HAVE_STDARG_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETDB_H 1
#define SIZEOF_VOID_P 4
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define HAVE_INTPTR_T 1
#define HAVE_UINTPTR_T 1
#define HAVE_PTRDIFF_T 1
#define JEL_THREADED_INTERPRETER 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_VPRINTF 1
#define HAVE_MEMCPY 1
#define HAVE_MEMMOVE 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_SIN 1
#define HAVE_COS 1
#define HAVE_TAN 1
#define HAVE_SQRT 1
#define HAVE_CEIL 1
#define HAVE_FLOOR 1
#define JEL_FP_SUPPORT 1
//#define JEL_SOCKET_SUPPORT 1
#define JEL_THREAD_NONE 1
//#define JEL_THREAD_POSIX 1
#define JEL_POINTER_REVERSAL 1
#define NDEBUG 1
#define HAVE_VA_COPY 1
#define JEL_CLASSPATH_DIR "/kolibrios/jelatine/classpath"

//#define JEL_JARFILE_SUPPORT 1

//typedef int* intptr_t;
typedef unsigned int uint32_t ;
typedef unsigned char uint8_t;
#   include <pthread.h>
